-- Weekly cumulative inventory snapshot table
-- Stores cumulative quantities at weekly intervals for performance optimization
-- Generated every Sunday at midnight for the 3-tier architecture

CREATE TABLE IF NOT EXISTS wms_inventory_weekly_snapshot
(
    -- Snapshot metadata
    snapshot_timestamp DateTime COMMENT 'Timestamp of the snapshot (Sunday midnight)',
    snapshot_type String DEFAULT 'weekly' COMMENT 'Type of snapshot (weekly)',
    wh_id UInt64 COMMENT 'Warehouse ID',
    
    -- Inventory position keys (defines unique position)
    hu_code String COMMENT 'Handling unit code',
    sku_code String COMMENT 'SKU code', 
    uom String COMMENT 'Unit of measure',
    bucket String COMMENT 'Inventory bucket/category',
    batch String COMMENT 'Batch identifier',
    price String COMMENT 'Price bucket',
    inclusion_status String COMMENT 'Inclusion status for inventory',
    locked_by_task_id String COMMENT 'Task that has locked this inventory',
    lock_mode String COMMENT 'Lock mode (shared/exclusive)',
    
    -- Cumulative metrics at snapshot time
    cumulative_qty Int64 COMMENT 'Total cumulative quantity from beginning of time to snapshot',
    total_event_count UInt64 COMMENT 'Total number of events processed up to this snapshot',
    
    -- Latest event identifiers at snapshot time
    latest_hu_event_id String,
    latest_quant_event_id String,
    last_event_time DateTime64(3) COMMENT 'Timestamp of last event in this snapshot',
    
    -- All other fields from inventory events (latest values at snapshot time)
    hu_event_seq UInt64,
    hu_id String,
    hu_event_type String,
    hu_event_payload String,
    hu_event_attrs String,
    session_id String,
    task_id String,
    correlation_id String,
    storage_id String,
    outer_hu_id String,
    effective_storage_id String,
    sku_id String,
    hu_kind_id String,
    hu_state String,
    hu_attrs String,
    hu_created_at DateTime64(3),
    hu_updated_at DateTime64(3),
    hu_lock_task_id String,
    hu_effective_storage_id String,
    
    -- HU Kind fields
    hu_kind_code String,
    hu_kind_name String,
    hu_kind_attrs String,
    hu_kind_active Boolean,
    hu_kind_max_volume Float64,
    hu_kind_max_weight Float64,
    hu_kind_usage_type String,
    hu_kind_abbr String,
    hu_kind_length Float64,
    hu_kind_breadth Float64,
    hu_kind_height Float64,
    hu_kind_weight Float64,
    
    -- Storage fields
    storage_bin_code String,
    storage_bin_description String,
    storage_bin_status String,
    storage_bin_hu_id String,
    storage_multi_sku Boolean,
    storage_multi_batch Boolean,
    storage_picking_position Int32,
    storage_putaway_position Int32,
    storage_rank Int32,
    storage_aisle String,
    storage_bay String,
    storage_level String,
    storage_position String,
    storage_depth String,
    storage_max_sku_count Int32,
    storage_max_sku_batch_count Int32,
    storage_bin_type_id String,
    storage_bin_type_code String,
    storage_bin_type_description String,
    storage_max_volume_in_cc Float64,
    storage_max_weight_in_kg Float64,
    storage_pallet_capacity Int32,
    storage_hu_type String,
    storage_auxiliary_bin Boolean,
    storage_hu_multi_sku Boolean,
    storage_hu_multi_batch Boolean,
    storage_use_derived_pallet_best_fit Boolean,
    storage_only_full_pallet Boolean,
    storage_bin_type_active Boolean,
    storage_zone_id String,
    storage_zone_code String,
    storage_zone_description String,
    storage_zone_face String,
    storage_peripheral Boolean,
    storage_surveillance_config String,
    storage_zone_active Boolean,
    storage_area_id String,
    storage_area_code String,
    storage_area_description String,
    storage_area_type String,
    storage_rolling_days Int32,
    storage_area_active Boolean,
    storage_x1 Float64,
    storage_x2 Float64,
    storage_y1 Float64,
    storage_y2 Float64,
    storage_position_active Boolean,
    storage_attrs String,
    storage_bin_mapping String,
    storage_created_at DateTime64(3),
    storage_updated_at DateTime64(3),
    
    -- SKU fields
    sku_name String,
    sku_short_description String,
    sku_description String,
    sku_category String,
    sku_product String,
    sku_product_id String,
    sku_category_group String,
    sku_sub_brand String,
    sku_brand String,
    sku_fulfillment_type String,
    sku_inventory_type String,
    sku_shelf_life Int32,
    sku_handling_unit_type String,
    sku_cases_per_layer Int32,
    sku_layers Int32,
    sku_active_from DateTime64(3),
    sku_active_till DateTime64(3),
    sku_l0_units Int32,
    sku_l0_name String,
    sku_l0_weight Float64,
    sku_l0_volume Float64,
    sku_l0_length Float64,
    sku_l0_width Float64,
    sku_l0_height Float64,
    sku_l1_units Int32,
    sku_l1_name String,
    sku_l1_weight Float64,
    sku_l1_volume Float64,
    sku_l1_length Float64,
    sku_l1_width Float64,
    sku_l1_height Float64,
    sku_active Boolean,
    sku_created_at DateTime64(3),
    sku_updated_at DateTime64(3),
    
    -- Effective storage fields (denormalized)
    effective_storage_bin_code String,
    effective_storage_bin_description String,
    effective_storage_bin_status String,
    effective_storage_bin_hu_id String,
    effective_storage_multi_sku Boolean,
    effective_storage_multi_batch Boolean,
    effective_storage_picking_position Int32,
    effective_storage_putaway_position Int32,
    effective_storage_rank Int32,
    effective_storage_aisle String,
    effective_storage_bay String,
    effective_storage_level String,
    effective_storage_position String,
    effective_storage_depth String,
    effective_storage_max_sku_count Int32,
    effective_storage_max_sku_batch_count Int32,
    effective_storage_bin_type_id String,
    effective_storage_bin_type_code String,
    effective_storage_bin_type_description String,
    effective_storage_max_volume_in_cc Float64,
    effective_storage_max_weight_in_kg Float64,
    effective_storage_pallet_capacity Int32,
    effective_storage_hu_type String,
    effective_storage_auxiliary_bin Boolean,
    effective_storage_hu_multi_sku Boolean,
    effective_storage_hu_multi_batch Boolean,
    effective_storage_use_derived_pallet_best_fit Boolean,
    effective_storage_only_full_pallet Boolean,
    effective_storage_bin_type_active Boolean,
    effective_storage_zone_id String,
    effective_storage_zone_code String,
    effective_storage_zone_description String,
    effective_storage_zone_face String,
    effective_storage_peripheral Boolean,
    effective_storage_surveillance_config String,
    effective_storage_zone_active Boolean,
    effective_storage_area_id String,
    effective_storage_area_code String,
    effective_storage_area_description String,
    effective_storage_area_type String,
    effective_storage_rolling_days Int32,
    effective_storage_area_active Boolean,
    effective_storage_x1 Float64,
    effective_storage_x2 Float64,
    effective_storage_y1 Float64,
    effective_storage_y2 Float64,
    effective_storage_position_active Boolean,
    effective_storage_attrs String,
    effective_storage_bin_mapping String,
    effective_storage_created_at DateTime64(3),
    effective_storage_updated_at DateTime64(3),
    
    -- Outer HU fields
    outer_hu_code String,
    outer_hu_kind_id String,
    outer_hu_session_id String,
    outer_hu_task_id String,
    outer_hu_storage_id String,
    outer_hu_outer_hu_id String,
    outer_hu_state String,
    outer_hu_attrs String,
    outer_hu_created_at DateTime64(3),
    outer_hu_updated_at DateTime64(3),
    outer_hu_lock_task_id String,
    outer_hu_effective_storage_id String,
    outer_hu_kind_code String,
    outer_hu_kind_name String,
    outer_hu_kind_attrs String,
    outer_hu_kind_active Boolean,
    outer_hu_kind_max_volume Float64,
    outer_hu_kind_max_weight Float64,
    outer_hu_kind_usage_type String,
    outer_hu_kind_abbr String,
    outer_hu_kind_length Float64,
    outer_hu_kind_breadth Float64,
    outer_hu_kind_height Float64,
    outer_hu_kind_weight Float64,
    
    -- Processing metadata
    _snapshot_generated_at DateTime DEFAULT now() COMMENT 'When this snapshot was generated',
    _processed_at DateTime64(3) COMMENT 'Processing timestamp from source'
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(snapshot_timestamp)
ORDER BY (wh_id, snapshot_timestamp, hu_code, sku_code, uom, bucket, batch, price, inclusion_status, locked_by_task_id, lock_mode)
SETTINGS index_granularity = 8192
COMMENT 'Weekly cumulative inventory snapshots for performance optimization in 3-tier architecture';

-- Create indexes for efficient lookups
ALTER TABLE wms_inventory_weekly_snapshot
    ADD INDEX idx_sku_code sku_code TYPE bloom_filter(0.01) GRANULARITY 4,
    ADD INDEX idx_hu_code hu_code TYPE bloom_filter(0.01) GRANULARITY 4,
    ADD INDEX idx_batch batch TYPE bloom_filter(0.01) GRANULARITY 4,
    ADD INDEX idx_snapshot_timestamp snapshot_timestamp TYPE minmax GRANULARITY 1;

-- Tracking table for snapshot generation metadata
CREATE TABLE IF NOT EXISTS wms_inventory_snapshot_metadata
(
    snapshot_type String COMMENT 'Type of snapshot (weekly)',
    wh_id UInt64 COMMENT 'Warehouse ID',
    snapshot_date Date COMMENT 'Date of snapshot',
    snapshot_timestamp DateTime COMMENT 'Exact timestamp of snapshot',
    records_count UInt64 COMMENT 'Number of records in snapshot',
    generation_started_at DateTime COMMENT 'When generation started',
    generation_completed_at DateTime COMMENT 'When generation completed',
    generation_duration_seconds UInt32 COMMENT 'Time taken to generate snapshot',
    status String COMMENT 'Status (pending/in_progress/completed/failed)',
    error_message String COMMENT 'Error message if failed',
    created_by String DEFAULT 'system' COMMENT 'User or system that created snapshot',
    created_at DateTime DEFAULT now()
)
ENGINE = MergeTree()
ORDER BY (snapshot_type, wh_id, snapshot_date)
SETTINGS index_granularity = 8192
COMMENT 'Metadata tracking for inventory snapshot generation';