-- Test simple insert to isolate upsert key issue
-- This will help identify if the problem is with basic key derivation or complex joins

INSERT INTO `sbx-uat.encarta.public.skus_master`
SELECT 
    s.id,
    s.principal_id,
    s.principal_id AS node_id,
    NULL AS category,              -- Simplified - no joins
    NULL AS product,               -- Simplified - no joins
    NULL AS category_group,        -- Simplified - no joins
    NULL AS sub_brand,             -- Simplified - no joins
    NULL AS brand,                 -- Simplified - no joins
    s.code,
    s.name,
    s.short_description,
    s.description,
    s.fulfillment_type,
    s.avg_l0_per_put,
    s.inventory_type,
    s.shelf_life,
    s.identifier1,
    s.identifier2,
    s.tag1,
    s.tag2,
    s.tag3,
    s.tag4,
    s.tag5,
    s.tag6,
    s.tag7,
    s.tag8,
    s.tag9,
    s.handling_unit_type,
    s.cases_per_layer,
    s.layers,
    s.active_from,
    s.active_till,
    0 AS l0_units,                 -- Simplified - no UOM joins
    0 AS l1_units,
    0 AS l2_units,
    0 AS l2_units_final,
    0 AS l3_units,
    0 AS l3_units_final,
    NULL AS l0_name,               -- All UOM fields as NULL
    NULL AS l0_weight,
    NULL AS l0_volume,
    NULL AS l0_package_type,
    NULL AS l0_length,
    NULL AS l0_width,
    NULL AS l0_height,
    NULL AS l0_packing_efficiency,
    NULL AS l0_itf_code,
    NULL AS l0_erp_weight,
    NULL AS l0_erp_volume,
    NULL AS l0_erp_length,
    NULL AS l0_erp_width,
    NULL AS l0_erp_height,
    NULL AS l0_text_tag1,
    NULL AS l0_text_tag2,
    NULL AS l0_image,
    NULL AS l0_num_tag1,
    NULL AS l1_name,
    NULL AS l1_weight,
    NULL AS l1_volume,
    NULL AS l1_package_type,
    NULL AS l1_length,
    NULL AS l1_width,
    NULL AS l1_height,
    NULL AS l1_packing_efficiency,
    NULL AS l1_itf_code,
    NULL AS l1_erp_weight,
    NULL AS l1_erp_volume,
    NULL AS l1_erp_length,
    NULL AS l1_erp_width,
    NULL AS l1_erp_height,
    NULL AS l1_text_tag1,
    NULL AS l1_text_tag2,
    NULL AS l1_image,
    NULL AS l1_num_tag1,
    NULL AS l2_name,
    NULL AS l2_weight,
    NULL AS l2_volume,
    NULL AS l2_package_type,
    NULL AS l2_length,
    NULL AS l2_width,
    NULL AS l2_height,
    NULL AS l2_packing_efficiency,
    NULL AS l2_itf_code,
    NULL AS l2_erp_weight,
    NULL AS l2_erp_volume,
    NULL AS l2_erp_length,
    NULL AS l2_erp_width,
    NULL AS l2_erp_height,
    NULL AS l2_text_tag1,
    NULL AS l2_text_tag2,
    NULL AS l2_image,
    NULL AS l2_num_tag1,
    NULL AS l3_name,
    NULL AS l3_weight,
    NULL AS l3_volume,
    NULL AS l3_package_type,
    NULL AS l3_length,
    NULL AS l3_width,
    NULL AS l3_height,
    NULL AS l3_packing_efficiency,
    NULL AS l3_itf_code,
    NULL AS l3_erp_weight,
    NULL AS l3_erp_volume,
    NULL AS l3_erp_length,
    NULL AS l3_erp_width,
    NULL AS l3_erp_height,
    NULL AS l3_text_tag1,
    NULL AS l3_text_tag2,
    NULL AS l3_image,
    NULL AS l3_num_tag1,
    COALESCE(s.active, FALSE) AS active,
    '{}' AS classifications,       -- Simplified - no classification joins
    '{}' AS product_classifications, -- Simplified - no classification joins
    COALESCE(s.is_deleted, FALSE) AS is_deleted,
    s.updated_at
FROM `sbx-uat.encarta.public.skus` s;
