apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-config
  namespace: flink-studio
  labels:
    app.kubernetes.io/name: hive-config
    app.kubernetes.io/component: configuration
data:
  hive-site.xml: |
    <?xml version="1.0"?>
    <configuration>
      <!-- Metastore Configuration -->
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:derby:memory:metastore_db;create=true</value>
        <description>JDBC connect string for a JDBC metastore</description>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.apache.derby.jdbc.EmbeddedDriver</value>
        <description>Driver class name for a JDBC metastore</description>
      </property>
      <property>
        <name>hive.metastore.schema.verification</name>
        <value>false</value>
      </property>
      <property>
        <name>hive.metastore.uris</name>
        <value></value>
        <description>Thrift URI for the remote metastore. Used by metastore client to connect to remote metastore.</description>
      </property>
      
      <!-- GCS Warehouse Configuration -->
      <property>
        <name>hive.metastore.warehouse.dir</name>
        <value>gs://sbx-stag-flink-storage/hive-warehouse</value>
        <description>Location of default database for the warehouse</description>
      </property>
      
      <!-- GCS Configuration -->
      <property>
        <name>fs.gs.impl</name>
        <value>com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem</value>
      </property>
      <property>
        <name>fs.AbstractFileSystem.gs.impl</name>
        <value>com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS</value>
      </property>
      <property>
        <name>fs.gs.project.id</name>
        <value>sbx-stag</value>
      </property>
      <property>
        <name>fs.gs.auth.service.account.enable</name>
        <value>true</value>
      </property>
      <property>
        <name>fs.gs.auth.service.account.json.keyfile</name>
        <value>/opt/flink/gcp/service-account.json</value>
      </property>
      
      <!-- Additional Hive Configuration -->
      <property>
        <name>hive.exec.dynamic.partition</name>
        <value>true</value>
      </property>
      <property>
        <name>hive.exec.dynamic.partition.mode</name>
        <value>nonstrict</value>
      </property>
    </configuration>
