apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-config
  namespace: flink-studio
  labels:
    app.kubernetes.io/name: hadoop-config
    app.kubernetes.io/component: configuration
data:
  core-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
      <!-- Google Cloud Storage Configuration -->
      <property>
        <name>fs.gs.impl</name>
        <value>com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem</value>
        <description>The FileSystem for gs: URIs</description>
      </property>
      
      <property>
        <name>fs.AbstractFileSystem.gs.impl</name>
        <value>com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS</value>
        <description>The AbstractFileSystem for gs: URIs</description>
      </property>
      
      <property>
        <name>fs.gs.project.id</name>
        <value>sbx-stag</value>
        <description>Google Cloud Project ID</description>
      </property>
      
      <!-- Authentication via service account JSON key -->
      <property>
        <name>fs.gs.auth.service.account.enable</name>
        <value>true</value>
        <description>Enable service account authentication</description>
      </property>
      
      <property>
        <name>fs.gs.auth.service.account.json.keyfile</name>
        <value>/opt/flink/gcp/service-account.json</value>
        <description>Path to service account JSON key file</description>
      </property>
      
      <!-- Performance tuning -->
      <property>
        <name>fs.gs.block.size</name>
        <value>134217728</value>
        <description>Block size for GCS (128MB)</description>
      </property>
      
      <property>
        <name>fs.gs.io.buffersize</name>
        <value>8388608</value>
        <description>Buffer size for GCS I/O (8MB)</description>
      </property>
    </configuration>
