apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-sql-gateway
  namespace: flink-studio
  labels:
    app.kubernetes.io/name: flink-sql-gateway
    app.kubernetes.io/component: sql-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flink-sql-gateway
      app.kubernetes.io/component: sql-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flink-sql-gateway
        app.kubernetes.io/component: sql-gateway
    spec:
      serviceAccountName: flink
      containers:
        - name: flink-sql-gateway
          image: asia-docker.pkg.dev/sbx-ci-cd/public/flink:latest
          imagePullPolicy: Always
          command: ["/opt/flink/bin/sql-gateway.sh"]
          args: 
            - "start-foreground"
            - "-Dsql-gateway.endpoint.rest.address=0.0.0.0"
            - "-Dsql-gateway.endpoint.rest.port=80"
            - "-Drest.address=flink-session-cluster-rest"
            - "-Drest.port=8081"
          ports:
            - containerPort: 80
              name: rest-api
          env:
            - name: HADOOP_CONF_DIR
              value: /opt/hadoop/conf
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /opt/flink/gcp/service-account.json
            - name: GOOGLE_CLOUD_PROJECT
              value: sbx-stag
            - name: FLINK_PROPERTIES
              value: |
                rest.address: flink-session-cluster-rest
                rest.port: 8081
                # Hive Catalog Configuration
                table.sql-dialect: default
                # GCS Configuration for Hive warehouse
                fs.gs.impl: com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem
                fs.AbstractFileSystem.gs.impl: com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS
                fs.gs.project.id: sbx-stag
                fs.gs.auth.service.account.enable: true
                fs.gs.auth.service.account.json.keyfile: /opt/flink/gcp/service-account.json
                # Kafka Configuration
                kafka.bootstrap.servers: bootstrap.sbx-kafka-cluster.asia-south1.managedkafka.sbx-stag.cloud.goog:9092
                kafka.security.protocol: SASL_SSL
                kafka.sasl.mechanism: OAUTHBEARER
                kafka.sasl.jaas.config: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;
                kafka.sasl.login.callback.handler.class: com.google.cloud.kafka.OAuthBearerTokenCallbackHandler
          volumeMounts:
            - name: gcp-service-account
              mountPath: /opt/flink/gcp
              readOnly: true
            - name: hadoop-config
              mountPath: /opt/hadoop/conf
              readOnly: true
            - name: hive-config
              mountPath: /opt/hive-conf
              readOnly: true
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /v1/info
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /v1/info
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: gcp-service-account
          secret:
            secretName: gcp-service-account-key
        - name: hadoop-config
          configMap:
            name: hadoop-config
        - name: hive-config
          configMap:
            name: hive-config
---
apiVersion: v1
kind: Service
metadata:
  name: flink-sql-gateway
  namespace: flink-studio
  labels:
    app.kubernetes.io/name: flink-sql-gateway
    app.kubernetes.io/component: sql-gateway
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: rest-api
  selector:
    app.kubernetes.io/name: flink-sql-gateway
    app.kubernetes.io/component: sql-gateway
