apiVersion: v1
kind: ResourceQuota
metadata:
  name: flink-studio-quota
  namespace: flink-studio
  labels:
    app.kubernetes.io/name: flink-studio
    app.kubernetes.io/component: resource-quota
spec:
  hard:
    requests.cpu: "64"
    requests.memory: 192Gi
    limits.cpu: "64"
    limits.memory: 192Gi
    persistentvolumeclaims: "100"
    pods: "100"
    services: "50"
    secrets: "50"
    configmaps: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: flink-studio-limits
  namespace: flink-studio
  labels:
    app.kubernetes.io/name: flink-studio
    app.kubernetes.io/component: limit-range
spec:
  limits:
    - default:
        cpu: "1"
        memory: 2Gi
      defaultRequest:
        cpu: "100m"
        memory: 256Mi
      max:
        cpu: "16"
        memory: 32Gi
      min:
        cpu: "50m"
        memory: 128Mi
      type: Container
    - max:
        storage: 500Gi
      min:
        storage: 1Gi
      type: PersistentVolumeClaim
