CREATE TABLE IF NOT EXISTS wms_ob_order
(
    id String DEFAULT '',
    whId Int64 DEFAULT 0,
    tripCode String DEFAULT '',
    code String DEFAULT '',
    retailerId Int32 DEFAULT 0,
    retailerCode String DEFAULT '',
    retailerChannel String DEFAULT '',
    retailerName String DEFAULT '',
    tripDate DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    deliveryDate DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    priority Int32 DEFAULT 0,
    sessionId String DEFAULT '',
    active Bool DEFAULT true,
    createdAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    sessionCreatedAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    salesmanCode String DEFAULT '',
    ginStatus String DEFAULT 'PENDING',
    ginTriggeredAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    cancelledAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    tripPriority Int32 DEFAULT 0,
    truckType String DEFAULT '',
    transporterCode String DEFAULT '',
    advanceReplenSessionId String DEFAULT '',
    orderType String DEFAULT '',
    loadingSeq Int32 DEFAULT 0,
    latestPickDate Date DEFAULT toDate('1970-01-01'),
    earliestPickDate Date DEFAULT toDate('1970-01-01'),
    documentType String DEFAULT 'DELIVERY_ORDER',
    orderReferenceId String DEFAULT '',
    orderReferenceCode String DEFAULT '',
    erpChannel String DEFAULT '',
    delinkedAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    relinkedAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    erpInvoiceCode String DEFAULT '',
    provisionalGinStatus String DEFAULT 'PENDING',
    provisionalGinTriggeredAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    erpInvoiceCodes String DEFAULT '[]',
)
ENGINE = ReplacingMergeTree(createdAt)
ORDER BY (whId, id)
SETTINGS index_granularity = 8192;


CREATE TABLE "public"."ob_order" (
    "id" uuid NOT NULL,
    "whId" int8 NOT NULL,
    "tripCode" text,
    "code" text NOT NULL,
    "retailerId" int4 NOT NULL,
    "retailerCode" text NOT NULL,
    "retailerChannel" text,
    "retailerName" text NOT NULL DEFAULT ''::text,
    "tripDate" timestamptz,
    "deliveryDate" timestamptz NOT NULL,
    "priority" int4 NOT NULL,
    "sessionId" uuid,
    "active" bool NOT NULL DEFAULT true,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "sessionCreatedAt" timestamptz,
    "salesmanCode" text NOT NULL,
    "ginStatus" text NOT NULL DEFAULT 'PENDING'::text,
    "ginTriggeredAt" timestamptz,
    "cancelledAt" timestamptz,
    "tripPriority" int4,
    "truckType" text,
    "transporterCode" text,
    "advanceReplenSessionId" uuid,
    "orderType" text,
    "loadingSeq" int4,
    "latestPickDate" date,
    "earliestPickDate" date,
    "documentType" text NOT NULL DEFAULT 'DELIVERY_ORDER'::text,
    "orderReferenceId" uuid,
    "orderReferenceCode" text,
    "erpChannel" text,
    "delinkedAt" timestamptz,
    "relinkedAt" timestamptz,
    "erpInvoiceCode" text,
    "provisionalGinStatus" text NOT NULL DEFAULT 'PENDING'::text,
    "provisionalGinTriggeredAt" timestamptz,
    "erpInvoiceCodes" jsonb DEFAULT '[]'::jsonb,
    PRIMARY KEY ("id")
);