-- ClickHouse table for Inventory

CREATE TABLE IF NOT EXISTS wms_inventory
(
    whId Int64 DEFAULT 0,
    id String DEFAULT '',
    huId String DEFAULT '',
    huCode String DEFAULT '',
    huKind String DEFAULT '',
    huWeight Float64 DEFAULT 0.0,
    huOnHold Bool DEFAULT false,
    huRendered Bool DEFAULT false,
    huLockTaskId String DEFAULT '',
    isBinHu Bool DEFAULT false,
    areaType String DEFAULT '',
    areaCode String DEFAULT '',
    zoneFace String DEFAULT '',
    zoneCode String DEFAULT '',
    binType String DEFAULT '',
    binCode String DEFAULT '',
    binStatus String DEFAULT '',
    binCapacity Int32 DEFAULT 0,
    outerHUCode String DEFAULT '',
    outerHUKind String DEFAULT '',
    skuId String DEFAULT '',
    skuCode String DEFAULT '',
    skuName String DEFAULT '',
    skuInventoryType String DEFAULT '',
    productCode String DEFAULT '',
    category String DEFAULT '',
    categoryGroup String DEFAULT '',
    skuClassification String DEFAULT '{}', -- JSON
    plantCode String DEFAULT '',
    brand String DEFAULT '',
    bucket String DEFAULT '',
    inclusionStatus String DEFAULT '',
    uom String DEFAULT '',
    batch String DEFAULT '',
    manufactureDate Date DEFAULT toDate('1970-01-01'),
    expiryDate Date DEFAULT toDate('1970-01-01'),
    price String DEFAULT '',
    quantLockMode String DEFAULT '',
    qty Int32 DEFAULT 0,
    qtyL0 Int64 DEFAULT 0,
    huUpdatedAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    quantUpdatedAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    updatedAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    binTypeId String DEFAULT '',
    usage Float64 DEFAULT 0.0,
    huCountBlocked Bool DEFAULT false,
    iloc String DEFAULT '',
    binId String DEFAULT '',
    outerHuLockTaskId String DEFAULT '',
    uomName String DEFAULT ''
)
ENGINE = ReplacingMergeTree(updatedAt)
ORDER BY (id)
SETTINGS index_granularity = 8192;