-- ClickHouse Materialized View for WMS Pick-Drop Enriched
-- Enriches pick_drop_staging with dimension data
-- NOTE: Removed session, task, trip, trip_relation enrichment
-- Only enriches with workers, handling_units, and SKU data (for picks only)

CREATE MATERIALIZED VIEW IF NOT EXISTS wms_pick_drop_enriched_mv
ENGINE = ReplacingMergeTree(event_time)
PARTITION BY toYYYYMM(pick_item_created_at)  
ORDER BY (wh_id, pick_item_created_at, pick_item_id, drop_item_id)
AS
SELECT
    -- Core identifiers
    pb.wh_id,
    COALESCE(sku.principal_id, 0) AS principal_id,
    pb.pick_item_id,
    pb.drop_item_id,
    
    -- All fields from pick_drop_basic
    pb.picked_bin,
    pb.picked_sku_id,
    pb.picked_batch,
    pb.picked_uom,
    pb.overall_qty,
    pb.qty,
    pb.hu_code,
    pb.destination_bin_code,
    pb.pick_item_created_at,
    pb.picked_qty,
    pb.picked_at,
    pb.picked_by_worker_id,
    pb.moved_at,
    pb.processed_at,
    pb.picked_hu_eq_uom,
    pb.picked_has_inner_hus,
    pb.picked_inner_hu_eq_uom,
    pb.picked_bin_assigned_at,
    pb.scan_source_hu_kind,
    pb.pick_source_hu_kind,
    pb.carrier_hu_kind,
    pb.scanned_source_hu_code,
    pb.picked_source_hu_code,
    pb.carrier_hu_code,
    pb.hu_kind,
    pb.source_hu_eq_uom,
    pb.pick_item_updated_at,
    pb.eligible_drop_locations,
    pb.parent_item_id,
    pb.old_batch,
    pb.dest_bucket,
    pb.original_source_bin_code,
    pb.lm_trip_id,
    pb.picked_inner_hu_code,
    pb.picked_inner_hu_kind_code,
    pb.picked_quant_bucket,
    pb.pick_auto_complete,
    pb.pick_hu,
    pb.short_allocation_reason,
    pb.pd_previous_task_id AS drop_item_previous_task_id,
    pb.dropped_sku_id,
    pb.dropped_batch,
    pb.dropped_uom,
    pb.drop_bucket,
    pb.picked_hu_code,
    pb.dropped_bin_code,
    pb.dropped_qty,
    pb.dropped_at,
    pb.drop_item_updated_at,
    pb.drop_hu_in_bin,
    pb.scan_dest_hu,
    pb.allow_hu_break,
    pb.dropped_has_inner_hus,
    pb.scan_inner_hus,
    pb.dropped_hu_eq_uom,
    pb.dest_hu_code,
    pb.dropped_inner_hu_id,
    pb.dropped_inner_hu_eq_uom,
    pb.dest_bin_assigned_at,
    pb.drop_uom,
    pb.drop_parent_item_id,
    pb.hu_broken,
    pb.drop_original_source_bin_code,
    pb.processed_for_loading_at,
    pb.drop_quant_bucket,
    pb.drop_inner_hu_code,
    pb.dropped_inner_hu_kind_code,
    pb.drop_inner_hu,
    pb.allow_inner_hu_break,
    pb.inner_hu_broken,
    pb.drop_auto_complete,
    pb.quant_slotting_for_hus,
    pb.processed_on_drop_at,
    pb.allow_hu_break_v2,
    
    -- Additional Pick Items columns
    pb.bin_id,
    pb.bin_hu_id,
    pb.destination_bin_id,
    pb.destination_bin_hu_id,
    pb.pick_deactivated_at,
    pb.pick_deactivated_by,
    pb.moved_by,
    pb.scanned_source_hu_id,
    pb.picked_source_hu_id,
    pb.carrier_hu_id,
    pb.original_source_bin_id,
    pb.inner_hu_id,
    pb.inner_hu_kind_id,
    pb.pd_previous_task_id,
    pb.input_source_bin_id,
    pb.provisional_item_id,
    pb.input_dest_hu_id,
    pb.pick_item_kind,
    pb.tp_assigned_at,
    pb.leg_index,
    pb.last_leg,
    pb.ep_assigned_at,
    pb.carrier_hu_formed_id,
    pb.hu_index,
    pb.pick_sequence,
    pb.carrier_hu_force_closed,
    pb.input_dest_bin_id,
    pb.inner_hu_index,
    pb.inner_carrier_hu_key,
    pb.inner_carrier_hu_formed_id,
    pb.inner_carrier_hu_id,
    pb.inner_carrier_hu_code,
    pb.inner_carrier_hu_kind,
    pb.induction_id,
    pb.inner_carrier_hu_force_closed,
    pb.mhe_id,
    pb.pick_attrs,
    pb.iloc,
    pb.dest_iloc,
    
    -- Additional Drop Items columns
    pb.source_bin_id,
    pb.source_bin_hu_id,
    pb.drop_bin_id,
    pb.drop_bin_hu_id,
    pb.drop_created_at,
    pb.drop_deactivated_at,
    pb.drop_deactivated_by,
    pb.dropped_by_worker_id,
    pb.dest_hu_id,
    pb.source_bucket,
    pb.original_destination_bin_id,
    pb.drop_lm_trip_id,
    pb.processed_for_pick_at,
    pb.drop_provisional_item_id,
    pb.drop_input_dest_hu_id,
    pb.drop_leg_index,
    pb.drop_last_leg,
    pb.drop_input_dest_bin_id,
    pb.drop_induction_id,
    pb.drop_attrs,
    pb.drop_mhe_id,
    pb.drop_iloc,
    pb.source_iloc,
    
    -- Mapping fields
    pb.mapping_id,
    pb.mapping_created_at,
    
    -- Worker enrichment (picked_by)
    w.code AS worker_code,
    w.name AS worker_name,
    w.phone AS worker_phone,
    w.supervisor AS worker_supervisor,
    w.active AS worker_active,
    
    -- Handling Unit enrichment (for dropped_inner_hu_id)
    hu.code AS dropped_hu_code,
    hu.kindId AS dropped_hu_kind_id,
    hu.sessionId AS dropped_hu_session_id,
    hu.taskId AS dropped_hu_task_id,
    hu.storageId AS dropped_hu_storage_id,
    hu.outerHuId AS dropped_hu_outer_hu_id,
    hu.state AS dropped_hu_state,
    hu.attrs AS dropped_hu_attrs,
    hu.lockTaskId AS dropped_hu_lock_task_id,
    hu.effectiveStorageId AS dropped_hu_effective_storage_id,
    hu.createdAt AS dropped_hu_created_at,
    hu.updatedAt AS dropped_hu_updated_at,
    
    -- Picked SKU enrichment (ONLY for pick events, not drop) from combined view
    sku.principal_id AS picked_sku_principal_id,
    sku.node_id AS picked_sku_node_id,
    sku.category AS picked_sku_category,
    sku.product AS picked_sku_product,
    sku.product_id AS picked_sku_product_id,
    sku.category_group AS picked_sku_category_group,
    sku.sub_brand AS picked_sku_sub_brand,
    sku.brand AS picked_sku_brand,
    sku.code AS picked_sku_code,
    sku.name AS picked_sku_name,
    sku.short_description AS picked_sku_short_description,
    sku.description AS picked_sku_description,
    sku.fulfillment_type AS picked_sku_fulfillment_type,
    sku.inventory_type AS picked_sku_inventory_type,
    sku.shelf_life AS picked_sku_shelf_life,
    sku.tag1 AS picked_sku_tag1,
    sku.tag2 AS picked_sku_tag2,
    sku.tag3 AS picked_sku_tag3,
    sku.tag4 AS picked_sku_tag4,
    sku.tag5 AS picked_sku_tag5,
    sku.handling_unit_type AS picked_sku_handling_unit_type,
    sku.cases_per_layer AS picked_sku_cases_per_layer,
    sku.layers AS picked_sku_layers,
    sku.l0_units AS picked_sku_l0_units,
    sku.l1_units AS picked_sku_l1_units,
    sku.l2_units AS picked_sku_l2_units,
    sku.l3_units AS picked_sku_l3_units,
    sku.l0_name AS picked_sku_l0_name,
    sku.l0_weight AS picked_sku_l0_weight,
    sku.l0_volume AS picked_sku_l0_volume,
    
    -- Event time for versioning
    pb.event_time
FROM wms_pick_drop_staging pb
-- Worker enrichment
LEFT JOIN wms_workers w ON pb.picked_by_worker_id = w.id
-- Handling Unit enrichment  
LEFT JOIN wms_handling_units hu ON pb.dropped_inner_hu_id = hu.id
-- SKU enrichment (ONLY for picks, not drops) using combined parameterized view
LEFT JOIN encarta_skus_combined(node_id = pb.wh_id) sku ON pb.picked_sku_id = sku.sku_id;