-- ClickHouse table for WMS Pick-Drop Staging
-- Raw pick-drop data from Flink processing pipeline
-- Source: sbx_uat.wms.flink.pick_drop_staging

CREATE TABLE IF NOT EXISTS wms_pick_drop_staging
(
    -- Primary Keys
    pick_item_id String,
    drop_item_id String,
    
    -- Core IDs
    wh_id Int64 DEFAULT 0,
    session_id String DEFAULT '',
    task_id String DEFAULT '',
    lm_trip_id String DEFAULT '',
    
    -- Pick item fields
    picked_bin String DEFAULT '',
    picked_sku_id String DEFAULT '',
    picked_batch String DEFAULT '',
    picked_uom String DEFAULT '',
    overall_qty Int32 DEFAULT 0,
    qty Int32 DEFAULT 0,
    hu_code String DEFAULT '',
    destination_bin_code String DEFAULT '',
    pick_item_created_at DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    picked_qty Int32 DEFAULT 0,
    picked_at DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    picked_by_worker_id String DEFAULT '',
    moved_at DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    processed_at DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    picked_hu_eq_uom String DEFAULT '',
    picked_has_inner_hus Bool DEFAULT false,
    picked_inner_hu_eq_uom String DEFAULT '',
    picked_bin_assigned_at DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    scan_source_hu_kind String DEFAULT '',
    pick_source_hu_kind String DEFAULT '',
    carrier_hu_kind String DEFAULT '',
    scanned_source_hu_code String DEFAULT '',
    picked_source_hu_code String DEFAULT '',
    carrier_hu_code String DEFAULT '',
    hu_kind String DEFAULT '',
    source_hu_eq_uom String DEFAULT '',
    pick_item_updated_at DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    eligible_drop_locations String DEFAULT '',
    parent_item_id String DEFAULT '',
    old_batch String DEFAULT '',
    dest_bucket String DEFAULT '',
    original_source_bin_code String DEFAULT '',
    picked_inner_hu_code String DEFAULT '',
    picked_inner_hu_kind_code String DEFAULT '',
    picked_quant_bucket String DEFAULT '',
    pick_auto_complete Bool DEFAULT false,
    pick_hu Bool DEFAULT false,
    short_allocation_reason String DEFAULT '',
    
    -- Drop item fields
    dropped_sku_id String DEFAULT '',
    dropped_batch String DEFAULT '',
    dropped_uom String DEFAULT '',
    drop_bucket String DEFAULT '',
    picked_hu_code String DEFAULT '',
    dropped_bin_code String DEFAULT '',
    dropped_qty Int32 DEFAULT 0,
    dropped_at DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    drop_item_updated_at DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    drop_hu_in_bin Bool DEFAULT false,
    scan_dest_hu Bool DEFAULT false,
    allow_hu_break Bool DEFAULT false,
    dropped_has_inner_hus Bool DEFAULT false,
    scan_inner_hus Bool DEFAULT false,
    dropped_hu_eq_uom String DEFAULT '',
    dest_hu_code String DEFAULT '',
    dropped_inner_hu_id String DEFAULT '',
    dropped_inner_hu_eq_uom String DEFAULT '',
    dest_bin_assigned_at DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    drop_uom String DEFAULT '',
    drop_parent_item_id String DEFAULT '',
    hu_broken Bool DEFAULT false,
    drop_original_source_bin_code String DEFAULT '',
    processed_for_loading_at DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    drop_quant_bucket String DEFAULT '',
    drop_inner_hu_code String DEFAULT '',
    dropped_inner_hu_kind_code String DEFAULT '',
    drop_inner_hu Bool DEFAULT false,
    allow_inner_hu_break Bool DEFAULT false,
    inner_hu_broken Bool DEFAULT false,
    drop_auto_complete Bool DEFAULT false,
    quant_slotting_for_hus Bool DEFAULT false,
    processed_on_drop_at DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    allow_hu_break_v2 Bool DEFAULT false,
    deactivated_at DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    
    -- Mapping fields
    mapping_id String DEFAULT '',
    mapping_created_at DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    
    -- Additional fields
    bin_id String DEFAULT '',
    bin_hu_id String DEFAULT '',
    destination_bin_id String DEFAULT '',
    destination_bin_hu_id String DEFAULT '',
    pick_deactivated_at DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    pick_deactivated_by String DEFAULT '',
    moved_by String DEFAULT '',
    scanned_source_hu_id String DEFAULT '',
    picked_source_hu_id String DEFAULT '',
    carrier_hu_id String DEFAULT '',
    original_source_bin_id String DEFAULT '',
    inner_hu_id String DEFAULT '',
    inner_hu_kind_id String DEFAULT '',
    pd_previous_task_id String DEFAULT '',
    input_source_bin_id String DEFAULT '',
    provisional_item_id String DEFAULT '',
    input_dest_hu_id String DEFAULT '',
    pick_item_kind String DEFAULT '',
    tp_assigned_at DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    leg_index Int32 DEFAULT 0,
    last_leg Bool DEFAULT false,
    ep_assigned_at DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    carrier_hu_formed_id String DEFAULT '',
    hu_index Int32 DEFAULT 0,
    pick_sequence Int32 DEFAULT 0,
    carrier_hu_force_closed Bool DEFAULT false,
    input_dest_bin_id String DEFAULT '',
    inner_hu_index Int32 DEFAULT 0,
    inner_carrier_hu_key String DEFAULT '',
    inner_carrier_hu_formed_id String DEFAULT '',
    inner_carrier_hu_id String DEFAULT '',
    inner_carrier_hu_code String DEFAULT '',
    inner_carrier_hu_kind String DEFAULT '',
    induction_id String DEFAULT '',
    inner_carrier_hu_force_closed Bool DEFAULT false,
    mhe_id String DEFAULT '',
    pick_attrs String DEFAULT '',
    iloc String DEFAULT '',
    dest_iloc String DEFAULT '',
    source_bin_id String DEFAULT '',
    source_bin_hu_id String DEFAULT '',
    drop_bin_id String DEFAULT '',
    drop_bin_hu_id String DEFAULT '',
    drop_created_at DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    drop_deactivated_at DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    drop_deactivated_by String DEFAULT '',
    dropped_by_worker_id String DEFAULT '',
    dest_hu_id String DEFAULT '',
    source_bucket String DEFAULT '',
    original_destination_bin_id String DEFAULT '',
    drop_lm_trip_id String DEFAULT '',
    processed_for_pick_at DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    drop_provisional_item_id String DEFAULT '',
    drop_input_dest_hu_id String DEFAULT '',
    drop_leg_index Int32 DEFAULT 0,
    drop_last_leg Bool DEFAULT false,
    drop_input_dest_bin_id String DEFAULT '',
    drop_induction_id String DEFAULT '',
    drop_attrs String DEFAULT '',
    drop_mhe_id String DEFAULT '',
    drop_iloc String DEFAULT '',
    source_iloc String DEFAULT '',
    -- Event time (maximum of pick and drop updated_at)
    event_time DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    
    -- Indexes for enrichment MV JOIN performance
    INDEX idx_wh_id wh_id TYPE minmax GRANULARITY 1,
    INDEX idx_picked_by_worker_id picked_by_worker_id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_dropped_inner_hu_id dropped_inner_hu_id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_picked_sku_id picked_sku_id TYPE bloom_filter(0.01) GRANULARITY 1
)
ENGINE = ReplacingMergeTree(event_time)
PARTITION BY toYYYYMM(pick_item_created_at)
ORDER BY (wh_id, pick_item_created_at, pick_item_id, drop_item_id)
SETTINGS index_granularity = 8192
COMMENT 'WMS Pick-Drop Staging data from Flink pipeline - Source table for enrichment MV';

-- Projection optimized for enrichment MV access pattern
ALTER TABLE wms_pick_drop_staging ADD PROJECTION proj_for_enrichment (
    SELECT *
    ORDER BY (wh_id, pick_item_id, drop_item_id)
);