-- Create final summary table structure
CREATE TABLE `sbx-uat.wms.public.pick_drop_item_summary`
(
    pick_item_id STRING,
    drop_item_id STRING,
    wh_id BIGINT,
    picked_bin STRING,
    picked_sku STRING,
    picked_batch STRING,
    picked_uom STRING,
    overall_qty INT,
    qty INT,
    hu_code STRING,
    destination_bin_code STRING,
    pick_item_created_at TIMESTAMP_LTZ(3),
    picked_qty INT,
    picked_at TIMESTAMP_LTZ(3),
    worker_code STRING,
    moved_at TIMESTAMP_LTZ(3),
    processed_at TIMESTAMP_LTZ(3),
    picked_hu_eq_uom STRING,
    picked_has_inner_hus BOOLEAN,
    picked_inner_hu_eq_uom STRING,
    picked_bin_assigned_at TIMESTAMP_LTZ(3),
    scan_source_hu_kind STRING,
    pick_source_hu_kind STRING,
    carrier_hu_kind STRING,
    scanned_source_hu_code STRING,
    picked_source_hu_code STRING,
    carrier_hu_code STRING,
    hu_kind STRING,
    source_hu_eq_uom STRING,
    pick_item_updated_at TIMESTAMP_LTZ(3),
    eligible_drop_locations STRING,
    parent_item_id STRING,
    old_batch STRING,
    dest_bucket STRING,
    original_source_bin_code STRING,
    lm_trip_id STRING,
    picked_inner_hu_code STRING,
    picked_inner_hu_kind_code STRING,
    picked_quant_bucket STRING,
    pick_auto_complete BOOLEAN,
    pick_hu BOOLEAN,
    short_allocation_reason STRING,
    drop_item_previous_task_id STRING,
    dropped_sku STRING,
    dropped_batch STRING,
    dropped_uom STRING,
    drop_bucket STRING,
    picked_hu_code STRING,
    dropped_bin_code STRING,
    dropped_qty INT,
    dropped_at TIMESTAMP_LTZ(3),
    drop_item_updated_at TIMESTAMP_LTZ(3),
    drop_hu_in_bin BOOLEAN,
    scan_dest_hu BOOLEAN,
    allow_hu_break BOOLEAN,
    dropped_has_inner_hus BOOLEAN,
    scan_inner_hus BOOLEAN,
    dropped_hu_eq_uom STRING,
    dest_hu_code STRING,
    dropped_inner_hu_code STRING,
    dropped_inner_hu_eq_uom STRING,
    dest_bin_assigned_at TIMESTAMP_LTZ(3),
    drop_uom STRING,
    drop_parent_item_id STRING,
    hu_broken BOOLEAN,
    drop_original_source_bin_code STRING,
    processed_for_loading_at TIMESTAMP_LTZ(3),
    drop_quant_bucket STRING,
    drop_inner_hu_code STRING,
    dropped_inner_hu_kind_code STRING,
    drop_inner_hu BOOLEAN,
    allow_inner_hu_break BOOLEAN,
    inner_hu_broken BOOLEAN,
    drop_auto_complete BOOLEAN,
    quant_slotting_for_hus BOOLEAN,
    processed_on_drop_at TIMESTAMP_LTZ(3),
    allow_hu_break_v2 BOOLEAN,
    task_kind STRING,
    task_code STRING,
    task_sequence INT,
    task_state STRING,
    task_attrs STRING,
    task_progress STRING,
    task_created_at TIMESTAMP_LTZ(3),
    task_updated_at TIMESTAMP_LTZ(3),
    allow_force_complete BOOLEAN,
    wave INT,
    force_completed BOOLEAN,
    task_subkind STRING,
    `label` STRING,
    session_kind STRING,
    session_code STRING,
    session_attrs STRING,
    session_created_at TIMESTAMP_LTZ(3),
    session_updated_at TIMESTAMP_LTZ(3),
    active BOOLEAN,
    session_state STRING,
    session_progress STRING,
    session_auto_complete BOOLEAN,
    worker_attrs STRING,
    worker_name STRING,
    supervisor BOOLEAN,
    product_code STRING,
    principal_id BIGINT,
    sku_id STRING,
    sku_code STRING,
    category STRING,
    class_value STRING,
    node_id BIGINT,
    final_class STRING,
    encarta_uom_id STRING,
    encarta_uom_code STRING,
    ibc STRING,
    case_count STRING,
    pallet_count STRING,
    lm_trip_code STRING,
    lm_trip_priority INT,
    lm_dockdoor STRING,
    lm_vehicle_no STRING,
    lm_vehicle_type STRING,
    lm_delivery_date DATE,
    xdock STRING,
    mm_trip_code STRING,
    mm_trip_priority INT,
    mm_dockdoor STRING,
    mm_vehicle_no STRING,
    mm_vehicle_type STRING,
    mm_delivery_date DATE,
    PRIMARY KEY (pick_item_id, drop_item_id) NOT ENFORCED
) WITH (
    'connector' = 'confluent',
    'value.format' = 'avro-registry',
    'value.fields-include' = 'all'
);

-- Continuously populate the summary table

INSERT INTO `sbx-uat.wms.public.pick_drop_item_summary`
SELECT
    pi.id AS pick_item_id,
    di.id AS drop_item_id,
    pi.wh_id,
    pi.picked_bin AS picked_bin,
    pi.sku AS picked_sku,
    pi.batch AS picked_batch,
    pi.uom AS picked_uom,
    pi.overall_qty AS overall_qty,
    pi.qty AS qty,
    pi.`huCode` AS hu_code,
    pi.`destinationBinCode` AS destination_bin_code,
    pi.`createdAt` AS pick_item_created_at,
    pi.picked_qty AS picked_qty,
    pi.picked_at AS picked_at,
    w.code AS worker_code,
    pi.moved_at AS moved_at,
    pi.processed_at AS processed_at,
    pi.picked_hu_eq_uom AS picked_hu_eq_uom,
    pi.picked_has_inner_hus AS picked_has_inner_hus,
    pi.picked_inner_hu_eq_uom AS picked_inner_hu_eq_uom,
    pi.picked_bin_assigned_at AS picked_bin_assigned_at,
    pi.scan_source_hu_kind AS scan_source_hu_kind,
    pi.pick_source_hu_kind AS pick_source_hu_kind,
    pi.carrier_hu_kind AS carrier_hu_kind,
    pi.scanned_source_hu_code AS scanned_source_hu_code,
    pi.picked_source_hu_code AS picked_source_hu_code,
    pi.carrier_hu_code AS carrier_hu_code,
    pi.hu_kind AS hu_kind,
    pi.source_hu_eq_uom AS source_hu_eq_uom,
    pi.`updatedAt` AS pick_item_updated_at,
    pi.eligible_drop_locations AS eligible_drop_locations,
    pi.parent_item_id AS parent_item_id,
    pi.old_batch AS old_batch,
    pi.dest_bucket AS dest_bucket,
    pi.original_source_bin_code AS original_source_bin_code,
    pi.lm_trip_id AS lm_trip_id,
    pi.picked_inner_hu_code AS picked_inner_hu_code,
    pi.picked_inner_hu_kind_code AS picked_inner_hu_kind_code,
    pi.picked_quant_bucket AS picked_quant_bucket,
    pi.pick_auto_complete AS pick_auto_complete,
    pi.pick_hu AS pick_hu,
    pi.short_allocation_reason AS short_allocation_reason,
    pi.drop_item_previous_task_id AS drop_item_previous_task_id,
    di.sku AS dropped_sku,
    di.batch AS dropped_batch,
    di.uom AS dropped_uom,
    di.drop_bucket AS drop_bucket,
    pi.`huCode` AS picked_hu_code,
    di.`binCode` AS dropped_bin_code,
    di.qty AS dropped_qty,
    di.`droppedAt` AS dropped_at,
    di.`updatedAt` AS drop_item_updated_at,
    di.`dropHUInBin` AS drop_hu_in_bin,
    di.`scanDestHU` AS scan_dest_hu,
    di.`allowHUBreak` AS allow_hu_break,
    di.`hasInnerHUs` AS dropped_has_inner_hus,
    di.`scanInnerHUs` AS scan_inner_hus,
    di.`huEqUOM` AS dropped_hu_eq_uom,
    di.`destHUCode` AS dest_hu_code,
    hu.code AS dropped_inner_hu_code,
    di.`innerHUEqUOM` AS dropped_inner_hu_eq_uom,
    di.`binAssignedAt` AS dest_bin_assigned_at,
    di.`dropUOM` AS drop_uom,
    di.`parentItemId` AS drop_parent_item_id,
    di.`huBroken` AS hu_broken,
    di.`originalSourceBinCode` AS drop_original_source_bin_code,
    di.`processedForLoadingAt` AS processed_for_loading_at,
    di.`quantBucket` AS drop_quant_bucket,
    di.`innerHUCode` AS drop_inner_hu_code,
    di.`innerHUKindCode` AS dropped_inner_hu_kind_code,
    di.`dropInnerHU` AS drop_inner_hu,
    di.`allowInnerHUBreak` AS allow_inner_hu_break,
    di.`innerHUBroken` AS inner_hu_broken,
    di.`autoCompleted` AS drop_auto_complete,
    di.`quantSlottingForHUs` AS quant_slotting_for_hus,
    di.`processedOnDropAt` AS processed_on_drop_at,
    di.`allowHUBreakV2` AS allow_hu_break_v2,
    t.kind AS task_kind,
    t.code AS task_code,
    t.seq AS task_sequence,
    t.state AS task_state,
    t.attrs AS task_attrs,
    t.progress AS task_progress,
    t.`createdAt` AS task_created_at,
    t.`updatedAt` AS task_updated_at,
    t.`allowForceComplete` AS allow_force_complete,
    t.`wave` AS wave,
    t.`forceCompleted` AS force_completed,
    t.`subKind` AS task_subkind,
    t.label,
    s.kind AS session_kind,
    s.code AS session_code,
    s.attrs AS session_attrs,
    s.`createdAt` AS session_created_at,
    s.`updatedAt` AS session_updated_at,
    s.active,
    s.state AS session_state,
    s.progress AS session_progress,
    s.`autoComplete` AS session_auto_complete,
    w.attrs AS worker_attrs,
    w.name AS worker_name,
    w.supervisor,
    esm.product_code AS product_code,
    esm.principal_id AS principal_id,
    esm.sku_id AS sku_id,
    esm.sku_code AS sku_code,
    esm.category AS category,
    esm.class_value AS class_value,
    esm.node_id AS node_id,
    esm.final_class AS final_class,
    esm.encarta_uom_id AS encarta_uom_id,
    esm.encarta_uom_code AS encarta_uom_code,
    esm.ibc AS ibc,
    esm.case_count AS case_count,
    esm.pallet_count AS pallet_count,
    lm_trip.code AS lm_trip_code,
    lm_trip.priority AS lm_trip_priority,
    lm_trip.`dockdoorCode` AS lm_dockdoor,
    lm_trip.`vehicleNo` AS lm_vehicle_no,
    lm_trip.`vehicleType` AS lm_vehicle_type,
    lm_trip.`deliveryDate` AS lm_delivery_date,
    pi.xdock AS xdock,
    mm_trip.code AS mm_trip_code,
    mm_trip.priority AS mm_trip_priority,
    mm_trip.`dockdoorCode` AS mm_dockdoor,
    mm_trip.`vehicleNo` AS mm_vehicle_no,
    mm_trip.`vehicleType` AS mm_vehicle_type,
    mm_trip.`deliveryDate` AS mm_delivery_date
FROM `sbx-uat.wms.public.pd_pick_item` pi
JOIN `sbx-uat.wms.public.pd_pick_drop_mapping` pdm ON pi.id = pdm.`pickItemId`
JOIN `sbx-uat.wms.public.pd_drop_item` di ON pdm.`dropItemId` = di.id
JOIN `sbx-uat.wms.public.task` t ON pi.`taskId` = t.id
JOIN `sbx-uat.wms.public.session` s ON t.`sessionId` = s.id
LEFT JOIN `sbx-uat.wms.public.worker` w ON CAST(pi.`pickedBy` AS UUID) = w.id
LEFT JOIN `sbx-uat.wms.public.handling_unit` hu ON di.`droppedInnerHUId` = hu.id
LEFT JOIN `sbx-uat.wms.public.lm_trip` lm_trip ON pi.`lmTripId` = lm_trip.id
LEFT JOIN `sbx-uat.wms.public.mm_trip` mm_trip ON pi.`mmTripId` = mm_trip.id
LEFT JOIN `sbx-uat.encarta.public.skus_master` esm ON pi.sku_id = esm.id;