CREATE TABLE wms_storage_bin_master (
    wh_id BIGINT NOT NULL,
    bin_code STRING NOT NULL,
    bin_id STRING NULL,
    bin_description STRING NULL,
    bin_status STRING NULL,
    bin_hu_id STRING NULL,
    multi_sku BOOLEAN NULL,
    multi_batch BOOLEAN NULL,
    picking_position INT NULL,
    putaway_position INT NULL,
    rank INT NULL,
    max_sku_count INT NULL,
    max_sku_batch_count INT NULL,
    aisle STRING NULL,
    bay STRING NULL,
    level STRING NULL,
    position STRING NULL,
    depth STRING NULL,
    bin_type_id STRING NULL,
    bin_type_code STRING NULL,
    bin_type_description STRING NULL,
    max_volume_in_cc DOUBLE NULL,
    max_weight_in_kg DOUBLE NULL,
    pallet_capacity INT NULL,
    storage_hu_type STRING NULL,
    auxiliary_bin BOOLEAN NULL,
    hu_multi_sku BOOLEAN NULL,
    hu_multi_batch BOOLEAN NULL,
    use_derived_pallet_best_fit BOOLEAN NULL,
    only_full_pallet BOOLEAN NULL,
    bin_type_active BOOLEAN NULL,
    zone_id STRING NULL,
    zone_code STRING NULL,
    zone_description STRING NULL,
    zone_face STRING NULL,
    peripheral BOOLEAN NULL,
    surveillance_config STRING NULL,
    zone_active BOOLEAN NULL,
    area_id STRING NULL,
    area_code STRING NULL,
    area_description STRING NULL,
    area_type STRING NULL,
    rolling_days INT NULL,
    area_active BOOLEAN NULL,
    x1 DOUBLE NULL,
    x2 DOUBLE NULL,
    y1 DOUBLE NULL,
    y2 DOUBLE NULL,
    position_active BOOLEAN NULL,
    attrs STRING NULL,
    bin_mapping STRING NULL,
    bin_created_at DATETIME NULL,
    bin_updated_at DATETIME NULL,
    bin_type_created_at DATETIME NULL,
    bin_type_updated_at DATETIME NULL,
    zone_created_at DATETIME NULL,
    zone_updated_at DATETIME NULL,
    area_created_at DATETIME NULL,
    area_updated_at DATETIME NULL,
    position_created_at DATETIME NULL,
    position_updated_at DATETIME NULL,
    mapping_created_at DATETIME NULL,
    mapping_updated_at DATETIME NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL
)
ENGINE=OLAP
PRIMARY KEY(wh_id, bin_code)
DISTRIBUTED BY HASH(wh_id) BUCKETS 2
ORDER BY (wh_id, bin_code)
PROPERTIES (
    "compression" = "LZ4",
    "enable_persistent_index" = "true",
    "fast_schema_evolution" = "true",
    "replicated_storage" = "true",
    "replication_num" = "2"
);
