apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kafka
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "2Gi"
              cpu: "1"
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "sbx-stag-kafka"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "sbx-stag-kafka-stackbox.e.aivencloud.com:22167"
            - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
              value: "https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159"
            - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRYAUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: aiven-credentials
                  key: username
            - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRYAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aiven-credentials
                  key: password
            - name: CLUSTER_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: aiven-credentials
                  key: username
            - name: CLUSTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aiven-credentials
                  key: password
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
              value: "SASL_SSL"
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM
              value: "SCRAM-SHA-512"
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG
              value: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"$(CLUSTER_USER_NAME)\" password=\"$(CLUSTER_PASSWORD)\";"

            # SSL handshake   
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION
              value: "/etc/kafka/secrets/kafka.truststore.jks"
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-truststore-secret
                  key: truststore-password
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
              value: "https"
          volumeMounts:
            - name: truststore-volume
              mountPath: /etc/kafka/secrets
              readOnly: true
      volumes:
        - name: truststore-volume
          secret:
            secretName: kafka-truststore-secret
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: kafka
spec:
  selector:
    app: kafka-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080