-- Source Table 1: Pick Items
CREATE TABLE pick_items (
    id STRING,
    `whId` BIGINT,
    `sessionId` STRING,
    `taskId` STRING,
    `binId` STRING,
    `binHUId` STRING,
    `binCode` STRING,
    `skuId` STRING,
    batch STRING,
    uom STRING,
    bucket STRING,
    `overallQty` INT,
    qty INT,
    `huId` STRING,
    `huCode` STRING,
    `destinationBinId` STRING,
    `destinationBinHUId` STRING,
    `destinationBinCode` STRING,
    `createdAt` TIMESTAMP(3),
    `deactivatedAt` TIMESTAMP(3),
    `deactivatedBy` STRING,
    `pickedQty` INT,
    `pickedAt` TIMESTAMP(3),
    `pickedBy` STRING,
    `movedAt` TIMESTAMP(3),
    `movedBy` STRING,
    `processedAt` TIMESTAMP(3),
    `huEqUOM` STRING,
    `hasInnerHUs` BOOLEAN,
    `innerHUEqUOM` STRING,
    `binAssignedAt` TIMESTAMP(3),
    `scanSourceHUKind` STRING,
    `pickSourceHUKind` STRING,
    `carrierHUKind` STRING,
    `scannedSourceHUId` STRING,
    `scannedSourceHUCode` STRING,
    `pickedSourceHUId` STRING,
    `pickedSourceHUCode` STRING,
    `carrierHUId` STRING,
    `carrierHUCode` STRING,
    `huKind` STRING,
    `sourceHUEqUOM` STRING,
    `updatedAt` TIMESTAMP(3),
    `eligibleDropLocations` STRING,
    `parentItemId` STRING,
    `oldBatch` STRING,
    `destBucket` STRING,
    `originalSourceBinId` STRING,
    `originalSourceBinCode` STRING,
    `lmTripId` STRING,
    `innerHUId` STRING,
    `innerHUCode` STRING,
    `innerHUKindId` STRING,
    `innerHUKindCode` STRING,
    `quantBucket` STRING,
    `autoCompleted` BOOLEAN,
    `pickHU` BOOLEAN,
    `shortAllocationReason` STRING,
    `pdPreviousTaskId` STRING,
    `inputSourceBinId` STRING,
    `provisionalItemId` STRING,
    `inputDestHUId` STRING,
    kind STRING,
    `tpAssignedAt` TIMESTAMP(3),
    `legIndex` INT,
    `lastLeg` BOOLEAN,
    `epAssignedAt` TIMESTAMP(3),
    `carrierHUFormedId` STRING,
    `huIndex` INT,
    sequence INT,
    `carrierHUForceClosed` BOOLEAN,
    `inputDestBinId` STRING,
    `innerHUIndex` INT,
    `innerCarrierHUKey` STRING,
    `innerCarrierHUFormedId` STRING,
    `innerCarrierHUId` STRING,
    `innerCarrierHUCode` STRING,
    `innerCarrierHUKind` STRING,
    `inductionId` STRING,
    `innerCarrierHUForceClosed` BOOLEAN,
    `mheId` STRING,
    attrs STRING,
    iloc STRING,
    `destIloc` STRING,
    -- CDC snapshot field (READ from true source tables, but never forward directly)
    `__source_snapshot` STRING,
    -- Computed event time from business timestamps
    `event_time` AS COALESCE(
        `updatedAt`,
        `createdAt`,
        TIMESTAMP '1970-01-01 00:00:00'
    ),
    -- Computed is_snapshot field for CDC snapshot detection
    `is_snapshot` AS COALESCE(
        `__source_snapshot` IN (
            'true',
            'first',
            'first_in_data_collection',
            'last_in_data_collection',
            'last'
        ),
        FALSE
    ),
    WATERMARK FOR `event_time` AS `event_time` - INTERVAL '5' SECOND
) WITH (
    'connector' = 'kafka',
    'topic' = 'sbx_uat.wms.public.pd_pick_item',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.group.id' = 'sbx-uat-wms-pick-drop-basic-debug',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'format' = 'avro-confluent',
    'avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'properties.auto.offset.reset' = 'earliest',
    'scan.startup.mode' = 'earliest-offset',
    -- Start from beginning
    'scan.bounded.mode' = 'latest-offset'
);
-- Source Table 2: Drop Items
CREATE TABLE drop_items (
    id STRING,
    `whId` BIGINT,
    `sessionId` STRING,
    `taskId` STRING,
    `sourceBinId` STRING,
    `sourceBinHUId` STRING,
    `sourceBinCode` STRING,
    `skuId` STRING,
    batch STRING,
    uom STRING,
    bucket STRING,
    qty INT,
    `huId` STRING,
    `huCode` STRING,
    `binId` STRING,
    `binHUId` STRING,
    `binCode` STRING,
    `createdAt` TIMESTAMP(3),
    `deactivatedAt` TIMESTAMP(3),
    `deactivatedBy` STRING,
    `droppedQty` INT,
    `droppedAt` TIMESTAMP(3),
    `droppedBy` STRING,
    `updatedAt` TIMESTAMP(3),
    `dropHUInBin` BOOLEAN,
    `scanDestHU` BOOLEAN,
    `allowHUBreak` BOOLEAN,
    `hasInnerHUs` BOOLEAN,
    `scanInnerHUs` BOOLEAN,
    `huEqUOM` STRING,
    `destHUId` STRING,
    `destHUCode` STRING,
    `droppedInnerHUId` STRING,
    `innerHUEqUOM` STRING,
    `binAssignedAt` TIMESTAMP(3),
    `dropUOM` STRING,
    `eligibleDropLocations` STRING,
    `parentItemId` STRING,
    `huBroken` BOOLEAN,
    `pickedBy` STRING,
    `sourceBucket` STRING,
    `originalDestinationBinId` STRING,
    `originalDestinationBinCode` STRING,
    `lmTripId` STRING,
    `processedForLoadingAt` TIMESTAMP(3),
    `quantBucket` STRING,
    `innerHUId` STRING,
    `innerHUCode` STRING,
    `innerHUKindId` STRING,
    `innerHUKindCode` STRING,
    `dropInnerHU` BOOLEAN,
    `allowInnerHUBreak` BOOLEAN,
    `innerHUBroken` BOOLEAN,
    `autoCompleted` BOOLEAN,
    `processedForPickAt` TIMESTAMP(3),
    `quantSlottingForHUs` BOOLEAN,
    `pdPreviousTaskId` STRING,
    `processedOnDropAt` TIMESTAMP(3),
    `provisionalItemId` STRING,
    `allowHUBreakV2` BOOLEAN,
    `inputDestHUId` STRING,
    `legIndex` INT,
    `lastLeg` BOOLEAN,
    `inputDestBinId` STRING,
    `inductionId` STRING,
    attrs STRING,
    `mheId` STRING,
    iloc STRING,
    `sourceIloc` STRING,
    -- CDC snapshot field (READ from true source tables, but never forward directly)
    `__source_snapshot` STRING,
    -- Computed event time from business timestamps
    `event_time` AS COALESCE(
        `updatedAt`,
        `createdAt`,
        TIMESTAMP '1970-01-01 00:00:00'
    ),
    -- Computed is_snapshot field for CDC snapshot detection
    `is_snapshot` AS COALESCE(
        `__source_snapshot` IN (
            'true',
            'first',
            'first_in_data_collection',
            'last_in_data_collection',
            'last'
        ),
        FALSE
    ),
    WATERMARK FOR `event_time` AS `event_time` - INTERVAL '5' SECOND
) WITH (
    'connector' = 'kafka',
    'topic' = 'sbx_uat.wms.public.pd_drop_item',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.group.id' = 'sbx-uat-wms-pick-drop-basic-debug',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'format' = 'avro-confluent',
    'avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'properties.auto.offset.reset' = 'earliest',
    'scan.startup.mode' = 'earliest-offset',
    -- Start from beginning
    'scan.bounded.mode' = 'latest-offset'
);
-- Source Table 3: Pick Drop Mapping
CREATE TABLE pick_drop_mapping (
    id STRING,
    `whId` BIGINT,
    `sessionId` STRING,
    `taskId` STRING,
    `pickItemId` STRING,
    `dropItemId` STRING,
    `createdAt` TIMESTAMP(3),
    -- CDC snapshot field (READ from true source tables, but never forward directly)
    `__source_snapshot` STRING,
    -- Computed event time from business timestamp
    `event_time` AS COALESCE(
        `createdAt`,
        TIMESTAMP '1970-01-01 00:00:00'
    ),
    -- Computed is_snapshot field for CDC snapshot detection
    `is_snapshot` AS COALESCE(
        `__source_snapshot` IN (
            'true',
            'first',
            'first_in_data_collection',
            'last_in_data_collection',
            'last'
        ),
        FALSE
    ),
    WATERMARK FOR `event_time` AS `event_time` - INTERVAL '5' SECOND
) WITH (
    'connector' = 'kafka',
    'topic' = 'sbx_uat.wms.public.pd_pick_drop_mapping',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.group.id' = 'sbx-uat-wms-pick-drop-basic-debug',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'format' = 'avro-confluent',
    'avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'properties.auto.offset.reset' = 'earliest',
    'scan.startup.mode' = 'earliest-offset',
    -- Start from beginning
    'scan.bounded.mode' = 'latest-offset'
);
CREATE TABLE pick_drop_basic (
    pick_item_id STRING,
    drop_item_id STRING,
    wh_id BIGINT,
    session_id STRING,
    task_id STRING,
    lm_trip_id STRING,
    -- Pick item fields
    picked_bin STRING,
    picked_sku_id STRING,
    picked_batch STRING,
    picked_uom STRING,
    overall_qty INT,
    qty INT,
    hu_code STRING,
    destination_bin_code STRING,
    pick_item_created_at TIMESTAMP(3),
    picked_qty INT,
    picked_at TIMESTAMP(3),
    picked_by_worker_id STRING,
    moved_at TIMESTAMP(3),
    processed_at TIMESTAMP(3),
    picked_hu_eq_uom STRING,
    picked_has_inner_hus BOOLEAN,
    picked_inner_hu_eq_uom STRING,
    picked_bin_assigned_at TIMESTAMP(3),
    scan_source_hu_kind STRING,
    pick_source_hu_kind STRING,
    carrier_hu_kind STRING,
    scanned_source_hu_code STRING,
    picked_source_hu_code STRING,
    carrier_hu_code STRING,
    hu_kind STRING,
    source_hu_eq_uom STRING,
    pick_item_updated_at TIMESTAMP(3),
    eligible_drop_locations STRING,
    parent_item_id STRING,
    old_batch STRING,
    dest_bucket STRING,
    original_source_bin_code STRING,
    picked_inner_hu_code STRING,
    picked_inner_hu_kind_code STRING,
    picked_quant_bucket STRING,
    pick_auto_complete BOOLEAN,
    pick_hu BOOLEAN,
    short_allocation_reason STRING,
    -- Drop item fields
    dropped_sku_id STRING,
    dropped_batch STRING,
    dropped_uom STRING,
    drop_bucket STRING,
    picked_hu_code STRING,
    dropped_bin_code STRING,
    dropped_qty INT,
    dropped_at TIMESTAMP(3),
    drop_item_updated_at TIMESTAMP(3),
    drop_hu_in_bin BOOLEAN,
    scan_dest_hu BOOLEAN,
    allow_hu_break BOOLEAN,
    dropped_has_inner_hus BOOLEAN,
    scan_inner_hus BOOLEAN,
    dropped_hu_eq_uom STRING,
    dest_hu_code STRING,
    dropped_inner_hu_id STRING,
    dropped_inner_hu_eq_uom STRING,
    dest_bin_assigned_at TIMESTAMP(3),
    drop_uom STRING,
    drop_parent_item_id STRING,
    hu_broken BOOLEAN,
    drop_original_source_bin_code STRING,
    processed_for_loading_at TIMESTAMP(3),
    drop_quant_bucket STRING,
    drop_inner_hu_code STRING,
    dropped_inner_hu_kind_code STRING,
    drop_inner_hu BOOLEAN,
    allow_inner_hu_break BOOLEAN,
    inner_hu_broken BOOLEAN,
    drop_auto_complete BOOLEAN,
    quant_slotting_for_hus BOOLEAN,
    processed_on_drop_at TIMESTAMP(3),
    allow_hu_break_v2 BOOLEAN,
    deactivated_at TIMESTAMP(3),
    -- Mapping fields
    mapping_id STRING,
    mapping_created_at TIMESTAMP(3),
    -- Additional fields
    bin_id STRING,
    bin_hu_id STRING,
    destination_bin_id STRING,
    destination_bin_hu_id STRING,
    pick_deactivated_at TIMESTAMP(3),
    pick_deactivated_by STRING,
    moved_by STRING,
    scanned_source_hu_id STRING,
    picked_source_hu_id STRING,
    carrier_hu_id STRING,
    original_source_bin_id STRING,
    inner_hu_id STRING,
    inner_hu_kind_id STRING,
    pd_previous_task_id STRING,
    input_source_bin_id STRING,
    provisional_item_id STRING,
    input_dest_hu_id STRING,
    pick_item_kind STRING,
    tp_assigned_at TIMESTAMP(3),
    leg_index INT,
    last_leg BOOLEAN,
    ep_assigned_at TIMESTAMP(3),
    carrier_hu_formed_id STRING,
    hu_index INT,
    pick_sequence INT,
    carrier_hu_force_closed BOOLEAN,
    input_dest_bin_id STRING,
    inner_hu_index INT,
    inner_carrier_hu_key STRING,
    inner_carrier_hu_formed_id STRING,
    inner_carrier_hu_id STRING,
    inner_carrier_hu_code STRING,
    inner_carrier_hu_kind STRING,
    induction_id STRING,
    inner_carrier_hu_force_closed BOOLEAN,
    mhe_id STRING,
    pick_attrs STRING,
    iloc STRING,
    dest_iloc STRING,
    source_bin_id STRING,
    source_bin_hu_id STRING,
    drop_bin_id STRING,
    drop_bin_hu_id STRING,
    drop_created_at TIMESTAMP(3),
    drop_deactivated_at TIMESTAMP(3),
    drop_deactivated_by STRING,
    dropped_by_worker_id STRING,
    dest_hu_id STRING,
    source_bucket STRING,
    original_destination_bin_id STRING,
    drop_lm_trip_id STRING,
    processed_for_pick_at TIMESTAMP(3),
    drop_provisional_item_id STRING,
    drop_input_dest_hu_id STRING,
    drop_leg_index INT,
    drop_last_leg BOOLEAN,
    drop_input_dest_bin_id STRING,
    drop_induction_id STRING,
    drop_attrs STRING,
    drop_mhe_id STRING,
    drop_iloc STRING,
    source_iloc STRING,
    -- Fields from the upstream pipeline
    is_snapshot BOOLEAN,
    event_time TIMESTAMP(3),
    proc_time AS PROCTIME() -- Processing time for historical data
) WITH (
    'connector' = 'kafka',
    'topic' = 'sbx_uat.wms.internal.pick_drop_basic',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    -- Shared group with real-time
    'properties.enable.auto.commit' = 'true',
    -- Commit offsets for real-time to continue
    'properties.auto.commit.interval.ms' = '5000',
    -- Commit every 5 seconds
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    --
    'properties.group.id' = 'sbx-uat-wms-pick-drop-enriched-debug',
    'scan.startup.mode' = 'earliest-offset',
    'scan.bounded.mode' = 'latest-offset',
    'properties.auto.offset.reset' = 'earliest',
    -- Process up to current latest offset then stop
    'format' = 'avro-confluent',
    'avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
--
CREATE TABLE pick_drop_summary (
wh_id BIGINT,
principal_id BIGINT,
pick_item_id STRING,
drop_item_id STRING,
picked_bin STRING,
picked_sku_id STRING,
picked_batch STRING,
picked_uom STRING,
overall_qty INT,
qty INT,
hu_code STRING,
destination_bin_code STRING,
pick_item_created_at TIMESTAMP(3),
picked_qty INT,
picked_at TIMESTAMP(3),
picked_by_worker_id STRING,
moved_at TIMESTAMP(3),
processed_at TIMESTAMP(3),
picked_hu_eq_uom STRING,
picked_has_inner_hus BOOLEAN,
picked_inner_hu_eq_uom STRING,
picked_bin_assigned_at TIMESTAMP(3),
scan_source_hu_kind STRING,
pick_source_hu_kind STRING,
carrier_hu_kind STRING,
scanned_source_hu_code STRING,
picked_source_hu_code STRING,
carrier_hu_code STRING,
hu_kind STRING,
source_hu_eq_uom STRING,
pick_item_updated_at TIMESTAMP(3),
eligible_drop_locations STRING,
parent_item_id STRING,
old_batch STRING,
dest_bucket STRING,
original_source_bin_code STRING,
lm_trip_id STRING,
picked_inner_hu_code STRING,
picked_inner_hu_kind_code STRING,
picked_quant_bucket STRING,
pick_auto_complete BOOLEAN,
pick_hu BOOLEAN,
short_allocation_reason STRING,
drop_item_previous_task_id STRING,
dropped_sku_id STRING,
dropped_batch STRING,
dropped_uom STRING,
drop_bucket STRING,
picked_hu_code STRING,
dropped_bin_code STRING,
dropped_qty INT,
dropped_at TIMESTAMP(3),
drop_item_updated_at TIMESTAMP(3),
drop_hu_in_bin BOOLEAN,
scan_dest_hu BOOLEAN,
allow_hu_break BOOLEAN,
dropped_has_inner_hus BOOLEAN,
scan_inner_hus BOOLEAN,
dropped_hu_eq_uom STRING,
dest_hu_code STRING,
dropped_inner_hu_id STRING,
dropped_inner_hu_eq_uom STRING,
dest_bin_assigned_at TIMESTAMP(3),
drop_uom STRING,
drop_parent_item_id STRING,
hu_broken BOOLEAN,
drop_original_source_bin_code STRING,
processed_for_loading_at TIMESTAMP(3),
drop_quant_bucket STRING,
drop_inner_hu_code STRING,
dropped_inner_hu_kind_code STRING,
drop_inner_hu BOOLEAN,
allow_inner_hu_break BOOLEAN,
inner_hu_broken BOOLEAN,
drop_auto_complete BOOLEAN,
quant_slotting_for_hus BOOLEAN,
processed_on_drop_at TIMESTAMP(3),
allow_hu_break_v2 BOOLEAN,
task_kind STRING,
task_code STRING,
task_sequence INT,
task_state STRING,
task_attrs STRING,
task_progress STRING,
task_created_at TIMESTAMP(3),
task_updated_at TIMESTAMP(3),
allow_force_complete BOOLEAN,
wave INT,
force_completed BOOLEAN,
task_subkind STRING,
`label` STRING,
session_kind STRING,
session_code STRING,
session_attrs STRING,
session_created_at TIMESTAMP(3),
session_updated_at TIMESTAMP(3),
active BOOLEAN,
session_state STRING,
session_progress STRING,
session_auto_complete BOOLEAN,
lm_trip_code STRING,
lm_trip_priority INT,
lm_dockdoor STRING,
lm_vehicle_no STRING,
lm_vehicle_type STRING,
lm_delivery_date STRING,
-- Additional Pick Items columns
bin_id STRING,
bin_hu_id STRING,
destination_bin_id STRING,
destination_bin_hu_id STRING,
pick_deactivated_at TIMESTAMP(3),
pick_deactivated_by STRING,
moved_by STRING,
scanned_source_hu_id STRING,
picked_source_hu_id STRING,
carrier_hu_id STRING,
original_source_bin_id STRING,
inner_hu_id STRING,
inner_hu_kind_id STRING,
pd_previous_task_id STRING,
input_source_bin_id STRING,
provisional_item_id STRING,
input_dest_hu_id STRING,
pick_item_kind STRING,
tp_assigned_at TIMESTAMP(3),
leg_index INT,
last_leg BOOLEAN,
ep_assigned_at TIMESTAMP(3),
carrier_hu_formed_id STRING,
hu_index INT,
pick_sequence INT,
carrier_hu_force_closed BOOLEAN,
input_dest_bin_id STRING,
inner_hu_index INT,
inner_carrier_hu_key STRING,
inner_carrier_hu_formed_id STRING,
inner_carrier_hu_id STRING,
inner_carrier_hu_code STRING,
inner_carrier_hu_kind STRING,
induction_id STRING,
inner_carrier_hu_force_closed BOOLEAN,
mhe_id STRING,
pick_attrs STRING,
iloc STRING,
dest_iloc STRING,
-- Additional Drop Items columns
source_bin_id STRING,
source_bin_hu_id STRING,
drop_bin_id STRING,
drop_bin_hu_id STRING,
drop_created_at TIMESTAMP(3),
drop_deactivated_at TIMESTAMP(3),
drop_deactivated_by STRING,
dropped_by_worker_id STRING,
dest_hu_id STRING,
source_bucket STRING,
original_destination_bin_id STRING,
drop_lm_trip_id STRING,
processed_for_pick_at TIMESTAMP(3),
drop_provisional_item_id STRING,
drop_input_dest_hu_id STRING,
drop_leg_index INT,
drop_last_leg BOOLEAN,
drop_input_dest_bin_id STRING,
drop_induction_id STRING,
drop_attrs STRING,
drop_mhe_id STRING,
drop_iloc STRING,
source_iloc STRING,
-- Additional Pick Drop Mapping columns
mapping_id STRING,
mapping_created_at TIMESTAMP(3),
-- Additional Tasks columns
task_exclusive BOOLEAN,
task_active BOOLEAN,
task_auto_complete BOOLEAN,
force_complete_task_id STRING,
-- Additional Trips columns (LM)
lm_session_created_at TIMESTAMP(3),
lm_trip_created_at TIMESTAMP(3),
lm_bb_id STRING,
lm_trip_type STRING,
lm_dockdoor_id STRING,
lm_vehicle_id STRING,
-- Trip Relation enrichment fields
trip_relation_id STRING,
trip_relation_xdock STRING,
trip_relation_parent_trip_id STRING,
trip_relation_created_at TIMESTAMP(3),
-- Parent Trip enrichment fields
parent_trip_code STRING,
parent_trip_type STRING,
parent_trip_priority INT,
parent_trip_dockdoor_code STRING,
parent_trip_vehicle_no STRING,
parent_trip_vehicle_type STRING,
parent_trip_delivery_date STRING,
parent_trip_created_at TIMESTAMP(3),
-- Worker enrichment fields
worker_code STRING,
worker_name STRING,
worker_phone STRING,
worker_supervisor BOOLEAN,
worker_active BOOLEAN,
-- Handling Unit enrichment fields
dropped_hu_code STRING,
dropped_hu_kind_id STRING,
dropped_hu_session_id STRING,
dropped_hu_task_id STRING,
dropped_hu_storage_id STRING,
dropped_hu_outer_hu_id STRING,
dropped_hu_state STRING,
dropped_hu_attrs STRING,
dropped_hu_lock_task_id STRING,
dropped_hu_effective_storage_id STRING,
dropped_hu_created_at TIMESTAMP(3),
dropped_hu_updated_at TIMESTAMP(3),
-- Picked SKU enrichment fields (comprehensive)
picked_sku_principal_id BIGINT,
picked_sku_node_id BIGINT,
picked_sku_category STRING,
picked_sku_product STRING,
picked_sku_product_id STRING,
picked_sku_category_group STRING,
picked_sku_sub_brand STRING,
picked_sku_brand STRING,
picked_sku_code STRING,
picked_sku_name STRING,
picked_sku_short_description STRING,
picked_sku_description STRING,
picked_sku_fulfillment_type STRING,
picked_sku_inventory_type STRING,
picked_sku_shelf_life INT,
picked_sku_tag1 STRING,
picked_sku_tag2 STRING,
picked_sku_tag3 STRING,
picked_sku_tag4 STRING,
picked_sku_tag5 STRING,
picked_sku_handling_unit_type STRING,
picked_sku_cases_per_layer INT,
picked_sku_layers INT,
picked_sku_l0_units INT,
picked_sku_l1_units INT,
picked_sku_l2_units INT,
picked_sku_l3_units INT,
picked_sku_l0_name STRING,
picked_sku_l0_weight DOUBLE,
picked_sku_l0_volume DOUBLE,
picked_sku_l0_package_type STRING,
picked_sku_l0_length DOUBLE,
picked_sku_l0_width DOUBLE,
picked_sku_l0_height DOUBLE,
picked_sku_l0_packing_efficiency DOUBLE,
picked_sku_l1_name STRING,
picked_sku_l1_weight DOUBLE,
picked_sku_l1_volume DOUBLE,
picked_sku_l1_package_type STRING,
picked_sku_l1_length DOUBLE,
picked_sku_l1_width DOUBLE,
picked_sku_l1_height DOUBLE,
picked_sku_l1_packing_efficiency DOUBLE,
picked_sku_l2_name STRING,
picked_sku_l2_weight DOUBLE,
picked_sku_l2_volume DOUBLE,
picked_sku_l2_package_type STRING,
picked_sku_l2_length DOUBLE,
picked_sku_l2_width DOUBLE,
picked_sku_l2_height DOUBLE,
picked_sku_l2_packing_efficiency DOUBLE,
picked_sku_l3_name STRING,
picked_sku_l3_weight DOUBLE,
picked_sku_l3_volume DOUBLE,
picked_sku_l3_package_type STRING,
picked_sku_l3_length DOUBLE,
picked_sku_l3_width DOUBLE,
picked_sku_l3_height DOUBLE,
picked_sku_l3_packing_efficiency DOUBLE,
picked_sku_active BOOLEAN,
picked_sku_classifications STRING,
picked_sku_product_classifications STRING,
-- Dropped SKU enrichment fields (comprehensive)
dropped_sku_principal_id BIGINT,
dropped_sku_node_id BIGINT,
dropped_sku_category STRING,
dropped_sku_product STRING,
dropped_sku_product_id STRING,
dropped_sku_category_group STRING,
dropped_sku_sub_brand STRING,
dropped_sku_brand STRING,
dropped_sku_code STRING,
dropped_sku_name STRING,
dropped_sku_short_description STRING,
dropped_sku_description STRING,
dropped_sku_fulfillment_type STRING,
dropped_sku_inventory_type STRING,
dropped_sku_shelf_life INT,
dropped_sku_tag1 STRING,
dropped_sku_tag2 STRING,
dropped_sku_tag3 STRING,
dropped_sku_tag4 STRING,
dropped_sku_tag5 STRING,
dropped_sku_handling_unit_type STRING,
dropped_sku_cases_per_layer INT,
dropped_sku_layers INT,
dropped_sku_l0_units INT,
dropped_sku_l1_units INT,
dropped_sku_l2_units INT,
dropped_sku_l3_units INT,
dropped_sku_l0_name STRING,
dropped_sku_l0_weight DOUBLE,
dropped_sku_l0_volume DOUBLE,
dropped_sku_l0_package_type STRING,
dropped_sku_l0_length DOUBLE,
dropped_sku_l0_width DOUBLE,
dropped_sku_l0_height DOUBLE,
dropped_sku_l0_packing_efficiency DOUBLE,
dropped_sku_l1_name STRING,
dropped_sku_l1_weight DOUBLE,
dropped_sku_l1_volume DOUBLE,
dropped_sku_l1_package_type STRING,
dropped_sku_l1_length DOUBLE,
dropped_sku_l1_width DOUBLE,
dropped_sku_l1_height DOUBLE,
dropped_sku_l1_packing_efficiency DOUBLE,
dropped_sku_l2_name STRING,
dropped_sku_l2_weight DOUBLE,
dropped_sku_l2_volume DOUBLE,
dropped_sku_l2_package_type STRING,
dropped_sku_l2_length DOUBLE,
dropped_sku_l2_width DOUBLE,
dropped_sku_l2_height DOUBLE,
dropped_sku_l2_packing_efficiency DOUBLE,
dropped_sku_l3_name STRING,
dropped_sku_l3_weight DOUBLE,
dropped_sku_l3_volume DOUBLE,
dropped_sku_l3_package_type STRING,
dropped_sku_l3_length DOUBLE,
dropped_sku_l3_width DOUBLE,
dropped_sku_l3_height DOUBLE,
dropped_sku_l3_packing_efficiency DOUBLE,
dropped_sku_active BOOLEAN,
dropped_sku_classifications STRING,
dropped_sku_product_classifications STRING
) WITH (
    'connector' = 'kafka',
    'topic' = 'sbx_uat.wms.public.pick_drop_enriched',
    'properties.group.id' = 'sbx-uat-wms-pick-drop-enriched-debug',
    'scan.startup.mode' = 'earliest-offset',
    'scan.bounded.mode' = 'latest-offset',
    'properties.auto.offset.reset' = 'earliest',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    --
    'format' = 'avro-confluent',
    'avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
--
select 'basic';
select pick_item_id,
    pick_item_updated_at,
    pick_item_created_at,
    drop_item_id,
    mapping_created_at,
    drop_item_updated_at,
    picked_by_worker_id,
    event_time,
    proc_time
from pick_drop_basic
where pick_item_id = '01989e1f-b065-74ae-a66b-b1105c7b2153';
--
select 'summary';
SELECT *
FROM pick_drop_summary
WHERE `pick_item_id` = '01989e1f-b065-74ae-a66b-b1105c7b2153';
--
select 'join';
SELECT pi.id,
    pi.`updatedAt`,
    pi.`createdAt`,
    pi.`pickedBy`,
    pdm.id AS mapping_id,
    pdm.`createdAt` AS mapping_created_at,
    di.id AS drop_item_id,
    di.`updatedAt` AS drop_item_updated_at
FROM pick_items pi
    LEFT JOIN pick_drop_mapping pdm ON pi.id = pdm.`pickItemId`
    LEFT JOIN drop_items di ON pdm.`dropItemId` = di.id
WHERE pi.`id` = '01989e1f-b065-74ae-a66b-b1105c7b2153';
-- --
select 'pick';
SELECT id,
    updatedAt,
    createdAt,
    pickedBy
FROM pick_items pi
WHERE pi.`id` = '01989e1f-b065-74ae-a66b-b1105c7b2153';