CREATE TABLE uoms (
    id STRING NOT NULL,
    principal_id BIGINT NOT NULL,
    sku_id STRING NOT NULL,
    name STRING,
    hierarchy STRING NOT NULL,
    weight DOUBLE,
    volume DOUBLE,
    package_type STRING,
    length DOUBLE,
    width DOUBLE,
    height DOUBLE,
    units INT,
    packing_efficiency DOUBLE,
    active BOOLEAN,
    itf_code STRING,
    created_at TIMESTAMP(3),
    updated_at TIMESTAMP(3),
    erp_weight DOUBLE,
    erp_volume DOUBLE,
    erp_length DOUBLE,
    erp_width DOUBLE,
    erp_height DOUBLE,
    text_tag1 STRING,
    text_tag2 STRING,
    image STRING,
    num_tag1 DOUBLE,
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'connector' = 'upsert-kafka',
    'topic' = '${KAFKA_ENV}.encarta.public.uoms',
    'properties.bootstrap.servers' = '${KAFKA_BOOTSTRAP_SERVERS}',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.auto.offset.reset' = 'earliest',
    'properties.allow.auto.create.topics' = 'true',
    'key.format' = 'avro-confluent',
    'key.avro-confluent.url' = '${SCHEMA_REGISTRY_URL}',
    'key.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'key.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'value.format' = 'avro-confluent',
    'value.avro-confluent.url' = '${SCHEMA_REGISTRY_URL}',
    'value.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'value.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
select *
from uoms
limit 10;