CREATE TABLE encarta_skus_master (
	id VARCHAR(36) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT "1970-01-01 00:00:00",
	principal_id BIGINT,
	category STRING,
	product STRING,
	product_id VARCHAR(36) NOT NULL,
	category_group STRING,
	sub_brand STRING,
	brand STRING,
	code STRING NOT NULL,
	name STRING,
	short_description STRING,
	description STRING,
	fulfillment_type STRING,
	avg_l0_per_put INT,
	inventory_type STRING,
	shelf_life INT,
	identifier1 STRING,
	identifier2 STRING,
	tag1 STRING,
	tag2 STRING,
	tag3 STRING,
	tag4 STRING,
	tag5 STRING,
	tag6 STRING,
	tag7 STRING,
	tag8 STRING,
	tag9 STRING,
	tag10 STRING,
	handling_unit_type STRING,
	cases_per_layer INT,
	layers INT,
	active_from DATETIME,
	active_till DATETIME,
	l0_units INT,
	l1_units INT,
	l2_units INT,
	l3_units INT,
	l0_name STRING,
	l0_weight DOUBLE,
	l0_volume DOUBLE,
	l0_package_type STRING,
	l0_length DOUBLE,
	l0_width DOUBLE,
	l0_height DOUBLE,
	l0_packing_efficiency DOUBLE,
	l0_itf_code STRING,
	l0_erp_weight DOUBLE,
	l0_erp_volume DOUBLE,
	l0_erp_length DOUBLE,
	l0_erp_width DOUBLE,
	l0_erp_height DOUBLE,
	l0_text_tag1 STRING,
	l0_text_tag2 STRING,
	l0_image STRING,
	l0_num_tag1 DOUBLE,
	l1_name STRING,
	l1_weight DOUBLE,
	l1_volume DOUBLE,
	l1_package_type STRING,
	l1_length DOUBLE,
	l1_width DOUBLE,
	l1_height DOUBLE,
	l1_packing_efficiency DOUBLE,
	l1_itf_code STRING,
	l1_erp_weight DOUBLE,
	l1_erp_volume DOUBLE,
	l1_erp_length DOUBLE,
	l1_erp_width DOUBLE,
	l1_erp_height DOUBLE,
	l1_text_tag1 STRING,
	l1_text_tag2 STRING,
	l1_image STRING,
	l1_num_tag1 DOUBLE,
	l2_name STRING,
	l2_weight DOUBLE,
	l2_volume DOUBLE,
	l2_package_type STRING,
	l2_length DOUBLE,
	l2_width DOUBLE,
	l2_height DOUBLE,
	l2_packing_efficiency DOUBLE,
	l2_itf_code STRING,
	l2_erp_weight DOUBLE,
	l2_erp_volume DOUBLE,
	l2_erp_length DOUBLE,
	l2_erp_width DOUBLE,
	l2_erp_height DOUBLE,
	l2_text_tag1 STRING,
	l2_text_tag2 STRING,
	l2_image STRING,
	l2_num_tag1 DOUBLE,
	l3_name STRING,
	l3_weight DOUBLE,
	l3_volume DOUBLE,
	l3_package_type STRING,
	l3_length DOUBLE,
	l3_width DOUBLE,
	l3_height DOUBLE,
	l3_packing_efficiency DOUBLE,
	l3_itf_code STRING,
	l3_erp_weight DOUBLE,
	l3_erp_volume DOUBLE,
	l3_erp_length DOUBLE,
	l3_erp_width DOUBLE,
	l3_erp_height DOUBLE,
	l3_text_tag1 STRING,
	l3_text_tag2 STRING,
	l3_image STRING,
	l3_num_tag1 DOUBLE,
	active BOOLEAN NOT NULL DEFAULT "true",
	classifications STRING,
	product_classifications STRING,
	sku_created_at DATETIME,
	sku_updated_at DATETIME,
	product_created_at DATETIME,
	product_updated_at DATETIME,
	uom_agg_created_at DATETIME,
	uom_agg_updated_at DATETIME,
	updated_at DATETIME NOT NULL DEFAULT "1970-01-01 00:00:00"
)
ENGINE=OLAP
PRIMARY KEY(id)
DISTRIBUTED BY HASH(id) BUCKETS 2
ORDER BY (id)
PROPERTIES (
	"compression" = "LZ4",
	"enable_persistent_index" = "true",
	"fast_schema_evolution" = "true",
	"replicated_storage" = "true",
	"replication_num" = "2"
);