CREATE TABLE wms_pd_drop_item (
    id STRING NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT "1970-01-01 00:00:00",
    whId BIGINT NULL,
    sessionId STRING NULL,
    taskId STRING NULL,
    sourceBinId STRING NULL,
    sourceBinHUId STRING NULL,
    sourceBinCode STRING NULL,
    skuId STRING NULL,
    batch STRING NULL,
    uom STRING NULL,
    bucket STRING NULL,
    qty INT NULL,
    huId STRING NULL,
    huCode STRING NULL,
    binId STRING NULL,
    binHUId STRING NULL,
    binCode STRING NULL,
    deactivatedAt DATETIME NULL,
    deactivatedBy STRING NULL,
    droppedQty INT NULL,
    droppedAt DATETIME NULL,
    droppedBy STRING NULL,
    updatedAt DATETIME NULL,
    dropHUInBin BOOLEAN NULL,
    scanDestHU BOOLEAN NULL,
    allowHUBreak BOOLEAN NULL,
    hasInnerHUs BOOLEAN NULL,
    scanInnerHUs BOOLEAN NULL,
    huEqUOM STRING NULL,
    destHUId STRING NULL,
    destHUCode STRING NULL,
    droppedInnerHUId STRING NULL,
    innerHUEqUOM STRING NULL,
    binAssignedAt DATETIME NULL,
    dropUOM STRING NULL,
    eligibleDropLocations STRING NULL,
    parentItemId STRING NULL,
    huBroken BOOLEAN NULL,
    pickedBy STRING NULL,
    sourceBucket STRING NULL,
    originalDestinationBinId STRING NULL,
    originalDestinationBinCode STRING NULL,
    lmTripId STRING NULL,
    processedForLoadingAt DATETIME NULL,
    quantBucket STRING NULL,
    innerHUId STRING NULL,
    innerHUCode STRING NULL,
    innerHUKindId STRING NULL,
    innerHUKindCode STRING NULL,
    dropInnerHU BOOLEAN NULL,
    allowInnerHUBreak BOOLEAN NULL,
    innerHUBroken BOOLEAN NULL,
    autoCompleted BOOLEAN NULL,
    processedForPickAt DATETIME NULL,
    quantSlottingForHUs BOOLEAN NULL,
    pdPreviousTaskId STRING NULL,
    processedOnDropAt DATETIME NULL,
    provisionalItemId STRING NULL,
    allowHUBreakV2 BOOLEAN NULL,
    inputDestHUId STRING NULL,
    legIndex INT NULL,
    lastLeg BOOLEAN NULL,
    inputDestBinId STRING NULL,
    inductionId STRING NULL,
    attrs STRING NULL,
    mheId STRING NULL,
    iloc STRING NULL,
    sourceIloc STRING NULL,
    huIndex INT NULL,
    sequence INT NULL
)
ENGINE=OLAP
PRIMARY KEY(id, createdAt)
PARTITION BY date_trunc('DAY', createdAt)
DISTRIBUTED BY HASH(id)
ORDER BY (id)
PROPERTIES (
    "compression" = "LZ4",
    "enable_persistent_index" = "true",
    "fast_schema_evolution" = "true",
    "replicated_storage" = "true",
    "replication_num" = "2"
);
