CREATE TABLE IF NOT EXISTS wms_pick_drop_enriched (
    -- Core Identifiers
    pick_item_id STRING NOT NULL,
    drop_item_id STRING NOT NULL,
    pick_item_created_at DATETIME NOT NULL,
    wh_id BIGINT NULL,
    principal_id BIGINT NULL,
    session_id STRING NULL,
    task_id STRING NULL,
    lm_trip_id STRING NULL,

    -- Pick Item Core Fields
    picked_bin STRING NULL,
    picked_sku_id STRING NULL,
    picked_batch STRING NULL,
    picked_uom STRING NULL,
    overall_qty INT NULL,
    qty INT NULL,
    hu_code STRING NULL,
    destination_bin_code STRING NULL,
    picked_qty INT NULL,
    picked_at DATETIME NULL,
    picked_by_worker_id STRING NULL,
    moved_at DATETIME NULL,
    processed_at DATETIME NULL,

    -- Pick Handling Unit Fields
    picked_hu_eq_uom STRING NULL,
    picked_has_inner_hus BOOLEAN NULL,
    picked_inner_hu_eq_uom STRING NULL,
    picked_bin_assigned_at DATETIME NULL,
    scan_source_hu_kind STRING NULL,
    pick_source_hu_kind STRING NULL,
    carrier_hu_kind STRING NULL,
    scanned_source_hu_code STRING NULL,
    picked_source_hu_code STRING NULL,
    carrier_hu_code STRING NULL,
    hu_kind STRING NULL,
    source_hu_eq_uom STRING NULL,
    pick_item_updated_at DATETIME NULL,

    -- Pick Additional Fields
    eligible_drop_locations STRING NULL,
    parent_item_id STRING NULL,
    old_batch STRING NULL,
    dest_bucket STRING NULL,
    original_source_bin_code STRING NULL,
    picked_inner_hu_code STRING NULL,
    picked_inner_hu_kind_code STRING NULL,
    picked_quant_bucket STRING NULL,
    pick_auto_complete BOOLEAN NULL,
    pick_hu BOOLEAN NULL,
    short_allocation_reason STRING NULL,
    drop_item_previous_task_id STRING NULL,

    -- Drop Item Core Fields
    dropped_sku_id STRING NULL,
    dropped_batch STRING NULL,
    dropped_uom STRING NULL,
    drop_bucket STRING NULL,
    picked_hu_code STRING NULL,
    dropped_bin_code STRING NULL,
    dropped_qty INT NULL,
    dropped_at DATETIME NULL,
    drop_item_updated_at DATETIME NULL,

    -- Drop Handling Unit Fields
    drop_hu_in_bin BOOLEAN NULL,
    scan_dest_hu BOOLEAN NULL,
    allow_hu_break BOOLEAN NULL,
    dropped_has_inner_hus BOOLEAN NULL,
    scan_inner_hus BOOLEAN NULL,
    dropped_hu_eq_uom STRING NULL,
    dest_hu_code STRING NULL,
    dropped_inner_hu_id STRING NULL,
    dropped_inner_hu_eq_uom STRING NULL,
    dest_bin_assigned_at DATETIME NULL,
    drop_uom STRING NULL,
    drop_parent_item_id STRING NULL,
    hu_broken BOOLEAN NULL,
    drop_original_source_bin_code STRING NULL,
    processed_for_loading_at DATETIME NULL,
    drop_quant_bucket STRING NULL,
    drop_inner_hu_code STRING NULL,
    dropped_inner_hu_kind_code STRING NULL,
    drop_inner_hu BOOLEAN NULL,
    allow_inner_hu_break BOOLEAN NULL,
    inner_hu_broken BOOLEAN NULL,
    drop_auto_complete BOOLEAN NULL,
    quant_slotting_for_hus BOOLEAN NULL,
    processed_on_drop_at DATETIME NULL,
    allow_hu_break_v2 BOOLEAN NULL,

    -- Additional Pick Item IDs
    bin_id STRING NULL,
    bin_hu_id STRING NULL,
    destination_bin_id STRING NULL,
    destination_bin_hu_id STRING NULL,
    pick_deactivated_at DATETIME NULL,
    pick_deactivated_by STRING NULL,
    moved_by STRING NULL,
    scanned_source_hu_id STRING NULL,
    picked_source_hu_id STRING NULL,
    carrier_hu_id STRING NULL,
    original_source_bin_id STRING NULL,
    inner_hu_id STRING NULL,
    inner_hu_kind_id STRING NULL,
    pd_previous_task_id STRING NULL,
    input_source_bin_id STRING NULL,
    provisional_item_id STRING NULL,
    input_dest_hu_id STRING NULL,
    pick_item_kind STRING NULL,
    tp_assigned_at DATETIME NULL,
    leg_index INT NULL,
    last_leg BOOLEAN NULL,
    ep_assigned_at DATETIME NULL,
    carrier_hu_formed_id STRING NULL,
    hu_index INT NULL,
    pick_sequence INT NULL,
    carrier_hu_force_closed BOOLEAN NULL,
    input_dest_bin_id STRING NULL,
    inner_hu_index INT NULL,
    inner_carrier_hu_key STRING NULL,
    inner_carrier_hu_formed_id STRING NULL,
    inner_carrier_hu_id STRING NULL,
    inner_carrier_hu_code STRING NULL,
    inner_carrier_hu_kind STRING NULL,
    induction_id STRING NULL,
    inner_carrier_hu_force_closed BOOLEAN NULL,
    mhe_id STRING NULL,
    pick_attrs STRING NULL,
    iloc STRING NULL,
    dest_iloc STRING NULL,

    -- Additional Drop Item IDs
    source_bin_id STRING NULL,
    source_bin_hu_id STRING NULL,
    drop_bin_id STRING NULL,
    drop_bin_hu_id STRING NULL,
    drop_created_at DATETIME NULL,
    drop_deactivated_at DATETIME NULL,
    drop_deactivated_by STRING NULL,
    dropped_by_worker_id STRING NULL,
    dest_hu_id STRING NULL,
    source_bucket STRING NULL,
    original_destination_bin_id STRING NULL,
    drop_lm_trip_id STRING NULL,
    processed_for_pick_at DATETIME NULL,
    drop_provisional_item_id STRING NULL,
    drop_input_dest_hu_id STRING NULL,
    drop_leg_index INT NULL,
    drop_last_leg BOOLEAN NULL,
    drop_input_dest_bin_id STRING NULL,
    drop_induction_id STRING NULL,
    drop_attrs STRING NULL,
    drop_mhe_id STRING NULL,
    drop_iloc STRING NULL,
    source_iloc STRING NULL,

    -- Mapping Fields
    mapping_id STRING NULL,
    mapping_created_at DATETIME NULL,

    -- Event time
    event_time DATETIME NULL,

    -- Worker Enrichment
    worker_code STRING NULL,
    worker_name STRING NULL,
    worker_phone STRING NULL,
    worker_supervisor BOOLEAN NULL,
    worker_active BOOLEAN NULL,

    -- Dropped Handling Unit Enrichment
    dropped_hu_code STRING NULL,
    dropped_hu_kind_id STRING NULL,
    dropped_hu_session_id STRING NULL,
    dropped_hu_task_id STRING NULL,
    dropped_hu_storage_id STRING NULL,
    dropped_hu_outer_hu_id STRING NULL,
    dropped_hu_state STRING NULL,
    dropped_hu_attrs STRING NULL,
    dropped_hu_lock_task_id STRING NULL,
    dropped_hu_effective_storage_id STRING NULL,
    dropped_hu_created_at DATETIME NULL,
    dropped_hu_updated_at DATETIME NULL,

    -- SKU Enrichment Fields (from picked_sku_id, captured at event time)
    sku_category STRING NULL,
    sku_product STRING NULL,
    sku_product_id STRING NULL,
    sku_category_group STRING NULL,
    sku_sub_brand STRING NULL,
    sku_brand STRING NULL,
    sku_code STRING NULL,
    sku_name STRING NULL,
    sku_short_description STRING NULL,
    sku_description STRING NULL,
    sku_fulfillment_type STRING NULL,
    sku_inventory_type STRING NULL,
    sku_shelf_life INT NULL,
    sku_tag1 STRING NULL,
    sku_tag2 STRING NULL,
    sku_tag3 STRING NULL,
    sku_tag4 STRING NULL,
    sku_tag5 STRING NULL,
    sku_handling_unit_type STRING NULL,
    sku_cases_per_layer INT NULL,
    sku_layers INT NULL,
    sku_l0_units INT NULL,
    sku_l1_units INT NULL,
    sku_l2_units INT NULL,
    sku_l3_units INT NULL,
    sku_l0_name STRING NULL,
    sku_l0_weight DOUBLE NULL,
    sku_l0_volume DOUBLE NULL,
    sku_l0_package_type STRING NULL,
    sku_l0_length DOUBLE NULL,
    sku_l0_width DOUBLE NULL,
    sku_l0_height DOUBLE NULL,
    sku_l0_itf_code STRING NULL,
    sku_l1_name STRING NULL,
    sku_l1_weight DOUBLE NULL,
    sku_l1_volume DOUBLE NULL,
    sku_l1_package_type STRING NULL,
    sku_l1_length DOUBLE NULL,
    sku_l1_width DOUBLE NULL,
    sku_l1_height DOUBLE NULL,
    sku_l1_itf_code STRING NULL,
    sku_l2_name STRING NULL,
    sku_l2_weight DOUBLE NULL,
    sku_l2_volume DOUBLE NULL,
    sku_l2_package_type STRING NULL,
    sku_l2_length DOUBLE NULL,
    sku_l2_width DOUBLE NULL,
    sku_l2_height DOUBLE NULL,
    sku_l2_itf_code STRING NULL,
    sku_l3_name STRING NULL,
    sku_l3_weight DOUBLE NULL,
    sku_l3_volume DOUBLE NULL,
    sku_l3_package_type STRING NULL,
    sku_l3_length DOUBLE NULL,
    sku_l3_width DOUBLE NULL,
    sku_l3_height DOUBLE NULL,
    sku_l3_itf_code STRING NULL,
    sku_avg_l0_per_put INT NULL,
    sku_combined_classification STRING NULL
)
ENGINE=OLAP
PRIMARY KEY(pick_item_id, drop_item_id, pick_item_created_at)
PARTITION BY date_trunc('MONTH', pick_item_created_at)
DISTRIBUTED BY HASH(pick_item_id) BUCKETS 4
ORDER BY (wh_id, pick_item_created_at)
PROPERTIES (
    "compression" = "ZSTD",
    "enable_persistent_index" = "true",
    "fast_schema_evolution" = "true",
    "replicated_storage" = "true",
    "replication_num" = "2",
    "partition_live_number" = "36"
);
