CREATE TABLE wms_ob_load_item (
  id varchar(36) NOT NULL COMMENT "",
  whId bigint(20) NOT NULL COMMENT "",
  sessionId varchar(36) NOT NULL COMMENT "",
  taskId varchar(36) NOT NULL COMMENT "",
  tripId varchar(36) NOT NULL COMMENT "",
  skuId varchar(36) NOT NULL COMMENT "",
  skuClass varchar(256) NOT NULL COMMENT "",
  uom varchar(64) NOT NULL COMMENT "",
  qty int(11) NOT NULL COMMENT "",
  seq bigint(20) NOT NULL COMMENT "",
  loadedQty int(11) NULL COMMENT "",
  loadedAt datetime NULL COMMENT "",
  loadedBy varchar(36) NULL COMMENT "",
  createdAt datetime NULL COMMENT "",
  invoiceId varchar(36) NULL COMMENT "",
  skuCategory varchar(256) NULL COMMENT "",
  originalSkuId varchar(36) NOT NULL COMMENT "",
  batch varchar(256) NULL COMMENT "",
  huId varchar(36) NULL COMMENT "",
  huCode varchar(256) NULL COMMENT "",
  mmTripId varchar(36) NULL COMMENT "",
  innerHUId varchar(36) NULL COMMENT "",
  innerHUCode varchar(256) NULL COMMENT "",
  innerHUKind varchar(128) NULL COMMENT "",
  binId varchar(36) NULL COMMENT "",
  binHUId varchar(36) NULL COMMENT "",
  binCode varchar(256) NULL COMMENT "",
  parentItemId varchar(36) NULL COMMENT "",
  classificationType varchar(256) NULL COMMENT "",
  originalQty int(11) NULL COMMENT "",
  originalUOM varchar(64) NULL COMMENT "",
  repicked boolean NULL COMMENT "",
  invoiceCode varchar(256) NULL COMMENT "",
  retailerId varchar(128) NULL COMMENT "",
  retailerCode varchar(128) NULL COMMENT "",
  retailerName varchar(256) NULL COMMENT "",
  retailerCity varchar(256) NULL COMMENT "",
  orderProgressProcessedAt datetime NULL COMMENT "",
  iloc varchar(256) NULL COMMENT "",
  salesOrderCode varchar(256) NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(id)
DISTRIBUTED BY HASH(id) BUCKETS 16 
PROPERTIES (
"compression" = "LZ4",
"enable_persistent_index" = "true",
"fast_schema_evolution" = "true",
"replicated_storage" = "true",
"replication_num" = "2"
);