CREATE TABLE wms_vehicle_event (
  id varchar(36) NOT NULL COMMENT "",
  whId bigint(20) NULL COMMENT "",
  vehicleId varchar(256) NULL COMMENT "",
  vehicleNo varchar(256) NULL COMMENT "",
  vehicleType varchar(256) NULL COMMENT "",
  gatingEnabled boolean NULL COMMENT "",
  attrs json NULL COMMENT "",
  status varchar(64) NULL COMMENT "",
  sessionId varchar(36) NULL COMMENT "",
  sessionKind varchar(128) NULL COMMENT "",
  gateReportedAt datetime NULL COMMENT "",
  gateInAt datetime NULL COMMENT "",
  gateOutAt datetime NULL COMMENT "",
  dockdoorId varchar(36) NULL COMMENT "",
  dockdoorCode varchar(256) NULL COMMENT "",
  dockdoorQueue int(11) NULL COMMENT "",
  dockInAt datetime NULL COMMENT "",
  dockOutAt datetime NULL COMMENT "",
  createdAt datetime NULL COMMENT "",
  updatedAt datetime NULL COMMENT "",
  active boolean NULL COMMENT "",
  parkingSlotId varchar(36) NULL COMMENT "",
  parkingSlotAssignedAt datetime NULL COMMENT "",
  gatePassCode varchar(256) NULL COMMENT "",
  undockedAt datetime NULL COMMENT "",
  transporterCode varchar(256) NULL COMMENT "",
  originalVehicle varchar(256) NULL COMMENT "",
  shipmentTypes json NULL COMMENT "",
  isSealCaptureSuccessful boolean NULL COMMENT "",
  sealCapturedAt datetime NULL COMMENT "",
  sealCaptureImages json NULL COMMENT "",
  sealCaptureRemarks text NULL COMMENT "",
  driverName varchar(256) NULL COMMENT "",
  driverNumber varchar(128) NULL COMMENT "",
  isDockingRejected boolean NULL COMMENT "",
  vehicleRejectedAt datetime NULL COMMENT "",
  dockingRejectedBy bigint(20) NULL COMMENT "",
  dockingRejectionRemark text NULL COMMENT "",
  dockingRejectionImages json NULL COMMENT "",
  fleetType varchar(256) NULL COMMENT "",
  loadType varchar(128) NULL COMMENT "",
  entryWeight double NULL COMMENT "",
  exitWeight double NULL COMMENT "",
  entryTemp double NULL COMMENT "",
  exitTemp double NULL COMMENT "",
  dockRejectedByApp varchar(256) NULL COMMENT "",
  oldDriverName varchar(256) NULL COMMENT "",
  oldDriverNumber varchar(128) NULL COMMENT "",
  commonQueue int(11) NULL COMMENT "",
  gatingQueue int(11) NULL COMMENT "",
  sealCapturedBy bigint(20) NULL COMMENT "",
  sealCapturedByApp varchar(256) NULL COMMENT "",
  lrNumber varchar(256) NULL COMMENT "",
  certificateVerificationStatus varchar(128) NULL COMMENT "",
  certificateVerificationReason varchar(512) NULL COMMENT "",
  driverSafetyTestResultId varchar(36) NULL COMMENT "",
  documentCollectionMode varchar(128) NULL COMMENT "",
  documentCollectedAt datetime NULL COMMENT "",
  processingStartedAt datetime NULL COMMENT "",
  processingEndedAt datetime NULL COMMENT "",
  manualTrips json NULL COMMENT "",
  manualTripsUpdatedAt datetime NULL COMMENT "",
  firstDockInAt datetime NULL COMMENT "",
  otpVerified boolean NULL COMMENT "",
  discrepancyCaptured boolean NULL COMMENT "",
  iloc varchar(256) NULL COMMENT "",
  stagingStartedAt datetime NULL COMMENT "",
  stagingEndedAt datetime NULL COMMENT "",
  dockAssignedAt datetime NULL COMMENT "",
  dockEligibleAt datetime NULL COMMENT "",
  dockHistory json NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(id)
DISTRIBUTED BY HASH(id) BUCKETS 16 
PROPERTIES (
"compression" = "LZ4",
"enable_persistent_index" = "true",
"fast_schema_evolution" = "true",
"replicated_storage" = "true",
"replication_num" = "2"
);
