CREATE TABLE wms_vehicle_event (
    id VARCHAR(255),
    createdAt DATETIME DEFAULT "1970-01-01 00:00:00",
    whId BIGINT DEFAULT "0",
    vehicleId VARCHAR(255) DEFAULT "",
    vehicleNo VARCHAR(255) DEFAULT "",
    vehicleType VARCHAR(255) DEFAULT "",
    gatingEnabled BOOLEAN DEFAULT "0",
    attrs JSON,
    status VARCHAR(100) DEFAULT "",
    sessionId VARCHAR(255) DEFAULT "",
    sessionKind VARCHAR(255) DEFAULT "",
    gateReportedAt DATETIME,
    gateInAt DATETIME,
    gateOutAt DATETIME,
    dockdoorId VARCHAR(255) DEFAULT "",
    dockdoorCode VARCHAR(255) DEFAULT "",
    dockdoorQueue INT DEFAULT "0",
    dockInAt DATETIME,
    dockOutAt DATETIME,
    updatedAt DATETIME DEFAULT "1970-01-01 00:00:00",
    active BOOLEAN DEFAULT "1",
    parkingSlotId VARCHAR(255) DEFAULT "",
    parkingSlotAssignedAt DATETIME,
    gatePassCode VARCHAR(255) DEFAULT "",
    undockedAt DATETIME,
    transporterCode VARCHAR(255) DEFAULT "",
    originalVehicle VARCHAR(255) DEFAULT "",
    shipmentTypes JSON,
    isSealCaptureSuccessful BOOLEAN DEFAULT "0",
    sealCapturedAt DATETIME,
    sealCaptureImages JSON,
    sealCaptureRemarks VARCHAR(1000) DEFAULT "",
    driverName VARCHAR(255) DEFAULT "",
    driverNumber VARCHAR(255) DEFAULT "",
    isDockingRejected BOOLEAN DEFAULT "0",
    vehicleRejectedAt DATETIME,
    dockingRejectedBy BIGINT DEFAULT "0",
    dockingRejectionRemark VARCHAR(1000) DEFAULT "",
    dockingRejectionImages JSON,
    fleetType VARCHAR(255) DEFAULT "",
    loadType VARCHAR(100) DEFAULT "NON_PALLETIZED",
    entryWeight DOUBLE DEFAULT "0",
    exitWeight DOUBLE DEFAULT "0",
    entryTemp DOUBLE DEFAULT "0",
    exitTemp DOUBLE DEFAULT "0",
    dockRejectedByApp VARCHAR(255) DEFAULT "",
    oldDriverName VARCHAR(255) DEFAULT "",
    oldDriverNumber VARCHAR(255) DEFAULT "",
    commonQueue INT DEFAULT "0",
    gatingQueue INT DEFAULT "0",
    sealCapturedBy BIGINT DEFAULT "0",
    sealCapturedByApp VARCHAR(255) DEFAULT "",
    lrNumber VARCHAR(255) DEFAULT "",
    certificateVerificationStatus VARCHAR(255) DEFAULT "",
    certificateVerificationReason VARCHAR(1000) DEFAULT "",
    driverSafetyTestResultId VARCHAR(255) DEFAULT "",
    documentCollectionMode VARCHAR(255) DEFAULT "",
    documentCollectedAt DATETIME,
    processingStartedAt DATETIME,
    processingEndedAt DATETIME,
    manualTrips JSON,
    manualTripsUpdatedAt DATETIME,
    firstDockInAt DATETIME,
    otpVerified BOOLEAN DEFAULT "0",
    discrepancyCaptured BOOLEAN DEFAULT "0",
    iloc VARCHAR(255) DEFAULT "",
    stagingStartedAt DATETIME,
    stagingEndedAt DATETIME,
    dockAssignedAt DATETIME,
    dockEligibleAt DATETIME,
    dockHistory JSON
)
ENGINE=OLAP
DUPLICATE KEY(id, createdAt)
PARTITION BY date_trunc('MONTH', createdAt)
DISTRIBUTED BY HASH(id) BUCKETS 16
PROPERTIES (
    "compression" = "LZ4",
    "enable_persistent_index" = "true",
    "fast_schema_evolution" = "true",
    "replicated_storage" = "true",
    "replication_num" = "2"
);