---
# StatefulSet for persistent dev environment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dev-pod
spec:
  serviceName: dev-pod-service
  replicas: 1
  selector:
    matchLabels:
      app: dev-pod
  template:
    metadata:
      labels:
        app: dev-pod
        environment: development
    spec:
      containers:
        - name: dev-container
          image: asia-docker.pkg.dev/sbx-ci-cd/public/dev-pod:latest
          imagePullPolicy: Always

          # Resource limits (adjust as needed)
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"

          # Environment variables
          env:
            - name: NODE_ENV
              value: "development"

          # Volume mounts
          volumeMounts:
            - name: workspace
              mountPath: /workspace
            - name: npm-cache
              mountPath: /root/.npm

          # Keep stdin open for kubectl exec
          stdin: true
          tty: true

          # Liveness probe to ensure container stays healthy
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "ps aux | grep 'tail -f /dev/null' | grep -v grep"
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3

          # Readiness probe
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "which node && which psql && which kafka-topics.sh"
            initialDelaySeconds: 10
            periodSeconds: 10

      volumes:
        # EmptyDir for npm cache
        - name: npm-cache
          emptyDir: {}

      # Allow scheduling on spot instances
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      
      # Prefer spot instances but allow regular nodes as fallback
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: "kubernetes.azure.com/scalesetpriority"
                    operator: In
                    values: ["spot"]
  
  # Volume claim templates for each pod replica
  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: managed-csi-premium
---
# Headless service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: dev-pod-service
spec:
  type: ClusterIP
  clusterIP: None # Headless service for StatefulSet
  selector:
    app: dev-pod
  ports:
    - name: nodejs
      port: 3000
      targetPort: 3000
    - name: debug
      port: 9229
      targetPort: 9229
