CREATE TABLE pick_drop_basic (
    pick_item_id STRING,
    drop_item_id STRING,
    wh_id BIGINT,
    session_id STRING,
    task_id STRING,
    lm_trip_id STRING,
    -- Pick item fields
    picked_bin STRING,
    picked_sku_id STRING,
    picked_batch STRING,
    picked_uom STRING,
    overall_qty INT,
    qty INT,
    hu_code STRING,
    destination_bin_code STRING,
    pick_item_created_at TIMESTAMP(3),
    picked_qty INT,
    picked_at TIMESTAMP(3),
    picked_by_worker_id STRING,
    moved_at TIMESTAMP(3),
    processed_at TIMESTAMP(3),
    picked_hu_eq_uom STRING,
    picked_has_inner_hus BOOLEAN,
    picked_inner_hu_eq_uom STRING,
    picked_bin_assigned_at TIMESTAMP(3),
    scan_source_hu_kind STRING,
    pick_source_hu_kind STRING,
    carrier_hu_kind STRING,
    scanned_source_hu_code STRING,
    picked_source_hu_code STRING,
    carrier_hu_code STRING,
    hu_kind STRING,
    source_hu_eq_uom STRING,
    pick_item_updated_at TIMESTAMP(3),
    eligible_drop_locations STRING,
    parent_item_id STRING,
    old_batch STRING,
    dest_bucket STRING,
    original_source_bin_code STRING,
    picked_inner_hu_code STRING,
    picked_inner_hu_kind_code STRING,
    picked_quant_bucket STRING,
    pick_auto_complete BOOLEAN,
    pick_hu BOOLEAN,
    short_allocation_reason STRING,
    -- Drop item fields
    dropped_sku_id STRING,
    dropped_batch STRING,
    dropped_uom STRING,
    drop_bucket STRING,
    picked_hu_code STRING,
    dropped_bin_code STRING,
    dropped_qty INT,
    dropped_at TIMESTAMP(3),
    drop_item_updated_at TIMESTAMP(3),
    drop_hu_in_bin BOOLEAN,
    scan_dest_hu BOOLEAN,
    allow_hu_break BOOLEAN,
    dropped_has_inner_hus BOOLEAN,
    scan_inner_hus BOOLEAN,
    dropped_hu_eq_uom STRING,
    dest_hu_code STRING,
    dropped_inner_hu_id STRING,
    dropped_inner_hu_eq_uom STRING,
    dest_bin_assigned_at TIMESTAMP(3),
    drop_uom STRING,
    drop_parent_item_id STRING,
    hu_broken BOOLEAN,
    drop_original_source_bin_code STRING,
    processed_for_loading_at TIMESTAMP(3),
    drop_quant_bucket STRING,
    drop_inner_hu_code STRING,
    dropped_inner_hu_kind_code STRING,
    drop_inner_hu BOOLEAN,
    allow_inner_hu_break BOOLEAN,
    inner_hu_broken BOOLEAN,
    drop_auto_complete BOOLEAN,
    quant_slotting_for_hus BOOLEAN,
    processed_on_drop_at TIMESTAMP(3),
    allow_hu_break_v2 BOOLEAN,
    deactivated_at TIMESTAMP(3),
    -- Mapping fields
    mapping_id STRING,
    mapping_created_at TIMESTAMP(3),
    -- Additional fields
    bin_id STRING,
    bin_hu_id STRING,
    destination_bin_id STRING,
    destination_bin_hu_id STRING,
    pick_deactivated_at TIMESTAMP(3),
    pick_deactivated_by STRING,
    moved_by STRING,
    scanned_source_hu_id STRING,
    picked_source_hu_id STRING,
    carrier_hu_id STRING,
    original_source_bin_id STRING,
    inner_hu_id STRING,
    inner_hu_kind_id STRING,
    pd_previous_task_id STRING,
    input_source_bin_id STRING,
    provisional_item_id STRING,
    input_dest_hu_id STRING,
    pick_item_kind STRING,
    tp_assigned_at TIMESTAMP(3),
    leg_index INT,
    last_leg BOOLEAN,
    ep_assigned_at TIMESTAMP(3),
    carrier_hu_formed_id STRING,
    hu_index INT,
    pick_sequence INT,
    carrier_hu_force_closed BOOLEAN,
    input_dest_bin_id STRING,
    inner_hu_index INT,
    inner_carrier_hu_key STRING,
    inner_carrier_hu_formed_id STRING,
    inner_carrier_hu_id STRING,
    inner_carrier_hu_code STRING,
    inner_carrier_hu_kind STRING,
    induction_id STRING,
    inner_carrier_hu_force_closed BOOLEAN,
    mhe_id STRING,
    pick_attrs STRING,
    iloc STRING,
    dest_iloc STRING,
    source_bin_id STRING,
    source_bin_hu_id STRING,
    drop_bin_id STRING,
    drop_bin_hu_id STRING,
    drop_created_at TIMESTAMP(3),
    drop_deactivated_at TIMESTAMP(3),
    drop_deactivated_by STRING,
    dropped_by_worker_id STRING,
    dest_hu_id STRING,
    source_bucket STRING,
    original_destination_bin_id STRING,
    drop_lm_trip_id STRING,
    processed_for_pick_at TIMESTAMP(3),
    drop_provisional_item_id STRING,
    drop_input_dest_hu_id STRING,
    drop_leg_index INT,
    drop_last_leg BOOLEAN,
    drop_input_dest_bin_id STRING,
    drop_induction_id STRING,
    drop_attrs STRING,
    drop_mhe_id STRING,
    drop_iloc STRING,
    source_iloc STRING,
    -- Fields from the upstream pipeline
    is_snapshot BOOLEAN,
    event_time TIMESTAMP(3),
    proc_time AS PROCTIME()  -- Processing time for historical data
) WITH (
    'connector' = 'kafka',
    'topic' = 'sbx_uat.wms.internal.pick_drop_basic',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.group.id' = 'sbx-uat-wms-pick-drop-enriched',  -- Shared group with real-time
    'properties.enable.auto.commit' = 'true',  -- Commit offsets for real-time to continue
    'properties.auto.commit.interval.ms' = '5000',  -- Commit every 5 seconds
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'scan.startup.mode' = 'earliest-offset',  -- Start from beginning
    'scan.bounded.mode' = 'latest-offset',  -- Process up to current latest offset then stop
    'format' = 'avro-confluent',
    'avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);

select * from pick_drop_basic
where pick_item_id = '019897a1-6ae9-76ae-b2a9-69c69c0597af';
