SET 'pipeline.name' = 'WMS Pick Drop Joined';
-- Source Table 1: Pick Items
CREATE TABLE pick_items (
    id STRING,
    `whId` BIGINT,
    `sessionId` STRING,
    `taskId` STRING,
    `binId` STRING,
    `binHUId` STRING,
    `binCode` STRING,
    `skuId` STRING,
    batch STRING,
    uom STRING,
    bucket STRING,
    `overallQty` INT,
    qty INT,
    `huId` STRING,
    `huCode` STRING,
    `destinationBinId` STRING,
    `destinationBinHUId` STRING,
    `destinationBinCode` STRING,
    `createdAt` TIMESTAMP(3),
    `deactivatedAt` TIMESTAMP(3),
    `deactivatedBy` STRING,
    `pickedQty` INT,
    `pickedAt` TIMESTAMP(3),
    `pickedBy` STRING,
    `movedAt` TIMESTAMP(3),
    `movedBy` STRING,
    `processedAt` TIMESTAMP(3),
    `huEqUOM` STRING,
    `hasInnerHUs` BOOLEAN,
    `innerHUEqUOM` STRING,
    `binAssignedAt` TIMESTAMP(3),
    `scanSourceHUKind` STRING,
    `pickSourceHUKind` STRING,
    `carrierHUKind` STRING,
    `scannedSourceHUId` STRING,
    `scannedSourceHUCode` STRING,
    `pickedSourceHUId` STRING,
    `pickedSourceHUCode` STRING,
    `carrierHUId` STRING,
    `carrierHUCode` STRING,
    `huKind` STRING,
    `sourceHUEqUOM` STRING,
    `updatedAt` TIMESTAMP(3),
    `eligibleDropLocations` STRING,
    `parentItemId` STRING,
    `oldBatch` STRING,
    `destBucket` STRING,
    `originalSourceBinId` STRING,
    `originalSourceBinCode` STRING,
    `lmTripId` STRING,
    `innerHUId` STRING,
    `innerHUCode` STRING,
    `innerHUKindId` STRING,
    `innerHUKindCode` STRING,
    `quantBucket` STRING,
    `autoCompleted` BOOLEAN,
    `pickHU` BOOLEAN,
    `shortAllocationReason` STRING,
    `pdPreviousTaskId` STRING,
    `inputSourceBinId` STRING,
    `provisionalItemId` STRING,
    `inputDestHUId` STRING,
    kind STRING,
    `tpAssignedAt` TIMESTAMP(3),
    `legIndex` INT,
    `lastLeg` BOOLEAN,
    `epAssignedAt` TIMESTAMP(3),
    `carrierHUFormedId` STRING,
    `huIndex` INT,
    sequence INT,
    `carrierHUForceClosed` BOOLEAN,
    `inputDestBinId` STRING,
    `innerHUIndex` INT,
    `innerCarrierHUKey` STRING,
    `innerCarrierHUFormedId` STRING,
    `innerCarrierHUId` STRING,
    `innerCarrierHUCode` STRING,
    `innerCarrierHUKind` STRING,
    `inductionId` STRING,
    `innerCarrierHUForceClosed` BOOLEAN,
    `mheId` STRING,
    attrs STRING,
    iloc STRING,
    `destIloc` STRING,
    `is_deleted` BOOLEAN,
    proc_time AS PROCTIME(),
    WATERMARK FOR `updatedAt` AS `updatedAt` - INTERVAL '5' SECOND
) WITH (
    'connector' = 'kafka',
    'topic' = 'sbx_uat.wms.public.pd_pick_item',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.group.id' = 'wms-pick-drop-joined',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.auto.offset.reset' = 'earliest',
    'format' = 'avro-confluent',
    'avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
-- Source Table 2: Drop Items
CREATE TABLE drop_items (
    id STRING,
    `whId` BIGINT,
    `sessionId` STRING,
    `taskId` STRING,
    `sourceBinId` STRING,
    `sourceBinHUId` STRING,
    `sourceBinCode` STRING,
    `skuId` STRING,
    batch STRING,
    uom STRING,
    bucket STRING,
    qty INT,
    `huId` STRING,
    `huCode` STRING,
    `binId` STRING,
    `binHUId` STRING,
    `binCode` STRING,
    `createdAt` TIMESTAMP(3),
    `deactivatedAt` TIMESTAMP(3),
    `deactivatedBy` STRING,
    `droppedQty` INT,
    `droppedAt` TIMESTAMP(3),
    `droppedBy` STRING,
    `updatedAt` TIMESTAMP(3),
    `dropHUInBin` BOOLEAN,
    `scanDestHU` BOOLEAN,
    `allowHUBreak` BOOLEAN,
    `hasInnerHUs` BOOLEAN,
    `scanInnerHUs` BOOLEAN,
    `huEqUOM` STRING,
    `destHUId` STRING,
    `destHUCode` STRING,
    `droppedInnerHUId` STRING,
    `innerHUEqUOM` STRING,
    `binAssignedAt` TIMESTAMP(3),
    `dropUOM` STRING,
    `eligibleDropLocations` STRING,
    `parentItemId` STRING,
    `huBroken` BOOLEAN,
    `pickedBy` STRING,
    `sourceBucket` STRING,
    `originalDestinationBinId` STRING,
    `originalDestinationBinCode` STRING,
    `lmTripId` STRING,
    `processedForLoadingAt` TIMESTAMP(3),
    `quantBucket` STRING,
    `innerHUId` STRING,
    `innerHUCode` STRING,
    `innerHUKindId` STRING,
    `innerHUKindCode` STRING,
    `dropInnerHU` BOOLEAN,
    `allowInnerHUBreak` BOOLEAN,
    `innerHUBroken` BOOLEAN,
    `autoCompleted` BOOLEAN,
    `processedForPickAt` TIMESTAMP(3),
    `quantSlottingForHUs` BOOLEAN,
    `pdPreviousTaskId` STRING,
    `processedOnDropAt` TIMESTAMP(3),
    `provisionalItemId` STRING,
    `allowHUBreakV2` BOOLEAN,
    `inputDestHUId` STRING,
    `legIndex` INT,
    `lastLeg` BOOLEAN,
    `inputDestBinId` STRING,
    `inductionId` STRING,
    attrs STRING,
    `mheId` STRING,
    iloc STRING,
    `sourceIloc` STRING,
    `is_deleted` BOOLEAN,
    WATERMARK FOR `updatedAt` AS `updatedAt` - INTERVAL '5' SECOND
) WITH (
    'connector' = 'kafka',
    'topic' = 'sbx_uat.wms.public.pd_drop_item',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.group.id' = 'wms-pick-drop-joined',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.auto.offset.reset' = 'earliest',
    'format' = 'avro-confluent',
    'avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
-- Source Table 3: Pick Drop Mapping
CREATE TABLE pick_drop_mapping (
    id STRING,
    `whId` BIGINT,
    `sessionId` STRING,
    `taskId` STRING,
    `pickItemId` STRING,
    `dropItemId` STRING,
    `createdAt` TIMESTAMP(3),
    `is_deleted` BOOLEAN,
    WATERMARK FOR `createdAt` AS `createdAt` - INTERVAL '5' SECOND
) WITH (
    'connector' = 'kafka',
    'topic' = 'sbx_uat.wms.public.pd_pick_drop_mapping',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.group.id' = 'wms-pick-drop-joined',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.auto.offset.reset' = 'earliest',
    'format' = 'avro-confluent',
    'avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
-- Source Table 4: Tasks
CREATE TABLE tasks (
    `whId` BIGINT,
    id STRING,
    `sessionId` STRING,
    kind STRING,
    code STRING,
    seq INT,
    exclusive BOOLEAN,
    state STRING,
    attrs STRING,
    progress STRING,
    `createdAt` TIMESTAMP(3),
    `updatedAt` TIMESTAMP(3),
    active BOOLEAN,
    `allowForceComplete` BOOLEAN,
    `autoComplete` BOOLEAN,
    wave INT,
    `forceCompleteTaskId` STRING,
    `forceCompleted` BOOLEAN,
    `subKind` STRING,
    label STRING,
    `is_deleted` BOOLEAN,
    WATERMARK FOR `updatedAt` AS `updatedAt` - INTERVAL '5' SECOND
) WITH (
    'connector' = 'kafka',
    'topic' = 'sbx_uat.wms.public.task',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.group.id' = 'wms-pick-drop-joined',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.auto.offset.reset' = 'earliest',
    'format' = 'avro-confluent',
    'avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
-- Source Table 5: Sessions
CREATE TABLE `sessions` (
    `whId` BIGINT,
    id STRING,
    kind STRING,
    code STRING,
    attrs STRING,
    `createdAt` TIMESTAMP(3),
    `updatedAt` TIMESTAMP(3),
    active BOOLEAN,
    state STRING,
    progress STRING,
    `autoComplete` BOOLEAN,
    `is_deleted` BOOLEAN,
    WATERMARK FOR `updatedAt` AS `updatedAt` - INTERVAL '5' SECOND
) WITH (
    'connector' = 'kafka',
    'topic' = 'sbx_uat.wms.public.session',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.group.id' = 'wms-pick-drop-joined',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.auto.offset.reset' = 'earliest',
    'format' = 'avro-confluent',
    'avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
-- Source Table 6: Trips
CREATE TABLE trips (
    `sessionCreatedAt` TIMESTAMP(3),
    `whId` BIGINT,
    `sessionId` STRING,
    id STRING,
    `createdAt` TIMESTAMP(3),
    `bbId` STRING,
    code STRING,
    `type` STRING,
    priority INT,
    `dockdoorId` STRING,
    `dockdoorCode` STRING,
    `vehicleId` STRING,
    `vehicleNo` STRING,
    `vehicleType` STRING,
    `deliveryDate` DATE,
    `is_deleted` BOOLEAN,
    WATERMARK FOR `createdAt` AS `createdAt` - INTERVAL '5' SECOND
) WITH (
    'connector' = 'kafka',
    'topic' = 'sbx_uat.wms.public.trip',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.group.id' = 'wms-pick-drop-joined',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.auto.offset.reset' = 'earliest',
    'format' = 'avro-confluent',
    'avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
-- Source Table 7: Trip Relations
CREATE TABLE trip_relation (
    `whId` BIGINT,
    id STRING,
    `sessionId` STRING,
    xdock STRING,
    `parentTripId` STRING,
    `childTripId` STRING,
    `is_deleted` BOOLEAN,
    `createdAt` TIMESTAMP(3),
    proc_time AS PROCTIME(),
    WATERMARK FOR `createdAt` AS `createdAt` - INTERVAL '5' SECOND
) WITH (
    'connector' = 'kafka',
    'topic' = 'sbx_uat.wms.public.trip_relation',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.group.id' = 'wms-pick-drop-joined',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.auto.offset.reset' = 'earliest',
    'format' = 'avro-confluent',
    'avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
-- Sink Table - sbx_uat.wms.public.pick_drop_joined
CREATE TABLE pick_drop_joined (
    wh_id BIGINT,
    principal_id BIGINT,
    pick_item_id STRING,
    drop_item_id STRING,
    picked_bin STRING,
    picked_sku STRING,
    picked_batch STRING,
    picked_uom STRING,
    overall_qty INT,
    qty INT,
    hu_code STRING,
    destination_bin_code STRING,
    pick_item_created_at TIMESTAMP(3),
    picked_qty INT,
    picked_at TIMESTAMP(3),
    picked_by STRING,
    moved_at TIMESTAMP(3),
    processed_at TIMESTAMP(3),
    picked_hu_eq_uom STRING,
    picked_has_inner_hus BOOLEAN,
    picked_inner_hu_eq_uom STRING,
    picked_bin_assigned_at TIMESTAMP(3),
    scan_source_hu_kind STRING,
    pick_source_hu_kind STRING,
    carrier_hu_kind STRING,
    scanned_source_hu_code STRING,
    picked_source_hu_code STRING,
    carrier_hu_code STRING,
    hu_kind STRING,
    source_hu_eq_uom STRING,
    pick_item_updated_at TIMESTAMP(3),
    eligible_drop_locations STRING,
    parent_item_id STRING,
    old_batch STRING,
    dest_bucket STRING,
    original_source_bin_code STRING,
    lm_trip_id STRING,
    picked_inner_hu_code STRING,
    picked_inner_hu_kind_code STRING,
    picked_quant_bucket STRING,
    pick_auto_complete BOOLEAN,
    pick_hu BOOLEAN,
    short_allocation_reason STRING,
    drop_item_previous_task_id STRING,
    dropped_sku STRING,
    dropped_batch STRING,
    dropped_uom STRING,
    drop_bucket STRING,
    picked_hu_code STRING,
    dropped_bin_code STRING,
    dropped_qty INT,
    dropped_at TIMESTAMP(3),
    drop_item_updated_at TIMESTAMP(3),
    drop_hu_in_bin BOOLEAN,
    scan_dest_hu BOOLEAN,
    allow_hu_break BOOLEAN,
    dropped_has_inner_hus BOOLEAN,
    scan_inner_hus BOOLEAN,
    dropped_hu_eq_uom STRING,
    dest_hu_code STRING,
    dropped_inner_hu_id STRING,
    dropped_inner_hu_eq_uom STRING,
    dest_bin_assigned_at TIMESTAMP(3),
    drop_uom STRING,
    drop_parent_item_id STRING,
    hu_broken BOOLEAN,
    drop_original_source_bin_code STRING,
    processed_for_loading_at TIMESTAMP(3),
    drop_quant_bucket STRING,
    drop_inner_hu_code STRING,
    dropped_inner_hu_kind_code STRING,
    drop_inner_hu BOOLEAN,
    allow_inner_hu_break BOOLEAN,
    inner_hu_broken BOOLEAN,
    drop_auto_complete BOOLEAN,
    quant_slotting_for_hus BOOLEAN,
    processed_on_drop_at TIMESTAMP(3),
    allow_hu_break_v2 BOOLEAN,
    task_kind STRING,
    task_code STRING,
    task_sequence INT,
    task_state STRING,
    task_attrs STRING,
    task_progress STRING,
    task_created_at TIMESTAMP(3),
    task_updated_at TIMESTAMP(3),
    allow_force_complete BOOLEAN,
    wave INT,
    force_completed BOOLEAN,
    task_subkind STRING,
    `label` STRING,
    session_kind STRING,
    session_code STRING,
    session_attrs STRING,
    session_created_at TIMESTAMP(3),
    session_updated_at TIMESTAMP(3),
    active BOOLEAN,
    session_state STRING,
    session_progress STRING,
    session_auto_complete BOOLEAN,
    lm_trip_code STRING,
    lm_trip_priority INT,
    lm_dockdoor STRING,
    lm_vehicle_no STRING,
    lm_vehicle_type STRING,
    lm_delivery_date DATE,
    xdock STRING,
    mm_trip_code STRING,
    mm_trip_priority INT,
    mm_dockdoor STRING,
    mm_vehicle_no STRING,
    mm_vehicle_type STRING,
    mm_delivery_date DATE,
    -- Additional Pick Items columns
    bin_id STRING,
    bin_hu_id STRING,
    destination_bin_id STRING,
    destination_bin_hu_id STRING,
    pick_deactivated_at TIMESTAMP(3),
    pick_deactivated_by STRING,
    moved_by STRING,
    scanned_source_hu_id STRING,
    picked_source_hu_id STRING,
    carrier_hu_id STRING,
    original_source_bin_id STRING,
    inner_hu_id STRING,
    inner_hu_kind_id STRING,
    pd_previous_task_id STRING,
    input_source_bin_id STRING,
    provisional_item_id STRING,
    input_dest_hu_id STRING,
    pick_item_kind STRING,
    tp_assigned_at TIMESTAMP(3),
    leg_index INT,
    last_leg BOOLEAN,
    ep_assigned_at TIMESTAMP(3),
    carrier_hu_formed_id STRING,
    hu_index INT,
    pick_sequence INT,
    carrier_hu_force_closed BOOLEAN,
    input_dest_bin_id STRING,
    inner_hu_index INT,
    inner_carrier_hu_key STRING,
    inner_carrier_hu_formed_id STRING,
    inner_carrier_hu_id STRING,
    inner_carrier_hu_code STRING,
    inner_carrier_hu_kind STRING,
    induction_id STRING,
    inner_carrier_hu_force_closed BOOLEAN,
    mhe_id STRING,
    pick_attrs STRING,
    iloc STRING,
    dest_iloc STRING,
    -- Additional Drop Items columns
    source_bin_id STRING,
    source_bin_hu_id STRING,
    drop_bin_id STRING,
    drop_bin_hu_id STRING,
    drop_created_at TIMESTAMP(3),
    drop_deactivated_at TIMESTAMP(3),
    drop_deactivated_by STRING,
    dropped_by STRING,
    dest_hu_id STRING,
    source_bucket STRING,
    original_destination_bin_id STRING,
    drop_lm_trip_id STRING,
    processed_for_pick_at TIMESTAMP(3),
    drop_provisional_item_id STRING,
    drop_input_dest_hu_id STRING,
    drop_leg_index INT,
    drop_last_leg BOOLEAN,
    drop_input_dest_bin_id STRING,
    drop_induction_id STRING,
    drop_attrs STRING,
    drop_mhe_id STRING,
    drop_iloc STRING,
    source_iloc STRING,
    -- Additional Pick Drop Mapping columns
    mapping_id STRING,
    mapping_created_at TIMESTAMP(3),
    -- Additional Tasks columns
    task_exclusive BOOLEAN,
    task_active BOOLEAN,
    task_auto_complete BOOLEAN,
    force_complete_task_id STRING,
    -- Additional Trips columns (LM)
    lm_session_created_at TIMESTAMP(3),
    lm_trip_created_at TIMESTAMP(3),
    lm_bb_id STRING,
    lm_trip_type STRING,
    lm_dockdoor_id STRING,
    lm_vehicle_id STRING,
    -- Additional Trips columns (MM)
    mm_session_created_at TIMESTAMP(3),
    mm_trip_created_at TIMESTAMP(3),
    mm_bb_id STRING,
    mm_trip_type STRING,
    mm_dockdoor_id STRING,
    mm_vehicle_id STRING,
    PRIMARY KEY (pick_item_id, drop_item_id) NOT ENFORCED
) WITH (
    'connector' = 'upsert-kafka',
    'topic' = 'sbx_uat.wms.public.pick_drop_joined',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.auto.offset.reset' = 'earliest',
    'key.format' = 'avro-confluent',
    'key.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'key.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'key.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'value.format' = 'avro-confluent',
    'value.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'value.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'value.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
-- Continuously populate the summary table
INSERT INTO pick_drop_joined
SELECT pi.`whId` AS wh_id,
    CAST(NULL AS BIGINT) AS principal_id,
    pi.id AS pick_item_id,
    COALESCE(di.id, 'NO_DROP') AS drop_item_id,
    pi.`binCode` AS picked_bin,
    pi.`skuId` AS picked_sku,
    pi.batch AS picked_batch,
    pi.uom AS picked_uom,
    pi.`overallQty` AS overall_qty,
    pi.qty AS qty,
    pi.`huCode` AS hu_code,
    pi.`destinationBinCode` AS destination_bin_code,
    pi.`createdAt` AS pick_item_created_at,
    pi.`pickedQty` AS picked_qty,
    pi.`pickedAt` AS picked_at,
    pi.`pickedBy` AS picked_by,
    pi.`movedAt` AS moved_at,
    pi.`processedAt` AS processed_at,
    pi.`huEqUOM` AS picked_hu_eq_uom,
    pi.`hasInnerHUs` AS picked_has_inner_hus,
    pi.`innerHUEqUOM` AS picked_inner_hu_eq_uom,
    pi.`binAssignedAt` AS picked_bin_assigned_at,
    pi.`scanSourceHUKind` AS scan_source_hu_kind,
    pi.`pickSourceHUKind` AS pick_source_hu_kind,
    pi.`carrierHUKind` AS carrier_hu_kind,
    pi.`scannedSourceHUCode` AS scanned_source_hu_code,
    pi.`pickedSourceHUCode` AS picked_source_hu_code,
    pi.`carrierHUCode` AS carrier_hu_code,
    pi.`huKind` AS hu_kind,
    pi.`sourceHUEqUOM` AS source_hu_eq_uom,
    CAST(pi.`updatedAt` AS TIMESTAMP) AS pick_item_updated_at,
    pi.`eligibleDropLocations` AS eligible_drop_locations,
    pi.`parentItemId` AS parent_item_id,
    pi.`oldBatch` AS old_batch,
    pi.`destBucket` AS dest_bucket,
    pi.`originalSourceBinCode` AS original_source_bin_code,
    pi.`lmTripId` AS lm_trip_id,
    pi.`innerHUCode` AS picked_inner_hu_code,
    pi.`innerHUKindCode` AS picked_inner_hu_kind_code,
    pi.`quantBucket` AS picked_quant_bucket,
    pi.`autoCompleted` AS pick_auto_complete,
    pi.`pickHU` AS pick_hu,
    pi.`shortAllocationReason` AS short_allocation_reason,
    pi.`pdPreviousTaskId` AS drop_item_previous_task_id,
    di.`skuId` AS dropped_sku,
    di.batch AS dropped_batch,
    di.uom AS dropped_uom,
    di.bucket AS drop_bucket,
    pi.`huCode` AS picked_hu_code,
    di.`binCode` AS dropped_bin_code,
    COALESCE(di.`droppedQty`, 0) AS dropped_qty,
    di.`droppedAt` AS dropped_at,
    CAST(di.`updatedAt` AS TIMESTAMP) AS drop_item_updated_at,
    di.`dropHUInBin` AS drop_hu_in_bin,
    di.`scanDestHU` AS scan_dest_hu,
    di.`allowHUBreak` AS allow_hu_break,
    di.`hasInnerHUs` AS dropped_has_inner_hus,
    di.`scanInnerHUs` AS scan_inner_hus,
    di.`huEqUOM` AS dropped_hu_eq_uom,
    di.`destHUCode` AS dest_hu_code,
    di.`droppedInnerHUId` AS dropped_inner_hu_id,
    di.`innerHUEqUOM` AS dropped_inner_hu_eq_uom,
    di.`binAssignedAt` AS dest_bin_assigned_at,
    di.`dropUOM` AS drop_uom,
    di.`parentItemId` AS drop_parent_item_id,
    di.`huBroken` AS hu_broken,
    di.`originalDestinationBinCode` AS drop_original_source_bin_code,
    di.`processedForLoadingAt` AS processed_for_loading_at,
    di.`quantBucket` AS drop_quant_bucket,
    di.`innerHUCode` AS drop_inner_hu_code,
    di.`innerHUKindCode` AS dropped_inner_hu_kind_code,
    di.`dropInnerHU` AS drop_inner_hu,
    di.`allowInnerHUBreak` AS allow_inner_hu_break,
    di.`innerHUBroken` AS inner_hu_broken,
    di.`autoCompleted` AS drop_auto_complete,
    di.`quantSlottingForHUs` AS quant_slotting_for_hus,
    di.`processedOnDropAt` AS processed_on_drop_at,
    di.`allowHUBreakV2` AS allow_hu_break_v2,
    t.kind AS task_kind,
    t.code AS task_code,
    COALESCE(t.seq, 0) AS task_sequence,
    t.state AS task_state,
    t.attrs AS task_attrs,
    t.progress AS task_progress,
    t.`createdAt` AS task_created_at,
    CAST(t.`updatedAt` AS TIMESTAMP) AS task_updated_at,
    t.`allowForceComplete` AS allow_force_complete,
    COALESCE(t.wave, 0) AS wave,
    t.`forceCompleted` AS force_completed,
    t.`subKind` AS task_subkind,
    t.label,
    s.kind AS session_kind,
    s.code AS session_code,
    s.attrs AS session_attrs,
    s.`createdAt` AS session_created_at,
    CAST(s.`updatedAt` AS TIMESTAMP) AS session_updated_at,
    s.active,
    s.state AS session_state,
    s.progress AS session_progress,
    s.`autoComplete` AS session_auto_complete,
    lm_trip.code AS lm_trip_code,
    COALESCE(lm_trip.priority, 0) AS lm_trip_priority,
    lm_trip.`dockdoorCode` AS lm_dockdoor,
    lm_trip.`vehicleNo` AS lm_vehicle_no,
    lm_trip.`vehicleType` AS lm_vehicle_type,
    lm_trip.`deliveryDate` AS lm_delivery_date,
    tmap.xdock AS xdock,
    mm_trip.code AS mm_trip_code,
    COALESCE(mm_trip.priority, 0) AS mm_trip_priority,
    mm_trip.`dockdoorCode` AS mm_dockdoor,
    mm_trip.`vehicleNo` AS mm_vehicle_no,
    mm_trip.`vehicleType` AS mm_vehicle_type,
    mm_trip.`deliveryDate` AS mm_delivery_date,
    -- Additional Pick Items columns
    pi.`binId` AS bin_id,
    pi.`binHUId` AS bin_hu_id,
    pi.`destinationBinId` AS destination_bin_id,
    pi.`destinationBinHUId` AS destination_bin_hu_id,
    pi.`deactivatedAt` AS pick_deactivated_at,
    pi.`deactivatedBy` AS pick_deactivated_by,
    pi.`movedBy` AS moved_by,
    pi.`scannedSourceHUId` AS scanned_source_hu_id,
    pi.`pickedSourceHUId` AS picked_source_hu_id,
    pi.`carrierHUId` AS carrier_hu_id,
    pi.`originalSourceBinId` AS original_source_bin_id,
    pi.`innerHUId` AS inner_hu_id,
    pi.`innerHUKindId` AS inner_hu_kind_id,
    pi.`pdPreviousTaskId` AS pd_previous_task_id,
    pi.`inputSourceBinId` AS input_source_bin_id,
    pi.`provisionalItemId` AS provisional_item_id,
    pi.`inputDestHUId` AS input_dest_hu_id,
    pi.kind AS pick_item_kind,
    pi.`tpAssignedAt` AS tp_assigned_at,
    pi.`legIndex` AS leg_index,
    pi.`lastLeg` AS last_leg,
    pi.`epAssignedAt` AS ep_assigned_at,
    pi.`carrierHUFormedId` AS carrier_hu_formed_id,
    COALESCE(pi.`huIndex`, 0) AS hu_index,
    COALESCE(pi.sequence, 0) AS pick_sequence,
    pi.`carrierHUForceClosed` AS carrier_hu_force_closed,
    pi.`inputDestBinId` AS input_dest_bin_id,
    COALESCE(pi.`innerHUIndex`, 0) AS inner_hu_index,
    pi.`innerCarrierHUKey` AS inner_carrier_hu_key,
    pi.`innerCarrierHUFormedId` AS inner_carrier_hu_formed_id,
    pi.`innerCarrierHUId` AS inner_carrier_hu_id,
    pi.`innerCarrierHUCode` AS inner_carrier_hu_code,
    pi.`innerCarrierHUKind` AS inner_carrier_hu_kind,
    pi.`inductionId` AS induction_id,
    pi.`innerCarrierHUForceClosed` AS inner_carrier_hu_force_closed,
    pi.`mheId` AS mhe_id,
    pi.attrs AS pick_attrs,
    pi.iloc AS iloc,
    pi.`destIloc` AS dest_iloc,
    -- Additional Drop Items columns
    di.`sourceBinId` AS source_bin_id,
    di.`sourceBinHUId` AS source_bin_hu_id,
    di.`binId` AS drop_bin_id,
    di.`binHUId` AS drop_bin_hu_id,
    di.`createdAt` AS drop_created_at,
    di.`deactivatedAt` AS drop_deactivated_at,
    di.`deactivatedBy` AS drop_deactivated_by,
    di.`droppedBy` AS dropped_by,
    di.`destHUId` AS dest_hu_id,
    di.`sourceBucket` AS source_bucket,
    di.`originalDestinationBinId` AS original_destination_bin_id,
    di.`lmTripId` AS drop_lm_trip_id,
    di.`processedForPickAt` AS processed_for_pick_at,
    di.`provisionalItemId` AS drop_provisional_item_id,
    di.`inputDestHUId` AS drop_input_dest_hu_id,
    COALESCE(di.`legIndex`, 0) AS drop_leg_index,
    di.`lastLeg` AS drop_last_leg,
    di.`inputDestBinId` AS drop_input_dest_bin_id,
    di.`inductionId` AS drop_induction_id,
    di.attrs AS drop_attrs,
    di.`mheId` AS drop_mhe_id,
    di.iloc AS drop_iloc,
    di.`sourceIloc` AS source_iloc,
    -- Additional Pick Drop Mapping columns
    pdm.id AS mapping_id,
    CAST(pdm.`createdAt` AS TIMESTAMP) AS mapping_created_at,
    -- Additional Tasks columns
    t.exclusive AS task_exclusive,
    t.active AS task_active,
    t.`autoComplete` AS task_auto_complete,
    t.`forceCompleteTaskId` AS force_complete_task_id,
    -- Additional Trips columns (LM)
    lm_trip.`sessionCreatedAt` AS lm_session_created_at,
    CAST(lm_trip.`createdAt` AS TIMESTAMP) AS lm_trip_created_at,
    lm_trip.`bbId` AS lm_bb_id,
    lm_trip.`type` AS lm_trip_type,
    lm_trip.`dockdoorId` AS lm_dockdoor_id,
    lm_trip.`vehicleId` AS lm_vehicle_id,
    -- Additional Trips columns (MM)
    mm_trip.`sessionCreatedAt` AS mm_session_created_at,
    CAST(mm_trip.`createdAt` AS TIMESTAMP) AS mm_trip_created_at,
    mm_trip.`bbId` AS mm_bb_id,
    mm_trip.`type` AS mm_trip_type,
    mm_trip.`dockdoorId` AS mm_dockdoor_id,
    mm_trip.`vehicleId` AS mm_vehicle_id
FROM pick_items pi
    LEFT JOIN `sessions` s ON pi.`sessionId` = s.id
    AND s.`updatedAt` BETWEEN pi.`updatedAt` - INTERVAL '48' HOUR
    AND pi.`updatedAt` + INTERVAL '48' HOUR
    LEFT JOIN tasks t ON pi.`taskId` = t.id
    AND t.`updatedAt` BETWEEN pi.`updatedAt` - INTERVAL '48' HOUR
    AND pi.`updatedAt` + INTERVAL '48' HOUR
    LEFT JOIN pick_drop_mapping pdm ON pi.id = pdm.`pickItemId`
    AND pdm.`createdAt` BETWEEN pi.`updatedAt` - INTERVAL '12' HOUR
    AND pi.`updatedAt` + INTERVAL '12' HOUR
    LEFT JOIN drop_items di ON pdm.`dropItemId` = di.id
    AND di.`updatedAt` BETWEEN pi.`updatedAt` - INTERVAL '12' HOUR
    AND pi.`updatedAt` + INTERVAL '12' HOUR
    LEFT JOIN trips lm_trip ON pi.`lmTripId` = lm_trip.id
    AND lm_trip.`createdAt` BETWEEN pi.`updatedAt` - INTERVAL '48' HOUR
    AND pi.`updatedAt` + INTERVAL '48' HOUR
    LEFT JOIN trip_relation tmap ON lm_trip.id = tmap.`childTripId`
    AND tmap.`createdAt` BETWEEN pi.`updatedAt` - INTERVAL '48' HOUR
    AND pi.`updatedAt` + INTERVAL '48' HOUR
    LEFT JOIN trips mm_trip ON tmap.`parentTripId` = mm_trip.id
    AND mm_trip.`createdAt` BETWEEN pi.`updatedAt` - INTERVAL '48' HOUR
    AND pi.`updatedAt` + INTERVAL '48' HOUR;