SET 'pipeline.name' = 'WMS Pick Drop Basic Processing';
SET 'table.exec.sink.not-null-enforcer' = 'drop';
SET 'parallelism.default' = '2';
SET 'table.optimizer.join-reorder-enabled' = 'true';
SET 'table.exec.resource.default-parallelism' = '2';
-- Performance optimizations
SET 'taskmanager.memory.managed.fraction' = '0.8';
SET 'table.exec.mini-batch.enabled' = 'true';
SET 'table.exec.mini-batch.allow-latency' = '1s';
SET 'table.exec.mini-batch.size' = '5000';
SET 'execution.checkpointing.interval' = '600000';
SET 'execution.checkpointing.timeout' = '1800000';
SET 'state.backend.incremental' = 'true';
SET 'state.backend.rocksdb.compression.type' = 'LZ4';
SET 'pipeline.operator-chaining' = 'true';
SET 'table.optimizer.multiple-input-enabled' = 'true';
-- Source Table 1: Pick Items
CREATE TABLE pick_items (
    id STRING,
    `whId` BIGINT,
    `sessionId` STRING,
    `taskId` STRING,
    `binId` STRING,
    `binHUId` STRING,
    `binCode` STRING,
    `skuId` STRING,
    batch STRING,
    uom STRING,
    bucket STRING,
    `overallQty` INT,
    qty INT,
    `huId` STRING,
    `huCode` STRING,
    `destinationBinId` STRING,
    `destinationBinHUId` STRING,
    `destinationBinCode` STRING,
    `createdAt` STRING,
    `deactivatedAt` STRING,
    `deactivatedBy` STRING,
    `pickedQty` INT,
    `pickedAt` STRING,
    `pickedBy` STRING,
    `movedAt` STRING,
    `movedBy` STRING,
    `processedAt` STRING,
    `huEqUOM` STRING,
    `hasInnerHUs` BOOLEAN,
    `innerHUEqUOM` STRING,
    `binAssignedAt` STRING,
    `scanSourceHUKind` STRING,
    `pickSourceHUKind` STRING,
    `carrierHUKind` STRING,
    `scannedSourceHUId` STRING,
    `scannedSourceHUCode` STRING,
    `pickedSourceHUId` STRING,
    `pickedSourceHUCode` STRING,
    `carrierHUId` STRING,
    `carrierHUCode` STRING,
    `huKind` STRING,
    `sourceHUEqUOM` STRING,
    `updatedAt` STRING,
    `eligibleDropLocations` STRING,
    `parentItemId` STRING,
    `oldBatch` STRING,
    `destBucket` STRING,
    `originalSourceBinId` STRING,
    `originalSourceBinCode` STRING,
    `lmTripId` STRING,
    `innerHUId` STRING,
    `innerHUCode` STRING,
    `innerHUKindId` STRING,
    `innerHUKindCode` STRING,
    `quantBucket` STRING,
    `autoCompleted` BOOLEAN,
    `pickHU` BOOLEAN,
    `shortAllocationReason` STRING,
    `pdPreviousTaskId` STRING,
    `inputSourceBinId` STRING,
    `provisionalItemId` STRING,
    `inputDestHUId` STRING,
    kind STRING,
    `tpAssignedAt` STRING,
    `legIndex` INT,
    `lastLeg` BOOLEAN,
    `epAssignedAt` STRING,
    `carrierHUFormedId` STRING,
    `huIndex` INT,
    sequence INT,
    `carrierHUForceClosed` BOOLEAN,
    `inputDestBinId` STRING,
    `innerHUIndex` INT,
    `innerCarrierHUKey` STRING,
    `innerCarrierHUFormedId` STRING,
    `innerCarrierHUId` STRING,
    `innerCarrierHUCode` STRING,
    `innerCarrierHUKind` STRING,
    `inductionId` STRING,
    `innerCarrierHUForceClosed` BOOLEAN,
    `mheId` STRING,
    attrs STRING,
    iloc STRING,
    `destIloc` STRING,
    `__source_ts_ms` BIGINT,
    `event_time` AS COALESCE(
        TO_TIMESTAMP_LTZ(`__source_ts_ms`, 3),
        TIMESTAMP '1970-01-01 00:00:00'
    ),
    WATERMARK FOR `event_time` AS `event_time` - INTERVAL '5' SECOND
) WITH (
    'connector' = 'kafka',
    'topic' = 'sbx_uat.wms.public.pd_pick_item',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.group.id' = 'sbx-uat-wms-pick-drop-basic',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'format' = 'avro-confluent',
    'avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'properties.auto.offset.reset' = 'earliest'
);
-- Source Table 2: Drop Items
CREATE TABLE drop_items (
    id STRING,
    `whId` BIGINT,
    `sessionId` STRING,
    `taskId` STRING,
    `sourceBinId` STRING,
    `sourceBinHUId` STRING,
    `sourceBinCode` STRING,
    `skuId` STRING,
    batch STRING,
    uom STRING,
    bucket STRING,
    qty INT,
    `huId` STRING,
    `huCode` STRING,
    `binId` STRING,
    `binHUId` STRING,
    `binCode` STRING,
    `createdAt` STRING,
    `deactivatedAt` STRING,
    `deactivatedBy` STRING,
    `droppedQty` INT,
    `droppedAt` STRING,
    `droppedBy` STRING,
    `updatedAt` STRING,
    `dropHUInBin` BOOLEAN,
    `scanDestHU` BOOLEAN,
    `allowHUBreak` BOOLEAN,
    `hasInnerHUs` BOOLEAN,
    `scanInnerHUs` BOOLEAN,
    `huEqUOM` STRING,
    `destHUId` STRING,
    `destHUCode` STRING,
    `droppedInnerHUId` STRING,
    `innerHUEqUOM` STRING,
    `binAssignedAt` STRING,
    `dropUOM` STRING,
    `eligibleDropLocations` STRING,
    `parentItemId` STRING,
    `huBroken` BOOLEAN,
    `pickedBy` STRING,
    `sourceBucket` STRING,
    `originalDestinationBinId` STRING,
    `originalDestinationBinCode` STRING,
    `lmTripId` STRING,
    `processedForLoadingAt` STRING,
    `quantBucket` STRING,
    `innerHUId` STRING,
    `innerHUCode` STRING,
    `innerHUKindId` STRING,
    `innerHUKindCode` STRING,
    `dropInnerHU` BOOLEAN,
    `allowInnerHUBreak` BOOLEAN,
    `innerHUBroken` BOOLEAN,
    `autoCompleted` BOOLEAN,
    `processedForPickAt` STRING,
    `quantSlottingForHUs` BOOLEAN,
    `pdPreviousTaskId` STRING,
    `processedOnDropAt` STRING,
    `provisionalItemId` STRING,
    `allowHUBreakV2` BOOLEAN,
    `inputDestHUId` STRING,
    `legIndex` INT,
    `lastLeg` BOOLEAN,
    `inputDestBinId` STRING,
    `inductionId` STRING,
    attrs STRING,
    `mheId` STRING,
    iloc STRING,
    `sourceIloc` STRING,
    `__source_ts_ms` BIGINT,
    `event_time` AS COALESCE(
        TO_TIMESTAMP_LTZ(`__source_ts_ms`, 3),
        TIMESTAMP '1970-01-01 00:00:00'
    ),
    WATERMARK FOR `event_time` AS `event_time` - INTERVAL '5' SECOND
) WITH (
    'connector' = 'kafka',
    'topic' = 'sbx_uat.wms.public.pd_drop_item',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.group.id' = 'sbx-uat-wms-pick-drop-basic',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'format' = 'avro-confluent',
    'avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'properties.auto.offset.reset' = 'earliest'
);
-- Source Table 3: Pick Drop Mapping
CREATE TABLE pick_drop_mapping (
    id STRING,
    `whId` BIGINT,
    `sessionId` STRING,
    `taskId` STRING,
    `pickItemId` STRING,
    `dropItemId` STRING,
    `createdAt` STRING,
    `__source_ts_ms` BIGINT,
    `event_time` AS COALESCE(
        TO_TIMESTAMP_LTZ(`__source_ts_ms`, 3),
        TIMESTAMP '1970-01-01 00:00:00'
    ),
    WATERMARK FOR `event_time` AS `event_time` - INTERVAL '5' SECOND
) WITH (
    'connector' = 'kafka',
    'topic' = 'sbx_uat.wms.public.pd_pick_drop_mapping',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.group.id' = 'sbx-uat-wms-pick-drop-basic',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'format' = 'avro-confluent',
    'avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'properties.auto.offset.reset' = 'earliest'
);
-- Intermediate sink table for basic pick-drop data
CREATE TABLE pick_drop_basic (
    pick_item_id STRING,
    drop_item_id STRING,
    wh_id BIGINT,
    session_id STRING,
    task_id STRING,
    lm_trip_id STRING,
    -- Pick item fields
    picked_bin STRING,
    picked_sku_id STRING,
    picked_batch STRING,
    picked_uom STRING,
    overall_qty INT,
    qty INT,
    hu_code STRING,
    destination_bin_code STRING,
    pick_item_created_at STRING,
    picked_qty INT,
    picked_at STRING,
    picked_by_worker_id STRING,
    moved_at STRING,
    processed_at STRING,
    picked_hu_eq_uom STRING,
    picked_has_inner_hus BOOLEAN,
    picked_inner_hu_eq_uom STRING,
    picked_bin_assigned_at STRING,
    scan_source_hu_kind STRING,
    pick_source_hu_kind STRING,
    carrier_hu_kind STRING,
    scanned_source_hu_code STRING,
    picked_source_hu_code STRING,
    carrier_hu_code STRING,
    hu_kind STRING,
    source_hu_eq_uom STRING,
    pick_item_updated_at STRING,
    eligible_drop_locations STRING,
    parent_item_id STRING,
    old_batch STRING,
    dest_bucket STRING,
    original_source_bin_code STRING,
    picked_inner_hu_code STRING,
    picked_inner_hu_kind_code STRING,
    picked_quant_bucket STRING,
    pick_auto_complete BOOLEAN,
    pick_hu BOOLEAN,
    short_allocation_reason STRING,
    -- Drop item fields
    dropped_sku_id STRING,
    dropped_batch STRING,
    dropped_uom STRING,
    drop_bucket STRING,
    picked_hu_code STRING,
    dropped_bin_code STRING,
    dropped_qty INT,
    dropped_at STRING,
    drop_item_updated_at STRING,
    drop_hu_in_bin BOOLEAN,
    scan_dest_hu BOOLEAN,
    allow_hu_break BOOLEAN,
    dropped_has_inner_hus BOOLEAN,
    scan_inner_hus BOOLEAN,
    dropped_hu_eq_uom STRING,
    dest_hu_code STRING,
    dropped_inner_hu_id STRING,
    dropped_inner_hu_eq_uom STRING,
    dest_bin_assigned_at STRING,
    drop_uom STRING,
    drop_parent_item_id STRING,
    hu_broken BOOLEAN,
    drop_original_source_bin_code STRING,
    processed_for_loading_at STRING,
    drop_quant_bucket STRING,
    drop_inner_hu_code STRING,
    dropped_inner_hu_kind_code STRING,
    drop_inner_hu BOOLEAN,
    allow_inner_hu_break BOOLEAN,
    inner_hu_broken BOOLEAN,
    drop_auto_complete BOOLEAN,
    quant_slotting_for_hus BOOLEAN,
    processed_on_drop_at STRING,
    allow_hu_break_v2 BOOLEAN,
    -- Mapping fields
    mapping_id STRING,
    mapping_created_at STRING,
    -- Additional fields for enrichment pipeline
    bin_id STRING,
    bin_hu_id STRING,
    destination_bin_id STRING,
    destination_bin_hu_id STRING,
    pick_deactivated_at STRING,
    pick_deactivated_by STRING,
    moved_by STRING,
    scanned_source_hu_id STRING,
    picked_source_hu_id STRING,
    carrier_hu_id STRING,
    original_source_bin_id STRING,
    inner_hu_id STRING,
    inner_hu_kind_id STRING,
    pd_previous_task_id STRING,
    input_source_bin_id STRING,
    provisional_item_id STRING,
    input_dest_hu_id STRING,
    pick_item_kind STRING,
    tp_assigned_at STRING,
    leg_index INT,
    last_leg BOOLEAN,
    ep_assigned_at STRING,
    carrier_hu_formed_id STRING,
    hu_index INT,
    pick_sequence INT,
    carrier_hu_force_closed BOOLEAN,
    input_dest_bin_id STRING,
    inner_hu_index INT,
    inner_carrier_hu_key STRING,
    inner_carrier_hu_formed_id STRING,
    inner_carrier_hu_id STRING,
    inner_carrier_hu_code STRING,
    inner_carrier_hu_kind STRING,
    induction_id STRING,
    inner_carrier_hu_force_closed BOOLEAN,
    mhe_id STRING,
    pick_attrs STRING,
    iloc STRING,
    dest_iloc STRING,
    source_bin_id STRING,
    source_bin_hu_id STRING,
    drop_bin_id STRING,
    drop_bin_hu_id STRING,
    drop_created_at STRING,
    drop_deactivated_at STRING,
    drop_deactivated_by STRING,
    dropped_by_worker_id STRING,
    dest_hu_id STRING,
    source_bucket STRING,
    original_destination_bin_id STRING,
    drop_lm_trip_id STRING,
    processed_for_pick_at STRING,
    drop_provisional_item_id STRING,
    drop_input_dest_hu_id STRING,
    drop_leg_index INT,
    drop_last_leg BOOLEAN,
    drop_input_dest_bin_id STRING,
    drop_induction_id STRING,
    drop_attrs STRING,
    drop_mhe_id STRING,
    drop_iloc STRING,
    source_iloc STRING,
    event_time TIMESTAMP(3) NOT NULL,
    WATERMARK FOR event_time AS event_time - INTERVAL '5' SECOND,
    PRIMARY KEY (pick_item_id, drop_item_id) NOT ENFORCED
) WITH (
    'connector' = 'upsert-kafka',
    'topic' = 'sbx_uat.wms.internal.pick_drop_basic',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.auto.offset.reset' = 'earliest',
    'sink.buffer-flush.max-rows' = '2000',
    'sink.buffer-flush.interval' = '5s',
    'sink.parallelism' = '2',
    'key.format' = 'avro-confluent',
    'key.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'key.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'key.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'value.format' = 'avro-confluent',
    'value.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'value.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'value.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
-- Basic pick-drop processing with 4-hour time windows
INSERT INTO pick_drop_basic
SELECT
    /*+ USE_HASH_JOIN */
    pi.id AS pick_item_id,
    COALESCE(pdm.`dropItemId`, 'NO_DROP') AS drop_item_id,
    pi.`whId` AS wh_id,
    pi.`sessionId` AS session_id,
    pi.`taskId` AS task_id,
    pi.`lmTripId` AS lm_trip_id,
    -- Pick item fields
    pi.`binCode` AS picked_bin,
    pi.`skuId` AS picked_sku_id,
    pi.batch AS picked_batch,
    pi.uom AS picked_uom,
    pi.`overallQty` AS overall_qty,
    pi.qty AS qty,
    pi.`huCode` AS hu_code,
    pi.`destinationBinCode` AS destination_bin_code,
    pi.`createdAt` AS pick_item_created_at,
    pi.`pickedQty` AS picked_qty,
    pi.`pickedAt` AS picked_at,
    pi.`pickedBy` AS picked_by_worker_id,
    pi.`movedAt` AS moved_at,
    pi.`processedAt` AS processed_at,
    pi.`huEqUOM` AS picked_hu_eq_uom,
    pi.`hasInnerHUs` AS picked_has_inner_hus,
    pi.`innerHUEqUOM` AS picked_inner_hu_eq_uom,
    pi.`binAssignedAt` AS picked_bin_assigned_at,
    pi.`scanSourceHUKind` AS scan_source_hu_kind,
    pi.`pickSourceHUKind` AS pick_source_hu_kind,
    pi.`carrierHUKind` AS carrier_hu_kind,
    pi.`scannedSourceHUCode` AS scanned_source_hu_code,
    pi.`pickedSourceHUCode` AS picked_source_hu_code,
    pi.`carrierHUCode` AS carrier_hu_code,
    pi.`huKind` AS hu_kind,
    pi.`sourceHUEqUOM` AS source_hu_eq_uom,
    pi.`updatedAt` AS pick_item_updated_at,
    pi.`eligibleDropLocations` AS eligible_drop_locations,
    pi.`parentItemId` AS parent_item_id,
    pi.`oldBatch` AS old_batch,
    pi.`destBucket` AS dest_bucket,
    pi.`originalSourceBinCode` AS original_source_bin_code,
    pi.`innerHUCode` AS picked_inner_hu_code,
    pi.`innerHUKindCode` AS picked_inner_hu_kind_code,
    pi.`quantBucket` AS picked_quant_bucket,
    pi.`autoCompleted` AS pick_auto_complete,
    pi.`pickHU` AS pick_hu,
    pi.`shortAllocationReason` AS short_allocation_reason,
    -- Drop item fields
    COALESCE(di.`skuId`, '') AS dropped_sku_id,
    COALESCE(di.batch, '') AS dropped_batch,
    COALESCE(di.uom, '') AS dropped_uom,
    COALESCE(di.bucket, '') AS drop_bucket,
    pi.`huCode` AS picked_hu_code,
    COALESCE(di.`binCode`, '') AS dropped_bin_code,
    COALESCE(di.`droppedQty`, 0) AS dropped_qty,
    di.`droppedAt` AS dropped_at,
    di.`updatedAt` AS drop_item_updated_at,
    di.`dropHUInBin` AS drop_hu_in_bin,
    di.`scanDestHU` AS scan_dest_hu,
    di.`allowHUBreak` AS allow_hu_break,
    di.`hasInnerHUs` AS dropped_has_inner_hus,
    di.`scanInnerHUs` AS scan_inner_hus,
    di.`huEqUOM` AS dropped_hu_eq_uom,
    di.`destHUCode` AS dest_hu_code,
    di.`droppedInnerHUId` AS dropped_inner_hu_id,
    di.`innerHUEqUOM` AS dropped_inner_hu_eq_uom,
    di.`binAssignedAt` AS dest_bin_assigned_at,
    di.`dropUOM` AS drop_uom,
    di.`parentItemId` AS drop_parent_item_id,
    di.`huBroken` AS hu_broken,
    di.`originalDestinationBinCode` AS drop_original_source_bin_code,
    di.`processedForLoadingAt` AS processed_for_loading_at,
    di.`quantBucket` AS drop_quant_bucket,
    di.`innerHUCode` AS drop_inner_hu_code,
    di.`innerHUKindCode` AS dropped_inner_hu_kind_code,
    di.`dropInnerHU` AS drop_inner_hu,
    di.`allowInnerHUBreak` AS allow_inner_hu_break,
    di.`innerHUBroken` AS inner_hu_broken,
    di.`autoCompleted` AS drop_auto_complete,
    di.`quantSlottingForHUs` AS quant_slotting_for_hus,
    di.`processedOnDropAt` AS processed_on_drop_at,
    di.`allowHUBreakV2` AS allow_hu_break_v2,
    -- Mapping fields
    COALESCE(pdm.id, '') AS mapping_id,
    pdm.`createdAt` AS mapping_created_at,
    -- Additional pick item fields
    pi.`binId` AS bin_id,
    pi.`binHUId` AS bin_hu_id,
    pi.`destinationBinId` AS destination_bin_id,
    pi.`destinationBinHUId` AS destination_bin_hu_id,
    pi.`deactivatedAt` AS pick_deactivated_at,
    pi.`deactivatedBy` AS pick_deactivated_by,
    pi.`movedBy` AS moved_by,
    pi.`scannedSourceHUId` AS scanned_source_hu_id,
    pi.`pickedSourceHUId` AS picked_source_hu_id,
    pi.`carrierHUId` AS carrier_hu_id,
    pi.`originalSourceBinId` AS original_source_bin_id,
    pi.`innerHUId` AS inner_hu_id,
    pi.`innerHUKindId` AS inner_hu_kind_id,
    pi.`pdPreviousTaskId` AS pd_previous_task_id,
    pi.`inputSourceBinId` AS input_source_bin_id,
    pi.`provisionalItemId` AS provisional_item_id,
    pi.`inputDestHUId` AS input_dest_hu_id,
    pi.kind AS pick_item_kind,
    pi.`tpAssignedAt` AS tp_assigned_at,
    pi.`legIndex` AS leg_index,
    pi.`lastLeg` AS last_leg,
    pi.`epAssignedAt` AS ep_assigned_at,
    pi.`carrierHUFormedId` AS carrier_hu_formed_id,
    COALESCE(pi.`huIndex`, 0) AS hu_index,
    COALESCE(pi.sequence, 0) AS pick_sequence,
    pi.`carrierHUForceClosed` AS carrier_hu_force_closed,
    pi.`inputDestBinId` AS input_dest_bin_id,
    COALESCE(pi.`innerHUIndex`, 0) AS inner_hu_index,
    pi.`innerCarrierHUKey` AS inner_carrier_hu_key,
    pi.`innerCarrierHUFormedId` AS inner_carrier_hu_formed_id,
    pi.`innerCarrierHUId` AS inner_carrier_hu_id,
    pi.`innerCarrierHUCode` AS inner_carrier_hu_code,
    pi.`innerCarrierHUKind` AS inner_carrier_hu_kind,
    pi.`inductionId` AS induction_id,
    pi.`innerCarrierHUForceClosed` AS inner_carrier_hu_force_closed,
    pi.`mheId` AS mhe_id,
    pi.attrs AS pick_attrs,
    pi.iloc AS iloc,
    pi.`destIloc` AS dest_iloc,
    -- Additional drop item fields
    COALESCE(di.`sourceBinId`, '') AS source_bin_id,
    COALESCE(di.`sourceBinHUId`, '') AS source_bin_hu_id,
    COALESCE(di.`binId`, '') AS drop_bin_id,
    COALESCE(di.`binHUId`, '') AS drop_bin_hu_id,
    di.`createdAt` AS drop_created_at,
    di.`deactivatedAt` AS drop_deactivated_at,
    di.`deactivatedBy` AS drop_deactivated_by,
    di.`droppedBy` AS dropped_by_worker_id,
    di.`destHUId` AS dest_hu_id,
    COALESCE(di.`sourceBucket`, '') AS source_bucket,
    di.`originalDestinationBinId` AS original_destination_bin_id,
    di.`lmTripId` AS drop_lm_trip_id,
    di.`processedForPickAt` AS processed_for_pick_at,
    di.`provisionalItemId` AS drop_provisional_item_id,
    di.`inputDestHUId` AS drop_input_dest_hu_id,
    COALESCE(di.`legIndex`, 0) AS drop_leg_index,
    di.`lastLeg` AS drop_last_leg,
    di.`inputDestBinId` AS drop_input_dest_bin_id,
    di.`inductionId` AS drop_induction_id,
    di.attrs AS drop_attrs,
    di.`mheId` AS drop_mhe_id,
    di.iloc AS drop_iloc,
    di.`sourceIloc` AS source_iloc,
    -- Event time for watermarking (greatest of all source event times)
    GREATEST(
        COALESCE(pi.`event_time`, TIMESTAMP '1970-01-01 00:00:00'),
        COALESCE(
            pdm.`event_time`,
            TIMESTAMP '1970-01-01 00:00:00'
        ),
        COALESCE(di.`event_time`, TIMESTAMP '1970-01-01 00:00:00')
    ) AS event_time
FROM pick_items pi -- Join with pick-drop mapping (6-hour window)
    LEFT JOIN pick_drop_mapping pdm ON pi.id = pdm.`pickItemId`
    AND pi.`whId` = pdm.`whId`
    AND pdm.`event_time` BETWEEN pi.`event_time` - INTERVAL '6' HOUR
    AND pi.`event_time` + INTERVAL '6' HOUR -- Join with drop items (6-hour window)
    LEFT JOIN drop_items di ON pdm.`dropItemId` = di.id
    AND di.`event_time` BETWEEN pi.`event_time` - INTERVAL '6' HOUR
    AND pi.`event_time` + INTERVAL '6' HOUR
WHERE pi.`event_time` > TIMESTAMP '1970-01-01 00:00:00';