-- Real-time WMS Pick-Drop Enrichment Pipeline
-- 
-- Purpose: Processes new pick-drop data continuously after historical pipeline completion
-- 
-- Key Configuration:
-- 1. Uses 'kafka' connector (not upsert-kafka) for streaming semantics on source table
-- 2. Starts from latest offset since historical pipeline has already processed past data
-- 3. Uses 5-minute watermark delay to ensure dimension tables are fully loaded
-- 4. Implements watermark alignment to synchronize progress across all sources
-- 5. Maintains same consumer group 'sbx-uat-wms-pick-drop-enriched' for offset continuity
-- 6. Simplified event_time logic - no snapshot handling needed for realtime data
--
-- Watermark Strategy:
-- - 5-minute delay allows dimension tables time to catch up with late-arriving data
-- - Watermark alignment ensures all sources progress together within 5-minute drift
-- - Idle timeout of 60s handles temporarily inactive partitions
--
-- Usage: Run this AFTER the historical pipeline (wms-pick-drop-enriched-historical.sql) completes
SET 'pipeline.name' = 'WMS Pick Drop Real-time Enrichment';
SET 'execution.runtime-mode' = 'STREAMING';
SET 'table.exec.sink.not-null-enforcer' = 'drop';
SET 'parallelism.default' = '4';
SET 'table.optimizer.join-reorder-enabled' = 'false';
SET 'table.exec.legacy-cast-behaviour' = 'enabled';
SET 'table.exec.resource.default-parallelism' = '4';
-- Performance optimizations
SET 'taskmanager.memory.managed.fraction' = '0.8';
SET 'table.exec.mini-batch.enabled' = 'true';
SET 'table.exec.mini-batch.allow-latency' = '1s';
SET 'table.exec.mini-batch.size' = '5000';
SET 'execution.checkpointing.interval' = '600000';
SET 'execution.checkpointing.timeout' = '1800000';
SET 'state.backend.incremental' = 'true';
SET 'state.backend.rocksdb.compression.type' = 'LZ4';
SET 'pipeline.operator-chaining' = 'true';
SET 'table.optimizer.multiple-input-enabled' = 'true';
-- Handle idle sources and watermark alignment for proper temporal join behavior
SET 'table.exec.source.idle-timeout' = '60s';
-- Watermark alignment to ensure all sources progress together
SET 'pipeline.watermark-alignment.group' = 'pick-drop-enrichment';
SET 'pipeline.watermark-alignment.max-drift' = '5 min';
SET 'pipeline.watermark-alignment.update-interval' = '30s';
-- Source: Basic pick-drop data from Pipeline 1 (streaming mode with kafka connector)
-- Uses kafka connector for streaming semantics and proper watermark handling
CREATE TABLE pick_drop_basic (
    pick_item_id STRING,
    drop_item_id STRING,
    wh_id BIGINT,
    session_id STRING,
    task_id STRING,
    lm_trip_id STRING,
    -- Pick item fields
    picked_bin STRING,
    picked_sku_id STRING,
    picked_batch STRING,
    picked_uom STRING,
    overall_qty INT,
    qty INT,
    hu_code STRING,
    destination_bin_code STRING,
    pick_item_created_at TIMESTAMP(3),
    picked_qty INT,
    picked_at TIMESTAMP(3),
    picked_by_worker_id STRING,
    moved_at TIMESTAMP(3),
    processed_at TIMESTAMP(3),
    picked_hu_eq_uom STRING,
    picked_has_inner_hus BOOLEAN,
    picked_inner_hu_eq_uom STRING,
    picked_bin_assigned_at TIMESTAMP(3),
    scan_source_hu_kind STRING,
    pick_source_hu_kind STRING,
    carrier_hu_kind STRING,
    scanned_source_hu_code STRING,
    picked_source_hu_code STRING,
    carrier_hu_code STRING,
    hu_kind STRING,
    source_hu_eq_uom STRING,
    pick_item_updated_at TIMESTAMP(3),
    eligible_drop_locations STRING,
    parent_item_id STRING,
    old_batch STRING,
    dest_bucket STRING,
    original_source_bin_code STRING,
    picked_inner_hu_code STRING,
    picked_inner_hu_kind_code STRING,
    picked_quant_bucket STRING,
    pick_auto_complete BOOLEAN,
    pick_hu BOOLEAN,
    short_allocation_reason STRING,
    -- Drop item fields
    dropped_sku_id STRING,
    dropped_batch STRING,
    dropped_uom STRING,
    drop_bucket STRING,
    picked_hu_code STRING,
    dropped_bin_code STRING,
    dropped_qty INT,
    dropped_at TIMESTAMP(3),
    drop_item_updated_at TIMESTAMP(3),
    drop_hu_in_bin BOOLEAN,
    scan_dest_hu BOOLEAN,
    allow_hu_break BOOLEAN,
    dropped_has_inner_hus BOOLEAN,
    scan_inner_hus BOOLEAN,
    dropped_hu_eq_uom STRING,
    dest_hu_code STRING,
    dropped_inner_hu_id STRING,
    dropped_inner_hu_eq_uom STRING,
    dest_bin_assigned_at TIMESTAMP(3),
    drop_uom STRING,
    drop_parent_item_id STRING,
    hu_broken BOOLEAN,
    drop_original_source_bin_code STRING,
    processed_for_loading_at TIMESTAMP(3),
    drop_quant_bucket STRING,
    drop_inner_hu_code STRING,
    dropped_inner_hu_kind_code STRING,
    drop_inner_hu BOOLEAN,
    allow_inner_hu_break BOOLEAN,
    inner_hu_broken BOOLEAN,
    drop_auto_complete BOOLEAN,
    quant_slotting_for_hus BOOLEAN,
    processed_on_drop_at TIMESTAMP(3),
    allow_hu_break_v2 BOOLEAN,
    deactivated_at TIMESTAMP(3),
    -- Mapping fields
    mapping_id STRING,
    mapping_created_at TIMESTAMP(3),
    -- Additional fields
    bin_id STRING,
    bin_hu_id STRING,
    destination_bin_id STRING,
    destination_bin_hu_id STRING,
    pick_deactivated_at TIMESTAMP(3),
    pick_deactivated_by STRING,
    moved_by STRING,
    scanned_source_hu_id STRING,
    picked_source_hu_id STRING,
    carrier_hu_id STRING,
    original_source_bin_id STRING,
    inner_hu_id STRING,
    inner_hu_kind_id STRING,
    pd_previous_task_id STRING,
    input_source_bin_id STRING,
    provisional_item_id STRING,
    input_dest_hu_id STRING,
    pick_item_kind STRING,
    tp_assigned_at TIMESTAMP(3),
    leg_index INT,
    last_leg BOOLEAN,
    ep_assigned_at TIMESTAMP(3),
    carrier_hu_formed_id STRING,
    hu_index INT,
    pick_sequence INT,
    carrier_hu_force_closed BOOLEAN,
    input_dest_bin_id STRING,
    inner_hu_index INT,
    inner_carrier_hu_key STRING,
    inner_carrier_hu_formed_id STRING,
    inner_carrier_hu_id STRING,
    inner_carrier_hu_code STRING,
    inner_carrier_hu_kind STRING,
    induction_id STRING,
    inner_carrier_hu_force_closed BOOLEAN,
    mhe_id STRING,
    pick_attrs STRING,
    iloc STRING,
    dest_iloc STRING,
    source_bin_id STRING,
    source_bin_hu_id STRING,
    drop_bin_id STRING,
    drop_bin_hu_id STRING,
    drop_created_at TIMESTAMP(3),
    drop_deactivated_at TIMESTAMP(3),
    drop_deactivated_by STRING,
    dropped_by_worker_id STRING,
    dest_hu_id STRING,
    source_bucket STRING,
    original_destination_bin_id STRING,
    drop_lm_trip_id STRING,
    processed_for_pick_at TIMESTAMP(3),
    drop_provisional_item_id STRING,
    drop_input_dest_hu_id STRING,
    drop_leg_index INT,
    drop_last_leg BOOLEAN,
    drop_input_dest_bin_id STRING,
    drop_induction_id STRING,
    drop_attrs STRING,
    drop_mhe_id STRING,
    drop_iloc STRING,
    source_iloc STRING,
    -- Fields from the upstream pipeline
    is_snapshot BOOLEAN,
    event_time TIMESTAMP(3),
    -- Use a 5-minute watermark delay to ensure dimension tables have sufficient time to load
    -- This helps handle late-arriving dimension data and ensures proper enrichment
    WATERMARK FOR event_time AS event_time - INTERVAL '5' MINUTE
) WITH (
    'connector' = 'kafka',
    'topic' = 'sbx_uat.wms.internal.pick_drop_basic',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.group.id' = 'sbx-uat-wms-pick-drop-enriched',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    -- Start from latest offset since historical pipeline has already processed past data
    'scan.startup.mode' = 'latest-offset',
    'format' = 'avro-confluent',
    'avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
-- Dimension Table 1: Tasks
CREATE TABLE tasks (
    `whId` BIGINT,
    id STRING,
    `sessionId` STRING,
    kind STRING,
    code STRING,
    seq INT,
    exclusive BOOLEAN,
    state STRING,
    attrs STRING,
    progress STRING,
    `createdAt` TIMESTAMP(3),
    `updatedAt` TIMESTAMP(3),
    active BOOLEAN,
    `allowForceComplete` BOOLEAN,
    `autoComplete` BOOLEAN,
    wave INT,
    `forceCompleteTaskId` STRING,
    `forceCompleted` BOOLEAN,
    `subKind` STRING,
    label STRING,
    `__source_snapshot` STRING,  -- Kept for schema compatibility but not used in realtime
    is_snapshot AS FALSE,  -- Always FALSE for realtime streaming data
    event_time AS `updatedAt`,
    WATERMARK FOR event_time AS event_time - INTERVAL '5' SECOND,
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'connector' = 'upsert-kafka',
    'topic' = 'sbx_uat.wms.public.task',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'key.format' = 'avro-confluent',
    'key.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'key.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'key.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'value.format' = 'avro-confluent',
    'value.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'value.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'value.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
-- Dimension Table 2: Sessions
CREATE TABLE `sessions` (
    `whId` BIGINT,
    id STRING,
    kind STRING,
    code STRING,
    attrs STRING,
    `createdAt` TIMESTAMP(3),
    `updatedAt` TIMESTAMP(3),
    active BOOLEAN,
    state STRING,
    progress STRING,
    `autoComplete` BOOLEAN,
    `__source_snapshot` STRING,  -- Kept for schema compatibility but not used in realtime
    is_snapshot AS FALSE,  -- Always FALSE for realtime streaming data
    event_time AS `updatedAt`,
    WATERMARK FOR event_time AS event_time - INTERVAL '5' SECOND,
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'connector' = 'upsert-kafka',
    'topic' = 'sbx_uat.wms.public.session',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'key.format' = 'avro-confluent',
    'key.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'key.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'key.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'value.format' = 'avro-confluent',
    'value.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'value.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'value.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
-- Dimension Table 3: Trips
CREATE TABLE trips (
    `sessionCreatedAt` TIMESTAMP(3),
    `whId` BIGINT,
    `sessionId` STRING,
    id STRING,
    `createdAt` TIMESTAMP(3),
    `bbId` STRING,
    code STRING,
    `type` STRING,
    priority INT,
    `dockdoorId` STRING,
    `dockdoorCode` STRING,
    `vehicleId` STRING,
    `vehicleNo` STRING,
    `vehicleType` STRING,
    `deliveryDate` DATE,
    `__source_snapshot` STRING,  -- Kept for schema compatibility but not used in realtime
    is_snapshot AS FALSE,  -- Always FALSE for realtime streaming data
    event_time AS `createdAt`,
    WATERMARK FOR event_time AS event_time - INTERVAL '5' SECOND,
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'connector' = 'upsert-kafka',
    'topic' = 'sbx_uat.wms.public.trip',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'key.format' = 'avro-confluent',
    'key.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'key.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'key.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'value.format' = 'avro-confluent',
    'value.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'value.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'value.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
-- Dimension Table 4: Trip Relations (rekeyed)
CREATE TABLE trip_relation_rekeyed (
    whId BIGINT,
    id STRING,
    sessionId STRING NOT NULL,
    xdock STRING,
    parentTripId STRING,
    childTripId STRING NOT NULL,
    createdAt TIMESTAMP(3),
    -- Fields from the upstream pipeline
    is_snapshot BOOLEAN,
    event_time TIMESTAMP(3),
    WATERMARK FOR event_time AS event_time - INTERVAL '5' SECOND,
    PRIMARY KEY (sessionId, childTripId) NOT ENFORCED
) WITH (
    'connector' = 'upsert-kafka',
    'topic' = 'sbx_uat.wms.internal.trip_relation_rekeyed1',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'key.format' = 'avro-confluent',
    'key.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'key.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'key.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'value.format' = 'avro-confluent',
    'value.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'value.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'value.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
-- Dimension Table 5: Workers
CREATE TABLE workers (
    `whId` BIGINT,
    id STRING,
    code STRING,
    name STRING,
    phone STRING,
    attrs STRING,
    images STRING,
    active BOOLEAN,
    `createdAt` TIMESTAMP(3),
    `updatedAt` TIMESTAMP(3),
    supervisor BOOLEAN,
    `quantIdentifiers` STRING,
    `mheKindIds` STRING,
    `eligibleZones` STRING,
    `__source_snapshot` STRING,  -- Kept for schema compatibility but not used in realtime
    is_snapshot AS FALSE,  -- Always FALSE for realtime streaming data
    event_time AS `updatedAt`,
    WATERMARK FOR event_time AS event_time - INTERVAL '5' SECOND,
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'connector' = 'upsert-kafka',
    'topic' = 'sbx_uat.wms.public.worker',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'key.format' = 'avro-confluent',
    'key.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'key.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'key.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'value.format' = 'avro-confluent',
    'value.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'value.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'value.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
-- Dimension Table 6: Handling Units
CREATE TABLE handling_units (
    `whId` BIGINT,
    id STRING,
    code STRING,
    `kindId` STRING,
    `sessionId` STRING,
    `taskId` STRING,
    `storageId` STRING,
    `outerHuId` STRING,
    state STRING,
    attrs STRING,
    `createdAt` TIMESTAMP(3),
    `updatedAt` TIMESTAMP(3),
    `lockTaskId` STRING,
    `effectiveStorageId` STRING,
    `__source_snapshot` STRING,  -- Kept for schema compatibility but not used in realtime
    is_snapshot AS FALSE,  -- Always FALSE for realtime streaming data
    event_time AS `updatedAt`,
    WATERMARK FOR event_time AS event_time - INTERVAL '5' SECOND,
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'connector' = 'upsert-kafka',
    'topic' = 'sbx_uat.wms.public.handling_unit',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'key.format' = 'avro-confluent',
    'key.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'key.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'key.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'value.format' = 'avro-confluent',
    'value.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'value.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'value.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
-- Dimension Table 7: SKU Overrides (Encarta) - Generated from another pipeline
CREATE TABLE sku_overrides (
    sku_id STRING,
    principal_id BIGINT,
    node_id BIGINT,
    category STRING,
    product STRING,
    product_id STRING,
    category_group STRING,
    sub_brand STRING,
    brand STRING,
    code STRING,
    name STRING,
    short_description STRING,
    description STRING,
    fulfillment_type STRING,
    avg_l0_per_put INT,
    inventory_type STRING,
    shelf_life INT,
    identifier1 STRING,
    identifier2 STRING,
    tag1 STRING,
    tag2 STRING,
    tag3 STRING,
    tag4 STRING,
    tag5 STRING,
    tag6 STRING,
    tag7 STRING,
    tag8 STRING,
    tag9 STRING,
    tag10 STRING,
    handling_unit_type STRING,
    cases_per_layer INT,
    layers INT,
    active_from TIMESTAMP(3),
    active_till TIMESTAMP(3),
    l0_units INT,
    l1_units INT,
    l2_units INT,
    l2_units_final INT,
    l3_units INT,
    l3_units_final INT,
    l0_name STRING,
    l0_weight DOUBLE,
    l0_volume DOUBLE,
    l0_package_type STRING,
    l0_length DOUBLE,
    l0_width DOUBLE,
    l0_height DOUBLE,
    l0_packing_efficiency DOUBLE,
    l0_itf_code STRING,
    l0_erp_weight DOUBLE,
    l0_erp_volume DOUBLE,
    l0_erp_length DOUBLE,
    l0_erp_width DOUBLE,
    l0_erp_height DOUBLE,
    l0_text_tag1 STRING,
    l0_text_tag2 STRING,
    l0_image STRING,
    l0_num_tag1 DOUBLE,
    l1_name STRING,
    l1_weight DOUBLE,
    l1_volume DOUBLE,
    l1_package_type STRING,
    l1_length DOUBLE,
    l1_width DOUBLE,
    l1_height DOUBLE,
    l1_packing_efficiency DOUBLE,
    l1_itf_code STRING,
    l1_erp_weight DOUBLE,
    l1_erp_volume DOUBLE,
    l1_erp_length DOUBLE,
    l1_erp_width DOUBLE,
    l1_erp_height DOUBLE,
    l1_text_tag1 STRING,
    l1_text_tag2 STRING,
    l1_image STRING,
    l1_num_tag1 DOUBLE,
    l2_name STRING,
    l2_weight DOUBLE,
    l2_volume DOUBLE,
    l2_package_type STRING,
    l2_length DOUBLE,
    l2_width DOUBLE,
    l2_height DOUBLE,
    l2_packing_efficiency DOUBLE,
    l2_itf_code STRING,
    l2_erp_weight DOUBLE,
    l2_erp_volume DOUBLE,
    l2_erp_length DOUBLE,
    l2_erp_width DOUBLE,
    l2_erp_height DOUBLE,
    l2_text_tag1 STRING,
    l2_text_tag2 STRING,
    l2_image STRING,
    l2_num_tag1 DOUBLE,
    l3_name STRING,
    l3_weight DOUBLE,
    l3_volume DOUBLE,
    l3_package_type STRING,
    l3_length DOUBLE,
    l3_width DOUBLE,
    l3_height DOUBLE,
    l3_packing_efficiency DOUBLE,
    l3_itf_code STRING,
    l3_erp_weight DOUBLE,
    l3_erp_volume DOUBLE,
    l3_erp_length DOUBLE,
    l3_erp_width DOUBLE,
    l3_erp_height DOUBLE,
    l3_text_tag1 STRING,
    l3_text_tag2 STRING,
    l3_image STRING,
    l3_num_tag1 DOUBLE,
    active BOOLEAN NOT NULL,
    classifications STRING NOT NULL,
    product_classifications STRING NOT NULL,
    created_at TIMESTAMP(3) NOT NULL,
    updated_at TIMESTAMP(3) NOT NULL,
    -- Fields from the upstream pipeline
    is_snapshot BOOLEAN,
    event_time TIMESTAMP(3),
    WATERMARK FOR event_time AS event_time - INTERVAL '5' SECOND,
    PRIMARY KEY (sku_id, node_id) NOT ENFORCED
) WITH (
    'connector' = 'upsert-kafka',
    'topic' = 'sbx_uat.encarta.public.skus_overrides',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'key.format' = 'avro-confluent',
    'key.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'key.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'key.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'value.format' = 'avro-confluent',
    'value.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'value.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'value.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
-- Dimension Table 8: SKU Masters (Encarta) - Generated from another pipeline
CREATE TABLE sku_masters (
    id STRING,
    principal_id BIGINT,
    node_id BIGINT,
    category STRING,
    product STRING,
    product_id STRING,
    category_group STRING,
    sub_brand STRING,
    brand STRING,
    code STRING,
    name STRING,
    short_description STRING,
    description STRING,
    fulfillment_type STRING,
    avg_l0_per_put INT,
    inventory_type STRING,
    shelf_life INT,
    identifier1 STRING,
    identifier2 STRING,
    tag1 STRING,
    tag2 STRING,
    tag3 STRING,
    tag4 STRING,
    tag5 STRING,
    tag6 STRING,
    tag7 STRING,
    tag8 STRING,
    tag9 STRING,
    tag10 STRING,
    handling_unit_type STRING,
    cases_per_layer INT,
    layers INT,
    active_from TIMESTAMP(3),
    active_till TIMESTAMP(3),
    l0_units INT,
    l1_units INT,
    l2_units INT,
    l2_units_final INT,
    l3_units INT,
    l3_units_final INT,
    l0_name STRING,
    l0_weight DOUBLE,
    l0_volume DOUBLE,
    l0_package_type STRING,
    l0_length DOUBLE,
    l0_width DOUBLE,
    l0_height DOUBLE,
    l0_packing_efficiency DOUBLE,
    l0_itf_code STRING,
    l0_erp_weight DOUBLE,
    l0_erp_volume DOUBLE,
    l0_erp_length DOUBLE,
    l0_erp_width DOUBLE,
    l0_erp_height DOUBLE,
    l0_text_tag1 STRING,
    l0_text_tag2 STRING,
    l0_image STRING,
    l0_num_tag1 DOUBLE,
    l1_name STRING,
    l1_weight DOUBLE,
    l1_volume DOUBLE,
    l1_package_type STRING,
    l1_length DOUBLE,
    l1_width DOUBLE,
    l1_height DOUBLE,
    l1_packing_efficiency DOUBLE,
    l1_itf_code STRING,
    l1_erp_weight DOUBLE,
    l1_erp_volume DOUBLE,
    l1_erp_length DOUBLE,
    l1_erp_width DOUBLE,
    l1_erp_height DOUBLE,
    l1_text_tag1 STRING,
    l1_text_tag2 STRING,
    l1_image STRING,
    l1_num_tag1 DOUBLE,
    l2_name STRING,
    l2_weight DOUBLE,
    l2_volume DOUBLE,
    l2_package_type STRING,
    l2_length DOUBLE,
    l2_width DOUBLE,
    l2_height DOUBLE,
    l2_packing_efficiency DOUBLE,
    l2_itf_code STRING,
    l2_erp_weight DOUBLE,
    l2_erp_volume DOUBLE,
    l2_erp_length DOUBLE,
    l2_erp_width DOUBLE,
    l2_erp_height DOUBLE,
    l2_text_tag1 STRING,
    l2_text_tag2 STRING,
    l2_image STRING,
    l2_num_tag1 DOUBLE,
    l3_name STRING,
    l3_weight DOUBLE,
    l3_volume DOUBLE,
    l3_package_type STRING,
    l3_length DOUBLE,
    l3_width DOUBLE,
    l3_height DOUBLE,
    l3_packing_efficiency DOUBLE,
    l3_itf_code STRING,
    l3_erp_weight DOUBLE,
    l3_erp_volume DOUBLE,
    l3_erp_length DOUBLE,
    l3_erp_width DOUBLE,
    l3_erp_height DOUBLE,
    l3_text_tag1 STRING,
    l3_text_tag2 STRING,
    l3_image STRING,
    l3_num_tag1 DOUBLE,
    active BOOLEAN NOT NULL,
    classifications STRING NOT NULL,
    product_classifications STRING NOT NULL,
    created_at TIMESTAMP(3) NOT NULL,
    updated_at TIMESTAMP(3) NOT NULL,
    -- Fields from the upstream pipeline
    is_snapshot BOOLEAN,
    event_time TIMESTAMP(3),
    WATERMARK FOR event_time AS event_time - INTERVAL '5' SECOND,
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'connector' = 'upsert-kafka',
    'topic' = 'sbx_uat.encarta.public.skus_master',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'key.format' = 'avro-confluent',
    'key.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'key.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'key.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'value.format' = 'avro-confluent',
    'value.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'value.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'value.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
-- Final sink table - same as original
CREATE TABLE pick_drop_summary (
    wh_id BIGINT,
    principal_id BIGINT,
    pick_item_id STRING,
    drop_item_id STRING,
    picked_bin STRING,
    picked_sku_id STRING,
    picked_batch STRING,
    picked_uom STRING,
    overall_qty INT,
    qty INT,
    hu_code STRING,
    destination_bin_code STRING,
    pick_item_created_at TIMESTAMP(3),
    picked_qty INT,
    picked_at TIMESTAMP(3),
    picked_by_worker_id STRING,
    moved_at TIMESTAMP(3),
    processed_at TIMESTAMP(3),
    picked_hu_eq_uom STRING,
    picked_has_inner_hus BOOLEAN,
    picked_inner_hu_eq_uom STRING,
    picked_bin_assigned_at TIMESTAMP(3),
    scan_source_hu_kind STRING,
    pick_source_hu_kind STRING,
    carrier_hu_kind STRING,
    scanned_source_hu_code STRING,
    picked_source_hu_code STRING,
    carrier_hu_code STRING,
    hu_kind STRING,
    source_hu_eq_uom STRING,
    pick_item_updated_at TIMESTAMP(3),
    eligible_drop_locations STRING,
    parent_item_id STRING,
    old_batch STRING,
    dest_bucket STRING,
    original_source_bin_code STRING,
    lm_trip_id STRING,
    picked_inner_hu_code STRING,
    picked_inner_hu_kind_code STRING,
    picked_quant_bucket STRING,
    pick_auto_complete BOOLEAN,
    pick_hu BOOLEAN,
    short_allocation_reason STRING,
    drop_item_previous_task_id STRING,
    dropped_sku_id STRING,
    dropped_batch STRING,
    dropped_uom STRING,
    drop_bucket STRING,
    picked_hu_code STRING,
    dropped_bin_code STRING,
    dropped_qty INT,
    dropped_at TIMESTAMP(3),
    drop_item_updated_at TIMESTAMP(3),
    drop_hu_in_bin BOOLEAN,
    scan_dest_hu BOOLEAN,
    allow_hu_break BOOLEAN,
    dropped_has_inner_hus BOOLEAN,
    scan_inner_hus BOOLEAN,
    dropped_hu_eq_uom STRING,
    dest_hu_code STRING,
    dropped_inner_hu_id STRING,
    dropped_inner_hu_eq_uom STRING,
    dest_bin_assigned_at TIMESTAMP(3),
    drop_uom STRING,
    drop_parent_item_id STRING,
    hu_broken BOOLEAN,
    drop_original_source_bin_code STRING,
    processed_for_loading_at TIMESTAMP(3),
    drop_quant_bucket STRING,
    drop_inner_hu_code STRING,
    dropped_inner_hu_kind_code STRING,
    drop_inner_hu BOOLEAN,
    allow_inner_hu_break BOOLEAN,
    inner_hu_broken BOOLEAN,
    drop_auto_complete BOOLEAN,
    quant_slotting_for_hus BOOLEAN,
    processed_on_drop_at TIMESTAMP(3),
    allow_hu_break_v2 BOOLEAN,
    task_kind STRING,
    task_code STRING,
    task_sequence INT,
    task_state STRING,
    task_attrs STRING,
    task_progress STRING,
    task_created_at TIMESTAMP(3),
    task_updated_at TIMESTAMP(3),
    allow_force_complete BOOLEAN,
    wave INT,
    force_completed BOOLEAN,
    task_subkind STRING,
    `label` STRING,
    session_kind STRING,
    session_code STRING,
    session_attrs STRING,
    session_created_at TIMESTAMP(3),
    session_updated_at TIMESTAMP(3),
    active BOOLEAN,
    session_state STRING,
    session_progress STRING,
    session_auto_complete BOOLEAN,
    lm_trip_code STRING,
    lm_trip_priority INT,
    lm_dockdoor STRING,
    lm_vehicle_no STRING,
    lm_vehicle_type STRING,
    lm_delivery_date DATE,
    -- Additional Pick Items columns
    bin_id STRING,
    bin_hu_id STRING,
    destination_bin_id STRING,
    destination_bin_hu_id STRING,
    pick_deactivated_at TIMESTAMP(3),
    pick_deactivated_by STRING,
    moved_by STRING,
    scanned_source_hu_id STRING,
    picked_source_hu_id STRING,
    carrier_hu_id STRING,
    original_source_bin_id STRING,
    inner_hu_id STRING,
    inner_hu_kind_id STRING,
    pd_previous_task_id STRING,
    input_source_bin_id STRING,
    provisional_item_id STRING,
    input_dest_hu_id STRING,
    pick_item_kind STRING,
    tp_assigned_at TIMESTAMP(3),
    leg_index INT,
    last_leg BOOLEAN,
    ep_assigned_at TIMESTAMP(3),
    carrier_hu_formed_id STRING,
    hu_index INT,
    pick_sequence INT,
    carrier_hu_force_closed BOOLEAN,
    input_dest_bin_id STRING,
    inner_hu_index INT,
    inner_carrier_hu_key STRING,
    inner_carrier_hu_formed_id STRING,
    inner_carrier_hu_id STRING,
    inner_carrier_hu_code STRING,
    inner_carrier_hu_kind STRING,
    induction_id STRING,
    inner_carrier_hu_force_closed BOOLEAN,
    mhe_id STRING,
    pick_attrs STRING,
    iloc STRING,
    dest_iloc STRING,
    -- Additional Drop Items columns
    source_bin_id STRING,
    source_bin_hu_id STRING,
    drop_bin_id STRING,
    drop_bin_hu_id STRING,
    drop_created_at TIMESTAMP(3),
    drop_deactivated_at TIMESTAMP(3),
    drop_deactivated_by STRING,
    dropped_by_worker_id STRING,
    dest_hu_id STRING,
    source_bucket STRING,
    original_destination_bin_id STRING,
    drop_lm_trip_id STRING,
    processed_for_pick_at TIMESTAMP(3),
    drop_provisional_item_id STRING,
    drop_input_dest_hu_id STRING,
    drop_leg_index INT,
    drop_last_leg BOOLEAN,
    drop_input_dest_bin_id STRING,
    drop_induction_id STRING,
    drop_attrs STRING,
    drop_mhe_id STRING,
    drop_iloc STRING,
    source_iloc STRING,
    -- Additional Pick Drop Mapping columns
    mapping_id STRING,
    mapping_created_at TIMESTAMP(3),
    -- Additional Tasks columns
    task_exclusive BOOLEAN,
    task_active BOOLEAN,
    task_auto_complete BOOLEAN,
    force_complete_task_id STRING,
    -- Additional Trips columns (LM)
    lm_session_created_at TIMESTAMP(3),
    lm_trip_created_at TIMESTAMP(3),
    lm_bb_id STRING,
    lm_trip_type STRING,
    lm_dockdoor_id STRING,
    lm_vehicle_id STRING,
    -- Trip Relation enrichment fields
    trip_relation_id STRING,
    trip_relation_xdock STRING,
    trip_relation_parent_trip_id STRING,
    trip_relation_created_at TIMESTAMP(3),
    -- Parent Trip enrichment fields
    parent_trip_code STRING,
    parent_trip_type STRING,
    parent_trip_priority INT,
    parent_trip_dockdoor_code STRING,
    parent_trip_vehicle_no STRING,
    parent_trip_vehicle_type STRING,
    parent_trip_delivery_date DATE,
    parent_trip_created_at TIMESTAMP(3),
    -- Worker enrichment fields
    worker_code STRING,
    worker_name STRING,
    worker_phone STRING,
    worker_supervisor BOOLEAN,
    worker_active BOOLEAN,
    -- Handling Unit enrichment fields
    dropped_hu_code STRING,
    dropped_hu_kind_id STRING,
    dropped_hu_session_id STRING,
    dropped_hu_task_id STRING,
    dropped_hu_storage_id STRING,
    dropped_hu_outer_hu_id STRING,
    dropped_hu_state STRING,
    dropped_hu_attrs STRING,
    dropped_hu_lock_task_id STRING,
    dropped_hu_effective_storage_id STRING,
    dropped_hu_created_at TIMESTAMP(3),
    dropped_hu_updated_at TIMESTAMP(3),
    -- Picked SKU enrichment fields (comprehensive)
    picked_sku_principal_id BIGINT,
    picked_sku_node_id BIGINT,
    picked_sku_category STRING,
    picked_sku_product STRING,
    picked_sku_product_id STRING,
    picked_sku_category_group STRING,
    picked_sku_sub_brand STRING,
    picked_sku_brand STRING,
    picked_sku_code STRING,
    picked_sku_name STRING,
    picked_sku_short_description STRING,
    picked_sku_description STRING,
    picked_sku_fulfillment_type STRING,
    picked_sku_inventory_type STRING,
    picked_sku_shelf_life INT,
    picked_sku_tag1 STRING,
    picked_sku_tag2 STRING,
    picked_sku_tag3 STRING,
    picked_sku_tag4 STRING,
    picked_sku_tag5 STRING,
    picked_sku_handling_unit_type STRING,
    picked_sku_cases_per_layer INT,
    picked_sku_layers INT,
    picked_sku_l0_units INT,
    picked_sku_l1_units INT,
    picked_sku_l2_units INT,
    picked_sku_l3_units INT,
    picked_sku_l0_name STRING,
    picked_sku_l0_weight DOUBLE,
    picked_sku_l0_volume DOUBLE,
    picked_sku_l0_package_type STRING,
    picked_sku_l0_length DOUBLE,
    picked_sku_l0_width DOUBLE,
    picked_sku_l0_height DOUBLE,
    picked_sku_l0_packing_efficiency DOUBLE,
    picked_sku_l1_name STRING,
    picked_sku_l1_weight DOUBLE,
    picked_sku_l1_volume DOUBLE,
    picked_sku_l1_package_type STRING,
    picked_sku_l1_length DOUBLE,
    picked_sku_l1_width DOUBLE,
    picked_sku_l1_height DOUBLE,
    picked_sku_l1_packing_efficiency DOUBLE,
    picked_sku_l2_name STRING,
    picked_sku_l2_weight DOUBLE,
    picked_sku_l2_volume DOUBLE,
    picked_sku_l2_package_type STRING,
    picked_sku_l2_length DOUBLE,
    picked_sku_l2_width DOUBLE,
    picked_sku_l2_height DOUBLE,
    picked_sku_l2_packing_efficiency DOUBLE,
    picked_sku_l3_name STRING,
    picked_sku_l3_weight DOUBLE,
    picked_sku_l3_volume DOUBLE,
    picked_sku_l3_package_type STRING,
    picked_sku_l3_length DOUBLE,
    picked_sku_l3_width DOUBLE,
    picked_sku_l3_height DOUBLE,
    picked_sku_l3_packing_efficiency DOUBLE,
    picked_sku_active BOOLEAN,
    picked_sku_classifications STRING,
    picked_sku_product_classifications STRING,
    -- Dropped SKU enrichment fields (comprehensive)
    dropped_sku_principal_id BIGINT,
    dropped_sku_node_id BIGINT,
    dropped_sku_category STRING,
    dropped_sku_product STRING,
    dropped_sku_product_id STRING,
    dropped_sku_category_group STRING,
    dropped_sku_sub_brand STRING,
    dropped_sku_brand STRING,
    dropped_sku_code STRING,
    dropped_sku_name STRING,
    dropped_sku_short_description STRING,
    dropped_sku_description STRING,
    dropped_sku_fulfillment_type STRING,
    dropped_sku_inventory_type STRING,
    dropped_sku_shelf_life INT,
    dropped_sku_tag1 STRING,
    dropped_sku_tag2 STRING,
    dropped_sku_tag3 STRING,
    dropped_sku_tag4 STRING,
    dropped_sku_tag5 STRING,
    dropped_sku_handling_unit_type STRING,
    dropped_sku_cases_per_layer INT,
    dropped_sku_layers INT,
    dropped_sku_l0_units INT,
    dropped_sku_l1_units INT,
    dropped_sku_l2_units INT,
    dropped_sku_l3_units INT,
    dropped_sku_l0_name STRING,
    dropped_sku_l0_weight DOUBLE,
    dropped_sku_l0_volume DOUBLE,
    dropped_sku_l0_package_type STRING,
    dropped_sku_l0_length DOUBLE,
    dropped_sku_l0_width DOUBLE,
    dropped_sku_l0_height DOUBLE,
    dropped_sku_l0_packing_efficiency DOUBLE,
    dropped_sku_l1_name STRING,
    dropped_sku_l1_weight DOUBLE,
    dropped_sku_l1_volume DOUBLE,
    dropped_sku_l1_package_type STRING,
    dropped_sku_l1_length DOUBLE,
    dropped_sku_l1_width DOUBLE,
    dropped_sku_l1_height DOUBLE,
    dropped_sku_l1_packing_efficiency DOUBLE,
    dropped_sku_l2_name STRING,
    dropped_sku_l2_weight DOUBLE,
    dropped_sku_l2_volume DOUBLE,
    dropped_sku_l2_package_type STRING,
    dropped_sku_l2_length DOUBLE,
    dropped_sku_l2_width DOUBLE,
    dropped_sku_l2_height DOUBLE,
    dropped_sku_l2_packing_efficiency DOUBLE,
    dropped_sku_l3_name STRING,
    dropped_sku_l3_weight DOUBLE,
    dropped_sku_l3_volume DOUBLE,
    dropped_sku_l3_package_type STRING,
    dropped_sku_l3_length DOUBLE,
    dropped_sku_l3_width DOUBLE,
    dropped_sku_l3_height DOUBLE,
    dropped_sku_l3_packing_efficiency DOUBLE,
    dropped_sku_active BOOLEAN,
    dropped_sku_classifications STRING,
    dropped_sku_product_classifications STRING,
    PRIMARY KEY (pick_item_id, drop_item_id) NOT ENFORCED
) WITH (
    'connector' = 'upsert-kafka',
    'topic' = 'sbx_uat.wms.public.pick_drop_enriched',
    'properties.bootstrap.servers' = 'sbx-stag-kafka-stackbox.e.aivencloud.com:22167',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.auto.offset.reset' = 'earliest',
    'sink.buffer-flush.max-rows' = '2000',
    'sink.buffer-flush.interval' = '5s',
    'sink.parallelism' = '4',
    'key.format' = 'avro-confluent',
    'key.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'key.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'key.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'value.format' = 'avro-confluent',
    'value.avro-confluent.url' = 'https://sbx-stag-kafka-stackbox.e.aivencloud.com:22159',
    'value.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'value.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);
-- Dimension enrichment with temporal joins (using watermark time)
INSERT INTO pick_drop_summary
SELECT
    /*+ USE_HASH_JOIN */
    pb.wh_id AS wh_id,
    COALESCE(pick_sm.principal_id, 0) AS principal_id,
    pb.pick_item_id AS pick_item_id,
    pb.drop_item_id AS drop_item_id,
    pb.picked_bin AS picked_bin,
    pb.picked_sku_id AS picked_sku_id,
    pb.picked_batch AS picked_batch,
    pb.picked_uom AS picked_uom,
    pb.overall_qty AS overall_qty,
    pb.qty AS qty,
    pb.hu_code AS hu_code,
    pb.destination_bin_code AS destination_bin_code,
    pb.pick_item_created_at AS pick_item_created_at,
    pb.picked_qty AS picked_qty,
    pb.picked_at AS picked_at,
    pb.picked_by_worker_id AS picked_by_worker_id,
    pb.moved_at AS moved_at,
    pb.processed_at AS processed_at,
    pb.picked_hu_eq_uom AS picked_hu_eq_uom,
    pb.picked_has_inner_hus AS picked_has_inner_hus,
    pb.picked_inner_hu_eq_uom AS picked_inner_hu_eq_uom,
    pb.picked_bin_assigned_at AS picked_bin_assigned_at,
    pb.scan_source_hu_kind AS scan_source_hu_kind,
    pb.pick_source_hu_kind AS pick_source_hu_kind,
    pb.carrier_hu_kind AS carrier_hu_kind,
    pb.scanned_source_hu_code AS scanned_source_hu_code,
    pb.picked_source_hu_code AS picked_source_hu_code,
    pb.carrier_hu_code AS carrier_hu_code,
    pb.hu_kind AS hu_kind,
    pb.source_hu_eq_uom AS source_hu_eq_uom,
    pb.pick_item_updated_at AS pick_item_updated_at,
    pb.eligible_drop_locations AS eligible_drop_locations,
    pb.parent_item_id AS parent_item_id,
    pb.old_batch AS old_batch,
    pb.dest_bucket AS dest_bucket,
    pb.original_source_bin_code AS original_source_bin_code,
    pb.lm_trip_id AS lm_trip_id,
    pb.picked_inner_hu_code AS picked_inner_hu_code,
    pb.picked_inner_hu_kind_code AS picked_inner_hu_kind_code,
    pb.picked_quant_bucket AS picked_quant_bucket,
    pb.pick_auto_complete AS pick_auto_complete,
    pb.pick_hu AS pick_hu,
    pb.short_allocation_reason AS short_allocation_reason,
    pb.pd_previous_task_id AS drop_item_previous_task_id,
    pb.dropped_sku_id AS dropped_sku_id,
    pb.dropped_batch AS dropped_batch,
    pb.dropped_uom AS dropped_uom,
    pb.drop_bucket AS drop_bucket,
    pb.picked_hu_code AS picked_hu_code,
    pb.dropped_bin_code AS dropped_bin_code,
    pb.dropped_qty AS dropped_qty,
    pb.dropped_at AS dropped_at,
    pb.drop_item_updated_at AS drop_item_updated_at,
    pb.drop_hu_in_bin AS drop_hu_in_bin,
    pb.scan_dest_hu AS scan_dest_hu,
    pb.allow_hu_break AS allow_hu_break,
    pb.dropped_has_inner_hus AS dropped_has_inner_hus,
    pb.scan_inner_hus AS scan_inner_hus,
    pb.dropped_hu_eq_uom AS dropped_hu_eq_uom,
    pb.dest_hu_code AS dest_hu_code,
    pb.dropped_inner_hu_id AS dropped_inner_hu_id,
    pb.dropped_inner_hu_eq_uom AS dropped_inner_hu_eq_uom,
    pb.dest_bin_assigned_at AS dest_bin_assigned_at,
    pb.drop_uom AS drop_uom,
    pb.drop_parent_item_id AS drop_parent_item_id,
    pb.hu_broken AS hu_broken,
    pb.drop_original_source_bin_code AS drop_original_source_bin_code,
    pb.processed_for_loading_at AS processed_for_loading_at,
    pb.drop_quant_bucket AS drop_quant_bucket,
    pb.drop_inner_hu_code AS drop_inner_hu_code,
    pb.dropped_inner_hu_kind_code AS dropped_inner_hu_kind_code,
    pb.drop_inner_hu AS drop_inner_hu,
    pb.allow_inner_hu_break AS allow_inner_hu_break,
    pb.inner_hu_broken AS inner_hu_broken,
    pb.drop_auto_complete AS drop_auto_complete,
    pb.quant_slotting_for_hus AS quant_slotting_for_hus,
    pb.processed_on_drop_at AS processed_on_drop_at,
    pb.allow_hu_break_v2 AS allow_hu_break_v2,
    -- Task enrichment fields
    t.kind AS task_kind,
    t.code AS task_code,
    COALESCE(t.seq, 0) AS task_sequence,
    t.state AS task_state,
    t.attrs AS task_attrs,
    t.progress AS task_progress,
    t.`createdAt` AS task_created_at,
    t.`updatedAt` AS task_updated_at,
    t.`allowForceComplete` AS allow_force_complete,
    COALESCE(t.wave, 0) AS wave,
    t.`forceCompleted` AS force_completed,
    t.`subKind` AS task_subkind,
    t.label AS label,
    -- Session enrichment fields
    s.kind AS session_kind,
    s.code AS session_code,
    s.attrs AS session_attrs,
    s.`createdAt` AS session_created_at,
    s.`updatedAt` AS session_updated_at,
    s.active,
    s.state AS session_state,
    s.progress AS session_progress,
    s.`autoComplete` AS session_auto_complete,
    -- LM Trip enrichment fields
    lm_trip.code AS lm_trip_code,
    COALESCE(lm_trip.priority, 0) AS lm_trip_priority,
    lm_trip.`dockdoorCode` AS lm_dockdoor,
    lm_trip.`vehicleNo` AS lm_vehicle_no,
    lm_trip.`vehicleType` AS lm_vehicle_type,
    lm_trip.`deliveryDate` AS lm_delivery_date,
    -- Additional Pick Items columns
    pb.bin_id AS bin_id,
    pb.bin_hu_id AS bin_hu_id,
    pb.destination_bin_id AS destination_bin_id,
    pb.destination_bin_hu_id AS destination_bin_hu_id,
    pb.pick_deactivated_at AS pick_deactivated_at,
    pb.pick_deactivated_by AS pick_deactivated_by,
    pb.moved_by AS moved_by,
    pb.scanned_source_hu_id AS scanned_source_hu_id,
    pb.picked_source_hu_id AS picked_source_hu_id,
    pb.carrier_hu_id AS carrier_hu_id,
    pb.original_source_bin_id AS original_source_bin_id,
    pb.inner_hu_id AS inner_hu_id,
    pb.inner_hu_kind_id AS inner_hu_kind_id,
    pb.pd_previous_task_id AS pd_previous_task_id,
    pb.input_source_bin_id AS input_source_bin_id,
    pb.provisional_item_id AS provisional_item_id,
    pb.input_dest_hu_id AS input_dest_hu_id,
    pb.pick_item_kind AS pick_item_kind,
    pb.tp_assigned_at AS tp_assigned_at,
    pb.leg_index AS leg_index,
    pb.last_leg AS last_leg,
    pb.ep_assigned_at AS ep_assigned_at,
    pb.carrier_hu_formed_id AS carrier_hu_formed_id,
    pb.hu_index AS hu_index,
    pb.pick_sequence AS pick_sequence,
    pb.carrier_hu_force_closed AS carrier_hu_force_closed,
    pb.input_dest_bin_id AS input_dest_bin_id,
    pb.inner_hu_index AS inner_hu_index,
    pb.inner_carrier_hu_key AS inner_carrier_hu_key,
    pb.inner_carrier_hu_formed_id AS inner_carrier_hu_formed_id,
    pb.inner_carrier_hu_id AS inner_carrier_hu_id,
    pb.inner_carrier_hu_code AS inner_carrier_hu_code,
    pb.inner_carrier_hu_kind AS inner_carrier_hu_kind,
    pb.induction_id AS induction_id,
    pb.inner_carrier_hu_force_closed AS inner_carrier_hu_force_closed,
    pb.mhe_id AS mhe_id,
    pb.pick_attrs AS pick_attrs,
    pb.iloc AS iloc,
    pb.dest_iloc AS dest_iloc,
    -- Additional Drop Items columns
    pb.source_bin_id AS source_bin_id,
    pb.source_bin_hu_id AS source_bin_hu_id,
    pb.drop_bin_id AS drop_bin_id,
    pb.drop_bin_hu_id AS drop_bin_hu_id,
    pb.drop_created_at AS drop_created_at,
    pb.drop_deactivated_at AS drop_deactivated_at,
    pb.drop_deactivated_by AS drop_deactivated_by,
    pb.dropped_by_worker_id AS dropped_by_worker_id,
    pb.dest_hu_id AS dest_hu_id,
    pb.source_bucket AS source_bucket,
    pb.original_destination_bin_id AS original_destination_bin_id,
    pb.drop_lm_trip_id AS drop_lm_trip_id,
    pb.processed_for_pick_at AS processed_for_pick_at,
    pb.drop_provisional_item_id AS drop_provisional_item_id,
    pb.drop_input_dest_hu_id AS drop_input_dest_hu_id,
    pb.drop_leg_index AS drop_leg_index,
    pb.drop_last_leg AS drop_last_leg,
    pb.drop_input_dest_bin_id AS drop_input_dest_bin_id,
    pb.drop_induction_id AS drop_induction_id,
    pb.drop_attrs AS drop_attrs,
    pb.drop_mhe_id AS drop_mhe_id,
    pb.drop_iloc AS drop_iloc,
    pb.source_iloc AS source_iloc,
    -- Additional Pick Drop Mapping columns
    pb.mapping_id AS mapping_id,
    pb.mapping_created_at AS mapping_created_at,
    -- Additional Tasks columns
    t.exclusive AS task_exclusive,
    t.active AS task_active,
    t.`autoComplete` AS task_auto_complete,
    t.`forceCompleteTaskId` AS force_complete_task_id,
    -- Additional Trips columns (LM)
    lm_trip.`sessionCreatedAt` AS lm_session_created_at,
    lm_trip.`createdAt` AS lm_trip_created_at,
    lm_trip.`bbId` AS lm_bb_id,
    lm_trip.`type` AS lm_trip_type,
    lm_trip.`dockdoorId` AS lm_dockdoor_id,
    lm_trip.`vehicleId` AS lm_vehicle_id,
    -- Trip Relation enrichment fields
    tr.id AS trip_relation_id,
    tr.xdock AS trip_relation_xdock,
    tr.parentTripId AS trip_relation_parent_trip_id,
    tr.createdAt AS trip_relation_created_at,
    -- Parent Trip enrichment fields
    parent_trip.code AS parent_trip_code,
    parent_trip.`type` AS parent_trip_type,
    COALESCE(parent_trip.priority, 0) AS parent_trip_priority,
    parent_trip.`dockdoorCode` AS parent_trip_dockdoor_code,
    parent_trip.`vehicleNo` AS parent_trip_vehicle_no,
    parent_trip.`vehicleType` AS parent_trip_vehicle_type,
    parent_trip.`deliveryDate` AS parent_trip_delivery_date,
    parent_trip.`createdAt` AS parent_trip_created_at,
    -- Worker enrichment fields
    w.code AS worker_code,
    w.name AS worker_name,
    w.phone AS worker_phone,
    w.supervisor AS worker_supervisor,
    w.active AS worker_active,
    -- Handling Unit enrichment fields
    hu.code AS dropped_hu_code,
    hu.`kindId` AS dropped_hu_kind_id,
    hu.`sessionId` AS dropped_hu_session_id,
    hu.`taskId` AS dropped_hu_task_id,
    hu.`storageId` AS dropped_hu_storage_id,
    hu.`outerHuId` AS dropped_hu_outer_hu_id,
    hu.state AS dropped_hu_state,
    hu.attrs AS dropped_hu_attrs,
    hu.`lockTaskId` AS dropped_hu_lock_task_id,
    hu.`effectiveStorageId` AS dropped_hu_effective_storage_id,
    hu.`createdAt` AS dropped_hu_created_at,
    hu.`updatedAt` AS dropped_hu_updated_at,
    -- Picked SKU enrichment fields (overrides prioritized over master)
    COALESCE(pick_so.principal_id, pick_sm.principal_id) AS picked_sku_principal_id,
    COALESCE(pick_so.node_id, pick_sm.node_id) AS picked_sku_node_id,
    COALESCE(pick_so.category, pick_sm.category) AS picked_sku_category,
    COALESCE(pick_so.product, pick_sm.product) AS picked_sku_product,
    COALESCE(pick_so.product_id, pick_sm.product_id) AS picked_sku_product_id,
    COALESCE(
        pick_so.category_group,
        pick_sm.category_group,
        ''
    ) AS picked_sku_category_group,
    COALESCE(pick_so.sub_brand, pick_sm.sub_brand) AS picked_sku_sub_brand,
    COALESCE(pick_so.brand, pick_sm.brand) AS picked_sku_brand,
    COALESCE(pick_so.code, pick_sm.code) AS picked_sku_code,
    COALESCE(pick_so.name, pick_sm.name) AS picked_sku_name,
    COALESCE(
        pick_so.short_description,
        pick_sm.short_description,
        ''
    ) AS picked_sku_short_description,
    COALESCE(pick_so.description, pick_sm.description) AS picked_sku_description,
    COALESCE(
        pick_so.fulfillment_type,
        pick_sm.fulfillment_type,
        ''
    ) AS picked_sku_fulfillment_type,
    COALESCE(
        pick_so.inventory_type,
        pick_sm.inventory_type,
        ''
    ) AS picked_sku_inventory_type,
    COALESCE(pick_so.shelf_life, pick_sm.shelf_life, 0) AS picked_sku_shelf_life,
    COALESCE(pick_so.tag1, pick_sm.tag1) AS picked_sku_tag1,
    COALESCE(pick_so.tag2, pick_sm.tag2) AS picked_sku_tag2,
    COALESCE(pick_so.tag3, pick_sm.tag3) AS picked_sku_tag3,
    COALESCE(pick_so.tag4, pick_sm.tag4) AS picked_sku_tag4,
    COALESCE(pick_so.tag5, pick_sm.tag5) AS picked_sku_tag5,
    COALESCE(
        pick_so.handling_unit_type,
        pick_sm.handling_unit_type,
        ''
    ) AS picked_sku_handling_unit_type,
    COALESCE(
        pick_so.cases_per_layer,
        pick_sm.cases_per_layer,
        0
    ) AS picked_sku_cases_per_layer,
    COALESCE(pick_so.layers, pick_sm.layers, 0) AS picked_sku_layers,
    COALESCE(pick_so.l0_units, pick_sm.l0_units, 0) AS picked_sku_l0_units,
    COALESCE(pick_so.l1_units, pick_sm.l1_units, 0) AS picked_sku_l1_units,
    COALESCE(pick_so.l2_units, pick_sm.l2_units, 0) AS picked_sku_l2_units,
    COALESCE(pick_so.l3_units, pick_sm.l3_units, 0) AS picked_sku_l3_units,
    COALESCE(pick_so.l0_name, pick_sm.l0_name) AS picked_sku_l0_name,
    COALESCE(pick_so.l0_weight, pick_sm.l0_weight, 0.0) AS picked_sku_l0_weight,
    COALESCE(pick_so.l0_volume, pick_sm.l0_volume, 0.0) AS picked_sku_l0_volume,
    COALESCE(
        pick_so.l0_package_type,
        pick_sm.l0_package_type,
        ''
    ) AS picked_sku_l0_package_type,
    COALESCE(pick_so.l0_length, pick_sm.l0_length, 0.0) AS picked_sku_l0_length,
    COALESCE(pick_so.l0_width, pick_sm.l0_width, 0.0) AS picked_sku_l0_width,
    COALESCE(pick_so.l0_height, pick_sm.l0_height, 0.0) AS picked_sku_l0_height,
    COALESCE(
        pick_so.l0_packing_efficiency,
        pick_sm.l0_packing_efficiency,
        0.0
    ) AS picked_sku_l0_packing_efficiency,
    COALESCE(pick_so.l1_name, pick_sm.l1_name) AS picked_sku_l1_name,
    COALESCE(pick_so.l1_weight, pick_sm.l1_weight, 0.0) AS picked_sku_l1_weight,
    COALESCE(pick_so.l1_volume, pick_sm.l1_volume, 0.0) AS picked_sku_l1_volume,
    COALESCE(
        pick_so.l1_package_type,
        pick_sm.l1_package_type,
        ''
    ) AS picked_sku_l1_package_type,
    COALESCE(pick_so.l1_length, pick_sm.l1_length, 0.0) AS picked_sku_l1_length,
    COALESCE(pick_so.l1_width, pick_sm.l1_width, 0.0) AS picked_sku_l1_width,
    COALESCE(pick_so.l1_height, pick_sm.l1_height, 0.0) AS picked_sku_l1_height,
    COALESCE(
        pick_so.l1_packing_efficiency,
        pick_sm.l1_packing_efficiency,
        0.0
    ) AS picked_sku_l1_packing_efficiency,
    COALESCE(pick_so.l2_name, pick_sm.l2_name) AS picked_sku_l2_name,
    COALESCE(pick_so.l2_weight, pick_sm.l2_weight, 0.0) AS picked_sku_l2_weight,
    COALESCE(pick_so.l2_volume, pick_sm.l2_volume, 0.0) AS picked_sku_l2_volume,
    COALESCE(
        pick_so.l2_package_type,
        pick_sm.l2_package_type,
        ''
    ) AS picked_sku_l2_package_type,
    COALESCE(pick_so.l2_length, pick_sm.l2_length, 0.0) AS picked_sku_l2_length,
    COALESCE(pick_so.l2_width, pick_sm.l2_width, 0.0) AS picked_sku_l2_width,
    COALESCE(pick_so.l2_height, pick_sm.l2_height, 0.0) AS picked_sku_l2_height,
    COALESCE(
        pick_so.l2_packing_efficiency,
        pick_sm.l2_packing_efficiency,
        0.0
    ) AS picked_sku_l2_packing_efficiency,
    COALESCE(pick_so.l3_name, pick_sm.l3_name) AS picked_sku_l3_name,
    COALESCE(pick_so.l3_weight, pick_sm.l3_weight, 0.0) AS picked_sku_l3_weight,
    COALESCE(pick_so.l3_volume, pick_sm.l3_volume, 0.0) AS picked_sku_l3_volume,
    COALESCE(
        pick_so.l3_package_type,
        pick_sm.l3_package_type,
        ''
    ) AS picked_sku_l3_package_type,
    COALESCE(pick_so.l3_length, pick_sm.l3_length, 0.0) AS picked_sku_l3_length,
    COALESCE(pick_so.l3_width, pick_sm.l3_width, 0.0) AS picked_sku_l3_width,
    COALESCE(pick_so.l3_height, pick_sm.l3_height, 0.0) AS picked_sku_l3_height,
    COALESCE(
        pick_so.l3_packing_efficiency,
        pick_sm.l3_packing_efficiency,
        0.0
    ) AS picked_sku_l3_packing_efficiency,
    COALESCE(pick_so.active, pick_sm.active) AS picked_sku_active,
    COALESCE(
        pick_so.classifications,
        pick_sm.classifications,
        ''
    ) AS picked_sku_classifications,
    COALESCE(
        pick_so.product_classifications,
        pick_sm.product_classifications,
        ''
    ) AS picked_sku_product_classifications,
    -- Dropped SKU enrichment fields (overrides prioritized over master)
    COALESCE(drop_so.principal_id, drop_sm.principal_id) AS dropped_sku_principal_id,
    COALESCE(drop_so.node_id, drop_sm.node_id) AS dropped_sku_node_id,
    COALESCE(drop_so.category, drop_sm.category) AS dropped_sku_category,
    COALESCE(drop_so.product, drop_sm.product) AS dropped_sku_product,
    COALESCE(drop_so.product_id, drop_sm.product_id) AS dropped_sku_product_id,
    COALESCE(
        drop_so.category_group,
        drop_sm.category_group,
        ''
    ) AS dropped_sku_category_group,
    COALESCE(drop_so.sub_brand, drop_sm.sub_brand) AS dropped_sku_sub_brand,
    COALESCE(drop_so.brand, drop_sm.brand) AS dropped_sku_brand,
    COALESCE(drop_so.code, drop_sm.code) AS dropped_sku_code,
    COALESCE(drop_so.name, drop_sm.name) AS dropped_sku_name,
    COALESCE(
        drop_so.short_description,
        drop_sm.short_description,
        ''
    ) AS dropped_sku_short_description,
    COALESCE(drop_so.description, drop_sm.description) AS dropped_sku_description,
    COALESCE(
        drop_so.fulfillment_type,
        drop_sm.fulfillment_type,
        ''
    ) AS dropped_sku_fulfillment_type,
    COALESCE(
        drop_so.inventory_type,
        drop_sm.inventory_type,
        ''
    ) AS dropped_sku_inventory_type,
    COALESCE(drop_so.shelf_life, drop_sm.shelf_life, 0) AS dropped_sku_shelf_life,
    COALESCE(drop_so.tag1, drop_sm.tag1) AS dropped_sku_tag1,
    COALESCE(drop_so.tag2, drop_sm.tag2) AS dropped_sku_tag2,
    COALESCE(drop_so.tag3, drop_sm.tag3) AS dropped_sku_tag3,
    COALESCE(drop_so.tag4, drop_sm.tag4) AS dropped_sku_tag4,
    COALESCE(drop_so.tag5, drop_sm.tag5) AS dropped_sku_tag5,
    COALESCE(
        drop_so.handling_unit_type,
        drop_sm.handling_unit_type,
        ''
    ) AS dropped_sku_handling_unit_type,
    COALESCE(
        drop_so.cases_per_layer,
        drop_sm.cases_per_layer,
        0
    ) AS dropped_sku_cases_per_layer,
    COALESCE(drop_so.layers, drop_sm.layers, 0) AS dropped_sku_layers,
    COALESCE(drop_so.l0_units, drop_sm.l0_units, 0) AS dropped_sku_l0_units,
    COALESCE(drop_so.l1_units, drop_sm.l1_units, 0) AS dropped_sku_l1_units,
    COALESCE(drop_so.l2_units, drop_sm.l2_units, 0) AS dropped_sku_l2_units,
    COALESCE(drop_so.l3_units, drop_sm.l3_units, 0) AS dropped_sku_l3_units,
    COALESCE(drop_so.l0_name, drop_sm.l0_name) AS dropped_sku_l0_name,
    COALESCE(drop_so.l0_weight, drop_sm.l0_weight, 0.0) AS dropped_sku_l0_weight,
    COALESCE(drop_so.l0_volume, drop_sm.l0_volume, 0.0) AS dropped_sku_l0_volume,
    COALESCE(
        drop_so.l0_package_type,
        drop_sm.l0_package_type,
        ''
    ) AS dropped_sku_l0_package_type,
    COALESCE(drop_so.l0_length, drop_sm.l0_length, 0.0) AS dropped_sku_l0_length,
    COALESCE(drop_so.l0_width, drop_sm.l0_width, 0.0) AS dropped_sku_l0_width,
    COALESCE(drop_so.l0_height, drop_sm.l0_height, 0.0) AS dropped_sku_l0_height,
    COALESCE(
        drop_so.l0_packing_efficiency,
        drop_sm.l0_packing_efficiency,
        0.0
    ) AS dropped_sku_l0_packing_efficiency,
    COALESCE(drop_so.l1_name, drop_sm.l1_name) AS dropped_sku_l1_name,
    COALESCE(drop_so.l1_weight, drop_sm.l1_weight, 0.0) AS dropped_sku_l1_weight,
    COALESCE(drop_so.l1_volume, drop_sm.l1_volume, 0.0) AS dropped_sku_l1_volume,
    COALESCE(
        drop_so.l1_package_type,
        drop_sm.l1_package_type,
        ''
    ) AS dropped_sku_l1_package_type,
    COALESCE(drop_so.l1_length, drop_sm.l1_length, 0.0) AS dropped_sku_l1_length,
    COALESCE(drop_so.l1_width, drop_sm.l1_width, 0.0) AS dropped_sku_l1_width,
    COALESCE(drop_so.l1_height, drop_sm.l1_height, 0.0) AS dropped_sku_l1_height,
    COALESCE(
        drop_so.l1_packing_efficiency,
        drop_sm.l1_packing_efficiency,
        0.0
    ) AS dropped_sku_l1_packing_efficiency,
    COALESCE(drop_so.l2_name, drop_sm.l2_name) AS dropped_sku_l2_name,
    COALESCE(drop_so.l2_weight, drop_sm.l2_weight, 0.0) AS dropped_sku_l2_weight,
    COALESCE(drop_so.l2_volume, drop_sm.l2_volume, 0.0) AS dropped_sku_l2_volume,
    COALESCE(
        drop_so.l2_package_type,
        drop_sm.l2_package_type,
        ''
    ) AS dropped_sku_l2_package_type,
    COALESCE(drop_so.l2_length, drop_sm.l2_length, 0.0) AS dropped_sku_l2_length,
    COALESCE(drop_so.l2_width, drop_sm.l2_width, 0.0) AS dropped_sku_l2_width,
    COALESCE(drop_so.l2_height, drop_sm.l2_height, 0.0) AS dropped_sku_l2_height,
    COALESCE(
        drop_so.l2_packing_efficiency,
        drop_sm.l2_packing_efficiency,
        0.0
    ) AS dropped_sku_l2_packing_efficiency,
    COALESCE(drop_so.l3_name, drop_sm.l3_name) AS dropped_sku_l3_name,
    COALESCE(drop_so.l3_weight, drop_sm.l3_weight, 0.0) AS dropped_sku_l3_weight,
    COALESCE(drop_so.l3_volume, drop_sm.l3_volume, 0.0) AS dropped_sku_l3_volume,
    COALESCE(
        drop_so.l3_package_type,
        drop_sm.l3_package_type,
        ''
    ) AS dropped_sku_l3_package_type,
    COALESCE(drop_so.l3_length, drop_sm.l3_length, 0.0) AS dropped_sku_l3_length,
    COALESCE(drop_so.l3_width, drop_sm.l3_width, 0.0) AS dropped_sku_l3_width,
    COALESCE(drop_so.l3_height, drop_sm.l3_height, 0.0) AS dropped_sku_l3_height,
    COALESCE(
        drop_so.l3_packing_efficiency,
        drop_sm.l3_packing_efficiency,
        0.0
    ) AS dropped_sku_l3_packing_efficiency,
    COALESCE(drop_so.active, drop_sm.active) AS dropped_sku_active,
    COALESCE(
        drop_so.classifications,
        drop_sm.classifications,
        ''
    ) AS dropped_sku_classifications,
    COALESCE(
        drop_so.product_classifications,
        drop_sm.product_classifications,
        ''
    ) AS dropped_sku_product_classifications
FROM pick_drop_basic pb
    LEFT JOIN `sessions` FOR SYSTEM_TIME AS OF pb.event_time AS s ON pb.session_id = s.id
    LEFT JOIN tasks FOR SYSTEM_TIME AS OF pb.event_time AS t ON pb.task_id = t.id
    LEFT JOIN trips FOR SYSTEM_TIME AS OF pb.event_time AS lm_trip ON pb.lm_trip_id = lm_trip.id
    LEFT JOIN trip_relation_rekeyed FOR SYSTEM_TIME AS OF pb.event_time AS tr ON pb.session_id = tr.sessionId
    AND pb.lm_trip_id = tr.childTripId
    LEFT JOIN trips FOR SYSTEM_TIME AS OF pb.event_time AS parent_trip ON tr.parentTripId = parent_trip.id
    LEFT JOIN workers FOR SYSTEM_TIME AS OF pb.event_time AS w ON pb.picked_by_worker_id = w.id
    LEFT JOIN handling_units FOR SYSTEM_TIME AS OF pb.event_time AS hu ON pb.dropped_inner_hu_id = hu.id
    LEFT JOIN sku_overrides FOR SYSTEM_TIME AS OF pb.event_time AS pick_so ON pb.picked_sku_id = pick_so.sku_id
    AND pb.wh_id = pick_so.node_id
    LEFT JOIN sku_masters FOR SYSTEM_TIME AS OF pb.event_time AS pick_sm ON pb.picked_sku_id = pick_sm.id
    LEFT JOIN sku_overrides FOR SYSTEM_TIME AS OF pb.event_time AS drop_so ON pb.dropped_sku_id = drop_so.sku_id
    AND pb.wh_id = drop_so.node_id
    LEFT JOIN sku_masters FOR SYSTEM_TIME AS OF pb.event_time AS drop_sm ON pb.dropped_sku_id = drop_sm.id;
---