CREATE MATERIALIZED VIEW sbx_uat_insights.mv_storage_bin_summary
TO sbx_uat_insights.storage_bin_summary
AS
SELECT
    sb."whId" AS "whId",
    sb.code AS bin_code,
    sb.description AS bin_description,
    sb."multiSku",
    sb."multiBatch",
    sb."pickingPosition",
    sb."putawayPosition",
    sb.rank,
    sb.aisle,
    sb.bay,
    sb.level,
    sb.position,
    sb.depth,
    sb."maxSkuCount",
    sb."maxSkuBatchCount",
    sbt.code AS bin_type_code,
    sbt.description AS bintype_description,
    sbt."maxVolumeInCC",
    sbt."maxWeightInKG",
    sbt."palletCapacity",
    sbt."storageHUType",
    sbt."auxiliaryBin",
    sbt."huMultiSku",
    sbt."huMultiBatch",
    sbt."useDerivedPalletBestFit",
    sz.code AS zone_code,
    sz.description AS zone_description,
    sz.face AS zone_face,
    sz.peripheral,
    sz."surveillanceConfig",
    sa.code AS area_code,
    sa.description AS sa_description,
    sa.type AS area_type,
    sa."rollingDays",
    ss.x1,
    ss.x2,
    ss.y1,
    ss.y2,
    sac.quality,
    sac.sloc,
    sac."slocDescription",
    sac."clientQuality",
    sac."inventoryVisible",
    sac."erpToWMS",
    sd.code AS sd_code,
    sbd.usage,
    sbd."multiTrip",
    sd.description AS sd_description,
    sd."maxQueue",
    sd."allowInbound",
    sd."allowOutbound",
    sd."allowReturns",
    sd."incompatibleVehicleTypes",
    sd."incompatibleLoadTypes",
    sdp.x AS dockdoor_x_coordinate,
    sdp.y AS dockdoor_y_coordinate,
    sb.status AS sb_status,
    sbt.active AS sbt_active,
if(sbfm.active = 'true' , 'FIXED','DYNAMIC') AS bin_mapping
FROM sbx_uat.wms_storage_bin AS sb
LEFT JOIN sbx_uat.wms_storage_bin_fixed_mapping sbfm on sb.id=sbfm."binId"
LEFT JOIN sbx_uat.wms_storage_bin_type sbt ON sb."binTypeId" = sbt.id
LEFT JOIN sbx_uat.wms_storage_zone sz ON sb."zoneId" = sz.id
LEFT JOIN sbx_uat.wms_storage_area sa ON sz."areaId" = sa.id
LEFT JOIN sbx_uat.wms_storage_position ss ON ss."storageId" = sb.id
LEFT JOIN sbx_uat.wms_storage_area_sloc sac ON sa."whId" = sac."whId" AND sa."code" = sac."areaCode"
LEFT JOIN sbx_uat.wms_storage_bin_dockdoor sbd ON sb.id = sbd."binId"
LEFT JOIN sbx_uat.wms_storage_dockdoor sd ON sbd."dockdoorId" = sd.id
LEFT JOIN sbx_uat.wms_storage_dockdoor_position sdp ON sd."id" = sdp."dockdoorId";


CREATE MATERIALIZED VIEW sbx_uat_insights.mv_inventory
TO sbx_uat_insights.inventory
AS
SELECT
    "whId",
    "id",
    "huId",
    "huCode",
    "huKind",
    "huWeight",
    "huOnHold",
    "huRendered",
    "huLockTaskId",
    "isBinHu",
    "areaType",
    "areaCode",
    "zoneFace",
    "zoneCode",
    "binType",
    "binCode",
    "binStatus",
    "binCapacity",
    "outerHUCode",
    "outerHUKind",
    "skuId",
    "skuCode",
    "skuName",
    "skuInventoryType",
    "productCode",
    "category",
    "categoryGroup",
    "skuClassification",
    "plantCode",
    "brand",
    "bucket",
    "inclusionStatus",
    "uom",
    "batch",
    "manufactureDate",
    "expiryDate",
    "price",
    "quantLockMode",
    "qty",
    "qtyL0",
    "huUpdatedAt",
    "quantUpdatedAt",
    "updatedAt",
    "binTypeId",
    "usage",
    "huCountBlocked",
    "is_deleted",
    "deleted_at"
FROM sbx_uat.wms_inventory;