CREATE TABLE IF NOT EXISTS sbx_uat_insights.storage_bin_summary
(
    whId Int64,
    bin_code String,
    bin_description String,
    multiSku Bool,
    multiBatch Bool,
    pickingPosition Int32,
    putawayPosition Int32,
    rank Int32,
    aisle String DEFAULT 0,
    bay String DEFAULT 0,
    level String DEFAULT 0,
    position String DEFAULT 0,
    depth String DEFAULT 0,
    maxSkuCount Int32 DEFAULT 0,
    maxSkuBatchCount Int32 DEFAULT 0,
    bin_type_code LowCardinality(String),
    bintype_description String,
    maxVolumeInCC Float64,
    maxWeightInKG Float64,
    palletCapacity Int32 DEFAULT 0,
    storageHUType LowCardinality(String) DEFAULT 'NONE',
    auxiliaryBin Bool,
    huMultiSku Bool,
    huMultiBatch Bool,
    useDerivedPalletBestFit Bool,
    zone_code LowCardinality(String),
    zone_description String,
    zone_face LowCardinality(String),
    peripheral Bool,
    surveillanceConfig String DEFAULT 0,
    area_code LowCardinality(String),
    sa_description String,
    area_type LowCardinality(String),
    rollingDays Int32 DEFAULT 0,
    x1 Float64,
    x2 Float64,
    y1 Float64,
    y2 Float64,
    quality LowCardinality(String),
    sloc LowCardinality(String),
    slocDescription String,
    clientQuality LowCardinality(String),
    inventoryVisible Bool,
    erpToWMS Bool,
    sd_code String,
    usage LowCardinality(String) DEFAULT 0,
    multiTrip Bool,
    sd_description String,
    maxQueue Int64,
    allowInbound Bool,
    allowOutbound Bool,
    allowReturns Bool,
    incompatibleVehicleTypes String,
    incompatibleLoadTypes String,
    dockdoor_x_coordinate Float64,
    dockdoor_y_coordinate Float64
)
ENGINE = ReplacingMergeTree()
ORDER BY ("whId", "bin_code", "quality");

CREATE TABLE IF NOT EXISTS sbx_uat_insights.inventory 
(
    "whId" Int64,
    "id" UUID,
    "huId" String,
    "huCode" String,
    "huKind" String,
    "huWeight" Float64 DEFAULT 0,
    "huOnHold" Bool,
    "huRendered" Bool,
    "huLockTaskId" Nullable(UUID),
    "isBinHu" Bool,
    "areaType" String DEFAULT 0,
    "areaCode" String DEFAULT 0,
    "zoneFace" String DEFAULT 0,
    "zoneCode" String DEFAULT 0,
    "binType" String DEFAULT 0,
    "binCode" String DEFAULT 0,
    "binStatus" String DEFAULT 0,
    "binCapacity" Int32 DEFAULT 0,
    "outerHUCode" String DEFAULT 0,
    "outerHUKind" String DEFAULT 0,
    "skuId" String,
    "skuCode" String,
    "skuName" String,
    "skuInventoryType" String,
    "productCode" String,
    "category" String,
    "categoryGroup" String,
    "skuClassification" String,
    "plantCode" String DEFAULT 0,
    "brand" String,
    "bucket" String,
    "inclusionStatus" String,
    "uom" String,
    "batch" String DEFAULT 0,
    "manufactureDate" Date DEFAULT 0,
    "expiryDate" Date DEFAULT 0,
    "price" String DEFAULT 0,
    "quantLockMode" String,
    "qty" Int32 NOT NULL,
    "qtyL0" Int64,
    "huUpdatedAt" DateTime64(3, 'UTC') DEFAULT 0,
    "quantUpdatedAt" DateTime64(3, 'UTC') DEFAULT 0,
    "updatedAt" DateTime64(3, 'UTC') DEFAULT 0,
    "binTypeId" Nullable(UUID),
    "usage" Float64 DEFAULT 0,
    "huCountBlocked" bool DEFAULT false,
)
ENGINE = ReplacingMergeTree(updatedAt)
ORDER BY (id);
