-- ClickHouse Materialized View for WMS Pick-Drop Enriched
-- Enriches pick_drop_staging with dimension data
-- Enriches with workers, handling_units, and SKU data (from picked_sku_id only)
-- NOTE: wms_pick_drop_staging has Nullable columns from RisingWave CDC sink.
--       All nullable pb.* columns wrapped with ifNull() to prevent MV insert failure.

CREATE MATERIALIZED VIEW IF NOT EXISTS wms_pick_drop_enriched_mv
TO wms_pick_drop_enriched
AS
SELECT
    -- Core identifiers (non-nullable in staging)
    pb.wh_id AS wh_id,
    if(so.principal_id != 0, so.principal_id, sm.principal_id) AS principal_id,
    pb.pick_item_id AS pick_item_id,
    pb.drop_item_id AS drop_item_id,

    -- All fields from pick_drop_staging (nullable columns wrapped with ifNull)
    ifNull(pb.picked_bin, '') AS picked_bin,
    ifNull(pb.picked_sku_id, '') AS picked_sku_id,
    ifNull(pb.picked_batch, '') AS picked_batch,
    ifNull(pb.picked_uom, '') AS picked_uom,
    ifNull(pb.overall_qty, 0) AS overall_qty,
    ifNull(pb.qty, 0) AS qty,
    ifNull(pb.hu_code, '') AS hu_code,
    ifNull(pb.destination_bin_code, '') AS destination_bin_code,
    pb.pick_item_created_at AS pick_item_created_at,
    ifNull(pb.picked_qty, 0) AS picked_qty,
    ifNull(pb.picked_at, toDateTime64('1970-01-01 00:00:00', 3)) AS picked_at,
    ifNull(pb.picked_by_worker_id, '') AS picked_by_worker_id,
    ifNull(pb.moved_at, toDateTime64('1970-01-01 00:00:00', 3)) AS moved_at,
    ifNull(pb.processed_at, toDateTime64('1970-01-01 00:00:00', 3)) AS processed_at,
    ifNull(pb.picked_hu_eq_uom, '') AS picked_hu_eq_uom,
    ifNull(pb.picked_has_inner_hus, false) AS picked_has_inner_hus,
    ifNull(pb.picked_inner_hu_eq_uom, '') AS picked_inner_hu_eq_uom,
    ifNull(pb.picked_bin_assigned_at, toDateTime64('1970-01-01 00:00:00', 3)) AS picked_bin_assigned_at,
    ifNull(pb.scan_source_hu_kind, '') AS scan_source_hu_kind,
    ifNull(pb.pick_source_hu_kind, '') AS pick_source_hu_kind,
    ifNull(pb.carrier_hu_kind, '') AS carrier_hu_kind,
    ifNull(pb.scanned_source_hu_code, '') AS scanned_source_hu_code,
    ifNull(pb.picked_source_hu_code, '') AS picked_source_hu_code,
    ifNull(pb.carrier_hu_code, '') AS carrier_hu_code,
    ifNull(pb.hu_kind, '') AS hu_kind,
    ifNull(pb.source_hu_eq_uom, '') AS source_hu_eq_uom,
    ifNull(pb.pick_item_updated_at, toDateTime64('1970-01-01 00:00:00', 3)) AS pick_item_updated_at,
    ifNull(pb.eligible_drop_locations, '') AS eligible_drop_locations,
    ifNull(pb.parent_item_id, '') AS parent_item_id,
    ifNull(pb.old_batch, '') AS old_batch,
    ifNull(pb.dest_bucket, '') AS dest_bucket,
    ifNull(pb.original_source_bin_code, '') AS original_source_bin_code,
    ifNull(pb.lm_trip_id, '') AS lm_trip_id,
    ifNull(pb.session_id, '') AS session_id,
    ifNull(pb.task_id, '') AS task_id,
    ifNull(pb.picked_inner_hu_code, '') AS picked_inner_hu_code,
    ifNull(pb.picked_inner_hu_kind_code, '') AS picked_inner_hu_kind_code,
    ifNull(pb.picked_quant_bucket, '') AS picked_quant_bucket,
    ifNull(pb.pick_auto_complete, false) AS pick_auto_complete,
    ifNull(pb.pick_hu, false) AS pick_hu,
    ifNull(pb.short_allocation_reason, '') AS short_allocation_reason,
    ifNull(pb.pd_previous_task_id, '') AS drop_item_previous_task_id,
    ifNull(pb.dropped_sku_id, '') AS dropped_sku_id,
    ifNull(pb.dropped_batch, '') AS dropped_batch,
    ifNull(pb.dropped_uom, '') AS dropped_uom,
    ifNull(pb.drop_bucket, '') AS drop_bucket,
    ifNull(pb.picked_hu_code, '') AS picked_hu_code,
    ifNull(pb.dropped_bin_code, '') AS dropped_bin_code,
    ifNull(pb.dropped_qty, 0) AS dropped_qty,
    ifNull(pb.dropped_at, toDateTime64('1970-01-01 00:00:00', 3)) AS dropped_at,
    ifNull(pb.drop_item_updated_at, toDateTime64('1970-01-01 00:00:00', 3)) AS drop_item_updated_at,
    ifNull(pb.drop_hu_in_bin, false) AS drop_hu_in_bin,
    ifNull(pb.scan_dest_hu, false) AS scan_dest_hu,
    ifNull(pb.allow_hu_break, false) AS allow_hu_break,
    ifNull(pb.dropped_has_inner_hus, false) AS dropped_has_inner_hus,
    ifNull(pb.scan_inner_hus, false) AS scan_inner_hus,
    ifNull(pb.dropped_hu_eq_uom, '') AS dropped_hu_eq_uom,
    ifNull(pb.dest_hu_code, '') AS dest_hu_code,
    ifNull(pb.dropped_inner_hu_id, '') AS dropped_inner_hu_id,
    ifNull(pb.dropped_inner_hu_eq_uom, '') AS dropped_inner_hu_eq_uom,
    ifNull(pb.dest_bin_assigned_at, toDateTime64('1970-01-01 00:00:00', 3)) AS dest_bin_assigned_at,
    ifNull(pb.drop_uom, '') AS drop_uom,
    ifNull(pb.drop_parent_item_id, '') AS drop_parent_item_id,
    ifNull(pb.hu_broken, false) AS hu_broken,
    ifNull(pb.drop_original_source_bin_code, '') AS drop_original_source_bin_code,
    ifNull(pb.processed_for_loading_at, toDateTime64('1970-01-01 00:00:00', 3)) AS processed_for_loading_at,
    ifNull(pb.drop_quant_bucket, '') AS drop_quant_bucket,
    ifNull(pb.drop_inner_hu_code, '') AS drop_inner_hu_code,
    ifNull(pb.dropped_inner_hu_kind_code, '') AS dropped_inner_hu_kind_code,
    ifNull(pb.drop_inner_hu, false) AS drop_inner_hu,
    ifNull(pb.allow_inner_hu_break, false) AS allow_inner_hu_break,
    ifNull(pb.inner_hu_broken, false) AS inner_hu_broken,
    ifNull(pb.drop_auto_complete, false) AS drop_auto_complete,
    ifNull(pb.quant_slotting_for_hus, false) AS quant_slotting_for_hus,
    ifNull(pb.processed_on_drop_at, toDateTime64('1970-01-01 00:00:00', 3)) AS processed_on_drop_at,
    ifNull(pb.allow_hu_break_v2, false) AS allow_hu_break_v2,

    -- Additional Pick Items columns
    ifNull(pb.bin_id, '') AS bin_id,
    ifNull(pb.bin_hu_id, '') AS bin_hu_id,
    ifNull(pb.destination_bin_id, '') AS destination_bin_id,
    ifNull(pb.destination_bin_hu_id, '') AS destination_bin_hu_id,
    ifNull(pb.pick_deactivated_at, toDateTime64('1970-01-01 00:00:00', 3)) AS pick_deactivated_at,
    ifNull(pb.pick_deactivated_by, '') AS pick_deactivated_by,
    ifNull(pb.moved_by, '') AS moved_by,
    ifNull(pb.scanned_source_hu_id, '') AS scanned_source_hu_id,
    ifNull(pb.picked_source_hu_id, '') AS picked_source_hu_id,
    ifNull(pb.carrier_hu_id, '') AS carrier_hu_id,
    ifNull(pb.original_source_bin_id, '') AS original_source_bin_id,
    ifNull(pb.inner_hu_id, '') AS inner_hu_id,
    ifNull(pb.inner_hu_kind_id, '') AS inner_hu_kind_id,
    ifNull(pb.pd_previous_task_id, '') AS pd_previous_task_id,
    ifNull(pb.input_source_bin_id, '') AS input_source_bin_id,
    ifNull(pb.provisional_item_id, '') AS provisional_item_id,
    ifNull(pb.input_dest_hu_id, '') AS input_dest_hu_id,
    ifNull(pb.pick_item_kind, '') AS pick_item_kind,
    ifNull(pb.tp_assigned_at, toDateTime64('1970-01-01 00:00:00', 3)) AS tp_assigned_at,
    ifNull(pb.leg_index, 0) AS leg_index,
    ifNull(pb.last_leg, false) AS last_leg,
    ifNull(pb.ep_assigned_at, toDateTime64('1970-01-01 00:00:00', 3)) AS ep_assigned_at,
    ifNull(pb.carrier_hu_formed_id, '') AS carrier_hu_formed_id,
    ifNull(pb.hu_index, 0) AS hu_index,
    ifNull(pb.pick_sequence, 0) AS pick_sequence,
    ifNull(pb.carrier_hu_force_closed, false) AS carrier_hu_force_closed,
    ifNull(pb.input_dest_bin_id, '') AS input_dest_bin_id,
    ifNull(pb.inner_hu_index, 0) AS inner_hu_index,
    ifNull(pb.inner_carrier_hu_key, '') AS inner_carrier_hu_key,
    ifNull(pb.inner_carrier_hu_formed_id, '') AS inner_carrier_hu_formed_id,
    ifNull(pb.inner_carrier_hu_id, '') AS inner_carrier_hu_id,
    ifNull(pb.inner_carrier_hu_code, '') AS inner_carrier_hu_code,
    ifNull(pb.inner_carrier_hu_kind, '') AS inner_carrier_hu_kind,
    ifNull(pb.induction_id, '') AS induction_id,
    ifNull(pb.inner_carrier_hu_force_closed, false) AS inner_carrier_hu_force_closed,
    ifNull(pb.mhe_id, '') AS mhe_id,
    ifNull(pb.pick_attrs, '') AS pick_attrs,
    ifNull(pb.iloc, '') AS iloc,
    ifNull(pb.dest_iloc, '') AS dest_iloc,

    -- Additional Drop Items columns
    ifNull(pb.source_bin_id, '') AS source_bin_id,
    ifNull(pb.source_bin_hu_id, '') AS source_bin_hu_id,
    ifNull(pb.drop_bin_id, '') AS drop_bin_id,
    ifNull(pb.drop_bin_hu_id, '') AS drop_bin_hu_id,
    ifNull(pb.drop_created_at, toDateTime64('1970-01-01 00:00:00', 3)) AS drop_created_at,
    ifNull(pb.drop_deactivated_at, toDateTime64('1970-01-01 00:00:00', 3)) AS drop_deactivated_at,
    ifNull(pb.drop_deactivated_by, '') AS drop_deactivated_by,
    ifNull(pb.dropped_by_worker_id, '') AS dropped_by_worker_id,
    ifNull(pb.dest_hu_id, '') AS dest_hu_id,
    ifNull(pb.source_bucket, '') AS source_bucket,
    ifNull(pb.original_destination_bin_id, '') AS original_destination_bin_id,
    ifNull(pb.drop_lm_trip_id, '') AS drop_lm_trip_id,
    ifNull(pb.processed_for_pick_at, toDateTime64('1970-01-01 00:00:00', 3)) AS processed_for_pick_at,
    ifNull(pb.drop_provisional_item_id, '') AS drop_provisional_item_id,
    ifNull(pb.drop_input_dest_hu_id, '') AS drop_input_dest_hu_id,
    ifNull(pb.drop_leg_index, 0) AS drop_leg_index,
    ifNull(pb.drop_last_leg, false) AS drop_last_leg,
    ifNull(pb.drop_input_dest_bin_id, '') AS drop_input_dest_bin_id,
    ifNull(pb.drop_induction_id, '') AS drop_induction_id,
    ifNull(pb.drop_attrs, '') AS drop_attrs,
    ifNull(pb.drop_mhe_id, '') AS drop_mhe_id,
    ifNull(pb.drop_iloc, '') AS drop_iloc,
    ifNull(pb.source_iloc, '') AS source_iloc,

    -- Mapping fields
    ifNull(pb.mapping_id, '') AS mapping_id,
    ifNull(pb.mapping_created_at, toDateTime64('1970-01-01 00:00:00', 3)) AS mapping_created_at,

    -- Worker enrichment (picked_by) — wms_workers has no Nullable columns
    w.code AS worker_code,
    w.name AS worker_name,
    w.phone AS worker_phone,
    w.supervisor AS worker_supervisor,
    w.active AS worker_active,

    -- Handling Unit enrichment (for dropped_inner_hu_id) — wms_handling_units has no Nullable columns
    hu.code AS dropped_hu_code,
    hu.kindId AS dropped_hu_kind_id,
    hu.sessionId AS dropped_hu_session_id,
    hu.taskId AS dropped_hu_task_id,
    hu.storageId AS dropped_hu_storage_id,
    hu.outerHuId AS dropped_hu_outer_hu_id,
    hu.state AS dropped_hu_state,
    hu.attrs AS dropped_hu_attrs,
    hu.lockTaskId AS dropped_hu_lock_task_id,
    hu.effectiveStorageId AS dropped_hu_effective_storage_id,
    hu.createdAt AS dropped_hu_created_at,
    hu.updatedAt AS dropped_hu_updated_at,

    -- SKU enrichment (from picked_sku_id only) - overrides over master
    sm.category AS sku_category,
    sm.product AS sku_product,
    sm.product_id AS sku_product_id,
    sm.category_group AS sku_category_group,
    sm.sub_brand AS sku_sub_brand,
    sm.brand AS sku_brand,
    sm.code AS sku_code,
    if(so.name != '', so.name, sm.name) AS sku_name,
    if(so.short_description != '', so.short_description, sm.short_description) AS sku_short_description,
    if(so.description != '', so.description, sm.description) AS sku_description,
    if(so.fulfillment_type != '', so.fulfillment_type, sm.fulfillment_type) AS sku_fulfillment_type,
    if(so.inventory_type != '', so.inventory_type, sm.inventory_type) AS sku_inventory_type,
    if(so.shelf_life != 0, so.shelf_life, sm.shelf_life) AS sku_shelf_life,
    if(so.tag1 != '', so.tag1, sm.tag1) AS sku_tag1,
    if(so.tag2 != '', so.tag2, sm.tag2) AS sku_tag2,
    if(so.tag3 != '', so.tag3, sm.tag3) AS sku_tag3,
    if(so.tag4 != '', so.tag4, sm.tag4) AS sku_tag4,
    if(so.tag5 != '', so.tag5, sm.tag5) AS sku_tag5,
    if(so.handling_unit_type != '', so.handling_unit_type, sm.handling_unit_type) AS sku_handling_unit_type,
    if(so.cases_per_layer != 0, so.cases_per_layer, sm.cases_per_layer) AS sku_cases_per_layer,
    if(so.layers != 0, so.layers, sm.layers) AS sku_layers,
    if(so.l0_units != 0, so.l0_units, sm.l0_units) AS sku_l0_units,
    if(so.l1_units != 0, so.l1_units, sm.l1_units) AS sku_l1_units,
    if(so.l2_units != 0, so.l2_units, sm.l2_units) AS sku_l2_units,
    if(so.l3_units != 0, so.l3_units, sm.l3_units) AS sku_l3_units,
    if(so.l0_name != '', so.l0_name, sm.l0_name) AS sku_l0_name,
    if(so.l0_weight != 0, so.l0_weight, sm.l0_weight) AS sku_l0_weight,
    if(so.l0_volume != 0, so.l0_volume, sm.l0_volume) AS sku_l0_volume,
    if(so.l0_package_type != '', so.l0_package_type, sm.l0_package_type) AS sku_l0_package_type,
    if(so.l0_length != 0, so.l0_length, sm.l0_length) AS sku_l0_length,
    if(so.l0_width != 0, so.l0_width, sm.l0_width) AS sku_l0_width,
    if(so.l0_height != 0, so.l0_height, sm.l0_height) AS sku_l0_height,
    if(so.l0_itf_code != '', so.l0_itf_code, sm.l0_itf_code) AS sku_l0_itf_code,

    -- SKU UOM L1 details
    if(so.l1_name != '', so.l1_name, sm.l1_name) AS sku_l1_name,
    if(so.l1_weight != 0, so.l1_weight, sm.l1_weight) AS sku_l1_weight,
    if(so.l1_volume != 0, so.l1_volume, sm.l1_volume) AS sku_l1_volume,
    if(so.l1_package_type != '', so.l1_package_type, sm.l1_package_type) AS sku_l1_package_type,
    if(so.l1_length != 0, so.l1_length, sm.l1_length) AS sku_l1_length,
    if(so.l1_width != 0, so.l1_width, sm.l1_width) AS sku_l1_width,
    if(so.l1_height != 0, so.l1_height, sm.l1_height) AS sku_l1_height,
    if(so.l1_itf_code != '', so.l1_itf_code, sm.l1_itf_code) AS sku_l1_itf_code,

    -- SKU UOM L2 details
    if(so.l2_name != '', so.l2_name, sm.l2_name) AS sku_l2_name,
    if(so.l2_weight != 0, so.l2_weight, sm.l2_weight) AS sku_l2_weight,
    if(so.l2_volume != 0, so.l2_volume, sm.l2_volume) AS sku_l2_volume,
    if(so.l2_package_type != '', so.l2_package_type, sm.l2_package_type) AS sku_l2_package_type,
    if(so.l2_length != 0, so.l2_length, sm.l2_length) AS sku_l2_length,
    if(so.l2_width != 0, so.l2_width, sm.l2_width) AS sku_l2_width,
    if(so.l2_height != 0, so.l2_height, sm.l2_height) AS sku_l2_height,
    if(so.l2_itf_code != '', so.l2_itf_code, sm.l2_itf_code) AS sku_l2_itf_code,

    -- SKU UOM L3 details
    if(so.l3_name != '', so.l3_name, sm.l3_name) AS sku_l3_name,
    if(so.l3_weight != 0, so.l3_weight, sm.l3_weight) AS sku_l3_weight,
    if(so.l3_volume != 0, so.l3_volume, sm.l3_volume) AS sku_l3_volume,
    if(so.l3_package_type != '', so.l3_package_type, sm.l3_package_type) AS sku_l3_package_type,
    if(so.l3_length != 0, so.l3_length, sm.l3_length) AS sku_l3_length,
    if(so.l3_width != 0, so.l3_width, sm.l3_width) AS sku_l3_width,
    if(so.l3_height != 0, so.l3_height, sm.l3_height) AS sku_l3_height,
    if(so.l3_itf_code != '', so.l3_itf_code, sm.l3_itf_code) AS sku_l3_itf_code,

    -- Additional SKU fields
    if(so.avg_l0_per_put != 0, so.avg_l0_per_put, sm.avg_l0_per_put) AS sku_avg_l0_per_put,
    -- Use isValidJSON + JSONType check to handle empty string, 'null', '[]', or any invalid JSON
    JSONExtractRaw(JSONMergePatch(
        if(isValidJSON(sm.classifications) AND JSONType(sm.classifications) = 'Object', sm.classifications, '{}'),
        if(isValidJSON(so.classifications) AND JSONType(so.classifications) = 'Object', so.classifications, '{}')
    )) AS sku_combined_classification,

    -- Event time from staging
    pb.event_time AS event_time
FROM wms_pick_drop_staging AS pb
-- Worker enrichment
LEFT JOIN wms_workers AS w ON pb.picked_by_worker_id = w.id
-- Handling Unit enrichment
LEFT JOIN wms_handling_units AS hu ON pb.dropped_inner_hu_id = hu.id
-- SKU Master data
LEFT JOIN encarta_skus_master AS sm ON pb.picked_sku_id = sm.id
-- SKU Overrides for specific warehouse (unique on sku_id + node_id)
LEFT JOIN encarta_skus_overrides AS so ON pb.picked_sku_id = so.sku_id AND pb.wh_id = so.node_id AND so.active = true;
