-- ClickHouse table for WMS PD Pick Item
-- Dimension table for PD Pick Item information
-- Source: samadhan_prod.wms.public.pd_pick_item

CREATE TABLE IF NOT EXISTS wms_pd_pick_item
(
    id String DEFAULT '',
    whId Int64 DEFAULT 0,
    sessionId String DEFAULT '',
    taskId String DEFAULT '',
    binId String DEFAULT '',
    binHUId String DEFAULT '',
    binCode String DEFAULT '',
    skuId String DEFAULT '',
    batch String DEFAULT '',
    uom String DEFAULT '',
    bucket String DEFAULT '',
    overallQty Int32 DEFAULT 0,
    qty Int32 DEFAULT 0,
    huId String DEFAULT '',
    huCode String DEFAULT '',
    destinationBinId String DEFAULT '',
    destinationBinHUId String DEFAULT '',
    destinationBinCode String DEFAULT '',   
    createdAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    deactivatedAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    deactivatedBy String DEFAULT '',
    pickedQty Int32 DEFAULT 0,
    pickedAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    pickedBy String DEFAULT '',
    movedAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    movedBy String DEFAULT '',
    processedAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    huEqUOM String DEFAULT '',
    hasInnerHUs bool DEFAULT true,
    innerHUEqUOM String DEFAULT '',
    binAssignedAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    scanSourceHUKind String DEFAULT 'NONE',
    pickSourceHUKind String DEFAULT 'NONE',
    carrierHUKind String DEFAULT 'NONE',
    scannedSourceHUId String DEFAULT '',
    scannedSourceHUCode String DEFAULT '',
    pickedSourceHUId String DEFAULT '',
    pickedSourceHUCode String DEFAULT '',
    carrierHUId String DEFAULT '',
    carrierHUCode String DEFAULT '',
    huKind String DEFAULT 'NONE',
    sourceHUEqUOM String DEFAULT '',
    updatedAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    eligibleDropLocations String DEFAULT '{}',
    parentItemId String DEFAULT '',
    oldBatch String DEFAULT '',
    destBucket String DEFAULT '',
    originalSourceBinId String DEFAULT '',
    originalSourceBinCode String DEFAULT '',
    lmTripId String DEFAULT '',
    innerHUId String DEFAULT '',
    innerHUCode String DEFAULT '',
    innerHUKindId String DEFAULT '',
    innerHUKindCode String DEFAULT '',
    quantBucket String DEFAULT '',
    autoCompleted bool DEFAULT false,
    pickHU bool DEFAULT true,
    shortAllocationReason String DEFAULT '',
    inputSourceBinId String DEFAULT '',
    pdPreviousTaskId String DEFAULT '',
    provisionalItemId String DEFAULT '',
    inputDestHUId String DEFAULT '',
    kind String DEFAULT 'WP',
    tpAssignedAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    legIndex Int32 DEFAULT 0,
    lastLeg bool DEFAULT false,
    epAssignedAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    carrierHUFormedId String DEFAULT '',
    huIndex Int32 DEFAULT 0,
    sequence Int32 DEFAULT 100,
    carrierHUForceClosed bool DEFAULT false,
    inputDestBinId String DEFAULT '',
    innerHUIndex Int32 DEFAULT 0,
    innerCarrierHUKey String DEFAULT '',
    innerCarrierHUFormedId String DEFAULT '',
    innerCarrierHUId String DEFAULT '',
    innerCarrierHUCode String DEFAULT '',
    innerCarrierHUKind String DEFAULT 'NONE',
    inductionId String DEFAULT '',
    innerCarrierHUForceClosed bool DEFAULT false,
    mheId String DEFAULT '',
    attrs String DEFAULT '{}',
    iloc String DEFAULT '',
    destIloc String DEFAULT '',
    dropHUIndex Int32 DEFAULT 0,
    dropSequence Int32 DEFAULT 0
)
ENGINE = ReplacingMergeTree(updatedAt)
PARTITION BY toYYYYMM(createdAt)
ORDER BY (id)
SETTINGS index_granularity = 8192;