-- ClickHouse table for WMS PD Drop Item
-- Dimension table for PD Drop Item information
-- Source: samadhan_prod.wms.public.pd_drop_item

CREATE TABLE IF NOT EXISTS wms_pd_drop_item
(
    id String DEFAULT '',
    whId Int64 DEFAULT 0,
    sessionId String DEFAULT '',
    taskId String DEFAULT '',
    sourceBinId String DEFAULT '',
    sourceBinHUId String DEFAULT '',
    sourceBinCode String DEFAULT '',
    skuId String DEFAULT '',
    batch String DEFAULT '',
    uom String DEFAULT '',
    bucket String DEFAULT '',
    qty Int32 DEFAULT 0,
    huId String DEFAULT '',
    huCode String DEFAULT '',
    binId String DEFAULT '',
    binHUId String DEFAULT '',
    binCode String DEFAULT '',
    createdAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    deactivatedAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    deactivatedBy String DEFAULT '',
    droppedQty Int32 DEFAULT 0,
    droppedAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    droppedBy String DEFAULT '',
    updatedAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    dropHUInBin bool DEFAULT true,
    scanDestHU bool DEFAULT false,
    allowHUBreak bool DEFAULT false,
    hasInnerHUs bool DEFAULT false,
    scanInnerHUs bool DEFAULT false,
    huEqUOM String DEFAULT '',
    destHUId String DEFAULT '',
    destHUCode String DEFAULT '',
    droppedInnerHUId String DEFAULT '',
    innerHUEqUOM String DEFAULT '',
    binAssignedAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    dropUOM String DEFAULT '',
    eligibleDropLocations String DEFAULT '{}',
    parentItemId String DEFAULT '',
    huBroken bool DEFAULT false,
    pickedBy String DEFAULT '',
    sourceBucket String DEFAULT '',
    originalDestinationBinId String DEFAULT '',
    originalDestinationBinCode String DEFAULT '',
    lmTripId String DEFAULT '',
    processedForLoadingAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    quantBucket String DEFAULT '',
    innerHUId String DEFAULT '',
    innerHUCode String DEFAULT '',
    innerHUKindId String DEFAULT '',
    innerHUKindCode String DEFAULT '',
    dropInnerHU bool DEFAULT true,
    allowInnerHUBreak bool DEFAULT false,
    innerHUBroken bool DEFAULT false,
    autoCompleted bool DEFAULT false,
    processedForPickAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    quantSlottingForHUs bool DEFAULT false,
    pdPreviousTaskId String DEFAULT '',
    processedOnDropAt DateTime64(3) DEFAULT toDateTime64('1970-01-01 00:00:00', 3),
    provisionalItemId String DEFAULT '',
    allowHUBreakV2 bool DEFAULT true,
    inputDestHUId String DEFAULT '',
    legIndex Int32 DEFAULT 0,
    lastLeg bool DEFAULT false,
    inputDestBinId String DEFAULT '',
    inductionId String DEFAULT '',
    attrs String DEFAULT '{}',
    mheId String DEFAULT '',
    iloc String DEFAULT '',
    sourceIloc String DEFAULT '',
    huIndex Int32 DEFAULT 0,
    sequence Int32 DEFAULT 0
)
ENGINE = ReplacingMergeTree(updatedAt)
PARTITION BY toYYYYMM(createdAt)
ORDER BY (id)
SETTINGS index_granularity = 8192;