-- ClickHouse Materialized View for WMS Inventory Hourly Position Aggregation
-- Automatically processes new events from wms_inventory_events_enriched
-- Aggregates inventory movements hourly for efficient time-series analysis

CREATE MATERIALIZED VIEW IF NOT EXISTS wms_inventory_hourly_position_mv
TO wms_inventory_hourly_position
AS
SELECT
    toStartOfHour(hu_event_timestamp) as hour_window,
    wh_id,
    
    -- Core inventory identifiers (GROUP BY keys)
    hu_id,
    hu_code,
    sku_id,
    uom,
    bucket,
    batch,
    price,
    inclusion_status,
    locked_by_task_id,
    lock_mode,
    
    -- Aggregated metrics
    sum(qty_added) as hourly_qty_change,
    count() as event_count,
    
    -- Event identifiers
    argMax(hu_event_id, hu_event_timestamp) as hu_event_id,
    argMax(quant_event_id, hu_event_timestamp) as quant_event_id,
    min(hu_event_timestamp) as first_event_time,
    max(hu_event_timestamp) as last_event_time,
    
    -- Handling unit event fields
    anyLast(hu_event_seq) as hu_event_seq,
    anyLast(hu_event_type) as hu_event_type,
    anyLast(hu_event_payload) as hu_event_payload,
    anyLast(hu_event_attrs) as hu_event_attrs,
    anyLast(session_id) as session_id,
    anyLast(task_id) as task_id,
    anyLast(correlation_id) as correlation_id,
    anyLast(storage_id) as storage_id,
    anyLast(outer_hu_id) as outer_hu_id,
    anyLast(effective_storage_id) as effective_storage_id,
    anyLast(quant_iloc) as quant_iloc,
    
    -- Handling unit attributes
    anyLast(hu_state) as hu_state,
    anyLast(hu_attrs) as hu_attrs,
    anyLast(hu_created_at) as hu_created_at,
    anyLast(hu_updated_at) as hu_updated_at,
    anyLast(hu_lock_task_id) as hu_lock_task_id,
    anyLast(hu_effective_storage_id) as hu_effective_storage_id,
    
    -- Handling unit kind fields
    anyLast(hu_kind_id) as hu_kind_id,
    anyLast(hu_kind_code) as hu_kind_code,
    anyLast(hu_kind_name) as hu_kind_name,
    anyLast(hu_kind_attrs) as hu_kind_attrs,
    anyLast(hu_kind_max_volume) as hu_kind_max_volume,
    anyLast(hu_kind_max_weight) as hu_kind_max_weight,
    anyLast(hu_kind_usage_type) as hu_kind_usage_type,
    anyLast(hu_kind_abbr) as hu_kind_abbr,
    anyLast(hu_kind_length) as hu_kind_length,
    anyLast(hu_kind_breadth) as hu_kind_breadth,
    anyLast(hu_kind_height) as hu_kind_height,
    anyLast(hu_kind_weight) as hu_kind_weight,
    
    -- Storage bin fields (from effective_storage enrichment)
    anyLast(storage_bin_code) as storage_bin_code,
    anyLast(storage_bin_description) as storage_bin_description,
    anyLast(storage_bin_status) as storage_bin_status,
    anyLast(storage_bin_hu_id) as storage_bin_hu_id,
    anyLast(storage_multi_sku) as storage_multi_sku,
    anyLast(storage_multi_batch) as storage_multi_batch,
    anyLast(storage_picking_position) as storage_picking_position,
    anyLast(storage_putaway_position) as storage_putaway_position,
    anyLast(storage_rank) as storage_rank,
    anyLast(storage_aisle) as storage_aisle,
    anyLast(storage_bay) as storage_bay,
    anyLast(storage_level) as storage_level,
    anyLast(storage_position) as storage_position,
    anyLast(storage_depth) as storage_depth,
    anyLast(storage_max_sku_count) as storage_max_sku_count,
    anyLast(storage_max_sku_batch_count) as storage_max_sku_batch_count,
    anyLast(storage_bin_type_id) as storage_bin_type_id,
    anyLast(storage_bin_type_code) as storage_bin_type_code,
    anyLast(storage_bin_type_description) as storage_bin_type_description,
    anyLast(storage_max_volume_in_cc) as storage_max_volume_in_cc,
    anyLast(storage_max_weight_in_kg) as storage_max_weight_in_kg,
    anyLast(storage_pallet_capacity) as storage_pallet_capacity,
    anyLast(storage_hu_type) as storage_hu_type,
    anyLast(storage_auxiliary_bin) as storage_auxiliary_bin,
    anyLast(storage_hu_multi_sku) as storage_hu_multi_sku,
    anyLast(storage_hu_multi_batch) as storage_hu_multi_batch,
    anyLast(storage_use_derived_pallet_best_fit) as storage_use_derived_pallet_best_fit,
    anyLast(storage_only_full_pallet) as storage_only_full_pallet,
    anyLast(storage_zone_id) as storage_zone_id,
    anyLast(storage_zone_code) as storage_zone_code,
    anyLast(storage_zone_description) as storage_zone_description,
    anyLast(storage_zone_face) as storage_zone_face,
    anyLast(storage_peripheral) as storage_peripheral,
    anyLast(storage_surveillance_config) as storage_surveillance_config,
    anyLast(storage_area_id) as storage_area_id,
    anyLast(storage_area_code) as storage_area_code,
    anyLast(storage_area_description) as storage_area_description,
    anyLast(storage_area_type) as storage_area_type,
    anyLast(storage_rolling_days) as storage_rolling_days,
    anyLast(storage_x1) as storage_x1,
    anyLast(storage_x2) as storage_x2,
    anyLast(storage_y1) as storage_y1,
    anyLast(storage_y2) as storage_y2,
    anyLast(storage_attrs) as storage_attrs,
    anyLast(storage_bin_mapping) as storage_bin_mapping,
    
    -- SKU fields
    anyLast(sku_code) as sku_code,
    anyLast(sku_name) as sku_name,
    anyLast(sku_short_description) as sku_short_description,
    anyLast(sku_description) as sku_description,
    anyLast(sku_category) as sku_category,
    anyLast(sku_category_group) as sku_category_group,
    anyLast(sku_product) as sku_product,
    anyLast(sku_product_id) as sku_product_id,
    anyLast(sku_brand) as sku_brand,
    anyLast(sku_sub_brand) as sku_sub_brand,
    anyLast(sku_fulfillment_type) as sku_fulfillment_type,
    anyLast(sku_inventory_type) as sku_inventory_type,
    anyLast(sku_shelf_life) as sku_shelf_life,
    anyLast(sku_handling_unit_type) as sku_handling_unit_type,
    anyLast(sku_principal_id) as sku_principal_id,
    
    -- SKU identifiers and tags
    anyLast(sku_identifier1) as sku_identifier1,
    anyLast(sku_identifier2) as sku_identifier2,
    anyLast(sku_tag1) as sku_tag1,
    anyLast(sku_tag2) as sku_tag2,
    anyLast(sku_tag3) as sku_tag3,
    anyLast(sku_tag4) as sku_tag4,
    anyLast(sku_tag5) as sku_tag5,
    anyLast(sku_tag6) as sku_tag6,
    anyLast(sku_tag7) as sku_tag7,
    anyLast(sku_tag8) as sku_tag8,
    anyLast(sku_tag9) as sku_tag9,
    anyLast(sku_tag10) as sku_tag10,
    
    -- SKU UOM hierarchy L0
    anyLast(sku_l0_name) as sku_l0_name,
    anyLast(sku_l0_units) as sku_l0_units,
    anyLast(sku_l0_weight) as sku_l0_weight,
    anyLast(sku_l0_volume) as sku_l0_volume,
    anyLast(sku_l0_package_type) as sku_l0_package_type,
    anyLast(sku_l0_length) as sku_l0_length,
    anyLast(sku_l0_width) as sku_l0_width,
    anyLast(sku_l0_height) as sku_l0_height,
    anyLast(sku_l0_itf_code) as sku_l0_itf_code,
    
    -- SKU UOM hierarchy L1
    anyLast(sku_l1_name) as sku_l1_name,
    anyLast(sku_l1_units) as sku_l1_units,
    anyLast(sku_l1_weight) as sku_l1_weight,
    anyLast(sku_l1_volume) as sku_l1_volume,
    anyLast(sku_l1_package_type) as sku_l1_package_type,
    anyLast(sku_l1_length) as sku_l1_length,
    anyLast(sku_l1_width) as sku_l1_width,
    anyLast(sku_l1_height) as sku_l1_height,
    anyLast(sku_l1_itf_code) as sku_l1_itf_code,
    
    -- SKU UOM hierarchy L2
    anyLast(sku_l2_name) as sku_l2_name,
    anyLast(sku_l2_units) as sku_l2_units,
    anyLast(sku_l2_weight) as sku_l2_weight,
    anyLast(sku_l2_volume) as sku_l2_volume,
    anyLast(sku_l2_package_type) as sku_l2_package_type,
    anyLast(sku_l2_length) as sku_l2_length,
    anyLast(sku_l2_width) as sku_l2_width,
    anyLast(sku_l2_height) as sku_l2_height,
    anyLast(sku_l2_itf_code) as sku_l2_itf_code,
    
    -- SKU UOM hierarchy L3
    anyLast(sku_l3_name) as sku_l3_name,
    anyLast(sku_l3_units) as sku_l3_units,
    anyLast(sku_l3_weight) as sku_l3_weight,
    anyLast(sku_l3_volume) as sku_l3_volume,
    anyLast(sku_l3_package_type) as sku_l3_package_type,
    anyLast(sku_l3_length) as sku_l3_length,
    anyLast(sku_l3_width) as sku_l3_width,
    anyLast(sku_l3_height) as sku_l3_height,
    anyLast(sku_l3_itf_code) as sku_l3_itf_code,
    
    -- SKU packaging config
    anyLast(sku_cases_per_layer) as sku_cases_per_layer,
    anyLast(sku_layers) as sku_layers,
    anyLast(sku_avg_l0_per_put) as sku_avg_l0_per_put,
    anyLast(sku_combined_classification) as sku_combined_classification,
    
    -- Outer HU fields
    anyLast(outer_hu_code) as outer_hu_code,
    anyLast(outer_hu_kind_id) as outer_hu_kind_id,
    anyLast(outer_hu_session_id) as outer_hu_session_id,
    anyLast(outer_hu_task_id) as outer_hu_task_id,
    anyLast(outer_hu_storage_id) as outer_hu_storage_id,
    anyLast(outer_hu_outer_hu_id) as outer_hu_outer_hu_id,
    anyLast(outer_hu_state) as outer_hu_state,
    anyLast(outer_hu_attrs) as outer_hu_attrs,
    anyLast(outer_hu_lock_task_id) as outer_hu_lock_task_id,
    
    -- Outer HU kind fields
    anyLast(outer_hu_kind_code) as outer_hu_kind_code,
    anyLast(outer_hu_kind_name) as outer_hu_kind_name,
    anyLast(outer_hu_kind_attrs) as outer_hu_kind_attrs,
    anyLast(outer_hu_kind_max_volume) as outer_hu_kind_max_volume,
    anyLast(outer_hu_kind_max_weight) as outer_hu_kind_max_weight,
    anyLast(outer_hu_kind_usage_type) as outer_hu_kind_usage_type,
    anyLast(outer_hu_kind_abbr) as outer_hu_kind_abbr,
    anyLast(outer_hu_kind_length) as outer_hu_kind_length,
    anyLast(outer_hu_kind_breadth) as outer_hu_kind_breadth,
    anyLast(outer_hu_kind_height) as outer_hu_kind_height,
    anyLast(outer_hu_kind_weight) as outer_hu_kind_weight
FROM wms_inventory_events_enriched
GROUP BY
    toStartOfHour(hu_event_timestamp),
    wh_id,
    hu_id,
    hu_code,
    sku_id,
    uom,
    bucket,
    batch,
    price,
    inclusion_status,
    locked_by_task_id,
    lock_mode
-- Only keep rows with quantity changes
HAVING sum(qty_added) != 0;