CREATE TABLE wms_vehicle_event (
    id VARCHAR(36) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT "1970-01-01 00:00:00",
    whId BIGINT NOT NULL,
    vehicleId STRING NOT NULL,
    vehicleNo STRING NOT NULL,
    vehicleType STRING,
    gatingEnabled BOOLEAN NOT NULL,
    attrs JSON,
    status STRING NOT NULL,
    sessionId VARCHAR(36),
    sessionKind STRING NOT NULL,
    gateReportedAt DATETIME,
    gateInAt DATETIME,
    gateOutAt DATETIME,
    dockdoorId VARCHAR(36),
    dockdoorCode STRING,
    dockdoorQueue INT,
    dockInAt DATETIME,
    dockOutAt DATETIME,
    updatedAt DATETIME NOT NULL DEFAULT "1970-01-01 00:00:00",
    active BOOLEAN NOT NULL DEFAULT "true",
    parkingSlotId VARCHAR(36),
    parkingSlotAssignedAt DATETIME,
    gatePassCode STRING,
    undockedAt DATETIME,
    transporterCode STRING,
    originalVehicle STRING,
    shipmentTypes JSON,
    isSealCaptureSuccessful BOOLEAN,
    sealCapturedAt DATETIME,
    sealCaptureImages JSON,
    sealCaptureRemarks STRING,
    driverName STRING,
    driverNumber STRING,
    isDockingRejected BOOLEAN NOT NULL DEFAULT "false",
    vehicleRejectedAt DATETIME,
    dockingRejectedBy BIGINT,
    dockingRejectionRemark STRING,
    dockingRejectionImages JSON,
    fleetType STRING,
    loadType STRING NOT NULL DEFAULT 'NON_PALLETIZED',
    entryWeight DOUBLE,
    exitWeight DOUBLE,
    entryTemp DOUBLE,
    exitTemp DOUBLE,
    dockRejectedByApp STRING,
    oldDriverName STRING,
    oldDriverNumber STRING,
    commonQueue INT,
    gatingQueue INT,
    sealCapturedBy BIGINT,
    sealCapturedByApp STRING,
    lrNumber STRING,
    certificateVerificationStatus STRING,
    certificateVerificationReason STRING,
    driverSafetyTestResultId VARCHAR(36),
    documentCollectionMode STRING,
    documentCollectedAt DATETIME,
    processingStartedAt DATETIME,
    processingEndedAt DATETIME,
    manualTrips JSON,
    manualTripsUpdatedAt DATETIME,
    firstDockInAt DATETIME,
    otpVerified BOOLEAN NOT NULL DEFAULT "false",
    discrepancyCaptured BOOLEAN NOT NULL DEFAULT "false",
    iloc STRING NOT NULL DEFAULT '',
    stagingStartedAt DATETIME,
    stagingEndedAt DATETIME,
    dockAssignedAt DATETIME,
    dockEligibleAt DATETIME,
    dockHistory JSON
)
ENGINE=OLAP
PRIMARY KEY(id, createdAt)
PARTITION BY date_trunc('DAY', createdAt)
DISTRIBUTED BY HASH(id) BUCKETS 16
ORDER BY (id)
PROPERTIES (
    "compression" = "LZ4",
    "enable_persistent_index" = "true",
    "fast_schema_evolution" = "true",
    "replicated_storage" = "true",
    "replication_num" = "2"
);