CREATE TABLE wms_pd_provisional_item (
    id VARCHAR(36) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT "1970-01-01 00:00:00",
    whId BIGINT NOT NULL,
    sessionId VARCHAR(36) NOT NULL,
    taskKind STRING NOT NULL,
    taskSubKind STRING,
    taskKey STRING NOT NULL,
    huId VARCHAR(36) NOT NULL,
    huCode STRING NOT NULL,
    skuId VARCHAR(36) NOT NULL,
    batch STRING NOT NULL DEFAULT '',
    uom STRING NOT NULL DEFAULT '',
    bucket STRING NOT NULL DEFAULT '',
    qty INT NOT NULL,
    updatedAt DATETIME NOT NULL DEFAULT "1970-01-01 00:00:00",
    inputSourceBinId VARCHAR(36),
    sourceBinId VARCHAR(36),
    sourceBinCode STRING,
    sourceBinHUId VARCHAR(36),
    sourceBinAssignedAt DATETIME,
    destBinId VARCHAR(36),
    destBinCode STRING,
    destBinHUId VARCHAR(36),
    destBinAssignedAt DATETIME,
    huEqUOM STRING,
    priority INT NOT NULL DEFAULT "0",
    pathZoneIds STRING,
    pathZoneCodes STRING,
    parentItemId VARCHAR(36),
    carrierHUFormedId VARCHAR(36),
    destZoneId VARCHAR(36),
    preferredDestBinTypeId VARCHAR(36),
    pathAssignedAt DATETIME,
    pickHU BOOLEAN NOT NULL DEFAULT "false",
    inputDestBinId VARCHAR(36),
    inputDestHUId VARCHAR(36),
    eligibleDropLocations JSON,
    scanSourceHUKind STRING NOT NULL DEFAULT 'NONE',
    pickSourceHUKind STRING NOT NULL DEFAULT 'NONE',
    carrierHUKind STRING NOT NULL DEFAULT 'NONE',
    categoryGroup STRING,
    taint STRING,
    destBucket STRING,
    innerCarrierHUKey STRING,
    innerCarrierHUFormedId VARCHAR(36),
    innerCarrierHUKindId VARCHAR(36),
    innerCarrierHUKind STRING NOT NULL DEFAULT 'NONE',
    innerHUIndex INT NOT NULL DEFAULT "0",
    deactivatedAt DATETIME,
    iloc STRING NOT NULL DEFAULT '',
    destIloc STRING,
    state STRING NOT NULL DEFAULT 'INITIATED',
    attrs JSON
)
ENGINE=OLAP
PRIMARY KEY(id, createdAt)
PARTITION BY date_trunc('WEEK', createdAt)
DISTRIBUTED BY HASH(id) BUCKETS 2
ORDER BY (id)
PROPERTIES (
    "compression" = "LZ4",
    "enable_persistent_index" = "true",
    "fast_schema_evolution" = "true",
    "replicated_storage" = "true",
    "replication_num" = "2"
);
