CREATE TABLE wms_inventory (
    id VARCHAR(36) NOT NULL,
    whId BIGINT NOT NULL,
    huId VARCHAR(36) NOT NULL,
    huCode STRING NOT NULL,
    huKind STRING NOT NULL,
    huWeight DOUBLE,
    huOnHold BOOLEAN NOT NULL DEFAULT "false",
    huRendered BOOLEAN NOT NULL DEFAULT "false",
    huLockTaskId VARCHAR(36),
    isBinHu BOOLEAN NOT NULL DEFAULT "false",
    areaType STRING,
    areaCode STRING,
    zoneFace STRING,
    zoneCode STRING,
    binType STRING,
    binCode STRING,
    binStatus STRING,
    binCapacity INT,
    outerHUCode STRING,
    outerHUKind STRING,
    skuId VARCHAR(36) NOT NULL,
    skuCode STRING NOT NULL,
    skuName STRING NOT NULL,
    skuInventoryType STRING,
    productCode STRING,
    category STRING,
    categoryGroup STRING,
    skuClassification JSON,
    plantCode STRING,
    brand STRING,
    bucket STRING NOT NULL,
    inclusionStatus STRING,
    uom STRING NOT NULL,
    batch STRING NOT NULL DEFAULT '',
    manufactureDate DATE,
    expiryDate DATE,
    price STRING,
    quantLockMode STRING,
    qty INT NOT NULL,
    qtyL0 BIGINT NOT NULL DEFAULT "0",
    huUpdatedAt DATETIME,
    quantUpdatedAt DATETIME,
    updatedAt DATETIME NOT NULL DEFAULT "1970-01-01 00:00:00",
    binTypeId VARCHAR(36),
    usage DOUBLE,
    huCountBlocked BOOLEAN NOT NULL DEFAULT "false",
    iloc STRING NOT NULL DEFAULT '',
    binId VARCHAR(36),
    outerHuLockTaskId VARCHAR(36),
    uomName STRING
)
ENGINE=OLAP
PRIMARY KEY(id)
DISTRIBUTED BY HASH(id)
ORDER BY (id)
PROPERTIES (
    "compression" = "LZ4",
    "enable_persistent_index" = "true",
    "fast_schema_evolution" = "true",
    "replicated_storage" = "true",
    "replication_num" = "2"
);
