apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink
  namespace: flink-studio
  labels:
    app.kubernetes.io/name: flink
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/cloud: azure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-role
  namespace: flink-studio
  labels:
    app.kubernetes.io/name: flink
    app.kubernetes.io/component: role
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-role-binding
  namespace: flink-studio
  labels:
    app.kubernetes.io/name: flink
    app.kubernetes.io/component: rolebinding
subjects:
- kind: ServiceAccount
  name: flink
  namespace: flink-studio
roleRef:
  kind: Role
  name: flink-role
  apiGroup: rbac.authorization.k8s.io
---
# Secret for Azure Storage Account Key
apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
  namespace: flink-studio
  labels:
    app.kubernetes.io/name: flink
    app.kubernetes.io/component: storage-secret
type: Opaque
data:
  # Base64 encoded Azure Storage Account Key
  # Replace with: echo -n "YOUR_STORAGE_ACCOUNT_KEY" | base64
  storage-account-key: "REPLACE_WITH_BASE64_ENCODED_STORAGE_KEY"
