apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-sql-gateway
  namespace: flink-studio
  labels:
    app.kubernetes.io/name: flink-sql-gateway
    app.kubernetes.io/component: sql-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flink-sql-gateway
      app.kubernetes.io/component: sql-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flink-sql-gateway
        app.kubernetes.io/component: sql-gateway
    spec:
      serviceAccountName: flink
      containers:
        - name: flink-sql-gateway
          # Note: Using default Docker Hub Flink image
          # Both GCP and Azure will use the same base image
          # Cloud-specific configurations are handled through environment variables and volumes
          image: flink:2.0.0-scala_2.12-java21
          command: ["/opt/flink/bin/sql-gateway.sh"]
          args:
            [
              "start-foreground",
              "-Dsql-gateway.endpoint.rest.address=0.0.0.0",
              "-Dsql-gateway.endpoint.rest.port=8083",
            ]
          ports:
            - containerPort: 8083
              name: rest-api
          env:
            - name: HADOOP_CONF_DIR
              value: /opt/hadoop/conf
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /opt/flink/gcp/service-account.json
            - name: GOOGLE_CLOUD_PROJECT
              value: sbx-stag
            - name: FLINK_PROPERTIES
              value: |
                jobmanager.rpc.address: flink-session-cluster-rest
                jobmanager.rpc.port: 6123
          volumeMounts:
            - name: gcp-service-account
              mountPath: /opt/flink/gcp
              readOnly: true
            - name: hadoop-config
              mountPath: /opt/hadoop/conf
              readOnly: true
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /v1/info
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /v1/info
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: gcp-service-account
          secret:
            secretName: gcp-service-account-key
        - name: hadoop-config
          configMap:
            name: hadoop-config
---
apiVersion: v1
kind: Service
metadata:
  name: flink-sql-gateway
  namespace: flink-studio
  labels:
    app.kubernetes.io/name: flink-sql-gateway
    app.kubernetes.io/component: sql-gateway
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: rest-api
  selector:
    app.kubernetes.io/name: flink-sql-gateway
    app.kubernetes.io/component: sql-gateway
