apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-sql-gateway
  namespace: flink-studio
  labels:
    app.kubernetes.io/name: flink-sql-gateway
    app.kubernetes.io/component: sql-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: flink-sql-gateway
      app.kubernetes.io/component: sql-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flink-sql-gateway
        app.kubernetes.io/component: sql-gateway
    spec:
      serviceAccountName: flink
      containers:
      - name: flink-sql-gateway
        image: flink:2.0.0-scala_2.12-java21
        command: ["/opt/flink/bin/sql-gateway.sh"]
        args: ["start-foreground"]
        ports:
        - containerPort: 8083
          name: rest-api
        env:
        - name: FLINK_PROPERTIES
          value: |
            jobmanager.rpc.address: flink-session-cluster-rest
            jobmanager.rpc.port: 6123
            rest.port: 8083
            sql-gateway.endpoint.rest.address: 0.0.0.0
            sql-gateway.endpoint.rest.port: 8083
            sql-gateway.session.max-num: 1000
            sql-gateway.session.idle-timeout: 600000
            sql-gateway.session.check-interval: 60000
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /v1/info
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v1/info
            port: 8083
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: flink-sql-gateway
  namespace: flink-studio
  labels:
    app.kubernetes.io/name: flink-sql-gateway
    app.kubernetes.io/component: sql-gateway
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: rest-api
  selector:
    app.kubernetes.io/name: flink-sql-gateway
    app.kubernetes.io/component: sql-gateway
