apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-sql-gateway
  namespace: flink-studio
  labels:
    app.kubernetes.io/name: flink-sql-gateway
    app.kubernetes.io/component: sql-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: flink-sql-gateway
      app.kubernetes.io/component: sql-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flink-sql-gateway
        app.kubernetes.io/component: sql-gateway
    spec:
      serviceAccountName: flink
      containers:
      - name: flink-sql-gateway
        # Note: This image will be updated by the deployment script based on cloud provider
        # GCP: asia-docker.pkg.dev/sbx-ci-cd/private/flink-gke:2.0.0-scala_2.12-java21
        # Azure: sbxstag.azurecr.io/flink-aks:2.0.0-scala_2.12-azure
        image: asia-docker.pkg.dev/sbx-ci-cd/private/flink-gke:2.0.0-scala_2.12-java21
        command: ["/opt/flink/bin/sql-gateway.sh"]
        args: ["start-foreground"]
        ports:
        - containerPort: 8083
          name: rest-api
        env:
        - name: HADOOP_CONF_DIR
          value: /opt/hadoop/conf
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /opt/flink/conf/service-account.json
        - name: GOOGLE_CLOUD_PROJECT
          value: sbx-stag
        - name: FLINK_PROPERTIES
          value: |
            jobmanager.rpc.address: flink-session-cluster-rest
            jobmanager.rpc.port: 6123
            rest.port: 8083
            sql-gateway.endpoint.rest.address: 0.0.0.0
            sql-gateway.endpoint.rest.port: 8083
            sql-gateway.session.max-num: 1000
            sql-gateway.session.idle-timeout: 600000
            sql-gateway.session.check-interval: 60000
        volumeMounts:
        - name: gcp-service-account
          mountPath: /opt/flink/conf
          readOnly: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /v1/info
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /v1/info
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: gcp-service-account
        secret:
          secretName: gcp-service-account-key
---
apiVersion: v1
kind: Service
metadata:
  name: flink-sql-gateway
  namespace: flink-studio
  labels:
    app.kubernetes.io/name: flink-sql-gateway
    app.kubernetes.io/component: sql-gateway
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: rest-api
  selector:
    app.kubernetes.io/name: flink-sql-gateway
    app.kubernetes.io/component: sql-gateway
