CREATE TABLE IF NOT EXISTS oms_allocation_line (
    id String DEFAULT '',
    allocation_id String DEFAULT '',
    allocation_group_id String DEFAULT '',
    `index` Int32 DEFAULT 0,
    partner String DEFAULT '',
    warehouse String DEFAULT '',
    location String DEFAULT '',
    inventory_type String DEFAULT '',
    code String DEFAULT '',
    code1 String DEFAULT '',
    code2 String DEFAULT '',
    customer String DEFAULT '',
    customer_child String DEFAULT '',
    channel String DEFAULT '',
    product String DEFAULT '',
    sku String DEFAULT '',
    batch String DEFAULT '',
    erp_batch String DEFAULT '',
    uom String DEFAULT '',
    cc Int32 DEFAULT 0,
    qty Int32 DEFAULT 0,
    `type` String DEFAULT '',
    mrp Float64 DEFAULT 0.0,
    bss_days Int32 DEFAULT 0,
    shelf_life Int32 DEFAULT 0,
    header_cbu String DEFAULT '',
    promo_cbu_type String DEFAULT '',
    line_id String DEFAULT '',
    created_at DateTime64(6) DEFAULT toDateTime64(0, 6),
    active Bool DEFAULT true,
    promo_ratio Int32 DEFAULT 0,
    node_id String DEFAULT '',
    last_updated_at DateTime64(6) DEFAULT toDateTime64(0, 6)
) ENGINE = ReplacingMergeTree(last_updated_at)
ORDER BY (id)
PARTITION BY toYYYYMM(created_at)
SETTINGS index_granularity = 8192,
         deduplicate_merge_projection_mode = 'drop';