-- Create denormalized table structure
CREATE TABLE `sbx-uat.encarta.public.skus_denormalized` (
    -- SKU fields
    sku_id STRING,
    principal_id BIGINT,
    sku_code STRING,
    sku_name STRING,
    sku_description STRING,
    short_description STRING,
    product_id STRING,
    ingredients STRING,
    shelf_life INT,
    fulfillment_type STRING,
    active_from STRING,
    active_till STRING,
    sku_active BOOLEAN,
    identifier1 STRING,
    identifier2 STRING,
    invoice_life INT,
    avg_l0_per_put INT,
    inventory_type STRING,
    tag1 STRING,
    tag2 STRING,
    tag3 STRING,
    tag4 STRING,
    tag5 STRING,
    tag6 STRING,
    tag7 STRING,
    tag8 STRING,
    tag9 STRING,
    tag10 STRING,
    sku_created_at STRING,
    sku_updated_at STRING,
    layers INT,
    cases_per_layer INT,
    handling_unit_type STRING,
    sku_is_deleted BOOLEAN,
    -- Product fields
    product_code STRING,
    product_name STRING,
    product_description STRING,
    sub_category_id STRING,
    sub_brand_id STRING,
    dangerous BOOLEAN,
    spillable BOOLEAN,
    frozen BOOLEAN,
    vegetarian BOOLEAN,
    dirty BOOLEAN,
    origin_country STRING,
    hsn_code STRING,
    product_active BOOLEAN,
    case_configuration INT,
    min_quantity INT,
    max_quantity INT,
    order_lot INT,
    taint STRING,
    product_text_tag1 STRING,
    product_text_tag2 STRING,
    product_num_tag1 INT,
    product_num_tag2 INT,
    product_is_deleted BOOLEAN,
    -- Sub Category fields
    subcategory_code STRING,
    subcategory_name STRING,
    subcategory_description STRING,
    subcategory_active BOOLEAN,
    category_id STRING,
    -- Category fields
    category_code STRING,
    category_name STRING,
    category_description STRING,
    category_active BOOLEAN,
    category_group_id STRING,
    -- Category Group fields
    category_group_code STRING,
    category_group_name STRING,
    category_group_description STRING,
    business_unit_id STRING,
    category_group_active BOOLEAN,
    -- Sub Brand fields
    subbrand_code STRING,
    subbrand_name STRING,
    subbrand_description STRING,
    subbrand_active BOOLEAN,
    brand_id STRING,
    -- Brand fields
    brand_code STRING,
    brand_name STRING,
    brand_description STRING,
    brand_owner_id STRING,
    brand_active BOOLEAN,
    -- Primary Key
    PRIMARY KEY (sku_id) NOT ENFORCED
) WITH (
    'connector' = 'confluent',
    'value.format' = 'avro-registry'
);
-- Continuously populate the denormalized table
INSERT INTO `sbx-uat.encarta.public.skus_denormalized`
SELECT -- SKU fields
    s.id AS sku_id,
    s.principal_id,
    s.code AS sku_code,
    s.name AS sku_name,
    s.description AS sku_description,
    s.short_description,
    s.product_id,
    s.ingredients,
    s.shelf_life,
    s.fulfillment_type,
    s.active_from,
    s.active_till,
    s.active AS sku_active,
    s.identifier1,
    s.identifier2,
    s.invoice_life,
    s.avg_l0_per_put,
    s.inventory_type,
    s.tag1,
    s.tag2,
    s.tag3,
    s.tag4,
    s.tag5,
    s.tag6,
    s.tag7,
    s.tag8,
    s.tag9,
    s.tag10,
    s.created_at AS sku_created_at,
    s.updated_at AS sku_updated_at,
    s.layers,
    s.cases_per_layer,
    s.handling_unit_type,
    s.is_deleted AS sku_is_deleted,
    -- Product fields
    p.code AS product_code,
    p.name AS product_name,
    p.description AS product_description,
    p.sub_category_id,
    p.sub_brand_id,
    p.dangerous,
    p.spillable,
    p.frozen,
    p.vegetarian,
    p.dirty,
    p.origin_country,
    p.hsn_code,
    p.active AS product_active,
    p.case_configuration,
    p.min_quantity,
    p.max_quantity,
    p.order_lot,
    p.taint,
    p.text_tag1 AS product_text_tag1,
    p.text_tag2 AS product_text_tag2,
    p.num_tag1 AS product_num_tag1,
    p.num_tag2 AS product_num_tag2,
    p.is_deleted AS product_is_deleted,
    -- Sub Category fields
    subcat.code AS subcategory_code,
    subcat.name AS subcategory_name,
    subcat.description AS subcategory_description,
    subcat.active AS subcategory_active,
    subcat.category_id,
    -- Category fields
    cat.code AS category_code,
    cat.name AS category_name,
    cat.description AS category_description,
    cat.active AS category_active,
    cat.category_group_id,
    -- Category Group fields
    cg.code AS category_group_code,
    cg.name AS category_group_name,
    cg.description AS category_group_description,
    cg.business_unit_id,
    cg.active AS category_group_active,
    -- Sub Brand fields
    sb.code AS subbrand_code,
    sb.name AS subbrand_name,
    sb.description AS subbrand_description,
    sb.active AS subbrand_active,
    sb.brand_id,
    -- Brand fields
    b.code AS brand_code,
    b.name AS brand_name,
    b.description AS brand_description,
    b.brand_owner_id,
    b.active AS brand_active
FROM `sbx-uat.encarta.public.skus` s
    LEFT JOIN `sbx-uat.encarta.public.products` p ON s.product_id = p.id
    LEFT JOIN `sbx-uat.encarta.public.sub_categories` subcat ON p.sub_category_id = subcat.id
    LEFT JOIN `sbx-uat.encarta.public.categories` cat ON subcat.category_id = cat.id
    LEFT JOIN `sbx-uat.encarta.public.category_groups` cg ON cat.category_group_id = cg.id
    LEFT JOIN `sbx-uat.encarta.public.sub_brands` sb ON p.sub_brand_id = sb.id
    LEFT JOIN `sbx-uat.encarta.public.brands` b ON sb.brand_id = b.id;