apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-connect
  namespace: kafka
  labels:
    app: cp-connect
  annotations:
      configmap.reloader.stakater.com/reload: token-config
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cp-connect
  template:
    metadata:
      labels:
        app: cp-connect
    spec:
      nodeSelector:
        instance_type: kafka-genral
      tolerations:
        - key: "instance_type"
          operator: "Equal"
          value: "kafka-genral"
          effect: "NoSchedule"
      serviceAccountName: kafka-sa
      containers:
        - name: cp-connect
          image: asia-docker.pkg.dev/sbx-ci-cd/public/devops-replication-kafka-connect:latest
          ports:
            - containerPort: 8083
          resources:
            limits:
              cpu: 4
              memory: 3Gi
            requests:
              cpu: 250m
              memory: 512Mi
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: "bootstrap.sbx-kafka-cluster.asia-south1.managedkafka.sbx-stag.cloud.goog:9092"
            - name: CONNECT_REST_PORT
              value: "8083"
            - name: CONNECT_GROUP_ID
              value: "connect-cluster"
            - name: CONNECT_PRODUCER_CLIENT_ID
              value: "connect-worker-producer"
            - name: CONNECT_PRODUCER_ENABLE_IDEMPOTENCE
              value: "true"
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: "connect-configs"
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: "connect-offsets"
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: "connect-status"
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KAFKA_JVM_PERFORMANCE_OPTS
              value: "-server -XX:+UseG1GC -XX:GCTimeRatio=1
                -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20
                -XX:MaxGCPauseMillis=10000 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent
                -XX:MaxInlineLevel=15 -Djava.awt.headless=true"
            - name: CONNECT_KEY_CONVERTER
              value: "org.apache.kafka.connect.storage.StringConverter"
            - name: CONNECT_VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY
              value: "All"
            - name: ACCESS_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: token-config
                  key: token
            - name: CONNECT_SECURITY_PROTOCOL
              value: "SASL_SSL"
            - name: CONNECT_SASL_MECHANISM
              value: "PLAIN"
            - name: CONNECT_SASL_JAAS_CONFIG
              value:  "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"kafka-sa@sbx-stag.iam.gserviceaccount.com\" password=\"$(ACCESS_TOKEN)\";"
            - name: CONNECT_CONSUMER_SECURITY_PROTOCOL
              value: "SASL_SSL"
            - name: CONNECT_CONSUMER_SASL_MECHANISM
              value: "PLAIN"
            - name: CONNECT_CONSUMER_SASL_JAAS_CONFIG
              value:  "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"kafka-sa@sbx-stag.iam.gserviceaccount.com\" password=\"$(ACCESS_TOKEN)\";"
            - name: CONNECT_PRODUCER_SECURITY_PROTOCOL
              value: "SASL_SSL"
            - name: CONNECT_PRODUCER_SASL_MECHANISM
              value: "PLAIN"
            - name: CONNECT_PRODUCER_SASL_JAAS_CONFIG
              value: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"kafka-sa@sbx-stag.iam.gserviceaccount.com\" password=\"$(ACCESS_TOKEN)\";"
            - name:  CONNECT_ADMIN_SECURITY_PROTOCOL
              value: "SASL_SSL"
            - name: CONNECT_ADMIN_SASL_MECHANISM
              value: "PLAIN"
            - name: CONNECT_ADMIN_SASL_JAAS_CONFIG
              value: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"kafka-sa@sbx-stag.iam.gserviceaccount.com\" password=\"$(ACCESS_TOKEN)\";"
---
apiVersion: v1
kind: Service
metadata:
  name: cp-connect
  namespace: kafka
spec:
  selector:
    app: cp-connect
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
