apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ksqldb-pvc
  namespace: kafka
spec:
  storageClassName: premium-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksqldb
  namespace: kafka
  labels:
    app: ksqldb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ksqldb
  template:
    metadata:
      labels:
        app: ksqldb
    spec:
      nodeSelector:
        instance_type: kafka-genral
      tolerations:
        - key: "instance_type"
          operator: "Equal"
          value: "kafka-genral"
          effect: "NoSchedule"
      serviceAccountName: kafka-sa
      containers:
        - name: kafka-auth-server
          image: shivamsbx/kafka-sasl@sha256:c7effb7b55aa487075e48b0b6b2c1822984f99c7a812be3cdb3cc181fcbbc398
          ports:
            - containerPort: 14293
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 10Mi
        - name: ksqldb-cli
          image: confluentinc/cp-ksqldb-cli:8.0.0
          command: ["/bin/sh"]
          tty: true
          stdin: true
          resources:
            limits:
              cpu: 2
              memory: 3Gi
            requests:
              cpu: 50m
              memory: 50Mi
        - name: ksqldb
          image: confluentinc/cp-ksqldb-server:8.0.0
          ports:
            - containerPort: 8088
          resources:
            limits:
              cpu: 2000m
              memory: 3Gi
            requests:
              cpu: 200m
              memory: 500Mi
          env:
            - name: KSQL_BOOTSTRAP_SERVERS
              value: "bootstrap.sbx-kafka-cluster.asia-south1.managedkafka.sbx-stag.cloud.goog:9092"
            - name: KSQL_LISTENERS
              value: http://0.0.0.0:8088/
            - name: KSQL_KSQL_SERVICE_ID
              value: "default_"
            - name: KSQL_KSQL_SINK_REPLICAS
              value: "3"
            - name: KSQL_KSQL_STREAMS_REPLICATION_FACTOR
              value: "3"
            - name: KSQL_KSQL_INTERNAL_TOPIC_REPLICAS
              value: "3"
            - name: KSQL_KSQL_SCHEMA_REGISTRY_URL
              value: http://cp-schema-registry
            - name: ACCESS_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: token-config
                  key: token
            - name: KSQL_SECURITY_PROTOCOL
              value: "SASL_SSL"
            - name: KSQL_SASL_MECHANISM
              value: "OAUTHBEARER"
            - name: KSQL_SASL_JAAS_CONFIG
              value: "org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required clientId=\"unused\" clientSecret=\"unused\";"
            - name: KSQL_SASL_LOGIN_CALLBACK_HANDLER_CLASS
              value: "org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler"
            - name: KSQL_SASL_OAUTHBEARER_TOKEN_ENDPOINT_URL
              value: "http://localhost:14293"
            - name: KAFKA_OPTS
              value: "-Dorg.apache.kafka.sasl.oauthbearer.allowed.urls=http://localhost:14293"
            - name: JAVA_TOOL_OPTIONS
              value: "-Dorg.apache.kafka.sasl.oauthbearer.allowed.urls=http://localhost:14293"
          volumeMounts:     
            - name: ksqldb-storage
              mountPath: /var/lib/ksqldb/data
      volumes:
        - name: ksqldb-storage
          persistentVolumeClaim:
            claimName: ksqldb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ksqldb
  namespace: kafka
spec:
  selector:
    app: ksqldb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksqldb-ui
  namespace: kafka
  labels:
    app: ksqldb-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksqldb-ui
  template:
    metadata:
      labels:
        app: ksqldb-ui
    spec:
      nodeSelector:
        instance_type: kafka-genral
      tolerations:
        - key: "instance_type"
          operator: "Equal"
          value: "kafka-genral"
          effect: "NoSchedule"
      serviceAccountName: kafka-sa
      containers:
        - name: ksqldb-ui
          image: deniskrumko/ksqldb-ui:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 3Gi
            requests:
              cpu: 50m
              memory: 50Mi
          env:
            - name: KSQLDB_UI__SERVERS__LOCALHOST__URL
              value: "http://ksqldb:80"
            - name: KSQLDB_UI__SERVERS__LOCALHOST__TOPIC_LINK
              value: http://kafka-ui.kafka/ui/clusters/sbx-kafka-cluster/topics/{}
            - name: KSQLDB_UI__SERVERS__GCP__URL
              value: "http://ksqldb:80"
            - name: KSQLDB_UI__SERVERS__GCP__TOPIC_LINK
              value: http://kafka-ui.kafka/ui/clusters/sbx-kafka-cluster/topics/{}
---
apiVersion: v1
kind: Service
metadata:
  name: ksqldb-ui
  namespace: kafka
spec:
  selector:
    app: ksqldb-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---