-- Hourly position snapshots for WMS Inventory
-- This table stores hourly aggregated inventory positions with cumulative tracking
-- Fed by materialized view from wms_inventory_events_enriched

-- Create the target table for hourly snapshots
CREATE TABLE IF NOT EXISTS wms_inventory_hourly_position
(
    -- Time and warehouse
    hour_window DateTime,
    wh_id UInt64,
    
    -- Inventory position keys (defines unique position)
    hu_code String,
    sku_code String,
    uom String,
    bucket String,
    batch String,
    price String,
    inclusion_status String,
    locked_by_task_id String,
    lock_mode String,
    
    -- Aggregated metrics for this hour
    hourly_qty_change SimpleAggregateFunction(sum, Int64),
    event_count SimpleAggregateFunction(sum, UInt64),
    
    -- Latest event identifiers
    latest_hu_event_id SimpleAggregateFunction(anyLast, String),
    latest_quant_event_id SimpleAggregateFunction(anyLast, String),
    
    -- Latest timestamps
    first_event_time SimpleAggregateFunction(min, DateTime64(3)),
    last_event_time SimpleAggregateFunction(max, DateTime64(3)),
    
    -- Latest handling unit event fields
    hu_event_seq SimpleAggregateFunction(anyLast, UInt64),
    hu_id SimpleAggregateFunction(anyLast, String),
    hu_event_type SimpleAggregateFunction(anyLast, String),
    hu_event_payload SimpleAggregateFunction(anyLast, String),
    hu_event_attrs SimpleAggregateFunction(anyLast, String),
    session_id SimpleAggregateFunction(anyLast, String),
    task_id SimpleAggregateFunction(anyLast, String),
    correlation_id SimpleAggregateFunction(anyLast, String),
    storage_id SimpleAggregateFunction(anyLast, String),
    outer_hu_id SimpleAggregateFunction(anyLast, String),
    effective_storage_id SimpleAggregateFunction(anyLast, String),
    
    -- Latest handling unit quant event fields
    sku_id SimpleAggregateFunction(anyLast, String),
    
    -- Latest enriched handling unit fields
    hu_kind_id SimpleAggregateFunction(anyLast, String),
    hu_state SimpleAggregateFunction(anyLast, String),
    hu_attrs SimpleAggregateFunction(anyLast, String),
    hu_created_at SimpleAggregateFunction(anyLast, DateTime64(3)),
    hu_updated_at SimpleAggregateFunction(anyLast, DateTime64(3)),
    hu_lock_task_id SimpleAggregateFunction(anyLast, String),
    hu_effective_storage_id SimpleAggregateFunction(anyLast, String),
    
    -- Latest enriched handling unit kind fields
    hu_kind_code SimpleAggregateFunction(anyLast, String),
    hu_kind_name SimpleAggregateFunction(anyLast, String),
    hu_kind_attrs SimpleAggregateFunction(anyLast, String),
    hu_kind_active SimpleAggregateFunction(anyLast, Boolean),
    hu_kind_max_volume SimpleAggregateFunction(anyLast, Float64),
    hu_kind_max_weight SimpleAggregateFunction(anyLast, Float64),
    hu_kind_usage_type SimpleAggregateFunction(anyLast, String),
    hu_kind_abbr SimpleAggregateFunction(anyLast, String),
    hu_kind_length SimpleAggregateFunction(anyLast, Float64),
    hu_kind_breadth SimpleAggregateFunction(anyLast, Float64),
    hu_kind_height SimpleAggregateFunction(anyLast, Float64),
    hu_kind_weight SimpleAggregateFunction(anyLast, Float64),
    
    -- Latest enriched storage bin fields
    storage_bin_code SimpleAggregateFunction(anyLast, String),
    storage_bin_description SimpleAggregateFunction(anyLast, String),
    storage_bin_status SimpleAggregateFunction(anyLast, String),
    storage_bin_hu_id SimpleAggregateFunction(anyLast, String),
    storage_multi_sku SimpleAggregateFunction(anyLast, Boolean),
    storage_multi_batch SimpleAggregateFunction(anyLast, Boolean),
    storage_picking_position SimpleAggregateFunction(anyLast, Int32),
    storage_putaway_position SimpleAggregateFunction(anyLast, Int32),
    storage_rank SimpleAggregateFunction(anyLast, Int32),
    storage_aisle SimpleAggregateFunction(anyLast, String),
    storage_bay SimpleAggregateFunction(anyLast, String),
    storage_level SimpleAggregateFunction(anyLast, String),
    storage_position SimpleAggregateFunction(anyLast, String),
    storage_depth SimpleAggregateFunction(anyLast, String),
    storage_max_sku_count SimpleAggregateFunction(anyLast, Int32),
    storage_max_sku_batch_count SimpleAggregateFunction(anyLast, Int32),
    storage_bin_type_id SimpleAggregateFunction(anyLast, String),
    storage_bin_type_code SimpleAggregateFunction(anyLast, String),
    storage_bin_type_description SimpleAggregateFunction(anyLast, String),
    storage_max_volume_in_cc SimpleAggregateFunction(anyLast, Float64),
    storage_max_weight_in_kg SimpleAggregateFunction(anyLast, Float64),
    storage_pallet_capacity SimpleAggregateFunction(anyLast, Int32),
    storage_hu_type SimpleAggregateFunction(anyLast, String),
    storage_auxiliary_bin SimpleAggregateFunction(anyLast, Boolean),
    storage_hu_multi_sku SimpleAggregateFunction(anyLast, Boolean),
    storage_hu_multi_batch SimpleAggregateFunction(anyLast, Boolean),
    storage_use_derived_pallet_best_fit SimpleAggregateFunction(anyLast, Boolean),
    storage_only_full_pallet SimpleAggregateFunction(anyLast, Boolean),
    storage_bin_type_active SimpleAggregateFunction(anyLast, Boolean),
    storage_zone_id SimpleAggregateFunction(anyLast, String),
    storage_zone_code SimpleAggregateFunction(anyLast, String),
    storage_zone_description SimpleAggregateFunction(anyLast, String),
    storage_zone_face SimpleAggregateFunction(anyLast, String),
    storage_peripheral SimpleAggregateFunction(anyLast, Boolean),
    storage_surveillance_config SimpleAggregateFunction(anyLast, String),
    storage_zone_active SimpleAggregateFunction(anyLast, Boolean),
    storage_area_id SimpleAggregateFunction(anyLast, String),
    storage_area_code SimpleAggregateFunction(anyLast, String),
    storage_area_description SimpleAggregateFunction(anyLast, String),
    storage_area_type SimpleAggregateFunction(anyLast, String),
    storage_rolling_days SimpleAggregateFunction(anyLast, Int32),
    storage_area_active SimpleAggregateFunction(anyLast, Boolean),
    storage_x1 SimpleAggregateFunction(anyLast, Float64),
    storage_x2 SimpleAggregateFunction(anyLast, Float64),
    storage_y1 SimpleAggregateFunction(anyLast, Float64),
    storage_y2 SimpleAggregateFunction(anyLast, Float64),
    storage_position_active SimpleAggregateFunction(anyLast, Boolean),
    storage_attrs SimpleAggregateFunction(anyLast, String),
    storage_bin_mapping SimpleAggregateFunction(anyLast, String),
    storage_created_at SimpleAggregateFunction(anyLast, DateTime64(3)),
    storage_updated_at SimpleAggregateFunction(anyLast, DateTime64(3)),
    
    -- Latest enriched SKU master fields
    sku_name SimpleAggregateFunction(anyLast, String),
    sku_short_description SimpleAggregateFunction(anyLast, String),
    sku_description SimpleAggregateFunction(anyLast, String),
    sku_category SimpleAggregateFunction(anyLast, String),
    sku_product SimpleAggregateFunction(anyLast, String),
    sku_product_id SimpleAggregateFunction(anyLast, String),
    sku_category_group SimpleAggregateFunction(anyLast, String),
    sku_sub_brand SimpleAggregateFunction(anyLast, String),
    sku_brand SimpleAggregateFunction(anyLast, String),
    sku_fulfillment_type SimpleAggregateFunction(anyLast, String),
    sku_inventory_type SimpleAggregateFunction(anyLast, String),
    sku_shelf_life SimpleAggregateFunction(anyLast, Int32),
    sku_handling_unit_type SimpleAggregateFunction(anyLast, String),
    sku_cases_per_layer SimpleAggregateFunction(anyLast, Int32),
    sku_layers SimpleAggregateFunction(anyLast, Int32),
    sku_active_from SimpleAggregateFunction(anyLast, DateTime64(3)),
    sku_active_till SimpleAggregateFunction(anyLast, DateTime64(3)),
    sku_l0_units SimpleAggregateFunction(anyLast, Int32),
    sku_l0_name SimpleAggregateFunction(anyLast, String),
    sku_l0_weight SimpleAggregateFunction(anyLast, Float64),
    sku_l0_volume SimpleAggregateFunction(anyLast, Float64),
    sku_l0_length SimpleAggregateFunction(anyLast, Float64),
    sku_l0_width SimpleAggregateFunction(anyLast, Float64),
    sku_l0_height SimpleAggregateFunction(anyLast, Float64),
    sku_l1_units SimpleAggregateFunction(anyLast, Int32),
    sku_l1_name SimpleAggregateFunction(anyLast, String),
    sku_l1_weight SimpleAggregateFunction(anyLast, Float64),
    sku_l1_volume SimpleAggregateFunction(anyLast, Float64),
    sku_l1_length SimpleAggregateFunction(anyLast, Float64),
    sku_l1_width SimpleAggregateFunction(anyLast, Float64),
    sku_l1_height SimpleAggregateFunction(anyLast, Float64),
    sku_active SimpleAggregateFunction(anyLast, Boolean),
    sku_created_at SimpleAggregateFunction(anyLast, DateTime64(3)),
    sku_updated_at SimpleAggregateFunction(anyLast, DateTime64(3)),
    
    -- Latest enriched effective storage fields
    effective_storage_bin_code SimpleAggregateFunction(anyLast, String),
    effective_storage_bin_description SimpleAggregateFunction(anyLast, String),
    effective_storage_bin_status SimpleAggregateFunction(anyLast, String),
    effective_storage_bin_hu_id SimpleAggregateFunction(anyLast, String),
    effective_storage_multi_sku SimpleAggregateFunction(anyLast, Boolean),
    effective_storage_multi_batch SimpleAggregateFunction(anyLast, Boolean),
    effective_storage_picking_position SimpleAggregateFunction(anyLast, Int32),
    effective_storage_putaway_position SimpleAggregateFunction(anyLast, Int32),
    effective_storage_rank SimpleAggregateFunction(anyLast, Int32),
    effective_storage_aisle SimpleAggregateFunction(anyLast, String),
    effective_storage_bay SimpleAggregateFunction(anyLast, String),
    effective_storage_level SimpleAggregateFunction(anyLast, String),
    effective_storage_position SimpleAggregateFunction(anyLast, String),
    effective_storage_depth SimpleAggregateFunction(anyLast, String),
    effective_storage_max_sku_count SimpleAggregateFunction(anyLast, Int32),
    effective_storage_max_sku_batch_count SimpleAggregateFunction(anyLast, Int32),
    effective_storage_bin_type_id SimpleAggregateFunction(anyLast, String),
    effective_storage_bin_type_code SimpleAggregateFunction(anyLast, String),
    effective_storage_bin_type_description SimpleAggregateFunction(anyLast, String),
    effective_storage_max_volume_in_cc SimpleAggregateFunction(anyLast, Float64),
    effective_storage_max_weight_in_kg SimpleAggregateFunction(anyLast, Float64),
    effective_storage_pallet_capacity SimpleAggregateFunction(anyLast, Int32),
    effective_storage_hu_type SimpleAggregateFunction(anyLast, String),
    effective_storage_auxiliary_bin SimpleAggregateFunction(anyLast, Boolean),
    effective_storage_hu_multi_sku SimpleAggregateFunction(anyLast, Boolean),
    effective_storage_hu_multi_batch SimpleAggregateFunction(anyLast, Boolean),
    effective_storage_use_derived_pallet_best_fit SimpleAggregateFunction(anyLast, Boolean),
    effective_storage_only_full_pallet SimpleAggregateFunction(anyLast, Boolean),
    effective_storage_bin_type_active SimpleAggregateFunction(anyLast, Boolean),
    effective_storage_zone_id SimpleAggregateFunction(anyLast, String),
    effective_storage_zone_code SimpleAggregateFunction(anyLast, String),
    effective_storage_zone_description SimpleAggregateFunction(anyLast, String),
    effective_storage_zone_face SimpleAggregateFunction(anyLast, String),
    effective_storage_peripheral SimpleAggregateFunction(anyLast, Boolean),
    effective_storage_surveillance_config SimpleAggregateFunction(anyLast, String),
    effective_storage_zone_active SimpleAggregateFunction(anyLast, Boolean),
    effective_storage_area_id SimpleAggregateFunction(anyLast, String),
    effective_storage_area_code SimpleAggregateFunction(anyLast, String),
    effective_storage_area_description SimpleAggregateFunction(anyLast, String),
    effective_storage_area_type SimpleAggregateFunction(anyLast, String),
    effective_storage_rolling_days SimpleAggregateFunction(anyLast, Int32),
    effective_storage_area_active SimpleAggregateFunction(anyLast, Boolean),
    effective_storage_x1 SimpleAggregateFunction(anyLast, Float64),
    effective_storage_x2 SimpleAggregateFunction(anyLast, Float64),
    effective_storage_y1 SimpleAggregateFunction(anyLast, Float64),
    effective_storage_y2 SimpleAggregateFunction(anyLast, Float64),
    effective_storage_position_active SimpleAggregateFunction(anyLast, Boolean),
    effective_storage_attrs SimpleAggregateFunction(anyLast, String),
    effective_storage_bin_mapping SimpleAggregateFunction(anyLast, String),
    effective_storage_created_at SimpleAggregateFunction(anyLast, DateTime64(3)),
    effective_storage_updated_at SimpleAggregateFunction(anyLast, DateTime64(3)),
    
    -- Latest enriched outer HU fields
    outer_hu_code SimpleAggregateFunction(anyLast, String),
    outer_hu_kind_id SimpleAggregateFunction(anyLast, String),
    outer_hu_session_id SimpleAggregateFunction(anyLast, String),
    outer_hu_task_id SimpleAggregateFunction(anyLast, String),
    outer_hu_storage_id SimpleAggregateFunction(anyLast, String),
    outer_hu_outer_hu_id SimpleAggregateFunction(anyLast, String),
    outer_hu_state SimpleAggregateFunction(anyLast, String),
    outer_hu_attrs SimpleAggregateFunction(anyLast, String),
    outer_hu_created_at SimpleAggregateFunction(anyLast, DateTime64(3)),
    outer_hu_updated_at SimpleAggregateFunction(anyLast, DateTime64(3)),
    outer_hu_lock_task_id SimpleAggregateFunction(anyLast, String),
    outer_hu_effective_storage_id SimpleAggregateFunction(anyLast, String),
    outer_hu_kind_code SimpleAggregateFunction(anyLast, String),
    outer_hu_kind_name SimpleAggregateFunction(anyLast, String),
    outer_hu_kind_attrs SimpleAggregateFunction(anyLast, String),
    outer_hu_kind_active SimpleAggregateFunction(anyLast, Boolean),
    outer_hu_kind_max_volume SimpleAggregateFunction(anyLast, Float64),
    outer_hu_kind_max_weight SimpleAggregateFunction(anyLast, Float64),
    outer_hu_kind_usage_type SimpleAggregateFunction(anyLast, String),
    outer_hu_kind_abbr SimpleAggregateFunction(anyLast, String),
    outer_hu_kind_length SimpleAggregateFunction(anyLast, Float64),
    outer_hu_kind_breadth SimpleAggregateFunction(anyLast, Float64),
    outer_hu_kind_height SimpleAggregateFunction(anyLast, Float64),
    outer_hu_kind_weight SimpleAggregateFunction(anyLast, Float64),
    
    -- Processing metadata
    _processed_at DateTime64(3) DEFAULT now64(3)
)
ENGINE = AggregatingMergeTree()
PARTITION BY toYYYYMM(hour_window)
ORDER BY (
    wh_id,
    hour_window,
    hu_code,
    sku_code,
    uom,
    bucket,
    batch,
    price,
    inclusion_status,
    locked_by_task_id,
    lock_mode
)
SETTINGS index_granularity = 8192;

-- Create materialized view that performs the aggregation
CREATE MATERIALIZED VIEW IF NOT EXISTS wms_inventory_hourly_position_mv
TO wms_inventory_hourly_position
AS
WITH deduplicated_events AS (
    -- Deduplicate by taking the latest version of each (hu_event_id, quant_event_id) pair
    SELECT
        hu_event_id,
        quant_event_id,
        argMax(wh_id, _ingested_at) as wh_id,
        argMax(hu_code, _ingested_at) as hu_code,
        argMax(sku_code, _ingested_at) as sku_code,
        argMax(uom, _ingested_at) as uom,
        argMax(bucket, _ingested_at) as bucket,
        argMax(batch, _ingested_at) as batch,
        argMax(price, _ingested_at) as price,
        argMax(inclusion_status, _ingested_at) as inclusion_status,
        argMax(locked_by_task_id, _ingested_at) as locked_by_task_id,
        argMax(lock_mode, _ingested_at) as lock_mode,
        argMax(qty_added, _ingested_at) as qty_added,
        argMax(hu_event_timestamp, _ingested_at) as hu_event_timestamp,
        -- All other fields using argMax
        argMax(hu_event_seq, _ingested_at) as hu_event_seq,
        argMax(hu_id, _ingested_at) as hu_id,
        argMax(hu_event_type, _ingested_at) as hu_event_type,
        argMax(hu_event_payload, _ingested_at) as hu_event_payload,
        argMax(hu_event_attrs, _ingested_at) as hu_event_attrs,
        argMax(session_id, _ingested_at) as session_id,
        argMax(task_id, _ingested_at) as task_id,
        argMax(correlation_id, _ingested_at) as correlation_id,
        argMax(storage_id, _ingested_at) as storage_id,
        argMax(outer_hu_id, _ingested_at) as outer_hu_id,
        argMax(effective_storage_id, _ingested_at) as effective_storage_id,
        argMax(sku_id, _ingested_at) as sku_id,
        argMax(hu_kind_id, _ingested_at) as hu_kind_id,
        argMax(hu_state, _ingested_at) as hu_state,
        argMax(hu_attrs, _ingested_at) as hu_attrs,
        argMax(hu_created_at, _ingested_at) as hu_created_at,
        argMax(hu_updated_at, _ingested_at) as hu_updated_at,
        argMax(hu_lock_task_id, _ingested_at) as hu_lock_task_id,
        argMax(hu_effective_storage_id, _ingested_at) as hu_effective_storage_id,
        argMax(hu_kind_code, _ingested_at) as hu_kind_code,
        argMax(hu_kind_name, _ingested_at) as hu_kind_name,
        argMax(hu_kind_attrs, _ingested_at) as hu_kind_attrs,
        argMax(hu_kind_active, _ingested_at) as hu_kind_active,
        argMax(hu_kind_max_volume, _ingested_at) as hu_kind_max_volume,
        argMax(hu_kind_max_weight, _ingested_at) as hu_kind_max_weight,
        argMax(hu_kind_usage_type, _ingested_at) as hu_kind_usage_type,
        argMax(hu_kind_abbr, _ingested_at) as hu_kind_abbr,
        argMax(hu_kind_length, _ingested_at) as hu_kind_length,
        argMax(hu_kind_breadth, _ingested_at) as hu_kind_breadth,
        argMax(hu_kind_height, _ingested_at) as hu_kind_height,
        argMax(hu_kind_weight, _ingested_at) as hu_kind_weight,
        argMax(storage_bin_code, _ingested_at) as storage_bin_code,
        argMax(storage_bin_description, _ingested_at) as storage_bin_description,
        argMax(storage_bin_status, _ingested_at) as storage_bin_status,
        argMax(storage_bin_hu_id, _ingested_at) as storage_bin_hu_id,
        argMax(storage_multi_sku, _ingested_at) as storage_multi_sku,
        argMax(storage_multi_batch, _ingested_at) as storage_multi_batch,
        argMax(storage_picking_position, _ingested_at) as storage_picking_position,
        argMax(storage_putaway_position, _ingested_at) as storage_putaway_position,
        argMax(storage_rank, _ingested_at) as storage_rank,
        argMax(storage_aisle, _ingested_at) as storage_aisle,
        argMax(storage_bay, _ingested_at) as storage_bay,
        argMax(storage_level, _ingested_at) as storage_level,
        argMax(storage_position, _ingested_at) as storage_position,
        argMax(storage_depth, _ingested_at) as storage_depth,
        argMax(storage_max_sku_count, _ingested_at) as storage_max_sku_count,
        argMax(storage_max_sku_batch_count, _ingested_at) as storage_max_sku_batch_count,
        argMax(storage_bin_type_id, _ingested_at) as storage_bin_type_id,
        argMax(storage_bin_type_code, _ingested_at) as storage_bin_type_code,
        argMax(storage_bin_type_description, _ingested_at) as storage_bin_type_description,
        argMax(storage_max_volume_in_cc, _ingested_at) as storage_max_volume_in_cc,
        argMax(storage_max_weight_in_kg, _ingested_at) as storage_max_weight_in_kg,
        argMax(storage_pallet_capacity, _ingested_at) as storage_pallet_capacity,
        argMax(storage_hu_type, _ingested_at) as storage_hu_type,
        argMax(storage_auxiliary_bin, _ingested_at) as storage_auxiliary_bin,
        argMax(storage_hu_multi_sku, _ingested_at) as storage_hu_multi_sku,
        argMax(storage_hu_multi_batch, _ingested_at) as storage_hu_multi_batch,
        argMax(storage_use_derived_pallet_best_fit, _ingested_at) as storage_use_derived_pallet_best_fit,
        argMax(storage_only_full_pallet, _ingested_at) as storage_only_full_pallet,
        argMax(storage_bin_type_active, _ingested_at) as storage_bin_type_active,
        argMax(storage_zone_id, _ingested_at) as storage_zone_id,
        argMax(storage_zone_code, _ingested_at) as storage_zone_code,
        argMax(storage_zone_description, _ingested_at) as storage_zone_description,
        argMax(storage_zone_face, _ingested_at) as storage_zone_face,
        argMax(storage_peripheral, _ingested_at) as storage_peripheral,
        argMax(storage_surveillance_config, _ingested_at) as storage_surveillance_config,
        argMax(storage_zone_active, _ingested_at) as storage_zone_active,
        argMax(storage_area_id, _ingested_at) as storage_area_id,
        argMax(storage_area_code, _ingested_at) as storage_area_code,
        argMax(storage_area_description, _ingested_at) as storage_area_description,
        argMax(storage_area_type, _ingested_at) as storage_area_type,
        argMax(storage_rolling_days, _ingested_at) as storage_rolling_days,
        argMax(storage_area_active, _ingested_at) as storage_area_active,
        argMax(storage_x1, _ingested_at) as storage_x1,
        argMax(storage_x2, _ingested_at) as storage_x2,
        argMax(storage_y1, _ingested_at) as storage_y1,
        argMax(storage_y2, _ingested_at) as storage_y2,
        argMax(storage_position_active, _ingested_at) as storage_position_active,
        argMax(storage_attrs, _ingested_at) as storage_attrs,
        argMax(storage_bin_mapping, _ingested_at) as storage_bin_mapping,
        argMax(storage_created_at, _ingested_at) as storage_created_at,
        argMax(storage_updated_at, _ingested_at) as storage_updated_at,
        argMax(sku_name, _ingested_at) as sku_name,
        argMax(sku_short_description, _ingested_at) as sku_short_description,
        argMax(sku_description, _ingested_at) as sku_description,
        argMax(sku_category, _ingested_at) as sku_category,
        argMax(sku_product, _ingested_at) as sku_product,
        argMax(sku_product_id, _ingested_at) as sku_product_id,
        argMax(sku_category_group, _ingested_at) as sku_category_group,
        argMax(sku_sub_brand, _ingested_at) as sku_sub_brand,
        argMax(sku_brand, _ingested_at) as sku_brand,
        argMax(sku_fulfillment_type, _ingested_at) as sku_fulfillment_type,
        argMax(sku_inventory_type, _ingested_at) as sku_inventory_type,
        argMax(sku_shelf_life, _ingested_at) as sku_shelf_life,
        argMax(sku_handling_unit_type, _ingested_at) as sku_handling_unit_type,
        argMax(sku_cases_per_layer, _ingested_at) as sku_cases_per_layer,
        argMax(sku_layers, _ingested_at) as sku_layers,
        argMax(sku_active_from, _ingested_at) as sku_active_from,
        argMax(sku_active_till, _ingested_at) as sku_active_till,
        argMax(sku_l0_units, _ingested_at) as sku_l0_units,
        argMax(sku_l0_name, _ingested_at) as sku_l0_name,
        argMax(sku_l0_weight, _ingested_at) as sku_l0_weight,
        argMax(sku_l0_volume, _ingested_at) as sku_l0_volume,
        argMax(sku_l0_length, _ingested_at) as sku_l0_length,
        argMax(sku_l0_width, _ingested_at) as sku_l0_width,
        argMax(sku_l0_height, _ingested_at) as sku_l0_height,
        argMax(sku_l1_units, _ingested_at) as sku_l1_units,
        argMax(sku_l1_name, _ingested_at) as sku_l1_name,
        argMax(sku_l1_weight, _ingested_at) as sku_l1_weight,
        argMax(sku_l1_volume, _ingested_at) as sku_l1_volume,
        argMax(sku_l1_length, _ingested_at) as sku_l1_length,
        argMax(sku_l1_width, _ingested_at) as sku_l1_width,
        argMax(sku_l1_height, _ingested_at) as sku_l1_height,
        argMax(sku_active, _ingested_at) as sku_active,
        argMax(sku_created_at, _ingested_at) as sku_created_at,
        argMax(sku_updated_at, _ingested_at) as sku_updated_at,
        argMax(effective_storage_bin_code, _ingested_at) as effective_storage_bin_code,
        argMax(effective_storage_bin_description, _ingested_at) as effective_storage_bin_description,
        argMax(effective_storage_bin_status, _ingested_at) as effective_storage_bin_status,
        argMax(effective_storage_bin_hu_id, _ingested_at) as effective_storage_bin_hu_id,
        argMax(effective_storage_multi_sku, _ingested_at) as effective_storage_multi_sku,
        argMax(effective_storage_multi_batch, _ingested_at) as effective_storage_multi_batch,
        argMax(effective_storage_picking_position, _ingested_at) as effective_storage_picking_position,
        argMax(effective_storage_putaway_position, _ingested_at) as effective_storage_putaway_position,
        argMax(effective_storage_rank, _ingested_at) as effective_storage_rank,
        argMax(effective_storage_aisle, _ingested_at) as effective_storage_aisle,
        argMax(effective_storage_bay, _ingested_at) as effective_storage_bay,
        argMax(effective_storage_level, _ingested_at) as effective_storage_level,
        argMax(effective_storage_position, _ingested_at) as effective_storage_position,
        argMax(effective_storage_depth, _ingested_at) as effective_storage_depth,
        argMax(effective_storage_max_sku_count, _ingested_at) as effective_storage_max_sku_count,
        argMax(effective_storage_max_sku_batch_count, _ingested_at) as effective_storage_max_sku_batch_count,
        argMax(effective_storage_bin_type_id, _ingested_at) as effective_storage_bin_type_id,
        argMax(effective_storage_bin_type_code, _ingested_at) as effective_storage_bin_type_code,
        argMax(effective_storage_bin_type_description, _ingested_at) as effective_storage_bin_type_description,
        argMax(effective_storage_max_volume_in_cc, _ingested_at) as effective_storage_max_volume_in_cc,
        argMax(effective_storage_max_weight_in_kg, _ingested_at) as effective_storage_max_weight_in_kg,
        argMax(effective_storage_pallet_capacity, _ingested_at) as effective_storage_pallet_capacity,
        argMax(effective_storage_hu_type, _ingested_at) as effective_storage_hu_type,
        argMax(effective_storage_auxiliary_bin, _ingested_at) as effective_storage_auxiliary_bin,
        argMax(effective_storage_hu_multi_sku, _ingested_at) as effective_storage_hu_multi_sku,
        argMax(effective_storage_hu_multi_batch, _ingested_at) as effective_storage_hu_multi_batch,
        argMax(effective_storage_use_derived_pallet_best_fit, _ingested_at) as effective_storage_use_derived_pallet_best_fit,
        argMax(effective_storage_only_full_pallet, _ingested_at) as effective_storage_only_full_pallet,
        argMax(effective_storage_bin_type_active, _ingested_at) as effective_storage_bin_type_active,
        argMax(effective_storage_zone_id, _ingested_at) as effective_storage_zone_id,
        argMax(effective_storage_zone_code, _ingested_at) as effective_storage_zone_code,
        argMax(effective_storage_zone_description, _ingested_at) as effective_storage_zone_description,
        argMax(effective_storage_zone_face, _ingested_at) as effective_storage_zone_face,
        argMax(effective_storage_peripheral, _ingested_at) as effective_storage_peripheral,
        argMax(effective_storage_surveillance_config, _ingested_at) as effective_storage_surveillance_config,
        argMax(effective_storage_zone_active, _ingested_at) as effective_storage_zone_active,
        argMax(effective_storage_area_id, _ingested_at) as effective_storage_area_id,
        argMax(effective_storage_area_code, _ingested_at) as effective_storage_area_code,
        argMax(effective_storage_area_description, _ingested_at) as effective_storage_area_description,
        argMax(effective_storage_area_type, _ingested_at) as effective_storage_area_type,
        argMax(effective_storage_rolling_days, _ingested_at) as effective_storage_rolling_days,
        argMax(effective_storage_area_active, _ingested_at) as effective_storage_area_active,
        argMax(effective_storage_x1, _ingested_at) as effective_storage_x1,
        argMax(effective_storage_x2, _ingested_at) as effective_storage_x2,
        argMax(effective_storage_y1, _ingested_at) as effective_storage_y1,
        argMax(effective_storage_y2, _ingested_at) as effective_storage_y2,
        argMax(effective_storage_position_active, _ingested_at) as effective_storage_position_active,
        argMax(effective_storage_attrs, _ingested_at) as effective_storage_attrs,
        argMax(effective_storage_bin_mapping, _ingested_at) as effective_storage_bin_mapping,
        argMax(effective_storage_created_at, _ingested_at) as effective_storage_created_at,
        argMax(effective_storage_updated_at, _ingested_at) as effective_storage_updated_at,
        argMax(outer_hu_code, _ingested_at) as outer_hu_code,
        argMax(outer_hu_kind_id, _ingested_at) as outer_hu_kind_id,
        argMax(outer_hu_session_id, _ingested_at) as outer_hu_session_id,
        argMax(outer_hu_task_id, _ingested_at) as outer_hu_task_id,
        argMax(outer_hu_storage_id, _ingested_at) as outer_hu_storage_id,
        argMax(outer_hu_outer_hu_id, _ingested_at) as outer_hu_outer_hu_id,
        argMax(outer_hu_state, _ingested_at) as outer_hu_state,
        argMax(outer_hu_attrs, _ingested_at) as outer_hu_attrs,
        argMax(outer_hu_created_at, _ingested_at) as outer_hu_created_at,
        argMax(outer_hu_updated_at, _ingested_at) as outer_hu_updated_at,
        argMax(outer_hu_lock_task_id, _ingested_at) as outer_hu_lock_task_id,
        argMax(outer_hu_effective_storage_id, _ingested_at) as outer_hu_effective_storage_id,
        argMax(outer_hu_kind_code, _ingested_at) as outer_hu_kind_code,
        argMax(outer_hu_kind_name, _ingested_at) as outer_hu_kind_name,
        argMax(outer_hu_kind_attrs, _ingested_at) as outer_hu_kind_attrs,
        argMax(outer_hu_kind_active, _ingested_at) as outer_hu_kind_active,
        argMax(outer_hu_kind_max_volume, _ingested_at) as outer_hu_kind_max_volume,
        argMax(outer_hu_kind_max_weight, _ingested_at) as outer_hu_kind_max_weight,
        argMax(outer_hu_kind_usage_type, _ingested_at) as outer_hu_kind_usage_type,
        argMax(outer_hu_kind_abbr, _ingested_at) as outer_hu_kind_abbr,
        argMax(outer_hu_kind_length, _ingested_at) as outer_hu_kind_length,
        argMax(outer_hu_kind_breadth, _ingested_at) as outer_hu_kind_breadth,
        argMax(outer_hu_kind_height, _ingested_at) as outer_hu_kind_height,
        argMax(outer_hu_kind_weight, _ingested_at) as outer_hu_kind_weight
    FROM wms_inventory_events_enriched
    GROUP BY hu_event_id, quant_event_id
)
SELECT
    toStartOfHour(hu_event_timestamp) as hour_window,
    wh_id,
    hu_code,
    sku_code,
    uom,
    bucket,
    batch,
    price,
    inclusion_status,
    locked_by_task_id,
    lock_mode,
    sum(qty_added) as hourly_qty_change,
    count() as event_count,
    argMax(hu_event_id, hu_event_timestamp) as latest_hu_event_id,
    argMax(quant_event_id, hu_event_timestamp) as latest_quant_event_id,
    min(hu_event_timestamp) as first_event_time,
    max(hu_event_timestamp) as last_event_time,
    -- All other fields using anyLast aggregate
    anyLast(hu_event_seq) as hu_event_seq,
    anyLast(hu_id) as hu_id,
    anyLast(hu_event_type) as hu_event_type,
    anyLast(hu_event_payload) as hu_event_payload,
    anyLast(hu_event_attrs) as hu_event_attrs,
    anyLast(session_id) as session_id,
    anyLast(task_id) as task_id,
    anyLast(correlation_id) as correlation_id,
    anyLast(storage_id) as storage_id,
    anyLast(outer_hu_id) as outer_hu_id,
    anyLast(effective_storage_id) as effective_storage_id,
    anyLast(sku_id) as sku_id,
    anyLast(hu_kind_id) as hu_kind_id,
    anyLast(hu_state) as hu_state,
    anyLast(hu_attrs) as hu_attrs,
    anyLast(hu_created_at) as hu_created_at,
    anyLast(hu_updated_at) as hu_updated_at,
    anyLast(hu_lock_task_id) as hu_lock_task_id,
    anyLast(hu_effective_storage_id) as hu_effective_storage_id,
    anyLast(hu_kind_code) as hu_kind_code,
    anyLast(hu_kind_name) as hu_kind_name,
    anyLast(hu_kind_attrs) as hu_kind_attrs,
    anyLast(hu_kind_active) as hu_kind_active,
    anyLast(hu_kind_max_volume) as hu_kind_max_volume,
    anyLast(hu_kind_max_weight) as hu_kind_max_weight,
    anyLast(hu_kind_usage_type) as hu_kind_usage_type,
    anyLast(hu_kind_abbr) as hu_kind_abbr,
    anyLast(hu_kind_length) as hu_kind_length,
    anyLast(hu_kind_breadth) as hu_kind_breadth,
    anyLast(hu_kind_height) as hu_kind_height,
    anyLast(hu_kind_weight) as hu_kind_weight,
    anyLast(storage_bin_code) as storage_bin_code,
    anyLast(storage_bin_description) as storage_bin_description,
    anyLast(storage_bin_status) as storage_bin_status,
    anyLast(storage_bin_hu_id) as storage_bin_hu_id,
    anyLast(storage_multi_sku) as storage_multi_sku,
    anyLast(storage_multi_batch) as storage_multi_batch,
    anyLast(storage_picking_position) as storage_picking_position,
    anyLast(storage_putaway_position) as storage_putaway_position,
    anyLast(storage_rank) as storage_rank,
    anyLast(storage_aisle) as storage_aisle,
    anyLast(storage_bay) as storage_bay,
    anyLast(storage_level) as storage_level,
    anyLast(storage_position) as storage_position,
    anyLast(storage_depth) as storage_depth,
    anyLast(storage_max_sku_count) as storage_max_sku_count,
    anyLast(storage_max_sku_batch_count) as storage_max_sku_batch_count,
    anyLast(storage_bin_type_id) as storage_bin_type_id,
    anyLast(storage_bin_type_code) as storage_bin_type_code,
    anyLast(storage_bin_type_description) as storage_bin_type_description,
    anyLast(storage_max_volume_in_cc) as storage_max_volume_in_cc,
    anyLast(storage_max_weight_in_kg) as storage_max_weight_in_kg,
    anyLast(storage_pallet_capacity) as storage_pallet_capacity,
    anyLast(storage_hu_type) as storage_hu_type,
    anyLast(storage_auxiliary_bin) as storage_auxiliary_bin,
    anyLast(storage_hu_multi_sku) as storage_hu_multi_sku,
    anyLast(storage_hu_multi_batch) as storage_hu_multi_batch,
    anyLast(storage_use_derived_pallet_best_fit) as storage_use_derived_pallet_best_fit,
    anyLast(storage_only_full_pallet) as storage_only_full_pallet,
    anyLast(storage_bin_type_active) as storage_bin_type_active,
    anyLast(storage_zone_id) as storage_zone_id,
    anyLast(storage_zone_code) as storage_zone_code,
    anyLast(storage_zone_description) as storage_zone_description,
    anyLast(storage_zone_face) as storage_zone_face,
    anyLast(storage_peripheral) as storage_peripheral,
    anyLast(storage_surveillance_config) as storage_surveillance_config,
    anyLast(storage_zone_active) as storage_zone_active,
    anyLast(storage_area_id) as storage_area_id,
    anyLast(storage_area_code) as storage_area_code,
    anyLast(storage_area_description) as storage_area_description,
    anyLast(storage_area_type) as storage_area_type,
    anyLast(storage_rolling_days) as storage_rolling_days,
    anyLast(storage_area_active) as storage_area_active,
    anyLast(storage_x1) as storage_x1,
    anyLast(storage_x2) as storage_x2,
    anyLast(storage_y1) as storage_y1,
    anyLast(storage_y2) as storage_y2,
    anyLast(storage_position_active) as storage_position_active,
    anyLast(storage_attrs) as storage_attrs,
    anyLast(storage_bin_mapping) as storage_bin_mapping,
    anyLast(storage_created_at) as storage_created_at,
    anyLast(storage_updated_at) as storage_updated_at,
    anyLast(sku_name) as sku_name,
    anyLast(sku_short_description) as sku_short_description,
    anyLast(sku_description) as sku_description,
    anyLast(sku_category) as sku_category,
    anyLast(sku_product) as sku_product,
    anyLast(sku_product_id) as sku_product_id,
    anyLast(sku_category_group) as sku_category_group,
    anyLast(sku_sub_brand) as sku_sub_brand,
    anyLast(sku_brand) as sku_brand,
    anyLast(sku_fulfillment_type) as sku_fulfillment_type,
    anyLast(sku_inventory_type) as sku_inventory_type,
    anyLast(sku_shelf_life) as sku_shelf_life,
    anyLast(sku_handling_unit_type) as sku_handling_unit_type,
    anyLast(sku_cases_per_layer) as sku_cases_per_layer,
    anyLast(sku_layers) as sku_layers,
    anyLast(sku_active_from) as sku_active_from,
    anyLast(sku_active_till) as sku_active_till,
    anyLast(sku_l0_units) as sku_l0_units,
    anyLast(sku_l0_name) as sku_l0_name,
    anyLast(sku_l0_weight) as sku_l0_weight,
    anyLast(sku_l0_volume) as sku_l0_volume,
    anyLast(sku_l0_length) as sku_l0_length,
    anyLast(sku_l0_width) as sku_l0_width,
    anyLast(sku_l0_height) as sku_l0_height,
    anyLast(sku_l1_units) as sku_l1_units,
    anyLast(sku_l1_name) as sku_l1_name,
    anyLast(sku_l1_weight) as sku_l1_weight,
    anyLast(sku_l1_volume) as sku_l1_volume,
    anyLast(sku_l1_length) as sku_l1_length,
    anyLast(sku_l1_width) as sku_l1_width,
    anyLast(sku_l1_height) as sku_l1_height,
    anyLast(sku_active) as sku_active,
    anyLast(sku_created_at) as sku_created_at,
    anyLast(sku_updated_at) as sku_updated_at,
    anyLast(effective_storage_bin_code) as effective_storage_bin_code,
    anyLast(effective_storage_bin_description) as effective_storage_bin_description,
    anyLast(effective_storage_bin_status) as effective_storage_bin_status,
    anyLast(effective_storage_bin_hu_id) as effective_storage_bin_hu_id,
    anyLast(effective_storage_multi_sku) as effective_storage_multi_sku,
    anyLast(effective_storage_multi_batch) as effective_storage_multi_batch,
    anyLast(effective_storage_picking_position) as effective_storage_picking_position,
    anyLast(effective_storage_putaway_position) as effective_storage_putaway_position,
    anyLast(effective_storage_rank) as effective_storage_rank,
    anyLast(effective_storage_aisle) as effective_storage_aisle,
    anyLast(effective_storage_bay) as effective_storage_bay,
    anyLast(effective_storage_level) as effective_storage_level,
    anyLast(effective_storage_position) as effective_storage_position,
    anyLast(effective_storage_depth) as effective_storage_depth,
    anyLast(effective_storage_max_sku_count) as effective_storage_max_sku_count,
    anyLast(effective_storage_max_sku_batch_count) as effective_storage_max_sku_batch_count,
    anyLast(effective_storage_bin_type_id) as effective_storage_bin_type_id,
    anyLast(effective_storage_bin_type_code) as effective_storage_bin_type_code,
    anyLast(effective_storage_bin_type_description) as effective_storage_bin_type_description,
    anyLast(effective_storage_max_volume_in_cc) as effective_storage_max_volume_in_cc,
    anyLast(effective_storage_max_weight_in_kg) as effective_storage_max_weight_in_kg,
    anyLast(effective_storage_pallet_capacity) as effective_storage_pallet_capacity,
    anyLast(effective_storage_hu_type) as effective_storage_hu_type,
    anyLast(effective_storage_auxiliary_bin) as effective_storage_auxiliary_bin,
    anyLast(effective_storage_hu_multi_sku) as effective_storage_hu_multi_sku,
    anyLast(effective_storage_hu_multi_batch) as effective_storage_hu_multi_batch,
    anyLast(effective_storage_use_derived_pallet_best_fit) as effective_storage_use_derived_pallet_best_fit,
    anyLast(effective_storage_only_full_pallet) as effective_storage_only_full_pallet,
    anyLast(effective_storage_bin_type_active) as effective_storage_bin_type_active,
    anyLast(effective_storage_zone_id) as effective_storage_zone_id,
    anyLast(effective_storage_zone_code) as effective_storage_zone_code,
    anyLast(effective_storage_zone_description) as effective_storage_zone_description,
    anyLast(effective_storage_zone_face) as effective_storage_zone_face,
    anyLast(effective_storage_peripheral) as effective_storage_peripheral,
    anyLast(effective_storage_surveillance_config) as effective_storage_surveillance_config,
    anyLast(effective_storage_zone_active) as effective_storage_zone_active,
    anyLast(effective_storage_area_id) as effective_storage_area_id,
    anyLast(effective_storage_area_code) as effective_storage_area_code,
    anyLast(effective_storage_area_description) as effective_storage_area_description,
    anyLast(effective_storage_area_type) as effective_storage_area_type,
    anyLast(effective_storage_rolling_days) as effective_storage_rolling_days,
    anyLast(effective_storage_area_active) as effective_storage_area_active,
    anyLast(effective_storage_x1) as effective_storage_x1,
    anyLast(effective_storage_x2) as effective_storage_x2,
    anyLast(effective_storage_y1) as effective_storage_y1,
    anyLast(effective_storage_y2) as effective_storage_y2,
    anyLast(effective_storage_position_active) as effective_storage_position_active,
    anyLast(effective_storage_attrs) as effective_storage_attrs,
    anyLast(effective_storage_bin_mapping) as effective_storage_bin_mapping,
    anyLast(effective_storage_created_at) as effective_storage_created_at,
    anyLast(effective_storage_updated_at) as effective_storage_updated_at,
    anyLast(outer_hu_code) as outer_hu_code,
    anyLast(outer_hu_kind_id) as outer_hu_kind_id,
    anyLast(outer_hu_session_id) as outer_hu_session_id,
    anyLast(outer_hu_task_id) as outer_hu_task_id,
    anyLast(outer_hu_storage_id) as outer_hu_storage_id,
    anyLast(outer_hu_outer_hu_id) as outer_hu_outer_hu_id,
    anyLast(outer_hu_state) as outer_hu_state,
    anyLast(outer_hu_attrs) as outer_hu_attrs,
    anyLast(outer_hu_created_at) as outer_hu_created_at,
    anyLast(outer_hu_updated_at) as outer_hu_updated_at,
    anyLast(outer_hu_lock_task_id) as outer_hu_lock_task_id,
    anyLast(outer_hu_effective_storage_id) as outer_hu_effective_storage_id,
    anyLast(outer_hu_kind_code) as outer_hu_kind_code,
    anyLast(outer_hu_kind_name) as outer_hu_kind_name,
    anyLast(outer_hu_kind_attrs) as outer_hu_kind_attrs,
    anyLast(outer_hu_kind_active) as outer_hu_kind_active,
    anyLast(outer_hu_kind_max_volume) as outer_hu_kind_max_volume,
    anyLast(outer_hu_kind_max_weight) as outer_hu_kind_max_weight,
    anyLast(outer_hu_kind_usage_type) as outer_hu_kind_usage_type,
    anyLast(outer_hu_kind_abbr) as outer_hu_kind_abbr,
    anyLast(outer_hu_kind_length) as outer_hu_kind_length,
    anyLast(outer_hu_kind_breadth) as outer_hu_kind_breadth,
    anyLast(outer_hu_kind_height) as outer_hu_kind_height,
    anyLast(outer_hu_kind_weight) as outer_hu_kind_weight
FROM deduplicated_events
GROUP BY
    hour_window,
    wh_id,
    hu_code,
    sku_code,
    uom,
    bucket,
    batch,
    price,
    inclusion_status,
    locked_by_task_id,
    lock_mode;

-- Create indexes for common query patterns
ALTER TABLE wms_inventory_hourly_position ADD INDEX idx_sku sku_code TYPE bloom_filter(0.01) GRANULARITY 4;
ALTER TABLE wms_inventory_hourly_position ADD INDEX idx_hu hu_code TYPE bloom_filter(0.01) GRANULARITY 4;
ALTER TABLE wms_inventory_hourly_position ADD INDEX idx_batch batch TYPE bloom_filter(0.01) GRANULARITY 4;
ALTER TABLE wms_inventory_hourly_position ADD INDEX idx_storage_zone storage_zone_code TYPE bloom_filter(0.01) GRANULARITY 4;