CREATE TABLE IF NOT EXISTS sbx_uat.pick_drop_item_summary
(
    pick_item_id UUID DEFAULT '00000000-0000-0000-0000-000000000000',
    whId Int64,
    picked_bin String DEFAULT 0,
    picked_sku UUID DEFAULT '00000000-0000-0000-0000-000000000000',
    picked_batch String  DEFAULT 0,
    picked_uom String DEFAULT 0,
    picked_qty String DEFAULT 0,
    overallQty Int32 DEFAULT 0,
    qty Int32 DEFAULT 0,
    huCode String DEFAULT 0,
    destinationBinCode String DEFAULT 0,
    pick_item_created_at DateTime64(3, 'UTC') DEFAULT 0,
    pickedQty Int32 DEFAULT 0,
    pickedAt DateTime64(3, 'UTC') DEFAULT 0,
    worker_code String DEFAULT 0,
    movedAt DateTime64(3, 'UTC') DEFAULT 0,
    processedAt DateTime64(3, 'UTC') DEFAULT 0,
    picked_hu_eq_uom String DEFAULT 0,
    picked_has_inner_hus Bool DEFAULT True,
    picked_inner_hu_eq_uom String DEFAULT 0,
    picked_bin_assigned_at DateTime64(3, 'UTC') DEFAULT 0,
    scanSourceHUKind String DEFAULT 0,
    pickSourceHUKind String DEFAULT 0,
    carrierHUKind String DEFAULT 0,
    scannedSourceHUCode String DEFAULT 0,
    pickedSourceHUCode String DEFAULT 0,
    carrierHUCode String DEFAULT 0,
    huKind String DEFAULT 0,
    sourceHUEqUOM String DEFAULT 0,
    pick_item_updated_at DateTime64(3, 'UTC') DEFAULT 0,
    eligibleDropLocations String DEFAULT 0,
    parentItemId UUID DEFAULT '00000000-0000-0000-0000-000000000000',
    oldBatch String DEFAULT 0,
    destBucket String DEFAULT 0,
    lmTripId UUID DEFAULT '00000000-0000-0000-0000-000000000000',
    picked_inner_hu_code String DEFAULT 0,
    picked_inner_hu_kind_code String DEFAULT 0,
    picked_quant_bucket String DEFAULT 0,
    pick_auto_complete Bool DEFAULT false,
    pickHU Bool DEFAULT true,
    shortAllocationReason String DEFAULT 0,
    drop_item_previous_task_id UUID DEFAULT '00000000-0000-0000-0000-000000000000',
    dropItemId UUID DEFAULT '00000000-0000-0000-0000-000000000000',
    dropped_sku UUID DEFAULT '00000000-0000-0000-0000-000000000000',
    dropped_batch String DEFAULT 0,
    dropped_uom String DEFAULT 0,
    drop_bucket String DEFAULT 0,
    dropped_qty Int32 DEFAULT 0,
    picked_hu_code String DEFAULT 0,
    dropped_bin_code String DEFAULT 0,
    droppedQty Int32 DEFAULT 0,
    droppedAt DateTime64(3, 'UTC') DEFAULT 0,
    drop_item_updated_at DateTime64(3, 'UTC') DEFAULT 0,
    dropHUInBin Bool DEFAULT true,
    scanDestHU Bool DEFAULT false,
    allowHUBreak Bool DEFAULT false,
    dropped_has_inner_hus Bool DEFAULT false,
    scanInnerHUs Bool DEFAULT false,
    dropped_hu_eq_uom String DEFAULT 0,
    destHUCode String DEFAULT 0,
    hu_code String DEFAULT 0,
    dropped_inner_hu_eq_uom String DEFAULT 0,
    dest_bin_assigned_at DateTime64(3, 'UTC') DEFAULT 0,
    dropUOM String DEFAULT 0,
    drop_parent_item_id UUID DEFAULT '00000000-0000-0000-0000-000000000000',
    huBroken Bool DEFAULT false,
    originalSourceBinCode String DEFAULT 0,
    processedForLoadingAt DateTime64(3, 'UTC') DEFAULT 0,
    drop_quant_bucket String DEFAULT 0,
    dropped_inner_hu_code String DEFAULT 0,
    dropped_inner_hu_kind_code String DEFAULT 0,
    dropInnerHU Bool DEFAULT true,
    allowInnerHUBreak Bool DEFAULT false,
    innerHUBroken Bool DEFAULT false,
    drop_auto_complete Bool DEFAULT false,
    quantSlottingForHUs Bool DEFAULT false,
    processedOnDropAt DateTime64(3, 'UTC') DEFAULT 0,
    allowHUBreakV2 Bool DEFAULT true,
    task_kind LowCardinality(String) DEFAULT 0,
    task_code String DEFAULT 0,
    task_sequence Int32 DEFAULT 0,
    task_state LowCardinality(String) DEFAULT 0,
    task_attrs String DEFAULT 0,
    task_progress String DEFAULT 0,
    task_created_at DateTime64(3, 'UTC') DEFAULT 0,
    task_updated_at DateTime64(3, 'UTC') DEFAULT 0,
    allowForceComplete Bool DEFAULT true,
    wave Int32 DEFAULT 0,
    forceCompleted Bool DEFAULT false,
    task_subkind LowCardinality(String) DEFAULT 0,
    label String DEFAULT 0,
    session_kind String DEFAULT 0,
    session_code String DEFAULT 0,
    session_attrs String DEFAULT 0,
    session_created_at DateTime64(3, 'UTC') DEFAULT 0,
    session_updated_at DateTime64(3, 'UTC') DEFAULT 0,
    active Bool DEFAULT true,
    session_state String DEFAULT 0,
    session_progress String DEFAULT 0,
    session_auto_complete Bool DEFAULT true,
    worker_attrs String DEFAULT 0,
    worker_name String DEFAULT 0,
    supervisor Bool DEFAULT false,
    product_code String DEFAULT 0,
    principal_id Int64 DEFAULT 0,
    sku_id UUID DEFAULT '00000000-0000-0000-0000-000000000000',
    sku_code String DEFAULT 0,
    category String DEFAULT 0,
    classvalue String DEFAULT 0,
    node_id Int64 DEFAULT 0,
    node_override_class String DEFAULT 0,
    finalclass String DEFAULT 0,
    encarta_uom_id UUID DEFAULT '00000000-0000-0000-0000-000000000000',
    encarta_uom_code String DEFAULT 0,
    ibc String DEFAULT 0,
    casecount String DEFAULT 0,
    pallet_count String DEFAULT 0,
    lm_trip_code String DEFAULT 0,
    lm_trip_priority  Int32,
    lm_dockdoor LowCardinality(String) DEFAULT 0,
    lm_vehicle_no String DEFAULT 0,
    lm_vehicle_type String DEFAULT 0,
    lm_delivery_date Date DEFAULT toDate('1970-01-01'),
    xdock String DEFAULT 0,
    mm_trip_code String DEFAULT 0,
    mm_trip_priority Int32,
    mm_dockdoor LowCardinality(String) DEFAULT 0,
    mm_vehicle_no String DEFAULT 0,
    mm_vehicle_type String DEFAULT 0,
    mm_delivery_date Date DEFAULT toDate('1970-01-01'),
    is_deleted Bool DEFAULT 0,
    deleted_at DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree()
ORDER BY ("pick_item_id" , "dropItemId")
TTL deleted_at + INTERVAL 1 MINUTE DELETE
   WHERE is_deleted = 1;
