CREATE TABLE IF NOT EXISTS sbx_uat.inventory 
(
    whId Int64,
    id UUID,
    huId String,
    huCode String,
    huKind String,
    huWeight Float64 DEFAULT 0,
    huOnHold Bool,
    huRendered Bool,
    huLockTaskId UUID DEFAULT '00000000-0000-0000-0000-000000000000',
    isBinHu Bool,
    areaType String DEFAULT 0,
    areaCode String DEFAULT 0,
    zoneFace String DEFAULT 0,
    zoneCode String DEFAULT 0,
    binType String DEFAULT 0,
    binCode String DEFAULT 0,
    binStatus String DEFAULT 0,
    binCapacity Int32 DEFAULT 0,
    outerHUCode String DEFAULT 0,
    outerHUKind String DEFAULT 0,
    skuId String,
    skuCode String,
    skuName String,
    skuInventoryType String,
    productCode String,
    category String,
    categoryGroup String,
    skuClassification String,
    plantCode String DEFAULT 0,
    brand String Default 0,
    bucket String,
    inclusionStatus String,
    uom String,
    batch String DEFAULT 0,
    manufactureDate Date DEFAULT toDate('1970-01-01'),
    expiryDate Date DEFAULT toDate('1970-01-01'),
    price String DEFAULT 0,
    quantLockMode String,
    qty Int32 NOT NULL,
    qtyL0 Int64,
    huUpdatedAt DateTime64(3, 'UTC') DEFAULT 0,
    quantUpdatedAt DateTime64(3, 'UTC') DEFAULT 0,
    updatedAt DateTime64(3, 'UTC') DEFAULT 0,
    binTypeId UUID DEFAULT '00000000-0000-0000-0000-000000000000',
    usage Float64 DEFAULT 0,
    huCountBlocked bool DEFAULT false,
    is_deleted Bool DEFAULT 0,
    deleted_at DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree(updatedAt)
ORDER BY (whId,huCode,binCode,skuCode,uom,batch,bucket)
TTL deleted_at + INTERVAL 1 MINUTE DELETE
   WHERE is_deleted = 1;
