CREATE TABLE IF NOT EXISTS sbx_uat.storage_bin_summary
(
    whId Int64,
    bin_code String,
    bin_description String,
    multiSku Bool,
    multiBatch Bool,
    pickingPosition Int32,
    putawayPosition Int32,
    rank Int32,
    aisle String DEFAULT 0,
    bay String DEFAULT 0,
    level String DEFAULT 0,
    position String DEFAULT 0,
    depth String DEFAULT 0,
    maxSkuCount Int32 DEFAULT 0,
    maxSkuBatchCount Int32 DEFAULT 0,
    bin_type_code LowCardinality(String),
    bintype_description String,
    maxVolumeInCC Float64,
    maxWeightInKG Float64,
    palletCapacity Int32 DEFAULT 0,
    storageHUType LowCardinality(String) DEFAULT 'NONE',
    auxiliaryBin Bool,
    huMultiSku Bool,
    huMultiBatch Bool,
    useDerivedPalletBestFit Bool,
    zone_code LowCardinality(String),
    zone_description String,
    zone_face LowCardinality(String),
    peripheral Bool,
    surveillanceConfig String DEFAULT 0,
    area_code LowCardinality(String),
    sa_description String,
    area_type LowCardinality(String),
    rollingDays Int32 DEFAULT 0,
    x1 Float64,
    x2 Float64,
    y1 Float64,
    y2 Float64,
    quality LowCardinality(String),
    sloc LowCardinality(String),
    slocDescription String,
    clientQuality LowCardinality(String),
    inventoryVisible Bool,
    erpToWMS Bool,
    sd_code String DEFAULT 0,
    usage LowCardinality(String) DEFAULT 0,
    multiTrip Bool,
    sd_description String,
    maxQueue Int64,
    allowInbound Bool,
    allowOutbound Bool,
    allowReturns Bool,
    incompatibleVehicleTypes String,
    incompatibleLoadTypes String,
    dockdoor_x_coordinate Float64,
    dockdoor_y_coordinate Float64,
    sb_status String,
    sbt_active Bool,
    bin_mapping String DEFAULT 'DYNAMIC',
    is_deleted Bool DEFAULT 0,
    deleted_at DateTime DEFAULT now()
)
ENGINE = ReplacingMergeTree()
ORDER BY ("whId", "bin_code", "quality","sd_code")
TTL deleted_at + INTERVAL 1 MINUTE DELETE
   WHERE is_deleted = 1;
