CREATE TABLE IF NOT EXISTS sbx_uat.storage_bin_summary
(
    wh_id Int64,
    bin_code String,
    quality LowCardinality(String),
    sd_code String DEFAULT '',
    bin_description String DEFAULT '',
    multi_sku Bool DEFAULT false,
    multi_batch Bool DEFAULT false,
    picking_position Int32 DEFAULT 0,
    putaway_position Int32 DEFAULT 0,
    rank Int32  DEFAULT 0,
    aisle String DEFAULT '',
    bay String DEFAULT '',
    level String DEFAULT '',
    position String DEFAULT '',
    depth String DEFAULT '',
    max_sku_count Int32 DEFAULT 0,
    max_sku_batch_count Int32 DEFAULT 0,
    bin_type_code LowCardinality(String) DEFAULT '',
    bin_type_description String DEFAULT '',
    max_volume_in_cc Float64 DEFAULT 0,
    max_weight_in_kg Float64 DEFAULT 0,
    pallet_capacity Int32 DEFAULT 0,
    storage_hu_type LowCardinality(String) DEFAULT 'NONE',
    auxiliary_bin Bool DEFAULT false,
    hu_multi_sku Bool DEFAULT false,
    hu_multi_batch Bool DEFAULT false,
    use_derived_pallet_best_fit Bool DEFAULT false,
    zone_code LowCardinality(String) DEFAULT '',
    zone_description String DEFAULT '',
    zone_face LowCardinality(String) DEFAULT '',
    peripheral Bool DEFAULT false,
    surveillance_config String DEFAULT '',
    area_code LowCardinality(String) DEFAULT '',
    sa_description String DEFAULT '',
    area_type LowCardinality(String) DEFAULT '',
    rolling_days Int32 DEFAULT 0,
    x1 Float64 DEFAULT 0,
    x2 Float64 DEFAULT 0,
    y1 Float64 DEFAULT 0,
    y2 Float64 DEFAULT 0,
    sloc LowCardinality(String) DEFAULT '',
    sloc_description String DEFAULT '',
    client_quality LowCardinality(String) DEFAULT '',
    inventory_visible Bool DEFAULT true,
    erp_to_wms Bool DEFAULT false,
    usage LowCardinality(String) DEFAULT 0,
    multi_trip Bool DEFAULT false,
    sd_description String DEFAULT '',
    max_queue Int64 DEFAULT 0,
    allow_inbound Bool DEFAULT false,
    allow_outbound Bool DEFAULT false,
    allow_returns Bool DEFAULT false,
    incompatible_vehicle_types String DEFAULT '',
    incompatible_load_types String DEFAULT '',
    dockdoor_x_coordinate Float64 DEFAULT 0,
    dockdoor_y_coordinate Float64 DEFAULT 0,
    sb_status String DEFAULT '',
    sbt_active Bool DEFAULT false,
    bin_mapping String DEFAULT 'DYNAMIC'
)
ENGINE = ReplacingMergeTree()
ORDER BY ("wh_id", "bin_code", "quality","sd_code");
