CREATE TABLE IF NOT EXISTS pick_drop_summary
(
    wh_id Int64,
    principal_id Int64 DEFAULT 0,
    pick_item_id String,
    drop_item_id String,
    picked_bin String DEFAULT '',
    picked_sku_id String DEFAULT '',
    picked_batch String DEFAULT '',
    picked_uom String DEFAULT '',
    overall_qty Int32 DEFAULT 0,
    qty Int32 DEFAULT 0,
    hu_code String DEFAULT '',
    destination_bin_code String DEFAULT '',
    pick_item_created_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    picked_qty Int32 DEFAULT 0,
    picked_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    picked_by_worker_id String DEFAULT '',
    moved_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    processed_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    picked_hu_eq_uom String DEFAULT '',
    picked_has_inner_hus Bool DEFAULT FALSE,
    picked_inner_hu_eq_uom String DEFAULT '',
    picked_bin_assigned_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    scan_source_hu_kind String DEFAULT '',
    pick_source_hu_kind String DEFAULT '',
    carrier_hu_kind String DEFAULT '',
    scanned_source_hu_code String DEFAULT '',
    picked_source_hu_code String DEFAULT '',
    carrier_hu_code String DEFAULT '',
    hu_kind String DEFAULT '',
    source_hu_eq_uom String DEFAULT '',
    pick_item_updated_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    eligible_drop_locations String DEFAULT '',
    parent_item_id String DEFAULT '',
    old_batch String DEFAULT '',
    dest_bucket String DEFAULT '',
    original_source_bin_code String DEFAULT '',
    lm_trip_id String DEFAULT '',
    picked_inner_hu_code String DEFAULT '',
    picked_inner_hu_kind_code String DEFAULT '',
    picked_quant_bucket String DEFAULT '',
    pick_auto_complete Bool DEFAULT FALSE,
    pick_hu Bool DEFAULT FALSE,
    short_allocation_reason String DEFAULT '',
    drop_item_previous_task_id String DEFAULT '',
    dropped_sku_id String DEFAULT '',
    dropped_batch String DEFAULT '',
    dropped_uom String DEFAULT '',
    drop_bucket String DEFAULT '',
    picked_hu_code String DEFAULT '',
    dropped_bin_code String DEFAULT '',
    dropped_qty Int32 DEFAULT 0,
    dropped_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    drop_item_updated_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    drop_hu_in_bin Bool DEFAULT FALSE,
    scan_dest_hu Bool DEFAULT FALSE,
    allow_hu_break Bool DEFAULT FALSE,
    dropped_has_inner_hus Bool DEFAULT FALSE,
    scan_inner_hus Bool DEFAULT FALSE,
    dropped_hu_eq_uom String DEFAULT '',
    dest_hu_code String DEFAULT '',
    dropped_inner_hu_id String DEFAULT '',
    dropped_inner_hu_eq_uom String DEFAULT '',
    dest_bin_assigned_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    drop_uom String DEFAULT '',
    drop_parent_item_id String DEFAULT '',
    hu_broken Bool DEFAULT FALSE,
    drop_original_source_bin_code String DEFAULT '',
    processed_for_loading_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    drop_quant_bucket String DEFAULT '',
    drop_inner_hu_code String DEFAULT '',
    dropped_inner_hu_kind_code String DEFAULT '',
    drop_inner_hu Bool DEFAULT FALSE,
    allow_inner_hu_break Bool DEFAULT FALSE,
    inner_hu_broken Bool DEFAULT FALSE,
    drop_auto_complete Bool DEFAULT FALSE,
    quant_slotting_for_hus Bool DEFAULT FALSE,
    processed_on_drop_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    allow_hu_break_v2 Bool DEFAULT FALSE,
    task_kind String DEFAULT '',
    task_code String DEFAULT '',
    task_sequence Int32 DEFAULT 0,
    task_state String DEFAULT '',
    task_attrs String DEFAULT '',
    task_progress String DEFAULT '',
    task_created_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    task_updated_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    allow_force_complete Bool DEFAULT FALSE,
    wave Int32 DEFAULT 0,
    force_completed Bool DEFAULT FALSE,
    task_subkind String DEFAULT '',
    `label` String DEFAULT '',
    session_kind String DEFAULT '',
    session_code String DEFAULT '',
    session_attrs String DEFAULT '',
    session_created_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    session_updated_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    active Bool DEFAULT FALSE,
    session_state String DEFAULT '',
    session_progress String DEFAULT '',
    session_auto_complete Bool DEFAULT FALSE,
    lm_trip_code String DEFAULT '',
    lm_trip_priority Int32 DEFAULT 0,
    lm_dockdoor String DEFAULT '',
    lm_vehicle_no String DEFAULT '',
    lm_vehicle_type String DEFAULT '',
    lm_delivery_date Date32 DEFAULT toDate32('1970-01-01'),
    bin_id String DEFAULT '',
    bin_hu_id String DEFAULT '',
    destination_bin_id String DEFAULT '',
    destination_bin_hu_id String DEFAULT '',
    pick_deactivated_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    pick_deactivated_by String DEFAULT '',
    moved_by String DEFAULT '',
    scanned_source_hu_id String DEFAULT '',
    picked_source_hu_id String DEFAULT '',
    carrier_hu_id String DEFAULT '',
    original_source_bin_id String DEFAULT '',
    inner_hu_id String DEFAULT '',
    inner_hu_kind_id String DEFAULT '',
    pd_previous_task_id String DEFAULT '',
    input_source_bin_id String DEFAULT '',
    provisional_item_id String DEFAULT '',
    input_dest_hu_id String DEFAULT '',
    pick_item_kind String DEFAULT '',
    tp_assigned_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    leg_index Int32 DEFAULT 0,
    last_leg Bool DEFAULT FALSE,
    ep_assigned_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    carrier_hu_formed_id String DEFAULT '',
    hu_index Int32 DEFAULT 0,
    pick_sequence Int32 DEFAULT 0,
    carrier_hu_force_closed Bool DEFAULT FALSE,
    input_dest_bin_id String DEFAULT '',
    inner_hu_index Int32 DEFAULT 0,
    inner_carrier_hu_key String DEFAULT '',
    inner_carrier_hu_formed_id String DEFAULT '',
    inner_carrier_hu_id String DEFAULT '',
    inner_carrier_hu_code String DEFAULT '',
    inner_carrier_hu_kind String DEFAULT '',
    induction_id String DEFAULT '',
    inner_carrier_hu_force_closed Bool DEFAULT FALSE,
    mhe_id String DEFAULT '',
    pick_attrs String DEFAULT '',
    iloc String DEFAULT '',
    dest_iloc String DEFAULT '',
    source_bin_id String DEFAULT '',
    source_bin_hu_id String DEFAULT '',
    drop_bin_id String DEFAULT '',
    drop_bin_hu_id String DEFAULT '',
    drop_created_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    drop_deactivated_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    drop_deactivated_by String DEFAULT '',
    dropped_by_worker_id String DEFAULT '',
    dest_hu_id String DEFAULT '',
    source_bucket String DEFAULT '',
    original_destination_bin_id String DEFAULT '',
    drop_lm_trip_id String DEFAULT '',
    processed_for_pick_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    drop_provisional_item_id String DEFAULT '',
    drop_input_dest_hu_id String DEFAULT '',
    drop_leg_index Int32 DEFAULT 0,
    drop_last_leg Bool DEFAULT FALSE,
    drop_input_dest_bin_id String DEFAULT '',
    drop_induction_id String DEFAULT '',
    drop_attrs String DEFAULT '',
    drop_mhe_id String DEFAULT '',
    drop_iloc String DEFAULT '',
    source_iloc String DEFAULT '',
    mapping_id String DEFAULT '',
    mapping_created_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    task_exclusive Bool DEFAULT FALSE,
    task_active Bool DEFAULT FALSE,
    task_auto_complete Bool DEFAULT FALSE,
    force_complete_task_id String DEFAULT '',
    lm_session_created_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    lm_trip_created_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    lm_bb_id String DEFAULT '',
    lm_trip_type String DEFAULT '',
    lm_dockdoor_id String DEFAULT '',
    lm_vehicle_id String DEFAULT '',
    worker_code String DEFAULT '',
    worker_name String DEFAULT '',
    worker_phone String DEFAULT '',
    worker_supervisor Bool DEFAULT FALSE,
    worker_active Bool DEFAULT FALSE,
    dropped_hu_code String DEFAULT '',
    dropped_hu_kind_id String DEFAULT '',
    dropped_hu_session_id String DEFAULT '',
    dropped_hu_task_id String DEFAULT '',
    dropped_hu_storage_id String DEFAULT '',
    dropped_hu_outer_hu_id String DEFAULT '',
    dropped_hu_state String DEFAULT '',
    dropped_hu_attrs String DEFAULT '',
    dropped_hu_lock_task_id String DEFAULT '',
    dropped_hu_effective_storage_id String DEFAULT '',
    dropped_hu_is_deleted Bool DEFAULT FALSE,
    dropped_hu_created_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    dropped_hu_updated_at DateTime64(3) DEFAULT '1970-01-01 00:00:00',
    picked_sku_principal_id Int64 DEFAULT 0,
    picked_sku_node_id Int64 DEFAULT 0,
    picked_sku_category String DEFAULT '',
    picked_sku_product String DEFAULT '',
    picked_sku_product_id String DEFAULT '',
    picked_sku_category_group String DEFAULT '',
    picked_sku_sub_brand String DEFAULT '',
    picked_sku_brand String DEFAULT '',
    picked_sku_code String DEFAULT '',
    picked_sku_name String DEFAULT '',
    picked_sku_short_description String DEFAULT '',
    picked_sku_description String DEFAULT '',
    picked_sku_fulfillment_type String DEFAULT '',
    picked_sku_inventory_type String DEFAULT '',
    picked_sku_shelf_life Int32  DEFAULT 0,
    picked_sku_tag1 String DEFAULT '',
    picked_sku_tag2 String DEFAULT '',
    picked_sku_tag3 String DEFAULT '',
    picked_sku_tag4 String DEFAULT '',
    picked_sku_tag5 String DEFAULT '',
    picked_sku_handling_unit_type String DEFAULT '',
    picked_sku_cases_per_layer Int32 DEFAULT 0,
    picked_sku_layers Int32 DEFAULT 0,
    picked_sku_l0_units Int32 DEFAULT 0,
    picked_sku_l1_units Int32 DEFAULT 0,
    picked_sku_l2_units Int32 DEFAULT 0,
    picked_sku_l3_units Int32 DEFAULT 0,
    picked_sku_l0_name String DEFAULT '',
    picked_sku_l0_weight Float64 DEFAULT 0,
    picked_sku_l0_volume Float64 DEFAULT 0,
    picked_sku_l0_package_type String DEFAULT '',
    picked_sku_l0_length Float64 DEFAULT 0,
    picked_sku_l0_width Float64 DEFAULT 0,
    picked_sku_l0_height Float64 DEFAULT 0,
    picked_sku_l0_packing_efficiency Float64 DEFAULT 0,
    picked_sku_l1_name String DEFAULT '',
    picked_sku_l1_weight Float64 DEFAULT 0,
    picked_sku_l1_volume Float64 DEFAULT 0,
    picked_sku_l1_package_type String DEFAULT '',
    picked_sku_l1_length Float64 DEFAULT 0,
    picked_sku_l1_width Float64 DEFAULT 0,
    picked_sku_l1_height Float64 DEFAULT 0,
    picked_sku_l1_packing_efficiency Float64 DEFAULT 0,
    picked_sku_l2_name String DEFAULT '',
    picked_sku_l2_weight Float64 DEFAULT 0,
    picked_sku_l2_volume Float64 DEFAULT 0,
    picked_sku_l2_package_type String DEFAULT '',
    picked_sku_l2_length Float64 DEFAULT 0,
    picked_sku_l2_width Float64 DEFAULT 0,
    picked_sku_l2_height Float64 DEFAULT 0,
    picked_sku_l2_packing_efficiency Float64 DEFAULT 0,
    picked_sku_l3_name String DEFAULT '',
    picked_sku_l3_weight Float64 DEFAULT 0,
    picked_sku_l3_volume Float64 DEFAULT 0,
    picked_sku_l3_package_type String DEFAULT '',
    picked_sku_l3_length Float64 DEFAULT 0,
    picked_sku_l3_width Float64 DEFAULT 0,
    picked_sku_l3_height Float64 DEFAULT 0,
    picked_sku_l3_packing_efficiency Float64 DEFAULT 0,
    picked_sku_active Bool DEFAULT FALSE,
    picked_sku_classifications String DEFAULT '',
    picked_sku_product_classifications String DEFAULT '',
    dropped_sku_principal_id Int64 DEFAULT 0,
    dropped_sku_node_id Int64 DEFAULT 0,
    dropped_sku_category String DEFAULT '',
    dropped_sku_product String DEFAULT '',
    dropped_sku_product_id String DEFAULT '',
    dropped_sku_category_group String DEFAULT '',
    dropped_sku_sub_brand String DEFAULT '',
    dropped_sku_brand String DEFAULT '',
    dropped_sku_code String DEFAULT '',
    dropped_sku_name String DEFAULT '',
    dropped_sku_short_description String DEFAULT '',
    dropped_sku_description String DEFAULT '',
    dropped_sku_fulfillment_type String DEFAULT '',
    dropped_sku_inventory_type String DEFAULT '',
    dropped_sku_shelf_life Int32 DEFAULT 0,
    dropped_sku_tag1 String DEFAULT '',
    dropped_sku_tag2 String DEFAULT '',
    dropped_sku_tag3 String DEFAULT '',
    dropped_sku_tag4 String DEFAULT '',
    dropped_sku_tag5 String DEFAULT '',
    dropped_sku_handling_unit_type String DEFAULT '',
    dropped_sku_cases_per_layer Int32 DEFAULT 0,
    dropped_sku_layers Int32 DEFAULT 0,
    dropped_sku_l0_units Int32 DEFAULT 0,
    dropped_sku_l1_units Int32 DEFAULT 0,
    dropped_sku_l2_units Int32 DEFAULT 0,
    dropped_sku_l3_units Int32 DEFAULT 0,
    dropped_sku_l0_name String DEFAULT '',
    dropped_sku_l0_weight Float64 DEFAULT 0,
    dropped_sku_l0_volume Float64 DEFAULT 0,
    dropped_sku_l0_package_type String DEFAULT '',
    dropped_sku_l0_length Float64 DEFAULT 0,
    dropped_sku_l0_width Float64 DEFAULT 0,
    dropped_sku_l0_height Float64 DEFAULT 0,
    dropped_sku_l0_packing_efficiency Float64 DEFAULT 0,
    dropped_sku_l1_name String DEFAULT '',
    dropped_sku_l1_weight Float64 DEFAULT 0,
    dropped_sku_l1_volume Float64 DEFAULT 0,
    dropped_sku_l1_package_type String DEFAULT '',
    dropped_sku_l1_length Float64 DEFAULT 0,
    dropped_sku_l1_width Float64 DEFAULT 0,
    dropped_sku_l1_height Float64 DEFAULT 0,
    dropped_sku_l1_packing_efficiency Float64 DEFAULT 0,
    dropped_sku_l2_name String DEFAULT '',
    dropped_sku_l2_weight Float64 DEFAULT 0,
    dropped_sku_l2_volume Float64 DEFAULT 0,
    dropped_sku_l2_package_type String DEFAULT '',
    dropped_sku_l2_length Float64 DEFAULT 0,
    dropped_sku_l2_width Float64 DEFAULT 0,
    dropped_sku_l2_height Float64 DEFAULT 0,
    dropped_sku_l2_packing_efficiency Float64 DEFAULT 0,
    dropped_sku_l3_name String DEFAULT '',
    dropped_sku_l3_weight Float64 DEFAULT 0,
    dropped_sku_l3_volume Float64 DEFAULT 0,
    dropped_sku_l3_package_type String DEFAULT '',
    dropped_sku_l3_length Float64 DEFAULT 0,
    dropped_sku_l3_width Float64 DEFAULT 0,
    dropped_sku_l3_height Float64 DEFAULT 0,
    dropped_sku_l3_packing_efficiency Float64 DEFAULT 0,
    dropped_sku_active Bool DEFAULT FALSE,
    dropped_sku_classifications String DEFAULT '',
    dropped_sku_product_classifications String DEFAULT ''
)
ENGINE = ReplacingMergeTree()
ORDER BY (pick_item_id, drop_item_id);
