-- Backfill script for WMS Inventory Hourly Position
-- This script populates the hourly position table with all historical data
-- Run this AFTER creating the tables and materialized view

-- Step 1: Check existing data range in source table
SELECT 
    'Source data range:' as info,
    min(hu_event_timestamp) as earliest_event,
    max(hu_event_timestamp) as latest_event,
    count(*) as total_events,
    uniqExact(wh_id) as warehouses
FROM wms_inventory_events_enriched;

-- Step 2: Check what's already in hourly position table
SELECT 
    'Existing hourly data:' as info,
    min(hour_window) as earliest_hour,
    max(hour_window) as latest_hour,
    count(*) as total_rows,
    sum(event_count) as total_events
FROM wms_inventory_hourly_position;

-- Step 3: Backfill all historical data from beginning of time
-- Using FINAL to automatically deduplicate based on ReplacingMergeTree's version column (_ingested_at)
INSERT INTO wms_inventory_hourly_position
SELECT
    toStartOfHour(hu_event_timestamp) as hour_window,
    wh_id,
    hu_code,
    sku_code,
    uom,
    bucket,
    batch,
    price,
    inclusion_status,
    locked_by_task_id,
    lock_mode,
    sum(qty_added) as hourly_qty_change,
    count() as event_count,
    argMax(hu_event_id, hu_event_timestamp) as latest_hu_event_id,
    argMax(quant_event_id, hu_event_timestamp) as latest_quant_event_id,
    min(hu_event_timestamp) as first_event_time,
    max(hu_event_timestamp) as last_event_time,
    -- Continue with all other fields using anyLast
    anyLast(hu_event_seq) as hu_event_seq,
    anyLast(hu_id) as hu_id,
    anyLast(hu_event_type) as hu_event_type,
    anyLast(hu_event_payload) as hu_event_payload,
    anyLast(hu_event_attrs) as hu_event_attrs,
    anyLast(session_id) as session_id,
    anyLast(task_id) as task_id,
    anyLast(correlation_id) as correlation_id,
    anyLast(storage_id) as storage_id,
    anyLast(outer_hu_id) as outer_hu_id,
    anyLast(effective_storage_id) as effective_storage_id,
    anyLast(sku_id) as sku_id,
    anyLast(hu_kind_id) as hu_kind_id,
    anyLast(hu_state) as hu_state,
    anyLast(hu_attrs) as hu_attrs,
    anyLast(hu_created_at) as hu_created_at,
    anyLast(hu_updated_at) as hu_updated_at,
    anyLast(hu_lock_task_id) as hu_lock_task_id,
    anyLast(hu_effective_storage_id) as hu_effective_storage_id,
    anyLast(hu_kind_code) as hu_kind_code,
    anyLast(hu_kind_name) as hu_kind_name,
    anyLast(hu_kind_attrs) as hu_kind_attrs,
    anyLast(hu_kind_active) as hu_kind_active,
    anyLast(hu_kind_max_volume) as hu_kind_max_volume,
    anyLast(hu_kind_max_weight) as hu_kind_max_weight,
    anyLast(hu_kind_usage_type) as hu_kind_usage_type,
    anyLast(hu_kind_abbr) as hu_kind_abbr,
    anyLast(hu_kind_length) as hu_kind_length,
    anyLast(hu_kind_breadth) as hu_kind_breadth,
    anyLast(hu_kind_height) as hu_kind_height,
    anyLast(hu_kind_weight) as hu_kind_weight,
    anyLast(storage_bin_code) as storage_bin_code,
    anyLast(storage_bin_description) as storage_bin_description,
    anyLast(storage_bin_status) as storage_bin_status,
    anyLast(storage_bin_hu_id) as storage_bin_hu_id,
    anyLast(storage_multi_sku) as storage_multi_sku,
    anyLast(storage_multi_batch) as storage_multi_batch,
    anyLast(storage_picking_position) as storage_picking_position,
    anyLast(storage_putaway_position) as storage_putaway_position,
    anyLast(storage_rank) as storage_rank,
    anyLast(storage_aisle) as storage_aisle,
    anyLast(storage_bay) as storage_bay,
    anyLast(storage_level) as storage_level,
    anyLast(storage_position) as storage_position,
    anyLast(storage_depth) as storage_depth,
    anyLast(storage_max_sku_count) as storage_max_sku_count,
    anyLast(storage_max_sku_batch_count) as storage_max_sku_batch_count,
    anyLast(storage_bin_type_id) as storage_bin_type_id,
    anyLast(storage_bin_type_code) as storage_bin_type_code,
    anyLast(storage_bin_type_description) as storage_bin_type_description,
    anyLast(storage_max_volume_in_cc) as storage_max_volume_in_cc,
    anyLast(storage_max_weight_in_kg) as storage_max_weight_in_kg,
    anyLast(storage_pallet_capacity) as storage_pallet_capacity,
    anyLast(storage_hu_type) as storage_hu_type,
    anyLast(storage_auxiliary_bin) as storage_auxiliary_bin,
    anyLast(storage_hu_multi_sku) as storage_hu_multi_sku,
    anyLast(storage_hu_multi_batch) as storage_hu_multi_batch,
    anyLast(storage_use_derived_pallet_best_fit) as storage_use_derived_pallet_best_fit,
    anyLast(storage_only_full_pallet) as storage_only_full_pallet,
    anyLast(storage_bin_type_active) as storage_bin_type_active,
    anyLast(storage_zone_id) as storage_zone_id,
    anyLast(storage_zone_code) as storage_zone_code,
    anyLast(storage_zone_description) as storage_zone_description,
    anyLast(storage_zone_face) as storage_zone_face,
    anyLast(storage_peripheral) as storage_peripheral,
    anyLast(storage_surveillance_config) as storage_surveillance_config,
    anyLast(storage_zone_active) as storage_zone_active,
    anyLast(storage_area_id) as storage_area_id,
    anyLast(storage_area_code) as storage_area_code,
    anyLast(storage_area_description) as storage_area_description,
    anyLast(storage_area_type) as storage_area_type,
    anyLast(storage_rolling_days) as storage_rolling_days,
    anyLast(storage_area_active) as storage_area_active,
    anyLast(storage_x1) as storage_x1,
    anyLast(storage_x2) as storage_x2,
    anyLast(storage_y1) as storage_y1,
    anyLast(storage_y2) as storage_y2,
    anyLast(storage_position_active) as storage_position_active,
    anyLast(storage_attrs) as storage_attrs,
    anyLast(storage_bin_mapping) as storage_bin_mapping,
    anyLast(storage_created_at) as storage_created_at,
    anyLast(storage_updated_at) as storage_updated_at,
    anyLast(sku_name) as sku_name,
    anyLast(sku_short_description) as sku_short_description,
    anyLast(sku_description) as sku_description,
    anyLast(sku_category) as sku_category,
    anyLast(sku_product) as sku_product,
    anyLast(sku_product_id) as sku_product_id,
    anyLast(sku_category_group) as sku_category_group,
    anyLast(sku_sub_brand) as sku_sub_brand,
    anyLast(sku_brand) as sku_brand,
    anyLast(sku_fulfillment_type) as sku_fulfillment_type,
    anyLast(sku_inventory_type) as sku_inventory_type,
    anyLast(sku_shelf_life) as sku_shelf_life,
    anyLast(sku_handling_unit_type) as sku_handling_unit_type,
    anyLast(sku_cases_per_layer) as sku_cases_per_layer,
    anyLast(sku_layers) as sku_layers,
    anyLast(sku_active_from) as sku_active_from,
    anyLast(sku_active_till) as sku_active_till,
    anyLast(sku_l0_units) as sku_l0_units,
    anyLast(sku_l0_name) as sku_l0_name,
    anyLast(sku_l0_weight) as sku_l0_weight,
    anyLast(sku_l0_volume) as sku_l0_volume,
    anyLast(sku_l0_length) as sku_l0_length,
    anyLast(sku_l0_width) as sku_l0_width,
    anyLast(sku_l0_height) as sku_l0_height,
    anyLast(sku_l1_units) as sku_l1_units,
    anyLast(sku_l1_name) as sku_l1_name,
    anyLast(sku_l1_weight) as sku_l1_weight,
    anyLast(sku_l1_volume) as sku_l1_volume,
    anyLast(sku_l1_length) as sku_l1_length,
    anyLast(sku_l1_width) as sku_l1_width,
    anyLast(sku_l1_height) as sku_l1_height,
    anyLast(sku_active) as sku_active,
    anyLast(sku_created_at) as sku_created_at,
    anyLast(sku_updated_at) as sku_updated_at,
    anyLast(effective_storage_bin_code) as effective_storage_bin_code,
    anyLast(effective_storage_bin_description) as effective_storage_bin_description,
    anyLast(effective_storage_bin_status) as effective_storage_bin_status,
    anyLast(effective_storage_bin_hu_id) as effective_storage_bin_hu_id,
    anyLast(effective_storage_multi_sku) as effective_storage_multi_sku,
    anyLast(effective_storage_multi_batch) as effective_storage_multi_batch,
    anyLast(effective_storage_picking_position) as effective_storage_picking_position,
    anyLast(effective_storage_putaway_position) as effective_storage_putaway_position,
    anyLast(effective_storage_rank) as effective_storage_rank,
    anyLast(effective_storage_aisle) as effective_storage_aisle,
    anyLast(effective_storage_bay) as effective_storage_bay,
    anyLast(effective_storage_level) as effective_storage_level,
    anyLast(effective_storage_position) as effective_storage_position,
    anyLast(effective_storage_depth) as effective_storage_depth,
    anyLast(effective_storage_max_sku_count) as effective_storage_max_sku_count,
    anyLast(effective_storage_max_sku_batch_count) as effective_storage_max_sku_batch_count,
    anyLast(effective_storage_bin_type_id) as effective_storage_bin_type_id,
    anyLast(effective_storage_bin_type_code) as effective_storage_bin_type_code,
    anyLast(effective_storage_bin_type_description) as effective_storage_bin_type_description,
    anyLast(effective_storage_max_volume_in_cc) as effective_storage_max_volume_in_cc,
    anyLast(effective_storage_max_weight_in_kg) as effective_storage_max_weight_in_kg,
    anyLast(effective_storage_pallet_capacity) as effective_storage_pallet_capacity,
    anyLast(effective_storage_hu_type) as effective_storage_hu_type,
    anyLast(effective_storage_auxiliary_bin) as effective_storage_auxiliary_bin,
    anyLast(effective_storage_hu_multi_sku) as effective_storage_hu_multi_sku,
    anyLast(effective_storage_hu_multi_batch) as effective_storage_hu_multi_batch,
    anyLast(effective_storage_use_derived_pallet_best_fit) as effective_storage_use_derived_pallet_best_fit,
    anyLast(effective_storage_only_full_pallet) as effective_storage_only_full_pallet,
    anyLast(effective_storage_bin_type_active) as effective_storage_bin_type_active,
    anyLast(effective_storage_zone_id) as effective_storage_zone_id,
    anyLast(effective_storage_zone_code) as effective_storage_zone_code,
    anyLast(effective_storage_zone_description) as effective_storage_zone_description,
    anyLast(effective_storage_zone_face) as effective_storage_zone_face,
    anyLast(effective_storage_peripheral) as effective_storage_peripheral,
    anyLast(effective_storage_surveillance_config) as effective_storage_surveillance_config,
    anyLast(effective_storage_zone_active) as effective_storage_zone_active,
    anyLast(effective_storage_area_id) as effective_storage_area_id,
    anyLast(effective_storage_area_code) as effective_storage_area_code,
    anyLast(effective_storage_area_description) as effective_storage_area_description,
    anyLast(effective_storage_area_type) as effective_storage_area_type,
    anyLast(effective_storage_rolling_days) as effective_storage_rolling_days,
    anyLast(effective_storage_area_active) as effective_storage_area_active,
    anyLast(effective_storage_x1) as effective_storage_x1,
    anyLast(effective_storage_x2) as effective_storage_x2,
    anyLast(effective_storage_y1) as effective_storage_y1,
    anyLast(effective_storage_y2) as effective_storage_y2,
    anyLast(effective_storage_position_active) as effective_storage_position_active,
    anyLast(effective_storage_attrs) as effective_storage_attrs,
    anyLast(effective_storage_bin_mapping) as effective_storage_bin_mapping,
    anyLast(effective_storage_created_at) as effective_storage_created_at,
    anyLast(effective_storage_updated_at) as effective_storage_updated_at,
    anyLast(outer_hu_code) as outer_hu_code,
    anyLast(outer_hu_kind_id) as outer_hu_kind_id,
    anyLast(outer_hu_session_id) as outer_hu_session_id,
    anyLast(outer_hu_task_id) as outer_hu_task_id,
    anyLast(outer_hu_storage_id) as outer_hu_storage_id,
    anyLast(outer_hu_outer_hu_id) as outer_hu_outer_hu_id,
    anyLast(outer_hu_state) as outer_hu_state,
    anyLast(outer_hu_attrs) as outer_hu_attrs,
    anyLast(outer_hu_created_at) as outer_hu_created_at,
    anyLast(outer_hu_updated_at) as outer_hu_updated_at,
    anyLast(outer_hu_lock_task_id) as outer_hu_lock_task_id,
    anyLast(outer_hu_effective_storage_id) as outer_hu_effective_storage_id,
    anyLast(outer_hu_kind_code) as outer_hu_kind_code,
    anyLast(outer_hu_kind_name) as outer_hu_kind_name,
    anyLast(outer_hu_kind_attrs) as outer_hu_kind_attrs,
    anyLast(outer_hu_kind_active) as outer_hu_kind_active,
    anyLast(outer_hu_kind_max_volume) as outer_hu_kind_max_volume,
    anyLast(outer_hu_kind_max_weight) as outer_hu_kind_max_weight,
    anyLast(outer_hu_kind_usage_type) as outer_hu_kind_usage_type,
    anyLast(outer_hu_kind_abbr) as outer_hu_kind_abbr,
    anyLast(outer_hu_kind_length) as outer_hu_kind_length,
    anyLast(outer_hu_kind_breadth) as outer_hu_kind_breadth,
    anyLast(outer_hu_kind_height) as outer_hu_kind_height,
    anyLast(outer_hu_kind_weight) as outer_hu_kind_weight,
    now64(3) as _processed_at
FROM wms_inventory_events_enriched FINAL
GROUP BY
    toStartOfHour(hu_event_timestamp),
    wh_id,
    hu_code,
    sku_code,
    uom,
    bucket,
    batch,
    price,
    inclusion_status,
    locked_by_task_id,
    lock_mode
HAVING sum(qty_added) != 0;

-- Step 4: Verify backfill results
SELECT 
    'Backfill complete:' as info,
    min(hour_window) as earliest_hour,
    max(hour_window) as latest_hour,
    count(*) as total_rows,
    sum(event_count) as total_events,
    count(DISTINCT wh_id) as warehouses
FROM wms_inventory_hourly_position;

-- Step 5: Generate initial weekly snapshot if needed
-- Run the weekly snapshot generation script after this