-- SET 'execution.savepoint.path' = '<path to checkpoint/savepoint>';
--
SET 'pipeline.name' = 'WMS Pick Drop Staging Unified Processing';
SET 'table.exec.sink.not-null-enforcer' = 'drop';
SET 'parallelism.default' = '6';
SET 'table.optimizer.join-reorder-enabled' = 'true';
SET 'table.optimizer.adaptive-join.enabled' = 'true';
SET 'table.exec.resource.default-parallelism' = '6';

-- State TTL configuration to prevent unbounded state growth
-- State will be kept for 4 hours after last access
SET 'table.exec.state.ttl' = '14400000';

-- Enhanced performance optimizations for unified pipeline
SET 'taskmanager.memory.managed.fraction' = '0.8';
SET 'table.exec.mini-batch.enabled' = 'true';
SET 'table.exec.mini-batch.allow-latency' = '2s';
SET 'table.exec.mini-batch.size' = '10000';
SET 'execution.checkpointing.interval' = '300000';
SET 'execution.checkpointing.timeout' = '1800000';
SET 'state.backend.incremental' = 'true';
SET 'state.backend.rocksdb.compression.type' = 'LZ4';
SET 'pipeline.operator-chaining' = 'true';
SET 'table.optimizer.multiple-input-enabled' = 'true';

-- Source Table 1: Pick Items (Raw with duplicates)
CREATE TABLE pick_items_raw (
    id STRING NOT NULL,
    `whId` BIGINT NOT NULL,
    `sessionId` STRING NOT NULL,
    `taskId` STRING,
    `binId` STRING,
    `binHUId` STRING,
    `binCode` STRING,
    `skuId` STRING NOT NULL,
    batch STRING NOT NULL,
    uom STRING NOT NULL,
    bucket STRING NOT NULL,
    `overallQty` INT NOT NULL,
    qty INT NOT NULL,
    `huId` STRING,
    `huCode` STRING,
    `destinationBinId` STRING,
    `destinationBinHUId` STRING,
    `destinationBinCode` STRING,
    `createdAt` TIMESTAMP(3) NOT NULL,
    `deactivatedAt` TIMESTAMP(3),
    `deactivatedBy` STRING,
    `pickedQty` INT,
    `pickedAt` TIMESTAMP(3),
    `pickedBy` STRING,
    `movedAt` TIMESTAMP(3),
    `movedBy` STRING,
    `processedAt` TIMESTAMP(3),
    `huEqUOM` STRING,
    `hasInnerHUs` BOOLEAN,
    `innerHUEqUOM` STRING,
    `binAssignedAt` TIMESTAMP(3),
    `scanSourceHUKind` STRING,
    `pickSourceHUKind` STRING,
    `carrierHUKind` STRING,
    `scannedSourceHUId` STRING,
    `scannedSourceHUCode` STRING,
    `pickedSourceHUId` STRING,
    `pickedSourceHUCode` STRING,
    `carrierHUId` STRING,
    `carrierHUCode` STRING,
    `huKind` STRING,
    `sourceHUEqUOM` STRING,
    `updatedAt` TIMESTAMP(3) NOT NULL,
    `eligibleDropLocations` STRING,
    `parentItemId` STRING,
    `oldBatch` STRING,
    `destBucket` STRING,
    `originalSourceBinId` STRING,
    `originalSourceBinCode` STRING,
    `lmTripId` STRING,
    `innerHUId` STRING,
    `innerHUCode` STRING,
    `innerHUKindId` STRING,
    `innerHUKindCode` STRING,
    `quantBucket` STRING,
    `autoCompleted` BOOLEAN,
    `pickHU` BOOLEAN,
    `shortAllocationReason` STRING,
    `pdPreviousTaskId` STRING,
    `inputSourceBinId` STRING,
    `provisionalItemId` STRING,
    `inputDestHUId` STRING,
    kind STRING,
    `tpAssignedAt` TIMESTAMP(3),
    `legIndex` INT,
    `lastLeg` BOOLEAN,
    `epAssignedAt` TIMESTAMP(3),
    `carrierHUFormedId` STRING,
    `huIndex` INT,
    sequence INT,
    `carrierHUForceClosed` BOOLEAN,
    `inputDestBinId` STRING,
    `innerHUIndex` INT,
    `innerCarrierHUKey` STRING,
    `innerCarrierHUFormedId` STRING,
    `innerCarrierHUId` STRING,
    `innerCarrierHUCode` STRING,
    `innerCarrierHUKind` STRING,
    `inductionId` STRING,
    `innerCarrierHUForceClosed` BOOLEAN,
    `mheId` STRING,
    attrs STRING,
    iloc STRING,
    `destIloc` STRING
) WITH (
    'connector' = 'kafka',
    'topic' = '${KAFKA_ENV}.wms.public.pd_pick_item',
    'properties.bootstrap.servers' = '${KAFKA_BOOTSTRAP_SERVERS}',
    'properties.group.id' = '${KAFKA_ENV}-wms-pick-drop-staging-unified',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.auto.offset.reset' = 'earliest',
    'format' = 'avro-confluent',
    'avro-confluent.url' = '${SCHEMA_REGISTRY_URL}',
    'avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'scan.startup.mode' = 'earliest-offset'
);

-- Source Table 2: Drop Items (Raw with duplicates)
CREATE TABLE drop_items_raw (
    id STRING NOT NULL,
    `whId` BIGINT NOT NULL,
    `sessionId` STRING NOT NULL,
    `taskId` STRING NOT NULL,
    `sourceBinId` STRING NOT NULL,
    `sourceBinHUId` STRING NOT NULL,
    `sourceBinCode` STRING NOT NULL,
    `skuId` STRING NOT NULL,
    batch STRING NOT NULL,
    uom STRING NOT NULL,
    bucket STRING NOT NULL,
    qty INT NOT NULL,
    `huId` STRING,
    `huCode` STRING,
    `binId` STRING,
    `binHUId` STRING,
    `binCode` STRING,
    `createdAt` TIMESTAMP(3) NOT NULL,
    `deactivatedAt` TIMESTAMP(3),
    `deactivatedBy` STRING,
    `droppedQty` INT,
    `droppedAt` TIMESTAMP(3),
    `droppedBy` STRING,
    `updatedAt` TIMESTAMP(3) NOT NULL,
    `dropHUInBin` BOOLEAN,
    `scanDestHU` BOOLEAN,
    `allowHUBreak` BOOLEAN,
    `hasInnerHUs` BOOLEAN,
    `scanInnerHUs` BOOLEAN,
    `huEqUOM` STRING,
    `destHUId` STRING,
    `destHUCode` STRING,
    `droppedInnerHUId` STRING,
    `innerHUEqUOM` STRING,
    `binAssignedAt` TIMESTAMP(3),
    `dropUOM` STRING,
    `eligibleDropLocations` STRING,
    `parentItemId` STRING,
    `huBroken` BOOLEAN,
    `pickedBy` STRING,
    `sourceBucket` STRING,
    `originalDestinationBinId` STRING,
    `originalDestinationBinCode` STRING,
    `lmTripId` STRING,
    `processedForLoadingAt` TIMESTAMP(3),
    `quantBucket` STRING,
    `innerHUId` STRING,
    `innerHUCode` STRING,
    `innerHUKindId` STRING,
    `innerHUKindCode` STRING,
    `dropInnerHU` BOOLEAN,
    `allowInnerHUBreak` BOOLEAN,
    `innerHUBroken` BOOLEAN,
    `autoCompleted` BOOLEAN,
    `processedForPickAt` TIMESTAMP(3),
    `quantSlottingForHUs` BOOLEAN,
    `pdPreviousTaskId` STRING,
    `processedOnDropAt` TIMESTAMP(3),
    `provisionalItemId` STRING,
    `allowHUBreakV2` BOOLEAN,
    `inputDestHUId` STRING,
    `legIndex` INT,
    `lastLeg` BOOLEAN,
    `inputDestBinId` STRING,
    `inductionId` STRING,
    attrs STRING,
    `mheId` STRING,
    iloc STRING,
    `sourceIloc` STRING
) WITH (
    'connector' = 'kafka',
    'topic' = '${KAFKA_ENV}.wms.public.pd_drop_item',
    'properties.bootstrap.servers' = '${KAFKA_BOOTSTRAP_SERVERS}',
    'properties.group.id' = '${KAFKA_ENV}-wms-pick-drop-staging-unified',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.auto.offset.reset' = 'earliest',
    'format' = 'avro-confluent',
    'avro-confluent.url' = '${SCHEMA_REGISTRY_URL}',
    'avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'scan.startup.mode' = 'earliest-offset'
);

-- Source Table 3: Pick Drop Mapping (Raw with duplicates)
CREATE TABLE pick_drop_mapping_raw (
    id STRING,
    `whId` BIGINT,
    `sessionId` STRING,
    `taskId` STRING,
    `pickItemId` STRING,
    `dropItemId` STRING,
    `createdAt` TIMESTAMP(3)
) WITH (
    'connector' = 'kafka',
    'topic' = '${KAFKA_ENV}.wms.public.pd_pick_drop_mapping',
    'properties.bootstrap.servers' = '${KAFKA_BOOTSTRAP_SERVERS}',
    'properties.group.id' = '${KAFKA_ENV}-wms-pick-drop-staging-unified',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.auto.offset.reset' = 'earliest',
    'format' = 'avro-confluent',
    'avro-confluent.url' = '${SCHEMA_REGISTRY_URL}',
    'avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'scan.startup.mode' = 'earliest-offset'
);

-- Sink table with exact same schema but using standard kafka connector
CREATE TABLE pick_drop_staging (
    pick_item_id STRING,
    drop_item_id STRING,
    wh_id BIGINT,
    session_id STRING,
    task_id STRING,
    lm_trip_id STRING,
    -- Pick item fields
    picked_bin STRING,
    picked_sku_id STRING,
    picked_batch STRING,
    picked_uom STRING,
    overall_qty INT,
    qty INT,
    hu_code STRING,
    destination_bin_code STRING,
    pick_item_created_at TIMESTAMP(3),
    picked_qty INT,
    picked_at TIMESTAMP(3),
    picked_by_worker_id STRING,
    moved_at TIMESTAMP(3),
    processed_at TIMESTAMP(3),
    picked_hu_eq_uom STRING,
    picked_has_inner_hus BOOLEAN,
    picked_inner_hu_eq_uom STRING,
    picked_bin_assigned_at TIMESTAMP(3),
    scan_source_hu_kind STRING,
    pick_source_hu_kind STRING,
    carrier_hu_kind STRING,
    scanned_source_hu_code STRING,
    picked_source_hu_code STRING,
    carrier_hu_code STRING,
    hu_kind STRING,
    source_hu_eq_uom STRING,
    pick_item_updated_at TIMESTAMP(3),
    eligible_drop_locations STRING,
    parent_item_id STRING,
    old_batch STRING,
    dest_bucket STRING,
    original_source_bin_code STRING,
    picked_inner_hu_code STRING,
    picked_inner_hu_kind_code STRING,
    picked_quant_bucket STRING,
    pick_auto_complete BOOLEAN,
    pick_hu BOOLEAN,
    short_allocation_reason STRING,
    -- Drop item fields
    dropped_sku_id STRING,
    dropped_batch STRING,
    dropped_uom STRING,
    drop_bucket STRING,
    picked_hu_code STRING,
    dropped_bin_code STRING,
    dropped_qty INT,
    dropped_at TIMESTAMP(3),
    drop_item_updated_at TIMESTAMP(3),
    drop_hu_in_bin BOOLEAN,
    scan_dest_hu BOOLEAN,
    allow_hu_break BOOLEAN,
    dropped_has_inner_hus BOOLEAN,
    scan_inner_hus BOOLEAN,
    dropped_hu_eq_uom STRING,
    dest_hu_code STRING,
    dropped_inner_hu_id STRING,
    dropped_inner_hu_eq_uom STRING,
    dest_bin_assigned_at TIMESTAMP(3),
    drop_uom STRING,
    drop_parent_item_id STRING,
    hu_broken BOOLEAN,
    drop_original_source_bin_code STRING,
    processed_for_loading_at TIMESTAMP(3),
    drop_quant_bucket STRING,
    drop_inner_hu_code STRING,
    dropped_inner_hu_kind_code STRING,
    drop_inner_hu BOOLEAN,
    allow_inner_hu_break BOOLEAN,
    inner_hu_broken BOOLEAN,
    drop_auto_complete BOOLEAN,
    quant_slotting_for_hus BOOLEAN,
    processed_on_drop_at TIMESTAMP(3),
    allow_hu_break_v2 BOOLEAN,
    -- Mapping fields
    mapping_id STRING,
    mapping_created_at TIMESTAMP(3),
    -- Additional fields for enrichment pipeline
    bin_id STRING,
    bin_hu_id STRING,
    destination_bin_id STRING,
    destination_bin_hu_id STRING,
    pick_deactivated_at TIMESTAMP(3),
    pick_deactivated_by STRING,
    moved_by STRING,
    scanned_source_hu_id STRING,
    picked_source_hu_id STRING,
    carrier_hu_id STRING,
    original_source_bin_id STRING,
    inner_hu_id STRING,
    inner_hu_kind_id STRING,
    pd_previous_task_id STRING,
    input_source_bin_id STRING,
    provisional_item_id STRING,
    input_dest_hu_id STRING,
    pick_item_kind STRING,
    tp_assigned_at TIMESTAMP(3),
    leg_index INT,
    last_leg BOOLEAN,
    ep_assigned_at TIMESTAMP(3),
    carrier_hu_formed_id STRING,
    hu_index INT,
    pick_sequence INT,
    carrier_hu_force_closed BOOLEAN,
    input_dest_bin_id STRING,
    inner_hu_index INT,
    inner_carrier_hu_key STRING,
    inner_carrier_hu_formed_id STRING,
    inner_carrier_hu_id STRING,
    inner_carrier_hu_code STRING,
    inner_carrier_hu_kind STRING,
    induction_id STRING,
    inner_carrier_hu_force_closed BOOLEAN,
    mhe_id STRING,
    pick_attrs STRING,
    iloc STRING,
    dest_iloc STRING,
    source_bin_id STRING,
    source_bin_hu_id STRING,
    drop_bin_id STRING,
    drop_bin_hu_id STRING,
    drop_created_at TIMESTAMP(3),
    drop_deactivated_at TIMESTAMP(3),
    drop_deactivated_by STRING,
    dropped_by_worker_id STRING,
    dest_hu_id STRING,
    source_bucket STRING,
    original_destination_bin_id STRING,
    drop_lm_trip_id STRING,
    processed_for_pick_at TIMESTAMP(3),
    drop_provisional_item_id STRING,
    drop_input_dest_hu_id STRING,
    drop_leg_index INT,
    drop_last_leg BOOLEAN,
    drop_input_dest_bin_id STRING,
    drop_induction_id STRING,
    drop_attrs STRING,
    drop_mhe_id STRING,
    drop_iloc STRING,
    source_iloc STRING,
    -- Event time is the latest update between pick and drop
    event_time TIMESTAMP(3) NOT NULL,
    -- Deactivated at - COALESCE of pick and drop deactivated timestamps
    deactivated_at TIMESTAMP(3),
    -- Primary key for partitioning - same as original
    PRIMARY KEY (pick_item_id, drop_item_id) NOT ENFORCED
) WITH (
    'connector' = 'upsert-kafka',
    'topic' = '${KAFKA_ENV}.wms.flink.pick_drop_staging',
    'properties.bootstrap.servers' = '${KAFKA_BOOTSTRAP_SERVERS}',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.auto.offset.reset' = 'earliest',
    'properties.transaction.timeout.ms' = '900000',
    'sink.parallelism' = '6',
    'key.format' = 'avro-confluent',
    'key.avro-confluent.url' = '${SCHEMA_REGISTRY_URL}',
    'key.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'key.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'value.format' = 'avro-confluent',
    'value.avro-confluent.url' = '${SCHEMA_REGISTRY_URL}',
    'value.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'value.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);

-- Intermediate view for deduplicated pick items
CREATE VIEW pick_items_deduped AS
SELECT * FROM (
    SELECT *, 
           ROW_NUMBER() OVER (PARTITION BY id ORDER BY `updatedAt` DESC) as rn
    FROM pick_items_raw
) WHERE rn = 1;

-- Intermediate view for mapping INNER JOIN drop items (complete pick-drop pairs)
-- Join first, then deduplicate based on drop item updated_at
CREATE VIEW pick_drop_pairs AS
SELECT 
    mapping_id,
    mapping_wh_id,
    mapping_session_id,
    mapping_task_id,
    `pickItemId`,
    `dropItemId`,
    mapping_created_at,
    -- All drop item fields
    drop_id,
    drop_wh_id,
    drop_session_id,
    drop_task_id,
    `sourceBinId`,
    `sourceBinHUId`,
    `sourceBinCode`,
    drop_sku_id,
    drop_batch,
    drop_uom,
    drop_bucket,
    drop_qty,
    drop_hu_id,
    drop_hu_code,
    drop_bin_id,
    drop_bin_hu_id,
    drop_bin_code,
    drop_created_at,
    drop_deactivated_at,
    drop_deactivated_by,
    `droppedQty`,
    `droppedAt`,
    `droppedBy`,
    drop_updated_at,
    `dropHUInBin`,
    `scanDestHU`,
    `allowHUBreak`,
    drop_has_inner_hus,
    `scanInnerHUs`,
    drop_hu_eq_uom,
    `destHUId`,
    `destHUCode`,
    `droppedInnerHUId`,
    drop_inner_hu_eq_uom,
    drop_bin_assigned_at,
    `dropUOM`,
    drop_eligible_drop_locations,
    drop_parent_item_id,
    `huBroken`,
    drop_picked_by,
    `sourceBucket`,
    `originalDestinationBinId`,
    `originalDestinationBinCode`,
    drop_lm_trip_id,
    `processedForLoadingAt`,
    drop_quant_bucket,
    drop_inner_hu_id,
    drop_inner_hu_code,
    drop_inner_hu_kind_id,
    drop_inner_hu_kind_code,
    `dropInnerHU`,
    `allowInnerHUBreak`,
    `innerHUBroken`,
    drop_auto_completed,
    `processedForPickAt`,
    `quantSlottingForHUs`,
    drop_pd_previous_task_id,
    `processedOnDropAt`,
    drop_provisional_item_id,
    `allowHUBreakV2`,
    drop_input_dest_hu_id,
    drop_leg_index,
    drop_last_leg,
    drop_input_dest_bin_id,
    drop_induction_id,
    drop_attrs,
    drop_mhe_id,
    drop_iloc,
    `sourceIloc`
FROM (
    SELECT 
        pdm.id AS mapping_id,
        pdm.`whId` AS mapping_wh_id,
        pdm.`sessionId` AS mapping_session_id,
        pdm.`taskId` AS mapping_task_id,
        pdm.`pickItemId`,
        pdm.`dropItemId`,
        pdm.`createdAt` AS mapping_created_at,
        -- All drop item fields
        di.id AS drop_id,
        di.`whId` AS drop_wh_id,
        di.`sessionId` AS drop_session_id,
        di.`taskId` AS drop_task_id,
        di.`sourceBinId`,
        di.`sourceBinHUId`,
        di.`sourceBinCode`,
        di.`skuId` AS drop_sku_id,
        di.batch AS drop_batch,
        di.uom AS drop_uom,
        di.bucket AS drop_bucket,
        di.qty AS drop_qty,
        di.`huId` AS drop_hu_id,
        di.`huCode` AS drop_hu_code,
        di.`binId` AS drop_bin_id,
        di.`binHUId` AS drop_bin_hu_id,
        di.`binCode` AS drop_bin_code,
        di.`createdAt` AS drop_created_at,
        di.`deactivatedAt` AS drop_deactivated_at,
        di.`deactivatedBy` AS drop_deactivated_by,
        di.`droppedQty`,
        di.`droppedAt`,
        di.`droppedBy`,
        di.`updatedAt` AS drop_updated_at,
        di.`dropHUInBin`,
        di.`scanDestHU`,
        di.`allowHUBreak`,
        di.`hasInnerHUs` AS drop_has_inner_hus,
        di.`scanInnerHUs`,
        di.`huEqUOM` AS drop_hu_eq_uom,
        di.`destHUId`,
        di.`destHUCode`,
        di.`droppedInnerHUId`,
        di.`innerHUEqUOM` AS drop_inner_hu_eq_uom,
        di.`binAssignedAt` AS drop_bin_assigned_at,
        di.`dropUOM`,
        di.`eligibleDropLocations` AS drop_eligible_drop_locations,
        di.`parentItemId` AS drop_parent_item_id,
        di.`huBroken`,
        di.`pickedBy` AS drop_picked_by,
        di.`sourceBucket`,
        di.`originalDestinationBinId`,
        di.`originalDestinationBinCode`,
        di.`lmTripId` AS drop_lm_trip_id,
        di.`processedForLoadingAt`,
        di.`quantBucket` AS drop_quant_bucket,
        di.`innerHUId` AS drop_inner_hu_id,
        di.`innerHUCode` AS drop_inner_hu_code,
        di.`innerHUKindId` AS drop_inner_hu_kind_id,
        di.`innerHUKindCode` AS drop_inner_hu_kind_code,
        di.`dropInnerHU`,
        di.`allowInnerHUBreak`,
        di.`innerHUBroken`,
        di.`autoCompleted` AS drop_auto_completed,
        di.`processedForPickAt`,
        di.`quantSlottingForHUs`,
        di.`pdPreviousTaskId` AS drop_pd_previous_task_id,
        di.`processedOnDropAt`,
        di.`provisionalItemId` AS drop_provisional_item_id,
        di.`allowHUBreakV2`,
        di.`inputDestHUId` AS drop_input_dest_hu_id,
        di.`legIndex` AS drop_leg_index,
        di.`lastLeg` AS drop_last_leg,
        di.`inputDestBinId` AS drop_input_dest_bin_id,
        di.`inductionId` AS drop_induction_id,
        di.attrs AS drop_attrs,
        di.`mheId` AS drop_mhe_id,
        di.iloc AS drop_iloc,
        di.`sourceIloc`,
        -- Deduplication ranking based on drop item updated_at
        ROW_NUMBER() OVER (PARTITION BY pdm.`pickItemId`, pdm.`dropItemId` ORDER BY di.`updatedAt` DESC) as rn
    FROM pick_drop_mapping_raw pdm
    INNER JOIN drop_items_raw di ON pdm.`dropItemId` = di.id AND pdm.`sessionId` = di.`sessionId`
) WHERE rn = 1;

-- Unified pick-drop processing with intermediate views
INSERT INTO pick_drop_staging
SELECT
    pi.id AS pick_item_id,
    COALESCE(pdp.`dropItemId`, '') AS drop_item_id,
    pi.`whId` AS wh_id,
    pi.`sessionId` AS session_id,
    pi.`taskId` AS task_id,
    pi.`lmTripId` AS lm_trip_id,
    -- Pick item fields
    pi.`binCode` AS picked_bin,
    pi.`skuId` AS picked_sku_id,
    pi.batch AS picked_batch,
    pi.uom AS picked_uom,
    pi.`overallQty` AS overall_qty,
    pi.qty AS qty,
    pi.`huCode` AS hu_code,
    pi.`destinationBinCode` AS destination_bin_code,
    pi.`createdAt` AS pick_item_created_at,
    pi.`pickedQty` AS picked_qty,
    pi.`pickedAt` AS picked_at,
    pi.`pickedBy` AS picked_by_worker_id,
    pi.`movedAt` AS moved_at,
    pi.`processedAt` AS processed_at,
    pi.`huEqUOM` AS picked_hu_eq_uom,
    pi.`hasInnerHUs` AS picked_has_inner_hus,
    pi.`innerHUEqUOM` AS picked_inner_hu_eq_uom,
    pi.`binAssignedAt` AS picked_bin_assigned_at,
    pi.`scanSourceHUKind` AS scan_source_hu_kind,
    pi.`pickSourceHUKind` AS pick_source_hu_kind,
    pi.`carrierHUKind` AS carrier_hu_kind,
    pi.`scannedSourceHUCode` AS scanned_source_hu_code,
    pi.`pickedSourceHUCode` AS picked_source_hu_code,
    pi.`carrierHUCode` AS carrier_hu_code,
    pi.`huKind` AS hu_kind,
    pi.`sourceHUEqUOM` AS source_hu_eq_uom,
    pi.`updatedAt` AS pick_item_updated_at,
    pi.`eligibleDropLocations` AS eligible_drop_locations,
    pi.`parentItemId` AS parent_item_id,
    pi.`oldBatch` AS old_batch,
    pi.`destBucket` AS dest_bucket,
    pi.`originalSourceBinCode` AS original_source_bin_code,
    pi.`innerHUCode` AS picked_inner_hu_code,
    pi.`innerHUKindCode` AS picked_inner_hu_kind_code,
    pi.`quantBucket` AS picked_quant_bucket,
    pi.`autoCompleted` AS pick_auto_complete,
    pi.`pickHU` AS pick_hu,
    pi.`shortAllocationReason` AS short_allocation_reason,
    -- Drop item fields
    COALESCE(pdp.drop_sku_id, '') AS dropped_sku_id,
    COALESCE(pdp.drop_batch, '') AS dropped_batch,
    COALESCE(pdp.drop_uom, '') AS dropped_uom,
    COALESCE(pdp.drop_bucket, '') AS drop_bucket,
    pi.`huCode` AS picked_hu_code,
    COALESCE(pdp.drop_bin_code, '') AS dropped_bin_code,
    COALESCE(pdp.`droppedQty`, 0) AS dropped_qty,
    pdp.`droppedAt` AS dropped_at,
    pdp.drop_updated_at AS drop_item_updated_at,
    pdp.`dropHUInBin` AS drop_hu_in_bin,
    pdp.`scanDestHU` AS scan_dest_hu,
    pdp.`allowHUBreak` AS allow_hu_break,
    pdp.drop_has_inner_hus AS dropped_has_inner_hus,
    pdp.`scanInnerHUs` AS scan_inner_hus,
    pdp.drop_hu_eq_uom AS dropped_hu_eq_uom,
    pdp.`destHUCode` AS dest_hu_code,
    pdp.`droppedInnerHUId` AS dropped_inner_hu_id,
    pdp.drop_inner_hu_eq_uom AS dropped_inner_hu_eq_uom,
    pdp.drop_bin_assigned_at AS dest_bin_assigned_at,
    pdp.`dropUOM` AS drop_uom,
    pdp.drop_parent_item_id AS drop_parent_item_id,
    pdp.`huBroken` AS hu_broken,
    pdp.`originalDestinationBinCode` AS drop_original_source_bin_code,
    pdp.`processedForLoadingAt` AS processed_for_loading_at,
    pdp.drop_quant_bucket AS drop_quant_bucket,
    pdp.drop_inner_hu_code AS drop_inner_hu_code,
    pdp.drop_inner_hu_kind_code AS dropped_inner_hu_kind_code,
    pdp.`dropInnerHU` AS drop_inner_hu,
    pdp.`allowInnerHUBreak` AS allow_inner_hu_break,
    pdp.`innerHUBroken` AS inner_hu_broken,
    pdp.drop_auto_completed AS drop_auto_complete,
    pdp.`quantSlottingForHUs` AS quant_slotting_for_hus,
    pdp.`processedOnDropAt` AS processed_on_drop_at,
    pdp.`allowHUBreakV2` AS allow_hu_break_v2,
    -- Mapping fields
    COALESCE(pdp.mapping_id, '') AS mapping_id,
    pdp.mapping_created_at AS mapping_created_at,
    -- Additional pick item fields
    pi.`binId` AS bin_id,
    pi.`binHUId` AS bin_hu_id,
    pi.`destinationBinId` AS destination_bin_id,
    pi.`destinationBinHUId` AS destination_bin_hu_id,
    pi.`deactivatedAt` AS pick_deactivated_at,
    pi.`deactivatedBy` AS pick_deactivated_by,
    pi.`movedBy` AS moved_by,
    pi.`scannedSourceHUId` AS scanned_source_hu_id,
    pi.`pickedSourceHUId` AS picked_source_hu_id,
    pi.`carrierHUId` AS carrier_hu_id,
    pi.`originalSourceBinId` AS original_source_bin_id,
    pi.`innerHUId` AS inner_hu_id,
    pi.`innerHUKindId` AS inner_hu_kind_id,
    pi.`pdPreviousTaskId` AS pd_previous_task_id,
    pi.`inputSourceBinId` AS input_source_bin_id,
    pi.`provisionalItemId` AS provisional_item_id,
    pi.`inputDestHUId` AS input_dest_hu_id,
    pi.kind AS pick_item_kind,
    pi.`tpAssignedAt` AS tp_assigned_at,
    pi.`legIndex` AS leg_index,
    pi.`lastLeg` AS last_leg,
    pi.`epAssignedAt` AS ep_assigned_at,
    pi.`carrierHUFormedId` AS carrier_hu_formed_id,
    COALESCE(pi.`huIndex`, 0) AS hu_index,
    COALESCE(pi.sequence, 0) AS pick_sequence,
    pi.`carrierHUForceClosed` AS carrier_hu_force_closed,
    pi.`inputDestBinId` AS input_dest_bin_id,
    COALESCE(pi.`innerHUIndex`, 0) AS inner_hu_index,
    pi.`innerCarrierHUKey` AS inner_carrier_hu_key,
    pi.`innerCarrierHUFormedId` AS inner_carrier_hu_formed_id,
    pi.`innerCarrierHUId` AS inner_carrier_hu_id,
    pi.`innerCarrierHUCode` AS inner_carrier_hu_code,
    pi.`innerCarrierHUKind` AS inner_carrier_hu_kind,
    pi.`inductionId` AS induction_id,
    pi.`innerCarrierHUForceClosed` AS inner_carrier_hu_force_closed,
    pi.`mheId` AS mhe_id,
    pi.attrs AS pick_attrs,
    pi.iloc AS iloc,
    pi.`destIloc` AS dest_iloc,
    -- Additional drop item fields
    COALESCE(pdp.`sourceBinId`, '') AS source_bin_id,
    COALESCE(pdp.`sourceBinHUId`, '') AS source_bin_hu_id,
    COALESCE(pdp.drop_bin_id, '') AS drop_bin_id,
    COALESCE(pdp.drop_bin_hu_id, '') AS drop_bin_hu_id,
    pdp.drop_created_at AS drop_created_at,
    pdp.drop_deactivated_at AS drop_deactivated_at,
    pdp.drop_deactivated_by AS drop_deactivated_by,
    pdp.`droppedBy` AS dropped_by_worker_id,
    pdp.`destHUId` AS dest_hu_id,
    COALESCE(pdp.`sourceBucket`, '') AS source_bucket,
    pdp.`originalDestinationBinId` AS original_destination_bin_id,
    pdp.drop_lm_trip_id AS drop_lm_trip_id,
    pdp.`processedForPickAt` AS processed_for_pick_at,
    pdp.drop_provisional_item_id AS drop_provisional_item_id,
    pdp.drop_input_dest_hu_id AS drop_input_dest_hu_id,
    COALESCE(pdp.drop_leg_index, 0) AS drop_leg_index,
    pdp.drop_last_leg AS drop_last_leg,
    pdp.drop_input_dest_bin_id AS drop_input_dest_bin_id,
    pdp.drop_induction_id AS drop_induction_id,
    pdp.drop_attrs AS drop_attrs,
    pdp.drop_mhe_id AS drop_mhe_id,
    pdp.drop_iloc AS drop_iloc,
    pdp.`sourceIloc` AS source_iloc,
    -- Event time is the maximum of pick and drop updated_at
    GREATEST(
        COALESCE(
            pi.`updatedAt`,
            pi.`createdAt`,
            TIMESTAMP '1970-01-01 00:00:00'
        ),
        COALESCE(
            pdp.drop_updated_at,
            pdp.drop_created_at,
            TIMESTAMP '1970-01-01 00:00:00'
        )
    ) AS event_time,
    -- Deactivated at - COALESCE of pick and drop deactivated timestamps
    COALESCE(pi.`deactivatedAt`, pdp.drop_deactivated_at) AS deactivated_at
FROM pick_items_deduped pi
LEFT JOIN pick_drop_pairs pdp ON pi.id = pdp.`pickItemId` AND pi.`sessionId` = pdp.mapping_session_id;