-- SET 'execution.savepoint.path' = '<path to checkpoint/savepoint>';
--
SET 'pipeline.name' = 'WMS Pick Drop Enrichment Pipeline';
SET 'table.exec.sink.not-null-enforcer' = 'drop';
SET 'parallelism.default' = '6';
SET 'table.optimizer.join-reorder-enabled' = 'true';
SET 'table.optimizer.adaptive-join.enabled' = 'true';
SET 'table.exec.resource.default-parallelism' = '6';

-- State TTL: 12 hours - sufficient for dimension data (SKUs, workers, HUs rarely change)
-- Prevents unbounded state growth while covering typical Kafka processing latency
SET 'table.exec.state.ttl' = '43200000';

-- Performance optimizations (matching staging pipeline settings)
SET 'taskmanager.memory.managed.fraction' = '0.8';
SET 'table.exec.mini-batch.enabled' = 'true';
SET 'table.exec.mini-batch.allow-latency' = '2s';
SET 'table.exec.mini-batch.size' = '10000';
SET 'execution.checkpointing.interval' = '300000';
SET 'execution.checkpointing.timeout' = '1800000';
SET 'state.backend.incremental' = 'true';
SET 'state.backend.rocksdb.compression.type' = 'LZ4';
SET 'pipeline.operator-chaining' = 'true';
SET 'table.optimizer.multiple-input-enabled' = 'true';

-- Source Table 1: Pick Drop Staging (already combined pick+drop events from staging pipeline)
-- Produced by wms-pick-drop-staging-unified.sql Flink pipeline
CREATE TABLE pick_drop_staging (
    pick_item_id STRING,
    drop_item_id STRING,
    wh_id BIGINT,
    session_id STRING,
    task_id STRING,
    lm_trip_id STRING,
    -- Pick item fields
    picked_bin STRING,
    picked_sku_id STRING,
    picked_batch STRING,
    picked_uom STRING,
    overall_qty INT,
    qty INT,
    hu_code STRING,
    destination_bin_code STRING,
    pick_item_created_at TIMESTAMP(3),
    picked_qty INT,
    picked_at TIMESTAMP(3),
    picked_by_worker_id STRING,
    moved_at TIMESTAMP(3),
    processed_at TIMESTAMP(3),
    picked_hu_eq_uom STRING,
    picked_has_inner_hus BOOLEAN,
    picked_inner_hu_eq_uom STRING,
    picked_bin_assigned_at TIMESTAMP(3),
    scan_source_hu_kind STRING,
    pick_source_hu_kind STRING,
    carrier_hu_kind STRING,
    scanned_source_hu_code STRING,
    picked_source_hu_code STRING,
    carrier_hu_code STRING,
    hu_kind STRING,
    source_hu_eq_uom STRING,
    pick_item_updated_at TIMESTAMP(3),
    eligible_drop_locations STRING,
    parent_item_id STRING,
    old_batch STRING,
    dest_bucket STRING,
    original_source_bin_code STRING,
    picked_inner_hu_code STRING,
    picked_inner_hu_kind_code STRING,
    picked_quant_bucket STRING,
    pick_auto_complete BOOLEAN,
    pick_hu BOOLEAN,
    short_allocation_reason STRING,
    -- Drop item fields
    dropped_sku_id STRING,
    dropped_batch STRING,
    dropped_uom STRING,
    drop_bucket STRING,
    picked_hu_code STRING,
    dropped_bin_code STRING,
    dropped_qty INT,
    dropped_at TIMESTAMP(3),
    drop_item_updated_at TIMESTAMP(3),
    drop_hu_in_bin BOOLEAN,
    scan_dest_hu BOOLEAN,
    allow_hu_break BOOLEAN,
    dropped_has_inner_hus BOOLEAN,
    scan_inner_hus BOOLEAN,
    dropped_hu_eq_uom STRING,
    dest_hu_code STRING,
    dropped_inner_hu_id STRING,
    dropped_inner_hu_eq_uom STRING,
    dest_bin_assigned_at TIMESTAMP(3),
    drop_uom STRING,
    drop_parent_item_id STRING,
    hu_broken BOOLEAN,
    drop_original_source_bin_code STRING,
    processed_for_loading_at TIMESTAMP(3),
    drop_quant_bucket STRING,
    drop_inner_hu_code STRING,
    dropped_inner_hu_kind_code STRING,
    drop_inner_hu BOOLEAN,
    allow_inner_hu_break BOOLEAN,
    inner_hu_broken BOOLEAN,
    drop_auto_complete BOOLEAN,
    quant_slotting_for_hus BOOLEAN,
    processed_on_drop_at TIMESTAMP(3),
    allow_hu_break_v2 BOOLEAN,
    -- Mapping fields
    mapping_id STRING,
    mapping_created_at TIMESTAMP(3),
    -- Additional pick item fields
    bin_id STRING,
    bin_hu_id STRING,
    destination_bin_id STRING,
    destination_bin_hu_id STRING,
    pick_deactivated_at TIMESTAMP(3),
    pick_deactivated_by STRING,
    moved_by STRING,
    scanned_source_hu_id STRING,
    picked_source_hu_id STRING,
    carrier_hu_id STRING,
    original_source_bin_id STRING,
    inner_hu_id STRING,
    inner_hu_kind_id STRING,
    pd_previous_task_id STRING,
    input_source_bin_id STRING,
    provisional_item_id STRING,
    input_dest_hu_id STRING,
    pick_item_kind STRING,
    tp_assigned_at TIMESTAMP(3),
    leg_index INT,
    last_leg BOOLEAN,
    ep_assigned_at TIMESTAMP(3),
    carrier_hu_formed_id STRING,
    hu_index INT,
    pick_sequence INT,
    carrier_hu_force_closed BOOLEAN,
    input_dest_bin_id STRING,
    inner_hu_index INT,
    inner_carrier_hu_key STRING,
    inner_carrier_hu_formed_id STRING,
    inner_carrier_hu_id STRING,
    inner_carrier_hu_code STRING,
    inner_carrier_hu_kind STRING,
    induction_id STRING,
    inner_carrier_hu_force_closed BOOLEAN,
    mhe_id STRING,
    pick_attrs STRING,
    iloc STRING,
    dest_iloc STRING,
    -- Additional drop item fields
    source_bin_id STRING,
    source_bin_hu_id STRING,
    drop_bin_id STRING,
    drop_bin_hu_id STRING,
    drop_created_at TIMESTAMP(3),
    drop_deactivated_at TIMESTAMP(3),
    drop_deactivated_by STRING,
    dropped_by_worker_id STRING,
    dest_hu_id STRING,
    source_bucket STRING,
    original_destination_bin_id STRING,
    drop_lm_trip_id STRING,
    processed_for_pick_at TIMESTAMP(3),
    drop_provisional_item_id STRING,
    drop_input_dest_hu_id STRING,
    drop_leg_index INT,
    drop_last_leg BOOLEAN,
    drop_input_dest_bin_id STRING,
    drop_induction_id STRING,
    drop_attrs STRING,
    drop_mhe_id STRING,
    drop_iloc STRING,
    source_iloc STRING,
    -- Event time is the maximum of pick and drop updated_at
    event_time TIMESTAMP(3) NOT NULL,
    -- Deactivated at - COALESCE of pick and drop deactivated timestamps
    deactivated_at TIMESTAMP(3),
    -- Primary key for upsert semantics
    PRIMARY KEY (pick_item_id, drop_item_id) NOT ENFORCED
) WITH (
    'connector' = 'upsert-kafka',
    'topic' = '${KAFKA_ENV}.wms.flink.pick_drop_staging',
    'properties.bootstrap.servers' = '${KAFKA_BOOTSTRAP_SERVERS}',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.auto.offset.reset' = 'earliest',
    'key.format' = 'avro-confluent',
    'key.avro-confluent.url' = '${SCHEMA_REGISTRY_URL}',
    'key.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'key.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'value.format' = 'avro-confluent',
    'value.avro-confluent.url' = '${SCHEMA_REGISTRY_URL}',
    'value.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'value.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);

-- Source Table 2: SKU Master (fully enriched with product hierarchy and UOMs)
-- Produced by encarta-skus-master.sql Flink pipeline
-- This is the point-in-time snapshot source: captures SKU attributes as they exist when events are processed
CREATE TABLE skus_master (
    id STRING NOT NULL,
    principal_id BIGINT NOT NULL,
    category STRING,
    product STRING,
    product_id STRING NOT NULL,
    category_group STRING,
    sub_brand STRING,
    brand STRING,
    code STRING NOT NULL,
    name STRING,
    short_description STRING,
    description STRING,
    fulfillment_type STRING,
    avg_l0_per_put INT,
    inventory_type STRING,
    shelf_life INT,
    identifier1 STRING,
    identifier2 STRING,
    tag1 STRING,
    tag2 STRING,
    tag3 STRING,
    tag4 STRING,
    tag5 STRING,
    tag6 STRING,
    tag7 STRING,
    tag8 STRING,
    tag9 STRING,
    tag10 STRING,
    handling_unit_type STRING,
    cases_per_layer INT,
    layers INT,
    active_from TIMESTAMP(3),
    active_till TIMESTAMP(3),
    l0_units INT,
    l1_units INT,
    l2_units INT,
    l3_units INT,
    l0_name STRING,
    l0_weight DOUBLE,
    l0_volume DOUBLE,
    l0_package_type STRING,
    l0_length DOUBLE,
    l0_width DOUBLE,
    l0_height DOUBLE,
    l0_itf_code STRING,
    l1_name STRING,
    l1_weight DOUBLE,
    l1_volume DOUBLE,
    l1_package_type STRING,
    l1_length DOUBLE,
    l1_width DOUBLE,
    l1_height DOUBLE,
    l1_itf_code STRING,
    l2_name STRING,
    l2_weight DOUBLE,
    l2_volume DOUBLE,
    l2_package_type STRING,
    l2_length DOUBLE,
    l2_width DOUBLE,
    l2_height DOUBLE,
    l2_itf_code STRING,
    l3_name STRING,
    l3_weight DOUBLE,
    l3_volume DOUBLE,
    l3_package_type STRING,
    l3_length DOUBLE,
    l3_width DOUBLE,
    l3_height DOUBLE,
    l3_itf_code STRING,
    active BOOLEAN NOT NULL,
    classifications STRING NOT NULL,
    product_classifications STRING NOT NULL,
    updated_at TIMESTAMP(3) NOT NULL,
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'connector' = 'upsert-kafka',
    'topic' = '${KAFKA_ENV}.encarta.flink.skus_master',
    'properties.bootstrap.servers' = '${KAFKA_BOOTSTRAP_SERVERS}',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.auto.offset.reset' = 'earliest',
    'key.format' = 'avro-confluent',
    'key.avro-confluent.url' = '${SCHEMA_REGISTRY_URL}',
    'key.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'key.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'value.format' = 'avro-confluent',
    'value.avro-confluent.url' = '${SCHEMA_REGISTRY_URL}',
    'value.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'value.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);

-- Source Table 3: SKU Node Overrides (warehouse-specific attribute overrides for SKUs)
-- Available override fields in this topic: fulfillment_type, avg_l0_per_put, l2_units, l3_units,
--   layers, cases_per_layer, handling_unit_type, sku_short_description, sku_description
-- Other fields (name, tags, shelf_life, etc.) are not in this topic → use skus_master directly
CREATE TABLE node_overrides (
    id STRING NOT NULL,
    sku_id STRING,
    node_id BIGINT,
    active BOOLEAN,
    fulfillment_type STRING,
    avg_l0_per_put INT,
    l2_units INT,
    l3_units INT,
    layers INT,
    cases_per_layer INT,
    handling_unit_type STRING,
    sku_short_description STRING,
    sku_description STRING,
    updated_at TIMESTAMP(3),
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'connector' = 'upsert-kafka',
    'topic' = '${KAFKA_ENV}.encarta.public.node_overrides',
    'properties.bootstrap.servers' = '${KAFKA_BOOTSTRAP_SERVERS}',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.auto.offset.reset' = 'earliest',
    'key.format' = 'avro-confluent',
    'key.avro-confluent.url' = '${SCHEMA_REGISTRY_URL}',
    'key.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'key.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'value.format' = 'avro-confluent',
    'value.avro-confluent.url' = '${SCHEMA_REGISTRY_URL}',
    'value.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'value.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);

-- Source Table 4: Workers (CDC from wms.public.worker)
-- Note: camelCase field names come from Debezium CDC connector
CREATE TABLE workers (
    id STRING NOT NULL,
    `whId` BIGINT,
    code STRING,
    name STRING,
    phone STRING,
    supervisor BOOLEAN,
    active BOOLEAN,
    `updatedAt` TIMESTAMP(3),
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'connector' = 'upsert-kafka',
    'topic' = '${KAFKA_ENV}.wms.public.worker',
    'properties.bootstrap.servers' = '${KAFKA_BOOTSTRAP_SERVERS}',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.auto.offset.reset' = 'earliest',
    'key.format' = 'avro-confluent',
    'key.avro-confluent.url' = '${SCHEMA_REGISTRY_URL}',
    'key.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'key.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'value.format' = 'avro-confluent',
    'value.avro-confluent.url' = '${SCHEMA_REGISTRY_URL}',
    'value.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'value.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);

-- Source Table 5: Handling Units (CDC from wms.public.handling_unit)
-- Note: camelCase field names come from Debezium CDC connector
CREATE TABLE handling_units (
    id STRING NOT NULL,
    code STRING,
    `kindId` STRING,
    `sessionId` STRING,
    `taskId` STRING,
    `storageId` STRING,
    `outerHuId` STRING,
    state STRING,
    attrs STRING,
    `lockTaskId` STRING,
    `effectiveStorageId` STRING,
    `createdAt` TIMESTAMP(3),
    `updatedAt` TIMESTAMP(3),
    PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'connector' = 'upsert-kafka',
    'topic' = '${KAFKA_ENV}.wms.public.handling_unit',
    'properties.bootstrap.servers' = '${KAFKA_BOOTSTRAP_SERVERS}',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.auto.offset.reset' = 'earliest',
    'key.format' = 'avro-confluent',
    'key.avro-confluent.url' = '${SCHEMA_REGISTRY_URL}',
    'key.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'key.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'value.format' = 'avro-confluent',
    'value.avro-confluent.url' = '${SCHEMA_REGISTRY_URL}',
    'value.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'value.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);

-- Sink Table: Pick Drop Enriched (point-in-time snapshot with SKU, worker, and HU data)
-- Mirrors wms_pick_drop_enriched StarRocks table schema exactly
CREATE TABLE pick_drop_enriched (
    -- Core Identifiers
    pick_item_id STRING NOT NULL,
    drop_item_id STRING NOT NULL,
    pick_item_created_at TIMESTAMP(3) NOT NULL,
    wh_id BIGINT,
    principal_id BIGINT,
    session_id STRING,
    task_id STRING,
    lm_trip_id STRING,
    -- Pick Item Core Fields
    picked_bin STRING,
    picked_sku_id STRING,
    picked_batch STRING,
    picked_uom STRING,
    overall_qty INT,
    qty INT,
    hu_code STRING,
    destination_bin_code STRING,
    picked_qty INT,
    picked_at TIMESTAMP(3),
    picked_by_worker_id STRING,
    moved_at TIMESTAMP(3),
    processed_at TIMESTAMP(3),
    -- Pick Handling Unit Fields
    picked_hu_eq_uom STRING,
    picked_has_inner_hus BOOLEAN,
    picked_inner_hu_eq_uom STRING,
    picked_bin_assigned_at TIMESTAMP(3),
    scan_source_hu_kind STRING,
    pick_source_hu_kind STRING,
    carrier_hu_kind STRING,
    scanned_source_hu_code STRING,
    picked_source_hu_code STRING,
    carrier_hu_code STRING,
    hu_kind STRING,
    source_hu_eq_uom STRING,
    pick_item_updated_at TIMESTAMP(3),
    -- Pick Additional Fields
    eligible_drop_locations STRING,
    parent_item_id STRING,
    old_batch STRING,
    dest_bucket STRING,
    original_source_bin_code STRING,
    picked_inner_hu_code STRING,
    picked_inner_hu_kind_code STRING,
    picked_quant_bucket STRING,
    pick_auto_complete BOOLEAN,
    pick_hu BOOLEAN,
    short_allocation_reason STRING,
    drop_item_previous_task_id STRING,
    -- Drop Item Core Fields
    dropped_sku_id STRING,
    dropped_batch STRING,
    dropped_uom STRING,
    drop_bucket STRING,
    picked_hu_code STRING,
    dropped_bin_code STRING,
    dropped_qty INT,
    dropped_at TIMESTAMP(3),
    drop_item_updated_at TIMESTAMP(3),
    -- Drop Handling Unit Fields
    drop_hu_in_bin BOOLEAN,
    scan_dest_hu BOOLEAN,
    allow_hu_break BOOLEAN,
    dropped_has_inner_hus BOOLEAN,
    scan_inner_hus BOOLEAN,
    dropped_hu_eq_uom STRING,
    dest_hu_code STRING,
    dropped_inner_hu_id STRING,
    dropped_inner_hu_eq_uom STRING,
    dest_bin_assigned_at TIMESTAMP(3),
    drop_uom STRING,
    drop_parent_item_id STRING,
    hu_broken BOOLEAN,
    drop_original_source_bin_code STRING,
    processed_for_loading_at TIMESTAMP(3),
    drop_quant_bucket STRING,
    drop_inner_hu_code STRING,
    dropped_inner_hu_kind_code STRING,
    drop_inner_hu BOOLEAN,
    allow_inner_hu_break BOOLEAN,
    inner_hu_broken BOOLEAN,
    drop_auto_complete BOOLEAN,
    quant_slotting_for_hus BOOLEAN,
    processed_on_drop_at TIMESTAMP(3),
    allow_hu_break_v2 BOOLEAN,
    -- Additional Pick Item IDs
    bin_id STRING,
    bin_hu_id STRING,
    destination_bin_id STRING,
    destination_bin_hu_id STRING,
    pick_deactivated_at TIMESTAMP(3),
    pick_deactivated_by STRING,
    moved_by STRING,
    scanned_source_hu_id STRING,
    picked_source_hu_id STRING,
    carrier_hu_id STRING,
    original_source_bin_id STRING,
    inner_hu_id STRING,
    inner_hu_kind_id STRING,
    pd_previous_task_id STRING,
    input_source_bin_id STRING,
    provisional_item_id STRING,
    input_dest_hu_id STRING,
    pick_item_kind STRING,
    tp_assigned_at TIMESTAMP(3),
    leg_index INT,
    last_leg BOOLEAN,
    ep_assigned_at TIMESTAMP(3),
    carrier_hu_formed_id STRING,
    hu_index INT,
    pick_sequence INT,
    carrier_hu_force_closed BOOLEAN,
    input_dest_bin_id STRING,
    inner_hu_index INT,
    inner_carrier_hu_key STRING,
    inner_carrier_hu_formed_id STRING,
    inner_carrier_hu_id STRING,
    inner_carrier_hu_code STRING,
    inner_carrier_hu_kind STRING,
    induction_id STRING,
    inner_carrier_hu_force_closed BOOLEAN,
    mhe_id STRING,
    pick_attrs STRING,
    iloc STRING,
    dest_iloc STRING,
    -- Additional Drop Item IDs
    source_bin_id STRING,
    source_bin_hu_id STRING,
    drop_bin_id STRING,
    drop_bin_hu_id STRING,
    drop_created_at TIMESTAMP(3),
    drop_deactivated_at TIMESTAMP(3),
    drop_deactivated_by STRING,
    dropped_by_worker_id STRING,
    dest_hu_id STRING,
    source_bucket STRING,
    original_destination_bin_id STRING,
    drop_lm_trip_id STRING,
    processed_for_pick_at TIMESTAMP(3),
    drop_provisional_item_id STRING,
    drop_input_dest_hu_id STRING,
    drop_leg_index INT,
    drop_last_leg BOOLEAN,
    drop_input_dest_bin_id STRING,
    drop_induction_id STRING,
    drop_attrs STRING,
    drop_mhe_id STRING,
    drop_iloc STRING,
    source_iloc STRING,
    -- Mapping Fields
    mapping_id STRING,
    mapping_created_at TIMESTAMP(3),
    -- Event time
    event_time TIMESTAMP(3) NOT NULL,
    -- Worker Enrichment (from picked_by_worker_id)
    worker_code STRING,
    worker_name STRING,
    worker_phone STRING,
    worker_supervisor BOOLEAN,
    worker_active BOOLEAN,
    -- Dropped Handling Unit Enrichment (from dropped_inner_hu_id)
    dropped_hu_code STRING,
    dropped_hu_kind_id STRING,
    dropped_hu_session_id STRING,
    dropped_hu_task_id STRING,
    dropped_hu_storage_id STRING,
    dropped_hu_outer_hu_id STRING,
    dropped_hu_state STRING,
    dropped_hu_attrs STRING,
    dropped_hu_lock_task_id STRING,
    dropped_hu_effective_storage_id STRING,
    dropped_hu_created_at TIMESTAMP(3),
    dropped_hu_updated_at TIMESTAMP(3),
    -- SKU Enrichment (captured at event processing time from skus_master + node_overrides)
    sku_category STRING,
    sku_product STRING,
    sku_product_id STRING,
    sku_category_group STRING,
    sku_sub_brand STRING,
    sku_brand STRING,
    sku_code STRING,
    sku_name STRING,
    sku_short_description STRING,
    sku_description STRING,
    sku_fulfillment_type STRING,
    sku_inventory_type STRING,
    sku_shelf_life INT,
    sku_tag1 STRING,
    sku_tag2 STRING,
    sku_tag3 STRING,
    sku_tag4 STRING,
    sku_tag5 STRING,
    sku_handling_unit_type STRING,
    sku_cases_per_layer INT,
    sku_layers INT,
    sku_l0_units INT,
    sku_l1_units INT,
    sku_l2_units INT,
    sku_l3_units INT,
    sku_l0_name STRING,
    sku_l0_weight DOUBLE,
    sku_l0_volume DOUBLE,
    sku_l0_package_type STRING,
    sku_l0_length DOUBLE,
    sku_l0_width DOUBLE,
    sku_l0_height DOUBLE,
    sku_l0_itf_code STRING,
    sku_l1_name STRING,
    sku_l1_weight DOUBLE,
    sku_l1_volume DOUBLE,
    sku_l1_package_type STRING,
    sku_l1_length DOUBLE,
    sku_l1_width DOUBLE,
    sku_l1_height DOUBLE,
    sku_l1_itf_code STRING,
    sku_l2_name STRING,
    sku_l2_weight DOUBLE,
    sku_l2_volume DOUBLE,
    sku_l2_package_type STRING,
    sku_l2_length DOUBLE,
    sku_l2_width DOUBLE,
    sku_l2_height DOUBLE,
    sku_l2_itf_code STRING,
    sku_l3_name STRING,
    sku_l3_weight DOUBLE,
    sku_l3_volume DOUBLE,
    sku_l3_package_type STRING,
    sku_l3_length DOUBLE,
    sku_l3_width DOUBLE,
    sku_l3_height DOUBLE,
    sku_l3_itf_code STRING,
    sku_avg_l0_per_put INT,
    sku_combined_classification STRING,
    -- Primary key for upsert-kafka sink (StarRocks table has additional pick_item_created_at in PK)
    PRIMARY KEY (pick_item_id, drop_item_id) NOT ENFORCED
) WITH (
    'connector' = 'upsert-kafka',
    'topic' = '${KAFKA_ENV}.wms.flink.pick_drop_enriched',
    'properties.bootstrap.servers' = '${KAFKA_BOOTSTRAP_SERVERS}',
    'properties.security.protocol' = 'SASL_SSL',
    'properties.sasl.mechanism' = 'SCRAM-SHA-512',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";',
    'properties.ssl.truststore.location' = '/etc/kafka/secrets/kafka.truststore.jks',
    'properties.ssl.truststore.password' = '${TRUSTSTORE_PASSWORD}',
    'properties.ssl.endpoint.identification.algorithm' = 'https',
    'properties.transaction.timeout.ms' = '900000',
    'sink.parallelism' = '6',
    'key.format' = 'avro-confluent',
    'key.avro-confluent.url' = '${SCHEMA_REGISTRY_URL}',
    'key.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'key.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}',
    'value.format' = 'avro-confluent',
    'value.avro-confluent.url' = '${SCHEMA_REGISTRY_URL}',
    'value.avro-confluent.basic-auth.credentials-source' = 'USER_INFO',
    'value.avro-confluent.basic-auth.user-info' = '${KAFKA_USERNAME}:${KAFKA_PASSWORD}'
);

-- Enrich pick-drop events with SKU master data, node overrides, workers, and handling units
-- KEY DESIGN: Captures dimension data AT event processing time (point-in-time snapshot)
--   → SKU name/brand/UOM captured when the pick-drop event flows through Flink
--   → Even if SKU changes later, historical pick-drop rows keep the original SKU attributes
-- Filter tombstones: event_time > epoch means a real pick-drop event (not a delete)
INSERT INTO pick_drop_enriched
SELECT
    pb.pick_item_id,
    pb.drop_item_id,
    pb.pick_item_created_at,
    pb.wh_id,
    sm.principal_id AS principal_id,
    pb.session_id,
    pb.task_id,
    pb.lm_trip_id,
    -- Pick Item Core Fields (pass-through from staging)
    pb.picked_bin,
    pb.picked_sku_id,
    pb.picked_batch,
    pb.picked_uom,
    pb.overall_qty,
    pb.qty,
    pb.hu_code,
    pb.destination_bin_code,
    pb.picked_qty,
    pb.picked_at,
    pb.picked_by_worker_id,
    pb.moved_at,
    pb.processed_at,
    -- Pick Handling Unit Fields
    pb.picked_hu_eq_uom,
    pb.picked_has_inner_hus,
    pb.picked_inner_hu_eq_uom,
    pb.picked_bin_assigned_at,
    pb.scan_source_hu_kind,
    pb.pick_source_hu_kind,
    pb.carrier_hu_kind,
    pb.scanned_source_hu_code,
    pb.picked_source_hu_code,
    pb.carrier_hu_code,
    pb.hu_kind,
    pb.source_hu_eq_uom,
    pb.pick_item_updated_at,
    -- Pick Additional Fields
    pb.eligible_drop_locations,
    pb.parent_item_id,
    pb.old_batch,
    pb.dest_bucket,
    pb.original_source_bin_code,
    pb.picked_inner_hu_code,
    pb.picked_inner_hu_kind_code,
    pb.picked_quant_bucket,
    pb.pick_auto_complete,
    pb.pick_hu,
    pb.short_allocation_reason,
    pb.pd_previous_task_id AS drop_item_previous_task_id,
    -- Drop Item Core Fields
    pb.dropped_sku_id,
    pb.dropped_batch,
    pb.dropped_uom,
    pb.drop_bucket,
    pb.picked_hu_code,
    pb.dropped_bin_code,
    pb.dropped_qty,
    pb.dropped_at,
    pb.drop_item_updated_at,
    -- Drop Handling Unit Fields
    pb.drop_hu_in_bin,
    pb.scan_dest_hu,
    pb.allow_hu_break,
    pb.dropped_has_inner_hus,
    pb.scan_inner_hus,
    pb.dropped_hu_eq_uom,
    pb.dest_hu_code,
    pb.dropped_inner_hu_id,
    pb.dropped_inner_hu_eq_uom,
    pb.dest_bin_assigned_at,
    pb.drop_uom,
    pb.drop_parent_item_id,
    pb.hu_broken,
    pb.drop_original_source_bin_code,
    pb.processed_for_loading_at,
    pb.drop_quant_bucket,
    pb.drop_inner_hu_code,
    pb.dropped_inner_hu_kind_code,
    pb.drop_inner_hu,
    pb.allow_inner_hu_break,
    pb.inner_hu_broken,
    pb.drop_auto_complete,
    pb.quant_slotting_for_hus,
    pb.processed_on_drop_at,
    pb.allow_hu_break_v2,
    -- Additional Pick Item IDs
    pb.bin_id,
    pb.bin_hu_id,
    pb.destination_bin_id,
    pb.destination_bin_hu_id,
    pb.pick_deactivated_at,
    pb.pick_deactivated_by,
    pb.moved_by,
    pb.scanned_source_hu_id,
    pb.picked_source_hu_id,
    pb.carrier_hu_id,
    pb.original_source_bin_id,
    pb.inner_hu_id,
    pb.inner_hu_kind_id,
    pb.pd_previous_task_id,
    pb.input_source_bin_id,
    pb.provisional_item_id,
    pb.input_dest_hu_id,
    pb.pick_item_kind,
    pb.tp_assigned_at,
    pb.leg_index,
    pb.last_leg,
    pb.ep_assigned_at,
    pb.carrier_hu_formed_id,
    pb.hu_index,
    pb.pick_sequence,
    pb.carrier_hu_force_closed,
    pb.input_dest_bin_id,
    pb.inner_hu_index,
    pb.inner_carrier_hu_key,
    pb.inner_carrier_hu_formed_id,
    pb.inner_carrier_hu_id,
    pb.inner_carrier_hu_code,
    pb.inner_carrier_hu_kind,
    pb.induction_id,
    pb.inner_carrier_hu_force_closed,
    pb.mhe_id,
    pb.pick_attrs,
    pb.iloc,
    pb.dest_iloc,
    -- Additional Drop Item IDs
    pb.source_bin_id,
    pb.source_bin_hu_id,
    pb.drop_bin_id,
    pb.drop_bin_hu_id,
    pb.drop_created_at,
    pb.drop_deactivated_at,
    pb.drop_deactivated_by,
    pb.dropped_by_worker_id,
    pb.dest_hu_id,
    pb.source_bucket,
    pb.original_destination_bin_id,
    pb.drop_lm_trip_id,
    pb.processed_for_pick_at,
    pb.drop_provisional_item_id,
    pb.drop_input_dest_hu_id,
    pb.drop_leg_index,
    pb.drop_last_leg,
    pb.drop_input_dest_bin_id,
    pb.drop_induction_id,
    pb.drop_attrs,
    pb.drop_mhe_id,
    pb.drop_iloc,
    pb.source_iloc,
    -- Mapping Fields
    pb.mapping_id,
    pb.mapping_created_at,
    -- Event time
    pb.event_time,
    -- Worker Enrichment (from picked_by_worker_id → workers table)
    w.code AS worker_code,
    w.name AS worker_name,
    w.phone AS worker_phone,
    w.supervisor AS worker_supervisor,
    w.active AS worker_active,
    -- Dropped Handling Unit Enrichment (from dropped_inner_hu_id → handling_units table)
    hu.code AS dropped_hu_code,
    hu.`kindId` AS dropped_hu_kind_id,
    hu.`sessionId` AS dropped_hu_session_id,
    hu.`taskId` AS dropped_hu_task_id,
    hu.`storageId` AS dropped_hu_storage_id,
    hu.`outerHuId` AS dropped_hu_outer_hu_id,
    hu.state AS dropped_hu_state,
    hu.attrs AS dropped_hu_attrs,
    hu.`lockTaskId` AS dropped_hu_lock_task_id,
    hu.`effectiveStorageId` AS dropped_hu_effective_storage_id,
    hu.`createdAt` AS dropped_hu_created_at,
    hu.`updatedAt` AS dropped_hu_updated_at,
    -- SKU Enrichment from skus_master with node_overrides applied where available
    -- Product hierarchy fields: always from master (never overridden)
    sm.category AS sku_category,
    sm.product AS sku_product,
    sm.product_id AS sku_product_id,
    sm.category_group AS sku_category_group,
    sm.sub_brand AS sku_sub_brand,
    sm.brand AS sku_brand,
    sm.code AS sku_code,       -- always from master, code is never overridden
    sm.name AS sku_name,       -- not in node_overrides topic, use master directly
    -- Apply node override for short_description if active override exists
    CASE WHEN so.active = true AND so.sku_short_description IS NOT NULL AND so.sku_short_description <> ''
         THEN so.sku_short_description ELSE sm.short_description END AS sku_short_description,
    -- Apply node override for description if active override exists
    CASE WHEN so.active = true AND so.sku_description IS NOT NULL AND so.sku_description <> ''
         THEN so.sku_description ELSE sm.description END AS sku_description,
    -- Apply node override for fulfillment_type if active override exists
    CASE WHEN so.active = true AND so.fulfillment_type IS NOT NULL AND so.fulfillment_type <> ''
         THEN so.fulfillment_type ELSE sm.fulfillment_type END AS sku_fulfillment_type,
    sm.inventory_type AS sku_inventory_type,  -- not in node_overrides, use master
    sm.shelf_life AS sku_shelf_life,          -- not in node_overrides, use master
    sm.tag1 AS sku_tag1,                      -- tags not in node_overrides, use master
    sm.tag2 AS sku_tag2,
    sm.tag3 AS sku_tag3,
    sm.tag4 AS sku_tag4,
    sm.tag5 AS sku_tag5,
    -- Apply node override for handling_unit_type if active override exists
    CASE WHEN so.active = true AND so.handling_unit_type IS NOT NULL AND so.handling_unit_type <> ''
         THEN so.handling_unit_type ELSE sm.handling_unit_type END AS sku_handling_unit_type,
    -- Apply node override for cases_per_layer if active override exists
    CASE WHEN so.active = true AND so.cases_per_layer IS NOT NULL AND so.cases_per_layer <> 0
         THEN so.cases_per_layer ELSE sm.cases_per_layer END AS sku_cases_per_layer,
    -- Apply node override for layers if active override exists
    CASE WHEN so.active = true AND so.layers IS NOT NULL AND so.layers <> 0
         THEN so.layers ELSE sm.layers END AS sku_layers,
    sm.l0_units AS sku_l0_units,  -- not in node_overrides, use master
    sm.l1_units AS sku_l1_units,  -- not in node_overrides, use master
    -- Apply node override for l2_units if active override exists
    CASE WHEN so.active = true AND so.l2_units IS NOT NULL AND so.l2_units <> 0
         THEN so.l2_units ELSE sm.l2_units END AS sku_l2_units,
    -- Apply node override for l3_units if active override exists
    CASE WHEN so.active = true AND so.l3_units IS NOT NULL AND so.l3_units <> 0
         THEN so.l3_units ELSE sm.l3_units END AS sku_l3_units,
    -- L0 (base unit) dimensions: from skus_master UOM aggregation
    sm.l0_name AS sku_l0_name,
    sm.l0_weight AS sku_l0_weight,
    sm.l0_volume AS sku_l0_volume,
    sm.l0_package_type AS sku_l0_package_type,
    sm.l0_length AS sku_l0_length,
    sm.l0_width AS sku_l0_width,
    sm.l0_height AS sku_l0_height,
    sm.l0_itf_code AS sku_l0_itf_code,
    -- L1 dimensions
    sm.l1_name AS sku_l1_name,
    sm.l1_weight AS sku_l1_weight,
    sm.l1_volume AS sku_l1_volume,
    sm.l1_package_type AS sku_l1_package_type,
    sm.l1_length AS sku_l1_length,
    sm.l1_width AS sku_l1_width,
    sm.l1_height AS sku_l1_height,
    sm.l1_itf_code AS sku_l1_itf_code,
    -- L2 dimensions
    sm.l2_name AS sku_l2_name,
    sm.l2_weight AS sku_l2_weight,
    sm.l2_volume AS sku_l2_volume,
    sm.l2_package_type AS sku_l2_package_type,
    sm.l2_length AS sku_l2_length,
    sm.l2_width AS sku_l2_width,
    sm.l2_height AS sku_l2_height,
    sm.l2_itf_code AS sku_l2_itf_code,
    -- L3 dimensions
    sm.l3_name AS sku_l3_name,
    sm.l3_weight AS sku_l3_weight,
    sm.l3_volume AS sku_l3_volume,
    sm.l3_package_type AS sku_l3_package_type,
    sm.l3_length AS sku_l3_length,
    sm.l3_width AS sku_l3_width,
    sm.l3_height AS sku_l3_height,
    sm.l3_itf_code AS sku_l3_itf_code,
    -- Apply node override for avg_l0_per_put if active override exists
    CASE WHEN so.active = true AND so.avg_l0_per_put IS NOT NULL AND so.avg_l0_per_put <> 0
         THEN so.avg_l0_per_put ELSE sm.avg_l0_per_put END AS sku_avg_l0_per_put,
    -- JSON merge of classifications not available in Flink SQL; NULL placeholder
    -- (StarRocks Kafka sink accepts NULL for this nullable column)
    CAST(NULL AS STRING) AS sku_combined_classification
FROM pick_drop_staging pb
-- Join SKU master for point-in-time SKU attributes (product hierarchy + UOMs)
LEFT JOIN skus_master sm ON pb.picked_sku_id = sm.id
-- Join node overrides for warehouse-specific SKU attribute overrides (active overrides only)
LEFT JOIN node_overrides so ON pb.picked_sku_id = so.sku_id AND pb.wh_id = so.node_id
-- Join workers for picker name, phone, supervisor status
LEFT JOIN workers w ON pb.picked_by_worker_id = w.id
-- Join handling units for dropped inner HU details (code, state, kind, etc.)
LEFT JOIN handling_units hu ON pb.dropped_inner_hu_id = hu.id
-- Filter tombstones: epoch timestamp means deleted/null record from upstream
WHERE pb.event_time > TIMESTAMP '1970-01-01 00:00:00';
